// Auto-generated by scripts/generate-index.mjs
// Version: RV1960 | Books: 66/66

import { GENESIS_RV1960 } from './genesis';
import { EXODO_RV1960 } from './exodo';
import { LEVITICO_RV1960 } from './levitico';
import { NUMEROS_RV1960 } from './numeros';
import { DEUTERONOMIO_RV1960 } from './deuteronomio';
import { JOSUE_RV1960 } from './josue';
import { JUIZES_RV1960 } from './juizes';
import { RUTE_RV1960 } from './rute';
import { BOOK_1SAMUEL_RV1960 } from './1samuel';
import { BOOK_2SAMUEL_RV1960 } from './2samuel';
import { BOOK_1REIS_RV1960 } from './1reis';
import { BOOK_2REIS_RV1960 } from './2reis';
import { BOOK_1CRONICAS_RV1960 } from './1cronicas';
import { BOOK_2CRONICAS_RV1960 } from './2cronicas';
import { ESDRAS_RV1960 } from './esdras';
import { NEEMIAS_RV1960 } from './neemias';
import { ESTER_RV1960 } from './ester';
import { JO_RV1960 } from './jo';
import { SALMOS_RV1960 } from './salmos';
import { PROVERBIOS_RV1960 } from './proverbios';
import { ECLESIASTES_RV1960 } from './eclesiastes';
import { CANTARES_RV1960 } from './cantares';
import { ISAIAS_RV1960 } from './isaias';
import { JEREMIAS_RV1960 } from './jeremias';
import { LAMENTACOES_RV1960 } from './lamentacoes';
import { EZEQUIEL_RV1960 } from './ezequiel';
import { DANIEL_RV1960 } from './daniel';
import { OSEIAS_RV1960 } from './oseias';
import { JOEL_RV1960 } from './joel';
import { AMOS_RV1960 } from './amos';
import { OBADIAS_RV1960 } from './obadias';
import { JONAS_RV1960 } from './jonas';
import { MIQUEIAS_RV1960 } from './miqueias';
import { NAUM_RV1960 } from './naum';
import { HABACUQUE_RV1960 } from './habacuque';
import { SOFONIAS_RV1960 } from './sofonias';
import { AGEU_RV1960 } from './ageu';
import { ZACARIAS_RV1960 } from './zacarias';
import { MALAQUIAS_RV1960 } from './malaquias';
import { MATEUS_RV1960 } from './mateus';
import { MARCOS_RV1960 } from './marcos';
import { LUCAS_RV1960 } from './lucas';
import { JOAO_RV1960 } from './joao';
import { ATOS_RV1960 } from './atos';
import { ROMANOS_RV1960 } from './romanos';
import { BOOK_1CORINTIOS_RV1960 } from './1corintios';
import { BOOK_2CORINTIOS_RV1960 } from './2corintios';
import { GALATAS_RV1960 } from './galatas';
import { EFESIOS_RV1960 } from './efesios';
import { FILIPENSES_RV1960 } from './filipenses';
import { COLOSSENSES_RV1960 } from './colossenses';
import { BOOK_1TESSALONICENSES_RV1960 } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_RV1960 } from './2tessalonicenses';
import { BOOK_1TIMOTEO_RV1960 } from './1timoteo';
import { BOOK_2TIMOTEO_RV1960 } from './2timoteo';
import { TITO_RV1960 } from './tito';
import { FILEMOM_RV1960 } from './filemom';
import { HEBREUS_RV1960 } from './hebreus';
import { TIAGO_RV1960 } from './tiago';
import { BOOK_1PEDRO_RV1960 } from './1pedro';
import { BOOK_2PEDRO_RV1960 } from './2pedro';
import { BOOK_1JOAO_RV1960 } from './1joao';
import { BOOK_2JOAO_RV1960 } from './2joao';
import { BOOK_3JOAO_RV1960 } from './3joao';
import { JUDAS_RV1960 } from './judas';
import { APOCALIPSE_RV1960 } from './apocalipse';

export const LOCAL_BIBLE_RV1960: Record<number, string[]>[] = [];

export const LOCAL_RV1960: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_RV1960,
  "exodo": EXODO_RV1960,
  "levitico": LEVITICO_RV1960,
  "numeros": NUMEROS_RV1960,
  "deuteronomio": DEUTERONOMIO_RV1960,
  "josue": JOSUE_RV1960,
  "juizes": JUIZES_RV1960,
  "rute": RUTE_RV1960,
  "1samuel": BOOK_1SAMUEL_RV1960,
  "2samuel": BOOK_2SAMUEL_RV1960,
  "1reis": BOOK_1REIS_RV1960,
  "2reis": BOOK_2REIS_RV1960,
  "1cronicas": BOOK_1CRONICAS_RV1960,
  "2cronicas": BOOK_2CRONICAS_RV1960,
  "esdras": ESDRAS_RV1960,
  "neemias": NEEMIAS_RV1960,
  "ester": ESTER_RV1960,
  "jo": JO_RV1960,
  "salmos": SALMOS_RV1960,
  "proverbios": PROVERBIOS_RV1960,
  "eclesiastes": ECLESIASTES_RV1960,
  "cantares": CANTARES_RV1960,
  "isaias": ISAIAS_RV1960,
  "jeremias": JEREMIAS_RV1960,
  "lamentacoes": LAMENTACOES_RV1960,
  "ezequiel": EZEQUIEL_RV1960,
  "daniel": DANIEL_RV1960,
  "oseias": OSEIAS_RV1960,
  "joel": JOEL_RV1960,
  "amos": AMOS_RV1960,
  "obadias": OBADIAS_RV1960,
  "jonas": JONAS_RV1960,
  "miqueias": MIQUEIAS_RV1960,
  "naum": NAUM_RV1960,
  "habacuque": HABACUQUE_RV1960,
  "sofonias": SOFONIAS_RV1960,
  "ageu": AGEU_RV1960,
  "zacarias": ZACARIAS_RV1960,
  "malaquias": MALAQUIAS_RV1960,
  "mateus": MATEUS_RV1960,
  "marcos": MARCOS_RV1960,
  "lucas": LUCAS_RV1960,
  "joao": JOAO_RV1960,
  "atos": ATOS_RV1960,
  "romanos": ROMANOS_RV1960,
  "1corintios": BOOK_1CORINTIOS_RV1960,
  "2corintios": BOOK_2CORINTIOS_RV1960,
  "galatas": GALATAS_RV1960,
  "efesios": EFESIOS_RV1960,
  "filipenses": FILIPENSES_RV1960,
  "colossenses": COLOSSENSES_RV1960,
  "1tessalonicenses": BOOK_1TESSALONICENSES_RV1960,
  "2tessalonicenses": BOOK_2TESSALONICENSES_RV1960,
  "1timoteo": BOOK_1TIMOTEO_RV1960,
  "2timoteo": BOOK_2TIMOTEO_RV1960,
  "tito": TITO_RV1960,
  "filemom": FILEMOM_RV1960,
  "hebreus": HEBREUS_RV1960,
  "tiago": TIAGO_RV1960,
  "1pedro": BOOK_1PEDRO_RV1960,
  "2pedro": BOOK_2PEDRO_RV1960,
  "1joao": BOOK_1JOAO_RV1960,
  "2joao": BOOK_2JOAO_RV1960,
  "3joao": BOOK_3JOAO_RV1960,
  "judas": JUDAS_RV1960,
  "apocalipse": APOCALIPSE_RV1960,
};
