// Auto-generated by scripts/generate-index.mjs
// Version: YLT | Books: 66/66

import { GENESIS_YLT } from './genesis';
import { EXODO_YLT } from './exodo';
import { LEVITICO_YLT } from './levitico';
import { NUMEROS_YLT } from './numeros';
import { DEUTERONOMIO_YLT } from './deuteronomio';
import { JOSUE_YLT } from './josue';
import { JUIZES_YLT } from './juizes';
import { RUTE_YLT } from './rute';
import { BOOK_1SAMUEL_YLT } from './1samuel';
import { BOOK_2SAMUEL_YLT } from './2samuel';
import { BOOK_1REIS_YLT } from './1reis';
import { BOOK_2REIS_YLT } from './2reis';
import { BOOK_1CRONICAS_YLT } from './1cronicas';
import { BOOK_2CRONICAS_YLT } from './2cronicas';
import { ESDRAS_YLT } from './esdras';
import { NEEMIAS_YLT } from './neemias';
import { ESTER_YLT } from './ester';
import { JO_YLT } from './jo';
import { SALMOS_YLT } from './salmos';
import { PROVERBIOS_YLT } from './proverbios';
import { ECLESIASTES_YLT } from './eclesiastes';
import { CANTARES_YLT } from './cantares';
import { ISAIAS_YLT } from './isaias';
import { JEREMIAS_YLT } from './jeremias';
import { LAMENTACOES_YLT } from './lamentacoes';
import { EZEQUIEL_YLT } from './ezequiel';
import { DANIEL_YLT } from './daniel';
import { OSEIAS_YLT } from './oseias';
import { JOEL_YLT } from './joel';
import { AMOS_YLT } from './amos';
import { OBADIAS_YLT } from './obadias';
import { JONAS_YLT } from './jonas';
import { MIQUEIAS_YLT } from './miqueias';
import { NAUM_YLT } from './naum';
import { HABACUQUE_YLT } from './habacuque';
import { SOFONIAS_YLT } from './sofonias';
import { AGEU_YLT } from './ageu';
import { ZACARIAS_YLT } from './zacarias';
import { MALAQUIAS_YLT } from './malaquias';
import { MATEUS_YLT } from './mateus';
import { MARCOS_YLT } from './marcos';
import { LUCAS_YLT } from './lucas';
import { JOAO_YLT } from './joao';
import { ATOS_YLT } from './atos';
import { ROMANOS_YLT } from './romanos';
import { BOOK_1CORINTIOS_YLT } from './1corintios';
import { BOOK_2CORINTIOS_YLT } from './2corintios';
import { GALATAS_YLT } from './galatas';
import { EFESIOS_YLT } from './efesios';
import { FILIPENSES_YLT } from './filipenses';
import { COLOSSENSES_YLT } from './colossenses';
import { BOOK_1TESSALONICENSES_YLT } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_YLT } from './2tessalonicenses';
import { BOOK_1TIMOTEO_YLT } from './1timoteo';
import { BOOK_2TIMOTEO_YLT } from './2timoteo';
import { TITO_YLT } from './tito';
import { FILEMOM_YLT } from './filemom';
import { HEBREUS_YLT } from './hebreus';
import { TIAGO_YLT } from './tiago';
import { BOOK_1PEDRO_YLT } from './1pedro';
import { BOOK_2PEDRO_YLT } from './2pedro';
import { BOOK_1JOAO_YLT } from './1joao';
import { BOOK_2JOAO_YLT } from './2joao';
import { BOOK_3JOAO_YLT } from './3joao';
import { JUDAS_YLT } from './judas';
import { APOCALIPSE_YLT } from './apocalipse';

export const LOCAL_BIBLE_YLT: Record<number, string[]>[] = [];

export const LOCAL_YLT: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_YLT,
  "exodo": EXODO_YLT,
  "levitico": LEVITICO_YLT,
  "numeros": NUMEROS_YLT,
  "deuteronomio": DEUTERONOMIO_YLT,
  "josue": JOSUE_YLT,
  "juizes": JUIZES_YLT,
  "rute": RUTE_YLT,
  "1samuel": BOOK_1SAMUEL_YLT,
  "2samuel": BOOK_2SAMUEL_YLT,
  "1reis": BOOK_1REIS_YLT,
  "2reis": BOOK_2REIS_YLT,
  "1cronicas": BOOK_1CRONICAS_YLT,
  "2cronicas": BOOK_2CRONICAS_YLT,
  "esdras": ESDRAS_YLT,
  "neemias": NEEMIAS_YLT,
  "ester": ESTER_YLT,
  "jo": JO_YLT,
  "salmos": SALMOS_YLT,
  "proverbios": PROVERBIOS_YLT,
  "eclesiastes": ECLESIASTES_YLT,
  "cantares": CANTARES_YLT,
  "isaias": ISAIAS_YLT,
  "jeremias": JEREMIAS_YLT,
  "lamentacoes": LAMENTACOES_YLT,
  "ezequiel": EZEQUIEL_YLT,
  "daniel": DANIEL_YLT,
  "oseias": OSEIAS_YLT,
  "joel": JOEL_YLT,
  "amos": AMOS_YLT,
  "obadias": OBADIAS_YLT,
  "jonas": JONAS_YLT,
  "miqueias": MIQUEIAS_YLT,
  "naum": NAUM_YLT,
  "habacuque": HABACUQUE_YLT,
  "sofonias": SOFONIAS_YLT,
  "ageu": AGEU_YLT,
  "zacarias": ZACARIAS_YLT,
  "malaquias": MALAQUIAS_YLT,
  "mateus": MATEUS_YLT,
  "marcos": MARCOS_YLT,
  "lucas": LUCAS_YLT,
  "joao": JOAO_YLT,
  "atos": ATOS_YLT,
  "romanos": ROMANOS_YLT,
  "1corintios": BOOK_1CORINTIOS_YLT,
  "2corintios": BOOK_2CORINTIOS_YLT,
  "galatas": GALATAS_YLT,
  "efesios": EFESIOS_YLT,
  "filipenses": FILIPENSES_YLT,
  "colossenses": COLOSSENSES_YLT,
  "1tessalonicenses": BOOK_1TESSALONICENSES_YLT,
  "2tessalonicenses": BOOK_2TESSALONICENSES_YLT,
  "1timoteo": BOOK_1TIMOTEO_YLT,
  "2timoteo": BOOK_2TIMOTEO_YLT,
  "tito": TITO_YLT,
  "filemom": FILEMOM_YLT,
  "hebreus": HEBREUS_YLT,
  "tiago": TIAGO_YLT,
  "1pedro": BOOK_1PEDRO_YLT,
  "2pedro": BOOK_2PEDRO_YLT,
  "1joao": BOOK_1JOAO_YLT,
  "2joao": BOOK_2JOAO_YLT,
  "3joao": BOOK_3JOAO_YLT,
  "judas": JUDAS_YLT,
  "apocalipse": APOCALIPSE_YLT,
};
