// Auto-generated by scripts/generate-index.mjs
// Version: TB | Books: 66/66

import { GENESIS_TB } from './genesis';
import { EXODO_TB } from './exodo';
import { LEVITICO_TB } from './levitico';
import { NUMEROS_TB } from './numeros';
import { DEUTERONOMIO_TB } from './deuteronomio';
import { JOSUE_TB } from './josue';
import { JUIZES_TB } from './juizes';
import { RUTE_TB } from './rute';
import { BOOK_1SAMUEL_TB } from './1samuel';
import { BOOK_2SAMUEL_TB } from './2samuel';
import { BOOK_1REIS_TB } from './1reis';
import { BOOK_2REIS_TB } from './2reis';
import { BOOK_1CRONICAS_TB } from './1cronicas';
import { BOOK_2CRONICAS_TB } from './2cronicas';
import { ESDRAS_TB } from './esdras';
import { NEEMIAS_TB } from './neemias';
import { ESTER_TB } from './ester';
import { JO_TB } from './jo';
import { SALMOS_TB } from './salmos';
import { PROVERBIOS_TB } from './proverbios';
import { ECLESIASTES_TB } from './eclesiastes';
import { CANTARES_TB } from './cantares';
import { ISAIAS_TB } from './isaias';
import { JEREMIAS_TB } from './jeremias';
import { LAMENTACOES_TB } from './lamentacoes';
import { EZEQUIEL_TB } from './ezequiel';
import { DANIEL_TB } from './daniel';
import { OSEIAS_TB } from './oseias';
import { JOEL_TB } from './joel';
import { AMOS_TB } from './amos';
import { OBADIAS_TB } from './obadias';
import { JONAS_TB } from './jonas';
import { MIQUEIAS_TB } from './miqueias';
import { NAUM_TB } from './naum';
import { HABACUQUE_TB } from './habacuque';
import { SOFONIAS_TB } from './sofonias';
import { AGEU_TB } from './ageu';
import { ZACARIAS_TB } from './zacarias';
import { MALAQUIAS_TB } from './malaquias';
import { MATEUS_TB } from './mateus';
import { MARCOS_TB } from './marcos';
import { LUCAS_TB } from './lucas';
import { JOAO_TB } from './joao';
import { ATOS_TB } from './atos';
import { ROMANOS_TB } from './romanos';
import { BOOK_1CORINTIOS_TB } from './1corintios';
import { BOOK_2CORINTIOS_TB } from './2corintios';
import { GALATAS_TB } from './galatas';
import { EFESIOS_TB } from './efesios';
import { FILIPENSES_TB } from './filipenses';
import { COLOSSENSES_TB } from './colossenses';
import { BOOK_1TESSALONICENSES_TB } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_TB } from './2tessalonicenses';
import { BOOK_1TIMOTEO_TB } from './1timoteo';
import { BOOK_2TIMOTEO_TB } from './2timoteo';
import { TITO_TB } from './tito';
import { FILEMOM_TB } from './filemom';
import { HEBREUS_TB } from './hebreus';
import { TIAGO_TB } from './tiago';
import { BOOK_1PEDRO_TB } from './1pedro';
import { BOOK_2PEDRO_TB } from './2pedro';
import { BOOK_1JOAO_TB } from './1joao';
import { BOOK_2JOAO_TB } from './2joao';
import { BOOK_3JOAO_TB } from './3joao';
import { JUDAS_TB } from './judas';
import { APOCALIPSE_TB } from './apocalipse';

export const LOCAL_BIBLE_TB: Record<number, string[]>[] = [];

export const LOCAL_TB: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_TB,
  "exodo": EXODO_TB,
  "levitico": LEVITICO_TB,
  "numeros": NUMEROS_TB,
  "deuteronomio": DEUTERONOMIO_TB,
  "josue": JOSUE_TB,
  "juizes": JUIZES_TB,
  "rute": RUTE_TB,
  "1samuel": BOOK_1SAMUEL_TB,
  "2samuel": BOOK_2SAMUEL_TB,
  "1reis": BOOK_1REIS_TB,
  "2reis": BOOK_2REIS_TB,
  "1cronicas": BOOK_1CRONICAS_TB,
  "2cronicas": BOOK_2CRONICAS_TB,
  "esdras": ESDRAS_TB,
  "neemias": NEEMIAS_TB,
  "ester": ESTER_TB,
  "jo": JO_TB,
  "salmos": SALMOS_TB,
  "proverbios": PROVERBIOS_TB,
  "eclesiastes": ECLESIASTES_TB,
  "cantares": CANTARES_TB,
  "isaias": ISAIAS_TB,
  "jeremias": JEREMIAS_TB,
  "lamentacoes": LAMENTACOES_TB,
  "ezequiel": EZEQUIEL_TB,
  "daniel": DANIEL_TB,
  "oseias": OSEIAS_TB,
  "joel": JOEL_TB,
  "amos": AMOS_TB,
  "obadias": OBADIAS_TB,
  "jonas": JONAS_TB,
  "miqueias": MIQUEIAS_TB,
  "naum": NAUM_TB,
  "habacuque": HABACUQUE_TB,
  "sofonias": SOFONIAS_TB,
  "ageu": AGEU_TB,
  "zacarias": ZACARIAS_TB,
  "malaquias": MALAQUIAS_TB,
  "mateus": MATEUS_TB,
  "marcos": MARCOS_TB,
  "lucas": LUCAS_TB,
  "joao": JOAO_TB,
  "atos": ATOS_TB,
  "romanos": ROMANOS_TB,
  "1corintios": BOOK_1CORINTIOS_TB,
  "2corintios": BOOK_2CORINTIOS_TB,
  "galatas": GALATAS_TB,
  "efesios": EFESIOS_TB,
  "filipenses": FILIPENSES_TB,
  "colossenses": COLOSSENSES_TB,
  "1tessalonicenses": BOOK_1TESSALONICENSES_TB,
  "2tessalonicenses": BOOK_2TESSALONICENSES_TB,
  "1timoteo": BOOK_1TIMOTEO_TB,
  "2timoteo": BOOK_2TIMOTEO_TB,
  "tito": TITO_TB,
  "filemom": FILEMOM_TB,
  "hebreus": HEBREUS_TB,
  "tiago": TIAGO_TB,
  "1pedro": BOOK_1PEDRO_TB,
  "2pedro": BOOK_2PEDRO_TB,
  "1joao": BOOK_1JOAO_TB,
  "2joao": BOOK_2JOAO_TB,
  "3joao": BOOK_3JOAO_TB,
  "judas": JUDAS_TB,
  "apocalipse": APOCALIPSE_TB,
};
