// Auto-generated by scripts/generate-index.mjs
// Version: NAA | Books: 66/66

import { GENESIS_NAA } from './genesis';
import { EXODO_NAA } from './exodo';
import { LEVITICO_NAA } from './levitico';
import { NUMEROS_NAA } from './numeros';
import { DEUTERONOMIO_NAA } from './deuteronomio';
import { JOSUE_NAA } from './josue';
import { JUIZES_NAA } from './juizes';
import { RUTE_NAA } from './rute';
import { BOOK_1SAMUEL_NAA } from './1samuel';
import { BOOK_2SAMUEL_NAA } from './2samuel';
import { BOOK_1REIS_NAA } from './1reis';
import { BOOK_2REIS_NAA } from './2reis';
import { BOOK_1CRONICAS_NAA } from './1cronicas';
import { BOOK_2CRONICAS_NAA } from './2cronicas';
import { ESDRAS_NAA } from './esdras';
import { NEEMIAS_NAA } from './neemias';
import { ESTER_NAA } from './ester';
import { JO_NAA } from './jo';
import { SALMOS_NAA } from './salmos';
import { PROVERBIOS_NAA } from './proverbios';
import { ECLESIASTES_NAA } from './eclesiastes';
import { CANTARES_NAA } from './cantares';
import { ISAIAS_NAA } from './isaias';
import { JEREMIAS_NAA } from './jeremias';
import { LAMENTACOES_NAA } from './lamentacoes';
import { EZEQUIEL_NAA } from './ezequiel';
import { DANIEL_NAA } from './daniel';
import { OSEIAS_NAA } from './oseias';
import { JOEL_NAA } from './joel';
import { AMOS_NAA } from './amos';
import { OBADIAS_NAA } from './obadias';
import { JONAS_NAA } from './jonas';
import { MIQUEIAS_NAA } from './miqueias';
import { NAUM_NAA } from './naum';
import { HABACUQUE_NAA } from './habacuque';
import { SOFONIAS_NAA } from './sofonias';
import { AGEU_NAA } from './ageu';
import { ZACARIAS_NAA } from './zacarias';
import { MALAQUIAS_NAA } from './malaquias';
import { MATEUS_NAA } from './mateus';
import { MARCOS_NAA } from './marcos';
import { LUCAS_NAA } from './lucas';
import { JOAO_NAA } from './joao';
import { ATOS_NAA } from './atos';
import { ROMANOS_NAA } from './romanos';
import { BOOK_1CORINTIOS_NAA } from './1corintios';
import { BOOK_2CORINTIOS_NAA } from './2corintios';
import { GALATAS_NAA } from './galatas';
import { EFESIOS_NAA } from './efesios';
import { FILIPENSES_NAA } from './filipenses';
import { COLOSSENSES_NAA } from './colossenses';
import { BOOK_1TESSALONICENSES_NAA } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_NAA } from './2tessalonicenses';
import { BOOK_1TIMOTEO_NAA } from './1timoteo';
import { BOOK_2TIMOTEO_NAA } from './2timoteo';
import { TITO_NAA } from './tito';
import { FILEMOM_NAA } from './filemom';
import { HEBREUS_NAA } from './hebreus';
import { TIAGO_NAA } from './tiago';
import { BOOK_1PEDRO_NAA } from './1pedro';
import { BOOK_2PEDRO_NAA } from './2pedro';
import { BOOK_1JOAO_NAA } from './1joao';
import { BOOK_2JOAO_NAA } from './2joao';
import { BOOK_3JOAO_NAA } from './3joao';
import { JUDAS_NAA } from './judas';
import { APOCALIPSE_NAA } from './apocalipse';

export const LOCAL_BIBLE_NAA: Record<number, string[]>[] = [];

export const LOCAL_NAA: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_NAA,
  "exodo": EXODO_NAA,
  "levitico": LEVITICO_NAA,
  "numeros": NUMEROS_NAA,
  "deuteronomio": DEUTERONOMIO_NAA,
  "josue": JOSUE_NAA,
  "juizes": JUIZES_NAA,
  "rute": RUTE_NAA,
  "1samuel": BOOK_1SAMUEL_NAA,
  "2samuel": BOOK_2SAMUEL_NAA,
  "1reis": BOOK_1REIS_NAA,
  "2reis": BOOK_2REIS_NAA,
  "1cronicas": BOOK_1CRONICAS_NAA,
  "2cronicas": BOOK_2CRONICAS_NAA,
  "esdras": ESDRAS_NAA,
  "neemias": NEEMIAS_NAA,
  "ester": ESTER_NAA,
  "jo": JO_NAA,
  "salmos": SALMOS_NAA,
  "proverbios": PROVERBIOS_NAA,
  "eclesiastes": ECLESIASTES_NAA,
  "cantares": CANTARES_NAA,
  "isaias": ISAIAS_NAA,
  "jeremias": JEREMIAS_NAA,
  "lamentacoes": LAMENTACOES_NAA,
  "ezequiel": EZEQUIEL_NAA,
  "daniel": DANIEL_NAA,
  "oseias": OSEIAS_NAA,
  "joel": JOEL_NAA,
  "amos": AMOS_NAA,
  "obadias": OBADIAS_NAA,
  "jonas": JONAS_NAA,
  "miqueias": MIQUEIAS_NAA,
  "naum": NAUM_NAA,
  "habacuque": HABACUQUE_NAA,
  "sofonias": SOFONIAS_NAA,
  "ageu": AGEU_NAA,
  "zacarias": ZACARIAS_NAA,
  "malaquias": MALAQUIAS_NAA,
  "mateus": MATEUS_NAA,
  "marcos": MARCOS_NAA,
  "lucas": LUCAS_NAA,
  "joao": JOAO_NAA,
  "atos": ATOS_NAA,
  "romanos": ROMANOS_NAA,
  "1corintios": BOOK_1CORINTIOS_NAA,
  "2corintios": BOOK_2CORINTIOS_NAA,
  "galatas": GALATAS_NAA,
  "efesios": EFESIOS_NAA,
  "filipenses": FILIPENSES_NAA,
  "colossenses": COLOSSENSES_NAA,
  "1tessalonicenses": BOOK_1TESSALONICENSES_NAA,
  "2tessalonicenses": BOOK_2TESSALONICENSES_NAA,
  "1timoteo": BOOK_1TIMOTEO_NAA,
  "2timoteo": BOOK_2TIMOTEO_NAA,
  "tito": TITO_NAA,
  "filemom": FILEMOM_NAA,
  "hebreus": HEBREUS_NAA,
  "tiago": TIAGO_NAA,
  "1pedro": BOOK_1PEDRO_NAA,
  "2pedro": BOOK_2PEDRO_NAA,
  "1joao": BOOK_1JOAO_NAA,
  "2joao": BOOK_2JOAO_NAA,
  "3joao": BOOK_3JOAO_NAA,
  "judas": JUDAS_NAA,
  "apocalipse": APOCALIPSE_NAA,
};
