// Auto-generated by scripts/generate-index.mjs
// Version: NVI | Books: 66/66

import { GENESIS_NVI } from './genesis';
import { EXODO_NVI } from './exodo';
import { LEVITICO_NVI } from './levitico';
import { NUMEROS_NVI } from './numeros';
import { DEUTERONOMIO_NVI } from './deuteronomio';
import { JOSUE_NVI } from './josue';
import { JUIZES_NVI } from './juizes';
import { RUTE_NVI } from './rute';
import { BOOK_1SAMUEL_NVI } from './1samuel';
import { BOOK_2SAMUEL_NVI } from './2samuel';
import { BOOK_1REIS_NVI } from './1reis';
import { BOOK_2REIS_NVI } from './2reis';
import { BOOK_1CRONICAS_NVI } from './1cronicas';
import { BOOK_2CRONICAS_NVI } from './2cronicas';
import { ESDRAS_NVI } from './esdras';
import { NEEMIAS_NVI } from './neemias';
import { ESTER_NVI } from './ester';
import { JO_NVI } from './jo';
import { SALMOS_NVI } from './salmos';
import { PROVERBIOS_NVI } from './proverbios';
import { ECLESIASTES_NVI } from './eclesiastes';
import { CANTARES_NVI } from './cantares';
import { ISAIAS_NVI } from './isaias';
import { JEREMIAS_NVI } from './jeremias';
import { LAMENTACOES_NVI } from './lamentacoes';
import { EZEQUIEL_NVI } from './ezequiel';
import { DANIEL_NVI } from './daniel';
import { OSEIAS_NVI } from './oseias';
import { JOEL_NVI } from './joel';
import { AMOS_NVI } from './amos';
import { OBADIAS_NVI } from './obadias';
import { JONAS_NVI } from './jonas';
import { MIQUEIAS_NVI } from './miqueias';
import { NAUM_NVI } from './naum';
import { HABACUQUE_NVI } from './habacuque';
import { SOFONIAS_NVI } from './sofonias';
import { AGEU_NVI } from './ageu';
import { ZACARIAS_NVI } from './zacarias';
import { MALAQUIAS_NVI } from './malaquias';
import { MATEUS_NVI } from './mateus';
import { MARCOS_NVI } from './marcos';
import { LUCAS_NVI } from './lucas';
import { JOAO_NVI } from './joao';
import { ATOS_NVI } from './atos';
import { ROMANOS_NVI } from './romanos';
import { BOOK_1CORINTIOS_NVI } from './1corintios';
import { BOOK_2CORINTIOS_NVI } from './2corintios';
import { GALATAS_NVI } from './galatas';
import { EFESIOS_NVI } from './efesios';
import { FILIPENSES_NVI } from './filipenses';
import { COLOSSENSES_NVI } from './colossenses';
import { BOOK_1TESSALONICENSES_NVI } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_NVI } from './2tessalonicenses';
import { BOOK_1TIMOTEO_NVI } from './1timoteo';
import { BOOK_2TIMOTEO_NVI } from './2timoteo';
import { TITO_NVI } from './tito';
import { FILEMOM_NVI } from './filemom';
import { HEBREUS_NVI } from './hebreus';
import { TIAGO_NVI } from './tiago';
import { BOOK_1PEDRO_NVI } from './1pedro';
import { BOOK_2PEDRO_NVI } from './2pedro';
import { BOOK_1JOAO_NVI } from './1joao';
import { BOOK_2JOAO_NVI } from './2joao';
import { BOOK_3JOAO_NVI } from './3joao';
import { JUDAS_NVI } from './judas';
import { APOCALIPSE_NVI } from './apocalipse';

export const LOCAL_BIBLE_NVI: Record<number, string[]>[] = [];

export const LOCAL_NVI: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_NVI,
  "exodo": EXODO_NVI,
  "levitico": LEVITICO_NVI,
  "numeros": NUMEROS_NVI,
  "deuteronomio": DEUTERONOMIO_NVI,
  "josue": JOSUE_NVI,
  "juizes": JUIZES_NVI,
  "rute": RUTE_NVI,
  "1samuel": BOOK_1SAMUEL_NVI,
  "2samuel": BOOK_2SAMUEL_NVI,
  "1reis": BOOK_1REIS_NVI,
  "2reis": BOOK_2REIS_NVI,
  "1cronicas": BOOK_1CRONICAS_NVI,
  "2cronicas": BOOK_2CRONICAS_NVI,
  "esdras": ESDRAS_NVI,
  "neemias": NEEMIAS_NVI,
  "ester": ESTER_NVI,
  "jo": JO_NVI,
  "salmos": SALMOS_NVI,
  "proverbios": PROVERBIOS_NVI,
  "eclesiastes": ECLESIASTES_NVI,
  "cantares": CANTARES_NVI,
  "isaias": ISAIAS_NVI,
  "jeremias": JEREMIAS_NVI,
  "lamentacoes": LAMENTACOES_NVI,
  "ezequiel": EZEQUIEL_NVI,
  "daniel": DANIEL_NVI,
  "oseias": OSEIAS_NVI,
  "joel": JOEL_NVI,
  "amos": AMOS_NVI,
  "obadias": OBADIAS_NVI,
  "jonas": JONAS_NVI,
  "miqueias": MIQUEIAS_NVI,
  "naum": NAUM_NVI,
  "habacuque": HABACUQUE_NVI,
  "sofonias": SOFONIAS_NVI,
  "ageu": AGEU_NVI,
  "zacarias": ZACARIAS_NVI,
  "malaquias": MALAQUIAS_NVI,
  "mateus": MATEUS_NVI,
  "marcos": MARCOS_NVI,
  "lucas": LUCAS_NVI,
  "joao": JOAO_NVI,
  "atos": ATOS_NVI,
  "romanos": ROMANOS_NVI,
  "1corintios": BOOK_1CORINTIOS_NVI,
  "2corintios": BOOK_2CORINTIOS_NVI,
  "galatas": GALATAS_NVI,
  "efesios": EFESIOS_NVI,
  "filipenses": FILIPENSES_NVI,
  "colossenses": COLOSSENSES_NVI,
  "1tessalonicenses": BOOK_1TESSALONICENSES_NVI,
  "2tessalonicenses": BOOK_2TESSALONICENSES_NVI,
  "1timoteo": BOOK_1TIMOTEO_NVI,
  "2timoteo": BOOK_2TIMOTEO_NVI,
  "tito": TITO_NVI,
  "filemom": FILEMOM_NVI,
  "hebreus": HEBREUS_NVI,
  "tiago": TIAGO_NVI,
  "1pedro": BOOK_1PEDRO_NVI,
  "2pedro": BOOK_2PEDRO_NVI,
  "1joao": BOOK_1JOAO_NVI,
  "2joao": BOOK_2JOAO_NVI,
  "3joao": BOOK_3JOAO_NVI,
  "judas": JUDAS_NVI,
  "apocalipse": APOCALIPSE_NVI,
};
