// Auto-generated by scripts/generate-index.mjs
// Available versions: ARA, KJV, NAA, NTLH, NVI, RV1960, YLT

import { LOCAL_ARA } from './bible-local/ARA/index';
import { LOCAL_KJV } from './bible-local/KJV/index';
import { LOCAL_NAA } from './bible-local/NAA/index';
import { LOCAL_NTLH } from './bible-local/NTLH/index';
import { LOCAL_NVI } from './bible-local/NVI/index';
import { LOCAL_RV1960 } from './bible-local/RV1960/index';
import { LOCAL_YLT } from './bible-local/YLT/index';

// Map of version code → book id → chapter → verses
export const LOCAL_BIBLE: Record<string, Record<string, Record<number, string[]>>> = {
  "ARA": LOCAL_ARA,
  "KJV": LOCAL_KJV,
  "NAA": LOCAL_NAA,
  "NTLH": LOCAL_NTLH,
  "NVI": LOCAL_NVI,
  "RV1960": LOCAL_RV1960,
  "YLT": LOCAL_YLT,
};

// Convenience: ARA is the primary offline version
export const LOCAL_BIBLE_ARA = LOCAL_BIBLE["ARA"] ?? {};
