// Auto-generated by scripts/generate-index.mjs
// Available versions: ARA, NAA, NTLH, NVI, TB

import { LOCAL_ARA } from './bible-local/ARA/index';
import { LOCAL_NAA } from './bible-local/NAA/index';
import { LOCAL_NTLH } from './bible-local/NTLH/index';
import { LOCAL_NVI } from './bible-local/NVI/index';
import { LOCAL_TB } from './bible-local/TB/index';

// Map of version code → book id → chapter → verses
export const LOCAL_BIBLE: Record<string, Record<string, Record<number, string[]>>> = {
  "ARA": LOCAL_ARA,
  "NAA": LOCAL_NAA,
  "NTLH": LOCAL_NTLH,
  "NVI": LOCAL_NVI,
  "TB": LOCAL_TB,
};

// Convenience: ARA is the primary offline version
export const LOCAL_BIBLE_ARA = LOCAL_BIBLE["ARA"] ?? {};
