/**
 * Conteúdo completo de Gênesis capítulos 1-10
 * Versão: Almeida Revista e Corrigida (ARC)
 */
export const GENESIS_ARC: Record<number, string[]> = {
  1: [
    "No princípio criou Deus o céu e a terra.",
    "E a terra era sem forma e vazia; e havia trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas.",
    "E disse Deus: Haja luz; e houve luz.",
    "E viu Deus que era boa a luz; e fez Deus separação entre a luz e as trevas.",
    "E Deus chamou à luz Dia; e às trevas chamou Noite. E foi a tarde e a manhã, o dia primeiro.",
    "E disse Deus: Haja uma expansão no meio das águas, e haja separação entre águas e águas.",
    "E fez Deus a expansão, e fez separação entre as águas que estavam debaixo da expansão e as águas que estavam sobre a expansão; e assim foi.",
    "E chamou Deus à expansão Céus; e foi a tarde e a manhã, o dia segundo.",
    "E disse Deus: Ajuntem-se as águas debaixo dos céus num lugar; e apareça o lugar seco; e assim foi.",
    "E chamou Deus ao lugar seco Terra; e à congregação das águas chamou Mares; e viu Deus que era bom.",
    "E disse Deus: Produza a terra erva verde, erva que dê semente, árvore frutífera que dê fruto conforme a sua espécie, cuja semente esteja nela sobre a terra; e assim foi.",
    "E a terra produziu erva, erva dando semente conforme a sua espécie, e árvore frutífera cuja semente estava nela conforme a sua espécie; e viu Deus que era bom.",
    "E foi a tarde e a manhã, o dia terceiro.",
    "E disse Deus: Haja luminares na expansão dos céus para fazer separação entre o dia e a noite; e sejam eles para sinais, e para estações, e para dias e anos.",
    "E sejam para luminares na expansão dos céus, para alumiar a terra; e assim foi.",
    "E fez Deus os dois grandes luminares: o luminar maior para governar o dia, e o luminar menor para governar a noite; e as estrelas.",
    "E Deus os pôs na expansão dos céus para alumiar a terra,",
    "E para governar o dia e a noite, e para fazer separação entre a luz e as trevas; e viu Deus que era bom.",
    "E foi a tarde e a manhã, o dia quarto.",
    "E disse Deus: Produzam as águas abundantemente répteis de alma vivente; e voem as aves sobre a terra em frente da expansão dos céus.",
    "E criou Deus os grandes monstros marinhos, e todo réptil de alma vivente que as águas produziram abundantemente conforme as suas espécies, e toda ave de asa conforme a sua espécie; e viu Deus que era bom.",
    "E Deus os abençoou, dizendo: Sede fecundos e multiplicai-vos, e enchei as águas nos mares; e as aves se multipliquem na terra.",
    "E foi a tarde e a manhã, o dia quinto.",
    "E disse Deus: Produza a terra alma vivente conforme a sua espécie: gado, e réptil, e animal terrestre conforme a sua espécie; e assim foi.",
    "E fez Deus os animais terrestres conforme a sua espécie, e o gado conforme a sua espécie, e todo o réptil da terra conforme a sua espécie; e viu Deus que era bom.",
    "E disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; e domine sobre os peixes do mar, e sobre as aves dos céus, e sobre o gado, e sobre toda a terra, e sobre todo réptil que se move sobre a terra.",
    "E criou Deus o homem à sua imagem; à imagem de Deus o criou; homem e mulher os criou.",
    "E Deus os abençoou, e Deus lhes disse: Sede fecundos e multiplicai-vos, e enchei a terra e sujeitai-a; e dominai sobre os peixes do mar e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.",
    "E disse Deus: Eis que vos tenho dado toda a erva que dá semente, que está sobre a face de toda a terra; e toda a árvore em que há fruto de árvore que dá semente, ser-vos-ão para mantimento.",
    "E a todo o animal da terra, e a toda a ave dos céus, e a todo réptil que se move sobre a terra, em que há alma vivente, toda a erva verde lhes será para mantimento; e assim foi.",
    "E viu Deus tudo o que tinha feito, e eis que era muito bom; e foi a tarde e a manhã, o dia sexto.",
  ],
  2: [
    "Assim os céus e a terra foram acabados, e todo o seu exército.",
    "E havendo Deus acabado no dia sétimo a obra que fizera, descansou no sétimo dia de toda a sua obra que tinha feito.",
    "E Deus abençoou o dia sétimo, e o santificou; porque nele descansou de toda a sua obra que Deus criara e fizera.",
    "Estas são as origens dos céus e da terra quando foram criados, no dia em que o SENHOR Deus fez a terra e os céus.",
    "E toda a planta do campo antes que estivesse na terra, e toda a erva do campo antes que crescesse; porque o SENHOR Deus ainda não tinha feito chover sobre a terra, e não havia homem para lavrar a terra.",
    "Mas subia um vapor da terra e regava toda a face da terra.",
    "E formou o SENHOR Deus o homem do pó da terra, e soprou em suas narinas o fôlego da vida; e o homem foi feito alma vivente.",
    "E plantou o SENHOR Deus um jardim no Éden, do lado do oriente; e pôs ali o homem que tinha formado.",
    "E o SENHOR Deus fez brotar da terra toda a árvore agradável à vista, e boa para comida; e a árvore da vida no meio do jardim, e a árvore do conhecimento do bem e do mal.",
    "E saía um rio do Éden para regar o jardim; e dali se dividia e se tornava em quatro braços.",
    "O nome do primeiro é Pisom; este é o que rodeia toda a terra de Havilá, onde há ouro.",
    "E o ouro dessa terra é bom; ali há bdélio e pedra de ônix.",
    "E o nome do segundo rio é Giom; este é o que rodeia toda a terra de Cuxe.",
    "E o nome do terceiro rio é Tigre; este é o que corre ao oriente da Assíria. E o quarto rio é o Eufrates.",
    "E tomou o SENHOR Deus o homem, e o pôs no jardim do Éden para o lavrar e o guardar.",
    "E ordenou o SENHOR Deus ao homem, dizendo: De toda a árvore do jardim comerás livremente,",
    "Mas da árvore do conhecimento do bem e do mal, dela não comerás; porque no dia em que dela comeres, certamente morrerás.",
    "E disse o SENHOR Deus: Não é bom que o homem esteja só; far-lhe-ei uma ajudadora idônea.",
    "E o SENHOR Deus formou da terra todo o animal do campo, e toda a ave dos céus, e os trouxe a Adão para este ver como lhes chamaria; e tudo o que Adão chamou a toda a alma vivente, isso foi o seu nome.",
    "E Adão pôs os nomes a todo o gado, e às aves dos céus, e a todo o animal do campo; mas para Adão não se achava uma ajudadora que lhe fosse idônea.",
    "Então o SENHOR Deus fez cair um sono profundo sobre Adão, e este adormeceu; e tomou uma das suas costelas, e fechou a carne em seu lugar.",
    "E da costela que o SENHOR Deus tomou do homem, formou uma mulher, e trouxe-a ao homem.",
    "E disse Adão: Esta é agora osso dos meus ossos, e carne da minha carne; esta será chamada varoa, porquanto do varão foi tomada.",
    "Por isso deixará o homem o seu pai e a sua mãe, e se unirá à sua mulher, e serão ambos uma carne.",
    "E ambos estavam nus, o homem e a sua mulher, e não se envergonhavam.",
  ],
  3: [
    "Ora, a serpente era mais astuta do que todos os animais do campo que o SENHOR Deus tinha feito; e disse à mulher: É assim que Deus disse: Não comereis de toda a árvore do jardim?",
    "E disse a mulher à serpente: Do fruto das árvores do jardim comeremos;",
    "Mas do fruto da árvore que está no meio do jardim, disse Deus: Não comereis dele, nem nele tocareis, para que não morrais.",
    "Então a serpente disse à mulher: Certamente não morrereis.",
    "Porque Deus sabe que no dia em que dele comerdes se abrirão os vossos olhos, e sereis como Deus, sabendo o bem e o mal.",
    "E viu a mulher que a árvore era boa para se comer, e agradável aos olhos, e árvore desejável para dar entendimento; e tomou do seu fruto, e comeu, e deu também ao seu marido, e ele comeu.",
    "Então foram abertos os olhos de ambos, e conheceram que estavam nus; e coseram folhas de figueira, e fizeram para si aventais.",
    "E ouviram a voz do SENHOR Deus, que passeava no jardim pela viração do dia; e o homem e a sua mulher esconderam-se da presença do SENHOR Deus entre as árvores do jardim.",
    "E chamou o SENHOR Deus ao homem, e disse-lhe: Onde estás?",
    "E ele disse: Ouvi a tua voz no jardim, e temi, porque estava nu; por isso me escondi.",
    "E Deus disse: Quem te mostrou que estavas nu? Comeste da árvore de que te ordenei que não comesses?",
    "E disse o homem: A mulher que me deste por companheira, ela me deu da árvore, e eu comi.",
    "E disse o SENHOR Deus à mulher: Por que fizeste isso? E disse a mulher: A serpente me enganou, e eu comi.",
    "E o SENHOR Deus disse à serpente: Porquanto fizeste isso, maldita serás mais do que todo o animal doméstico, e mais do que todos os animais do campo; sobre o teu ventre andarás, e pó comerás todos os dias da tua vida.",
    "E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar.",
    "E à mulher disse: Multiplicarei grandemente a tua dor, e a tua conceição; com dor darás à luz filhos; e o teu desejo será para o teu marido, e ele te governará.",
    "E a Adão disse: Porquanto ouviste a voz de tua mulher, e comeste da árvore de que te ordenei, dizendo: Não comerás dela, maldita é a terra por causa de ti; com dor comerás dela todos os dias da tua vida.",
    "Espinhos e cardos também te produzirá; e comerás a erva do campo.",
    "No suor do teu rosto comerás o teu pão, até que tornes à terra; porque dela foste tomado; porquanto és pó, e em pó te tornarás.",
    "E chamou Adão o nome de sua mulher Eva; porque era a mãe de todos os viventes.",
    "E o SENHOR Deus fez túnicas de peles para Adão e para sua mulher, e os vestiu.",
    "E disse o SENHOR Deus: Eis que o homem é como um de nós, sabendo o bem e o mal; e agora, para que não estenda a sua mão, e tome também da árvore da vida, e coma, e viva para sempre,",
    "O SENHOR Deus mandou-o embora do jardim do Éden, para lavrar a terra de que foi tomado.",
    "E expulsou o homem; e pôs querubins ao oriente do jardim do Éden, e uma espada flamejante que se revolvia em todo sentido, para guardar o caminho da árvore da vida.",
  ],
  4: [
    "E conheceu Adão a Eva, sua mulher, e ela concebeu, e deu à luz a Caim, e disse: Alcancei do SENHOR um varão.",
    "E também deu à luz a Abel, seu irmão. E Abel foi pastor de ovelhas, e Caim foi lavrador da terra.",
    "E aconteceu ao cabo de dias que Caim trouxe do fruto da terra uma oferta ao SENHOR.",
    "E Abel trouxe também dos primogênitos das suas ovelhas, e da sua gordura. E atentou o SENHOR para Abel e para a sua oferta.",
    "Mas para Caim e para a sua oferta não atentou. E irou-se Caim fortemente, e descaiu o seu semblante.",
    "E o SENHOR disse a Caim: Por que te iraste? e por que descaiu o teu semblante?",
    "Se bem fizeres, não é certo que serás aceito? e se não fizeres bem, o pecado jaz à porta, e sobre ti será o seu desejo, mas sobre ele deves dominar.",
    "E falou Caim com o seu irmão Abel; e aconteceu que, estando eles no campo, se levantou Caim contra o seu irmão Abel, e o matou.",
    "E disse o SENHOR a Caim: Onde está Abel, teu irmão? E ele disse: Não sei; sou eu o guarda do meu irmão?",
    "E disse Deus: Que fizeste tu? A voz do sangue do teu irmão clama a mim desde a terra.",
    "E agora maldito és tu da terra, que abriu a sua boca para receber da tua mão o sangue de teu irmão.",
    "Quando lavrares a terra, não te tornará a dar a sua força; fugitivo e vagabundo serás na terra.",
    "E disse Caim ao SENHOR: A minha maldade é maior do que a que possa ser perdoada.",
    "Eis que hoje me expulsas da face da terra; e da tua face me esconderei, e serei fugitivo e vagabundo na terra; e será que todo aquele que me encontrar me matará.",
    "E o SENHOR lhe disse: Portanto, todo aquele que matar a Caim, sete vezes o padecerá. E pôs o SENHOR um sinal em Caim, para que não o ferisse todo aquele que o encontrasse.",
    "E saiu Caim de diante da face do SENHOR, e habitou na terra de Node, ao oriente do Éden.",
    "E conheceu Caim a sua mulher, e ela concebeu, e deu à luz a Enoque; e edificou uma cidade, e chamou o nome dessa cidade conforme o nome de seu filho, Enoque.",
    "E a Enoque nasceu Irade; e Irade gerou a Meujael; e Meujael gerou a Metusael; e Metusael gerou a Lameque.",
    "E tomou Lameque para si duas mulheres; o nome de uma era Ada, e o nome da outra Zilá.",
    "E Ada deu à luz a Jabal; este foi o pai dos que habitam em tendas, e criam gados.",
    "E o nome de seu irmão era Jubal; este foi o pai de todos os que tocam harpa e flauta.",
    "E Zilá também deu à luz a Tubalcaim, artífice de todo instrumento cortante, de bronze e de ferro; e a irmã de Tubalcaim era Naamá.",
    "E disse Lameque às suas mulheres: Ada e Zilá, ouvi a minha voz; mulheres de Lameque, escutai o meu dito; porque matei um homem por ferir-me, e um jovem por me pisar.",
    "Se Caim for vingado sete vezes, Lameque na verdade o será setenta e sete vezes.",
    "E conheceu Adão outra vez a sua mulher; e ela deu à luz um filho, e chamou o seu nome Sete; porque, disse ela, Deus me estabeleceu outra semente em lugar de Abel; pois Caim o matou.",
    "E a Sete também nasceu um filho, e chamou o seu nome Enos; então se começou a invocar o nome do SENHOR.",
  ],
  5: [
    "Este é o livro das gerações de Adão. No dia em que Deus criou o homem, à semelhança de Deus o fez.",
    "Homem e mulher os criou; e os abençoou, e chamou o seu nome Adão, no dia em que foram criados.",
    "E viveu Adão cento e trinta anos, e gerou um filho à sua semelhança, conforme a sua imagem; e chamou o seu nome Sete.",
    "E foram os dias de Adão, depois que gerou a Sete, oitocentos anos; e gerou filhos e filhas.",
    "Assim todos os dias que Adão viveu foram novecentos e trinta anos; e morreu.",
    "E viveu Sete cento e cinco anos, e gerou a Enos.",
    "E viveu Sete depois que gerou a Enos, oitocentos e sete anos; e gerou filhos e filhas.",
    "Assim todos os dias de Sete foram novecentos e doze anos; e morreu.",
    "E viveu Enos noventa anos, e gerou a Cainã.",
    "E viveu Enos depois que gerou a Cainã, oitocentos e quinze anos; e gerou filhos e filhas.",
    "Assim todos os dias de Enos foram novecentos e cinco anos; e morreu.",
    "E viveu Cainã setenta anos, e gerou a Maalaleel.",
    "E viveu Cainã depois que gerou a Maalaleel, oitocentos e quarenta anos; e gerou filhos e filhas.",
    "Assim todos os dias de Cainã foram novecentos e dez anos; e morreu.",
    "E viveu Maalaleel sessenta e cinco anos, e gerou a Jarede.",
    "E viveu Maalaleel depois que gerou a Jarede, oitocentos e trinta anos; e gerou filhos e filhas.",
    "Assim todos os dias de Maalaleel foram oitocentos e noventa e cinco anos; e morreu.",
    "E viveu Jarede cento e sessenta e dois anos, e gerou a Enoque.",
    "E viveu Jarede depois que gerou a Enoque, oitocentos anos; e gerou filhos e filhas.",
    "Assim todos os dias de Jarede foram novecentos e sessenta e dois anos; e morreu.",
    "E viveu Enoque sessenta e cinco anos, e gerou a Metusalém.",
    "E andou Enoque com Deus depois que gerou a Metusalém, trezentos anos; e gerou filhos e filhas.",
    "Assim todos os dias de Enoque foram trezentos e sessenta e cinco anos.",
    "E andou Enoque com Deus; e não apareceu mais, porque Deus o tomou.",
    "E viveu Metusalém cento e oitenta e sete anos, e gerou a Lameque.",
    "E viveu Metusalém depois que gerou a Lameque, setecentos e oitenta e dois anos; e gerou filhos e filhas.",
    "Assim todos os dias de Metusalém foram novecentos e sessenta e nove anos; e morreu.",
    "E viveu Lameque cento e oitenta e dois anos, e gerou um filho.",
    "E chamou o seu nome Noé, dizendo: Este nos consolará de nossas obras e da dor das nossas mãos, por causa da terra que o SENHOR amaldiçoou.",
    "E viveu Lameque depois que gerou a Noé, quinhentos e noventa e cinco anos; e gerou filhos e filhas.",
    "Assim todos os dias de Lameque foram setecentos e setenta e sete anos; e morreu.",
    "E tinha Noé quinhentos anos de idade, e Noé gerou a Sem, a Cam e a Jafé.",
  ],
  6: [
    "E aconteceu que, como os homens começaram a multiplicar-se sobre a face da terra, e lhes nasceram filhas,",
    "Viram os filhos de Deus que as filhas dos homens eram formosas, e tomaram para si mulheres de todas as que escolheram.",
    "E disse o SENHOR: Não contenderá o meu Espírito para sempre com o homem, porque ele também é carne; mas os seus dias serão cento e vinte anos.",
    "Havia naqueles dias gigantes na terra; e também depois, quando os filhos de Deus entraram às filhas dos homens, e elas lhes deram filhos; estes foram os poderosos que houve na antiguidade, os homens de renome.",
    "E viu o SENHOR que era grande a maldade do homem na terra, e que todo o propósito dos pensamentos do seu coração era só continuamente mau.",
    "E arrependeu-se o SENHOR de ter feito o homem na terra, e isso causou-lhe tristeza no coração.",
    "E disse o SENHOR: Destruirei o homem que criei da face da terra, desde o homem até ao animal, até ao réptil, e até à ave dos céus; porque me arrependo de os ter feito.",
    "Mas Noé achou graça aos olhos do SENHOR.",
    "Estas são as gerações de Noé. Noé era homem justo e perfeito em suas gerações; Noé andava com Deus.",
    "E Noé gerou três filhos: Sem, Cam e Jafé.",
    "E corrompeu-se a terra diante de Deus, e encheu-se de violência.",
    "E olhou Deus para a terra, e eis que estava corrompida; porque toda a carne havia corrompido o seu caminho sobre a terra.",
    "E disse Deus a Noé: O fim de toda a carne está diante de mim; porque a terra está cheia de violência diante deles; eis que os destruirei juntamente com a terra.",
    "Faze para ti uma arca de madeira de gófer; farás a arca com câmaras, e a calafetarás por dentro e por fora com betume.",
    "E desta forma a farás: de trezentos côvados o comprimento da arca, de cinquenta côvados a sua largura, e de trinta côvados a sua altura.",
    "Uma janela farás à arca, e de um côvado a acabarás por cima; e a porta da arca porás no seu lado; com câmaras inferiores, segundas e terceiras a farás.",
    "E eu, eis que faço vir um dilúvio de águas sobre a terra, para destruir toda a carne em que há fôlego de vida debaixo do céu; tudo o que há na terra morrerá.",
    "Mas contigo estabelecerei a minha aliança; e entrarás na arca, tu, e teus filhos, e tua mulher, e as mulheres de teus filhos contigo.",
    "E de todo o ser vivente, de toda a carne, dois de cada espécie farás entrar na arca, para os conservares vivos contigo; macho e fêmea serão.",
    "Das aves conforme a sua espécie, e dos animais conforme a sua espécie, de todo réptil da terra conforme a sua espécie; dois de cada um virão a ti, para os conservares vivos.",
    "E tu toma contigo de todo o mantimento que se come, e o ajuntarás a ti; e ser-te-á para mantimento, e a eles.",
    "E fez Noé conforme a tudo o que Deus lhe ordenou; assim o fez.",
  ],
  7: [
    "E disse o SENHOR a Noé: Entra tu, e toda a tua casa, na arca; porque a ti tenho visto justo diante de mim nesta geração.",
    "De todo o animal limpo tomar-te-ás sete pares, o macho e a sua fêmea; mas dos animais que não são limpos, um par, o macho e a sua fêmea.",
    "Também das aves dos céus sete pares, macho e fêmea, para manter a semente viva sobre a face de toda a terra.",
    "Porque, ao fim de sete dias ainda, farei chover sobre a terra quarenta dias e quarenta noites; e desfarei toda a substância que fiz de sobre a face da terra.",
    "E fez Noé conforme a tudo o que o SENHOR lhe ordenou.",
    "E era Noé da idade de seiscentos anos quando o dilúvio das águas veio sobre a terra.",
    "E entrou Noé, e seus filhos, e sua mulher, e as mulheres de seus filhos, com ele na arca, por causa das águas do dilúvio.",
    "Dos animais limpos e dos animais que não eram limpos, e das aves, e de todo o réptil que se move sobre a terra,",
    "Dois a dois entraram a Noé na arca, macho e fêmea, como Deus ordenara a Noé.",
    "E aconteceu que ao fim dos sete dias as águas do dilúvio vieram sobre a terra.",
    "No ano seiscentos da vida de Noé, no segundo mês, no dia dezessete do mês, nesse dia se romperam todas as fontes do grande abismo, e as janelas dos céus se abriram.",
    "E houve chuva sobre a terra quarenta dias e quarenta noites.",
    "Nesse mesmo dia entrou Noé, e Sem, e Cam, e Jafé, os filhos de Noé, e a mulher de Noé, e as três mulheres de seus filhos com eles, na arca.",
    "Eles e todos os animais conforme a sua espécie, e todo o gado conforme a sua espécie, e todo réptil que se move sobre a terra conforme a sua espécie, e toda a ave conforme a sua espécie, todo pássaro, tudo o que tem asas.",
    "E entraram a Noé na arca, dois a dois, de toda a carne em que há fôlego de vida.",
    "E os que entraram, macho e fêmea de toda a carne, entraram como Deus lhe ordenara; e o SENHOR fechou a porta sobre ele.",
    "E durou o dilúvio quarenta dias sobre a terra; e as águas cresceram, e levantaram a arca, e ela se elevou sobre a terra.",
    "E prevaleceram as águas, e cresceram muito sobre a terra; e a arca andava sobre a face das águas.",
    "E as águas prevaleceram grandissimamente sobre a terra; e foram cobertas todas as altas montanhas que havia debaixo de todo o céu.",
    "Quinze côvados acima prevaleceram as águas; e foram cobertas as montanhas.",
    "E morreu toda a carne que se movia sobre a terra: aves, e gado, e animais, e todo réptil que se move sobre a terra, e todo homem.",
    "Tudo o que havia no seco, tudo em cujas narinas havia fôlego de vida, morreu.",
    "E foi destruída toda a substância que havia sobre a face da terra, desde o homem até ao animal, até ao réptil, e até à ave dos céus; foram destruídos da terra; e ficou somente Noé, e os que com ele estavam na arca.",
    "E prevaleceram as águas sobre a terra cento e cinquenta dias.",
  ],
  8: [
    "E lembrou-se Deus de Noé, e de todos os animais, e de todo o gado que estava com ele na arca; e fez Deus passar um vento sobre a terra, e as águas abrandaram.",
    "E fecharam-se as fontes do abismo, e as janelas dos céus; e a chuva dos céus foi detida.",
    "E as águas foram descendo da terra progressivamente; e ao fim de cento e cinquenta dias as águas minguaram.",
    "E a arca repousou no sétimo mês, no dia dezessete do mês, sobre os montes de Ararate.",
    "E as águas foram minguando até ao décimo mês; no décimo mês, no primeiro dia do mês, apareceram os cumes dos montes.",
    "E aconteceu que ao fim de quarenta dias abriu Noé a janela da arca que tinha feito.",
    "E soltou um corvo, que saiu indo e voltando, até que as águas se secaram sobre a terra.",
    "E soltou uma pomba, para ver se as águas tinham diminuído sobre a face da terra.",
    "Mas a pomba não achou lugar onde pousasse o pé, e voltou a ele para a arca; porque as águas estavam sobre a face de toda a terra. E estendeu ele a mão, e pegou nela, e a recolheu consigo na arca.",
    "E esperou ainda outros sete dias, e tornou a soltar a pomba da arca.",
    "E a pomba voltou a ele à tarde; e eis uma folha de oliveira arrancada no seu bico; e entendeu Noé que as águas tinham diminuído sobre a terra.",
    "E esperou ainda outros sete dias, e soltou a pomba; e não voltou mais a ele.",
    "E aconteceu que no ano seiscentos e um, no primeiro mês, no primeiro dia do mês, as águas secaram sobre a terra; e removeu Noé a coberta da arca, e olhou, e eis que a face da terra estava enxuta.",
    "E no segundo mês, no dia vinte e sete do mês, a terra estava seca.",
    "E falou Deus a Noé, dizendo:",
    "Sai da arca, tu, e tua mulher, e teus filhos, e as mulheres de teus filhos contigo.",
    "Todo animal que está contigo, de toda a carne, tanto aves como animais e todo réptil que se move sobre a terra, faze sair contigo; e frutifiquem na terra, e se multipliquem sobre ela.",
    "E saiu Noé, e seus filhos, e sua mulher, e as mulheres de seus filhos com ele.",
    "Todos os animais, todo réptil, e toda ave, tudo o que se move sobre a terra, conforme as suas espécies, saíram da arca.",
    "E edificou Noé um altar ao SENHOR; e tomou de todo o animal limpo, e de toda a ave limpa, e ofereceu holocaustos sobre o altar.",
    "E o SENHOR cheirou o suave cheiro; e disse o SENHOR no seu coração: Não tornarei mais a amaldiçoar a terra por causa do homem, porque o intento do coração do homem é mau desde a sua meninice; não tornarei mais a ferir todo vivente, como fiz.",
    "Enquanto a terra durar, sementeira e ceifa, e frio e calor, e verão e inverno, e dia e noite, não cessarão.",
  ],
  9: [
    "E abençoou Deus a Noé e a seus filhos, e disse-lhes: Frutificai, e multiplicai-vos, e enchei a terra.",
    "E o temor de vós e o pavor de vós serão sobre todo o animal da terra, e sobre toda a ave dos céus; tudo o que se move sobre a terra, e todos os peixes do mar, nas vossas mãos são entregues.",
    "Todo réptil que vive, vos será para mantimento; assim como a erva verde, tudo vos dou.",
    "Mas a carne com sua alma, isto é, com seu sangue, não comereis.",
    "E certamente requererei o vosso sangue, o sangue das vossas almas; da mão de todo o animal o requererei; e da mão do homem, da mão de cada um seu irmão, requererei a alma do homem.",
    "Quem derramar o sangue do homem, pelo homem o seu sangue será derramado; porque Deus fez o homem à sua imagem.",
    "Mas vós frutificai, e multiplicai-vos; reproduzi-vos na terra, e multiplicai-vos nela.",
    "E falou Deus a Noé e a seus filhos com ele, dizendo:",
    "E eu, eis que estabeleço a minha aliança convosco, e com a vossa descendência depois de vós,",
    "E com todo o ser vivente que está convosco, tanto aves como animais domésticos e animais selvagens convosco; de tudo o que saiu da arca, até a todo o animal da terra.",
    "E estabelecerei a minha aliança convosco; e não será mais destruída toda a carne pelas águas do dilúvio, nem haverá mais dilúvio para destruir a terra.",
    "E disse Deus: Este é o sinal da aliança que eu faço entre mim e vós, e todo ser vivente que está convosco, por gerações perpétuas.",
    "Ponho o meu arco nas nuvens, e será por sinal de aliança entre mim e a terra.",
    "E acontecerá que quando eu trouxer nuvens sobre a terra, então se verá o arco nas nuvens.",
    "E lembrarei da minha aliança, que há entre mim e vós, e todo ser vivente de toda a carne; e as águas não se tornarão mais em dilúvio, para destruir toda a carne.",
    "E o arco estará nas nuvens; e ver-me-ei nele, para me lembrar da aliança perpétua entre Deus e todo o ser vivente, de toda a carne que há sobre a terra.",
    "E disse Deus a Noé: Este é o sinal da aliança que estabeleci entre mim e toda a carne que há sobre a terra.",
    "E os filhos de Noé, que saíram da arca, foram Sem, Cam e Jafé; e Cam é o pai de Canaã.",
    "Estes três foram os filhos de Noé; e destes se povoou toda a terra.",
    "E começou Noé a ser lavrador da terra, e plantou uma vinha.",
    "E bebeu do vinho, e embriagou-se; e descobriu-se no meio da sua tenda.",
    "E viu Cam, o pai de Canaã, a nudez de seu pai, e o contou a seus dois irmãos lá fora.",
    "E tomaram Sem e Jafé uma veste, e puseram-na nos dois ombros, e foram andando de costas, e cobriram a nudez de seu pai; e os seus rostos estavam virados, e não viram a nudez de seu pai.",
    "E despertou Noé do seu vinho, e soube o que o seu filho menor lhe fizera.",
    "E disse: Maldito seja Canaã; servo dos servos será a seus irmãos.",
    "E disse também: Bendito seja o SENHOR Deus de Sem; e seja Canaã servo seu.",
    "Deus dilatará a Jafé, e ele habitará nas tendas de Sem; e Canaã lhe será servo.",
    "E viveu Noé depois do dilúvio trezentos e cinquenta anos.",
    "Assim todos os dias de Noé foram novecentos e cinquenta anos; e morreu.",
  ],
  10: [
    "Estas são as gerações dos filhos de Noé: Sem, Cam e Jafé; e nasceram-lhes filhos depois do dilúvio.",
    "Os filhos de Jafé foram: Gômer, Magogue, Madai, Javã, Tubal, Meseque e Tiras.",
    "E os filhos de Gômer foram: Asquenaz, Rifate e Togarma.",
    "E os filhos de Javã foram: Elisá, Társis, Quitim e Dodanim.",
    "Destes se dividiram as ilhas dos gentios pelas suas terras; cada um conforme a sua língua, conforme as suas famílias, pelas suas nações.",
    "E os filhos de Cam foram: Cuxe, Mizraim, Pute e Canaã.",
    "E os filhos de Cuxe foram: Seba, Havilá, Sabtá, Raamá e Sabtecá; e os filhos de Raamá foram Sabá e Dedã.",
    "E Cuxe gerou a Ninrode; este começou a ser poderoso na terra.",
    "Este foi poderoso caçador diante do SENHOR; pelo que se diz: Como Ninrode, poderoso caçador diante do SENHOR.",
    "E o princípio do seu reino foi Babel, e Ereque, e Acade, e Calné, na terra de Sinar.",
    "Dessa terra saiu Assur, e edificou Nínive, e Reobote-Ir, e Calá,",
    "E Resém, entre Nínive e Calá; esta é a grande cidade.",
    "E Mizraim gerou a Ludim, e Anamim, e Leabim, e Naftuim,",
    "E Patrusim, e Casluim (dos quais saíram os filisteus) e Caftorim.",
    "E Canaã gerou a Sidom, seu primogênito, e a Hete,",
    "E ao jebuseu, e ao amorreu, e ao girgaseu,",
    "E ao heveu, e ao arqueu, e ao sineu,",
    "E ao arvadeu, e ao zemarreu, e ao hamateu; e depois se espalharam as famílias dos cananeus.",
    "E o limite dos cananeus foi desde Sidom, indo para Gerar até Gaza; indo para Sodoma, e Gomorra, e Admá, e Zeboim, até Lasa.",
    "Estes são os filhos de Cam, conforme as suas famílias, conforme as suas línguas, pelas suas terras e nações.",
    "Nasceram também filhos a Sem, o pai de todos os filhos de Héber, irmão mais velho de Jafé.",
    "Os filhos de Sem foram: Elão, Assur, Arfaxade, Lude e Arã.",
    "E os filhos de Arã foram: Uz, Hul, Geter e Mas.",
    "E Arfaxade gerou a Salá; e Salá gerou a Héber.",
    "E a Héber nasceram dois filhos; o nome de um foi Pelegue; porque em seus dias foi a terra dividida; e o nome de seu irmão era Joctã.",
    "E Joctã gerou a Almodade, e Salefe, e Hazarmavet, e Jeará,",
    "E Hadorão, e Uzal, e Dicla,",
    "E Obal, e Abimael, e Sabá,",
    "E Ofir, e Havilá, e Jobabe; todos estes foram filhos de Joctã.",
    "E a habitação deles foi desde Mesá, indo para Sefar, ao monte do oriente.",
    "Estes são os filhos de Sem, conforme as suas famílias, conforme as suas línguas, pelas suas terras e pelas suas nações.",
    "Estas são as famílias dos filhos de Noé, conforme as suas gerações pelas suas nações; e deles se dividiram as nações na terra depois do dilúvio.",
  ],
};
