import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_ESTER: Record<string, Record<number, BankQuestion[]>> = {
    ester: {
        1: [
            { question: "Qual era o nome do rei que reinou sobre cento e vinte e sete províncias, desde a Índia até a Etiópia?", answer: "Assuero (Xerxes)", distractors: ["Nabucodonosor", "Ciro"] },
            { question: "Onde se localizava o palácio real onde o rei Assuero deu o banquete?", answer: "Em Susã", distractors: ["Na Babilônia", "Em Persépolis"] },
            { question: "Por quantos dias durou o banquete que o rei deu a todo o povo em Susã?", answer: "Sete dias", distractors: ["Três dias", "Cento e oitenta dias"] },
            { question: "Qual era o nome da rainha que recusou o convite do rei Assuero para se apresentar no banquete?", answer: "Vasti", distractors: ["Ester", "Jezabel"] },
            { question: "O que o rei Assuero queria que a rainha Vasti fizesse?", answer: "Viesse perante o rei com a coroa real para mostrar sua beleza", distractors: ["Cantasse para os convidados", "Servisse vinho aos príncipes"] },
            { question: "Qual foi o conselho de Memucã sobre a recusa da rainha Vasti?", answer: "Que ela fosse deposta e sua dignidade real dada a outra melhor", distractors: ["Que ela fosse presa por trinta dias", "Que o rei pedisse desculpas publicamente"] },
            { question: "Por que os conselheiros do rei acharam que a atitude de Vasti era perigosa?", answer: "Porque todas as mulheres desprezariam seus maridos seguindo o exemplo dela", distractors: ["Porque ela conspirava com os inimigos", "Porque ela havia quebrado uma lei religiosa"] },
            { question: "O que o decreto real enviado a todas as províncias determinava após o caso de Vasti?", answer: "Que cada homem fosse senhor em sua própria casa", distractors: ["Que as mulheres não podiam ir a banquetes", "Que todas as rainhas deveriam ser estrangeiras"] },
        ],
        2: [
            { question: "Como se chamava o primo de Ester que a criou como filha?", answer: "Mordecai", distractors: ["Hamã", "Hegai"] },
            { question: "Qual era o nome hebraico de Ester?", answer: "Hadassa", distractors: ["Sara", "Débora"] },
            { question: "De qual tribo de Israel descendia Mordecai?", answer: "Benjamim", distractors: ["Judá", "Levi"] },
            { question: "Quem era o guarda das mulheres no palácio de Susã?", answer: "Hegai", distractors: ["Meumã", "Hataca"] },
            { question: "Por quanto tempo as moças passavam por tratamentos de beleza antes de irem ao rei?", answer: "Doze meses", distractors: ["Seis meses", "Três meses"] },
            { question: "O que Ester não revelou a ninguém por ordem de Mordecai?", answer: "Seu povo e sua parentela (sua origem judaica)", distractors: ["Que sabia ler e escrever", "Seu verdadeiro nome"] },
            { question: "Qual conspiração Mordecai descobriu enquanto estava à porta do rei?", answer: "Dois oficiais planejavam assassinar o rei Assuero", distractors: ["Um plano para roubar o tesouro real", "Uma invasão dos exércitos gregos"] },
            { question: "Como se chamavam os dois oficiais que planejaram matar o rei?", answer: "Bigtã e Teres", distractors: ["Meumã e Bizta", "Carsena e Setar"] },
        ],
        3: [
            { question: "Quem o rei Assuero exaltou acima de todos os príncipes em seu reino?", answer: "Hamã, o agagita", distractors: ["Mordecai", "Memucã"] },
            { question: "Por que Hamã ficou cheio de furor contra Mordecai?", answer: "Porque Mordecai não se inclinava nem o reverenciava", distractors: ["Porque Mordecai o acusou de roubo", "Porque Mordecai queria o cargo dele"] },
            { question: "Qual era a origem de Hamã mencionada no texto?", answer: "Agagita", distractors: ["Amalequita", "Babilônio"] },
            { question: "O que Hamã planejou fazer como vingança contra Mordecai?", answer: "Destruir todos os judeus que havia em todo o reino", distractors: ["Prender Mordecai por toda a vida", "Expulsar Mordecai de Susã"] },
            { question: "Como foi escolhido o dia para a destruição dos judeus?", answer: "Lançando o Pur (sorte)", distractors: ["Consultando os astros", "Escolha pessoal de Hamã"] },
            { question: "Quanto Hamã prometeu pagar ao tesouro real para que o decreto contra os judeus fosse assinado?", answer: "Dez mil talentos de prata", distractors: ["Cem mil moedas de ouro", "Cinco mil talentos de ouro"] },
            { question: "Como as pessoas em Susã reagiram ao decreto de destruição?", answer: "A cidade de Susã estava perplexa (confusa)", distractors: ["Houve grande festa entre os persas", "Ninguém deu importância ao decreto"] },
            { question: "Para qual dia foi marcado o extermínio dos judeus?", answer: "O dia treze do décimo segundo mês (mês de Adar)", distractors: ["O primeiro dia do ano novo", "O dia sete do sétimo mês"] },
        ],
        4: [
            { question: "O que Mordecai fez ao saber do decreto de Hamã?", answer: "Rasgou suas vestes, vestiu-se de saco e cinza e clamou com grande clamor", distractors: ["Fugiu de Susã imediatamente", "Foi falar com o rei Assuero"] },
            { question: "Por que Ester não podia ir falar com o rei imediatamente?", answer: "Havia uma lei que punia com morte quem entrasse no pátio interior sem ser chamado", distractors: ["Ela estava doente e acamada", "O rei estava em viagem de guerra"] },
            { question: "Qual foi a resposta famosa de Mordecai a Ester sobre ela se calar naquele momento?", answer: "Quem sabe se para tal tempo como este chegaste a este reino?", distractors: ["Deus te enviará ao Egito se não ajudares", "O rei te matará se souber que és judia"] },
            { question: "O que Ester pediu que todos os judeus em Susã fizessem por ela?", answer: "Jejuassem por três dias e três noites", distractors: ["Orassem no templo de Jerusalém", "Fugissem para as montanhas"] },
            { question: "Qual frase Ester disse ao decidir ir ao rei, mesmo correndo risco de morte?", answer: "Se perecer, pereci", distractors: ["Deus é minha força", "Pela vida do meu povo"] },
            { question: "Quem era o oficial que servia de mediador entre Ester e Mordecai?", answer: "Hataca", distractors: ["Hegai", "Meumã"] },
            { question: "Há quanto tempo Ester não era chamada pelo rei quando Mordecai pediu sua ajuda?", answer: "Trinta dias", distractors: ["Três meses", "Um ano"] },
        ],
        5: [
            { question: "O que o rei Assuero estendeu para Ester quando ela apareceu no pátio interior?", answer: "O cetro de ouro", distractors: ["Sua mão direita", "Um anel de sinete"] },
            { question: "O que o rei prometeu dar a Ester, demonstrando seu favor?", answer: "Até a metade do reino", distractors: ["Ouro e prata em abundância", "O palácio de Vasti"] },
            { question: "Qual foi o primeiro pedido de Ester ao rei?", answer: "Que o rei e Hamã viessem a um banquete que ela preparara", distractors: ["Que o decreto contra os judeus fosse revogado", "Que Mordecai fosse nomeado príncipe"] },
            { question: "O que Hamã mandou construir por sugestão de sua mulher e amigos?", answer: "Uma forca de cinquenta côvados de altura", distractors: ["Uma estátua em sua própria honra", "Uma nova casa em Susã"] },
            { question: "Como se chamava a mulher de Hamã?", answer: "Zeres", distractors: ["Vasti", "Dalila"] },
            { question: "Por que a alegria de Hamã ao sair do banquete de Ester se transformou em ira?", answer: "Porque viu Mordecai à porta do rei e este não se levantou", distractors: ["Porque o rei não falou com ele no banquete", "Porque Ester não o serviu pessoalmente"] },
            { question: "O que os amigos de Hamã sugeriram que ele pedisse ao rei na manhã seguinte?", answer: "Que enforcassem Mordecai na forca que ele construíra", distractors: ["Que Mordecai fosse expulso do reino", "Que Mordecai fosse transformado em escravo"] },
        ],
        6: [
            { question: "O que o rei fez na noite em que não conseguiu dormir?", answer: "Mandou trazer o livro das crônicas e que se lesse diante dele", distractors: ["Chamou músicos para tocar harpa", "Saiu para caminhar nos jardins"] },
            { question: "O que o rei descobriu no livro das crônicas que não havia sido recompensado?", answer: "Que Mordecai denunciara a conspiração contra a vida do rei", distractors: ["Que Hamã havia roubado do tesouro", "Que Vasti queria voltar ao palácio"] },
            { question: "Quem estava no pátio do rei quando ele perguntou quem estava lá?", answer: "Hamã", distractors: ["Mordecai", "Ester"] },
            { question: "O que Hamã estava fazendo no pátio naquela manhã cedo?", answer: "Para pedir ao rei que Mordecai fosse enforcado", distractors: ["Para convidar o rei para caçar", "Para relatar as receitas do imposto"] },
            { question: "O que o rei perguntou a Hamã quando este entrou?", answer: "Que se faria ao homem a quem o rei deseja honrar?", distractors: ["Qual o preço da vida de um judeu?", "Como se deve construir uma forca real?"] },
            { question: "O que Hamã sugeriu como honra, pensando que o rei falava dele mesmo?", answer: "Vestes reais, cavalo real e a coroa, e ser conduzido por um príncipe", distractors: ["Metade das províncias do reino", "Ouro e o anel de sinete do rei"] },
            { question: "A quem o rei ordenou que Hamã prestasse essa honra?", answer: "A Mordecai, o judeu", distractors: ["Ao capitão da guarda", "Ao príncipe de Susã"] },
            { question: "O que Hamã teve que fazer com Mordecai pelas ruas da cidade?", answer: "Passeá-lo a cavalo e proclamar as honras do rei diante dele", distractors: ["Servir-lhe vinho e pão em público", "Lavar-lhe os pés na praça central"] },
        ],
        7: [
            { question: "O que Ester pediu ao rei Assuero durante o segundo banquete?", answer: "Sua vida e a vida do seu povo", distractors: ["O cargo de Hamã para Mordecai", "A construção de um templo em Susã"] },
            { question: "Quem Ester denunciou como o adversário e inimigo dos judeus?", answer: "Este mau Hamã", distractors: ["O oficial Bigtã", "A rainha Vasti"] },
            { question: "Como o rei reagiu à denúncia de Ester contra Hamã?", answer: "Levantou-se com furor e saiu para o jardim", distractors: ["Riu e disse que era uma brincadeira", "Mandou Ester para a prisão imediatamente"] },
            { question: "O que Hamã fez enquanto o rei estava no jardim?", answer: "Prostrou-se sobre o leito de Ester para rogar pela sua vida", distractors: ["Tentou fugir do palácio", "Escreveu um pedido de perdão"] },
            { question: "O que o rei disse ao voltar do jardim e ver Hamã sobre o leito de Ester?", answer: "Acaso quereria ele também forçar a rainha perante mim?", distractors: ["Levantem este homem e levem-no embora", "Hamã, você é um traidor!"] },
            { question: "Qual foi o fim de Hamã?", answer: "Foi enforcado na mesma forca que preparara para Mordecai", distractors: ["Foi expulso para o deserto", "Foi decapitado na praça real"] },
            { question: "Quem contou ao rei sobre a forca que Hamã havia construído?", answer: "Harbona, um dos oficiais", distractors: ["Ester", "Mordecai"] },
        ],
        8: [
            { question: "O que o rei deu a Ester após a morte de Hamã?", answer: "A casa (os bens) de Hamã", distractors: ["O anel de sinete", "A província de Babilônia"] },
            { question: "O que o rei entregou a Mordecai que antes pertencera a Hamã?", answer: "O seu anel de sinete", distractors: ["As vestes de príncipe", "A coroa real"] },
            { question: "Por que o primeiro decreto de Hamã contra os judeus não podia ser simplesmente cancelado?", answer: "Porque a escrita assinada em nome do rei e selada não se podia revogar", distractors: ["Porque os judeus já haviam fugido", "Porque a lei persa proibia mudar decretos no mesmo ano"] },
            { question: "Qual foi a solução do rei para ajudar os judeus contra o decreto de Hamã?", answer: "Dar aos judeus o direito de se reunirem e se defenderem com as armas", distractors: ["Pedir que se escondessem em cavernas", "Pagar resgate por cada judeu capturado"] },
            { question: "Como os judeus reagiram ao novo decreto favorável enviado por Mordecai?", answer: "Houve para os judeus luz, alegria, gozo e honra", distractors: ["Ficaram ainda mais amedrontados", "Foram embora da Pérsia imediatamente"] },
            { question: "O que aconteceu com muitos povos da terra após o decreto de Mordecai?", answer: "Tornaram-se judeus, porque o temor dos judeus caíra sobre eles", distractors: ["Atacaram os judeus de surpresa", "Fugiram para o Egito"] },
            { question: "Como foram enviadas as cartas com o novo decreto para todas as províncias?", answer: "Por correios a cavalo, em ginetes e dromedários", distractors: ["Por navios através do golfo", "Por pombos correios treinados"] },
        ],
        9: [
            { question: "O que aconteceu no dia treze do mês de Adar, marcado por Hamã para o massacre?", answer: "Os judeus dominaram sobre os que os odiavam", distractors: ["Os judeus foram capturados em massa", "Houve um grande eclipse solar"] },
            { question: "Quantos homens os judeus mataram em Susã no primeiro dia de combate?", answer: "Quinhentos homens", distractors: ["Cem homens", "Mil homens"] },
            { question: "O que aconteceu com os dez filhos de Hamã?", answer: "Foram mortos e enforcados no madeiro", distractors: ["Foram exilados para a Índia", "Foram perdoados por Ester"] },
            { question: "Sobre o que os judeus não estenderam a mão durante a vitória?", answer: "Sobre o despojo (saque)", distractors: ["Sobre as crianças e idosos", "Sobre os templos persas"] },
            { question: "Qual é o nome da festa instituída para comemorar o livramento dos judeus?", answer: "Purim", distractors: ["Páscoa", "Tabernáculos"] },
            { question: "O que significa o nome 'Purim'?", answer: "Por causa da palavra Pur (sorte)", distractors: ["Lugar de vitória", "Vaso de bênçãos"] },
            { question: "Como Purim devia ser celebrado, segundo a ordem de Mordecai?", answer: "Como dias de banquete, alegria e mandar presentes e dádivas aos pobres", distractors: ["Como dias de jejum e lamento absoluto", "Como dias de silêncio e reflexão no templo"] },
            { question: "Em quais dias do mês de Adar os judeus descansaram e celebraram Purim?", answer: "Nos dias catorze e quinze", distractors: ["Nos dias primeiro e segundo", "Nos dias dez e onze"] },
        ],
            10: [
            { question: "Como é descrito o governo do rei Assuero no capítulo final?", answer: "Impôs tributo sobre a terra e sobre as ilhas do mar", distractors: ["Ficou pobre após as guerras", "Libertou todas as províncias do imposto"] },
            { question: "Qual era a posição de Mordecai no reino após os eventos de Ester?", answer: "O segundo depois do rei Assuero", distractors: ["Governador de Susã apenas", "Sacerdote em Jerusalém"] },
            { question: "Onde foram escritas as grandezas de Mordecai e do rei?", answer: "No livro das crônicas dos reis da Média e da Pérsia", distractors: ["No livro de Ester apenas", "Em tábuas de pedra no deserto"] },
            { question: "Por que Mordecai era aceito pela multidão de seus irmãos?", answer: "Porque buscava o bem do seu povo e trabalhava pela prosperidade deles", distractors: ["Porque era o homem mais rico da Pérsia", "Porque havia vencido Hamã em combate"] },
            { question: "Quantos versículos tem o capítulo 10 de Ester?", answer: "Três versículos", distractors: ["Dez versículos", "Cinco versículos"] },
        ],
    },
};
