import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_NT_GENERAL: Record<string, Record<number, BankQuestion[]>> = {
  hebreus: {
    1: [
      { question: "Por meio de quem Deus falou aos pais nos últimos dias, segundo Hebreus 1?", answer: "Por meio do Filho", distractors: ["Por meio dos profetas", "Por meio dos anjos"] },
      { question: "Segundo Hebreus 1, o Filho é o resplendor de quê?", answer: "Da glória de Deus", distractors: ["Da sabedoria eterna", "Da graça divina"] },
      { question: "O que o Filho fez depois de realizar a purificação dos pecados, segundo Hebreus 1?", answer: "Assentou-se à direita da Majestade nas alturas", distractors: ["Voltou ao mundo", "Enviou o Espírito Santo"] },
      { question: "Em Hebreus 1, qual é a posição do Filho em relação aos anjos?", answer: "Ele é superior aos anjos", distractors: ["Ele é igual aos anjos", "Ele é inferior aos anjos"] },
      { question: "Segundo Hebreus 1, o que Deus disse ao Filho: 'O teu trono, ó Deus, permanece para sempre'?", answer: "É uma citação do Salmo que exalta o Filho acima dos anjos", distractors: ["É uma promessa feita a Davi", "É uma palavra dita aos profetas"] },
      { question: "Em Hebreus 1, o que são os anjos, segundo sua função?", answer: "Espíritos ministradores enviados para servir os que herdarão a salvação", distractors: ["Mensageiros apenas para os profetas", "Guardiões do trono celestial"] },
    ],
    2: [
      { question: "Hebreus 2 adverte que devemos prestar mais atenção às coisas que ouvimos para não quê?", answer: "Para não derivarmos", distractors: ["Para não pecarmos", "Para não esquecermos"] },
      { question: "Por que o Filho se fez um pouco menor do que os anjos, segundo Hebreus 2?", answer: "Para sofrer a morte e provar a morte por todos", distractors: ["Para ensinar a lei de Moisés", "Para receber louvor dos homens"] },
      { question: "Segundo Hebreus 2, mediante a morte Jesus destruiu quem tinha o poder da morte. Quem é esse?", answer: "O diabo", distractors: ["O pecado", "A lei"] },
      { question: "Em Hebreus 2, Jesus é chamado de quê em relação aos que santifica?", answer: "Não se envergonha de chamá-los de irmãos", distractors: ["Senhor e Mestre", "Rei e Salvador"] },
      { question: "Qual é a função de Jesus como sumo sacerdote misericordioso, segundo Hebreus 2?", answer: "Expiar os pecados do povo", distractors: ["Oferecer sacrifícios diários", "Ensinar a lei no templo"] },
      { question: "Segundo Hebreus 2, por que Jesus precisou ser feito semelhante aos irmãos?", answer: "Para ser um sumo sacerdote misericordioso e fiel", distractors: ["Para cumprir as profecias de Isaías", "Para provar que era humano"] },
    ],
    3: [
      { question: "Em Hebreus 3, quem é comparado a Moisés como aquele que foi fiel?", answer: "Jesus", distractors: ["Arão", "Josué"] },
      { question: "Qual é a diferença entre Moisés e Jesus segundo Hebreus 3?", answer: "Moisés foi fiel como servo, Jesus como Filho", distractors: ["Moisés foi profeta, Jesus foi sacerdote", "Moisés foi rei, Jesus foi servo"] },
      { question: "Hebreus 3 cita o Salmo 95: 'Hoje, se ouvirdes a sua voz, não endureçais...' referindo-se a qual evento histórico?", answer: "À rebelião de Israel no deserto", distractors: ["À construção do templo", "À conquista de Canaã"] },
      { question: "O que Hebreus 3 chama de 'mau coração de incredulidade'?", answer: "O que afasta o homem do Deus vivo", distractors: ["O que leva ao pecado de idolatria", "O que endurece diante da lei"] },
      { question: "Segundo Hebreus 3, por que a geração do deserto não entrou no repouso?", answer: "Por causa da incredulidade", distractors: ["Por causa da idolatria com o bezerro de ouro", "Por causa da desobediência a Moisés"] },
      { question: "Em Hebreus 3, com qual frequência somos exortados a nos encorajar uns aos outros?", answer: "Cada dia, enquanto ainda é chamado 'hoje'", distractors: ["Semanalmente", "Em cada reunião da assembleia"] },
    ],
    4: [
      { question: "Segundo Hebreus 4, o que permanece para o povo de Deus?", answer: "Um repouso sabático", distractors: ["Uma herança na terra prometida", "Uma nova aliança"] },
      { question: "Em Hebreus 4, a palavra de Deus é descrita como mais cortante do que quê?", answer: "Do que qualquer espada de dois gumes", distractors: ["Do que fogo do céu", "Do que pedras afiadas"] },
      { question: "Segundo Hebreus 4, nosso sumo sacerdote pode se compadecer das nossas fraquezas porque quê?", answer: "Foi tentado em tudo como nós, mas sem pecado", distractors: ["Conhece todos os nossos pensamentos", "Viveu entre os pobres e sofredores"] },
      { question: "O que Hebreus 4 nos exorta a fazer diante do trono da graça?", answer: "Chegar com confiança para obter misericórdia e graça", distractors: ["Trazer ofertas e sacrifícios", "Jejuar e orar em silêncio"] },
      { question: "Hebreus 4 diz que a palavra de Deus penetra até à divisão de quê?", answer: "Alma e espírito, juntas e medulas", distractors: ["Mente e vontade", "Coração e consciência"] },
      { question: "Segundo Hebreus 4, quem entrou no repouso de Deus cessou de suas obras assim como?", answer: "Como Deus cessou das suas", distractors: ["Como os anjos no céu", "Como Moisés no Sinai"] },
    ],
    5: [
      { question: "Segundo Hebreus 5, todo sumo sacerdote é constituído em favor dos homens para quê?", answer: "Para oferecer dons e sacrifícios pelos pecados", distractors: ["Para ensinar a lei ao povo", "Para abençoar as tribos de Israel"] },
      { question: "Em Hebreus 5, de qual ordem é o sacerdócio de Jesus?", answer: "Da ordem de Melquisedeque", distractors: ["Da ordem de Arão", "Da ordem de Levi"] },
      { question: "O que Hebreus 5 diz que Jesus aprendeu por meio do que padeceu?", answer: "A obediência", distractors: ["A humildade", "A misericórdia"] },
      { question: "Segundo Hebreus 5, quem é aquele que ainda precisa de leite e não de alimento sólido?", answer: "O que é inexperiente na palavra da justiça", distractors: ["O que ainda não foi batizado", "O que não leu as Escrituras"] },
      { question: "Em Hebreus 5, Jesus foi designado por Deus como sumo sacerdote, citando qual versículo dos Salmos?", answer: "'Tu és sacerdote eternamente, segundo a ordem de Melquisedeque'", distractors: ["'Tu és meu Filho amado, em quem me comprazo'", "'Assienta-te à minha direita'"] },
      { question: "Segundo Hebreus 5, os de idade madura têm os sentidos exercitados para discernir o quê?", answer: "O bem e o mal", distractors: ["O certo e o errado segundo a lei", "O espiritual e o carnal"] },
    ],
    6: [
      { question: "Hebreus 6 exorta a deixar os princípios elementares e avançar para quê?", answer: "Para a perfeição (maturidade)", distractors: ["Para o serviço sacerdotal", "Para a profecia"] },
      { question: "Segundo Hebreus 6, qual é o perigo descrito para aqueles que, após terem sido iluminados, se afastam?", answer: "É impossível renová-los outra vez para o arrependimento", distractors: ["Perderão sua herança na terra prometida", "Serão entregues a Satanás"] },
      { question: "Hebreus 6 compara a terra que bebe a chuva e produz ervas úteis a quê?", answer: "Aos que recebem a bênção de Deus", distractors: ["Aos que praticam obras de misericórdia", "Aos que guardam a lei"] },
      { question: "Segundo Hebreus 6, a promessa que Deus fez a Abraão foi confirmada por quê?", answer: "Por um juramento", distractors: ["Por um sacrifício", "Por um sinal no céu"] },
      { question: "Em Hebreus 6, a esperança é comparada a quê?", answer: "A uma âncora da alma", distractors: ["A um escudo de fé", "A uma luz no caminho"] },
      { question: "Segundo Hebreus 6, Jesus entrou como precursor por nós no lugar chamado quê?", answer: "Atrás do véu (lugar santíssimo)", distractors: ["No monte Sinai", "No templo de Jerusalém"] },
    ],
    7: [
      { question: "Quem era Melquisedeque segundo Hebreus 7?", answer: "Rei de Salém e sacerdote do Deus Altíssimo", distractors: ["Um anjo enviado por Deus", "Um profeta do tempo de Abraão"] },
      { question: "Segundo Hebreus 7, o que significa o nome 'Melquisedeque'?", answer: "Rei da justiça", distractors: ["Rei da paz", "Sacerdote eterno"] },
      { question: "Em Hebreus 7, qual a limitação do sacerdócio levítico que tornou necessário um novo sacerdote?", answer: "Ele não podia trazer a perfeição", distractors: ["Os sacerdotes morriam e precisavam ser substituídos", "O povo não obedecia aos sacerdotes"] },
      { question: "Segundo Hebreus 7, o sacerdócio de Jesus é permanente porque quê?", answer: "Ele vive para sempre", distractors: ["Ele foi consagrado por Deus no céu", "Ele nunca pecou"] },
      { question: "Em Hebreus 7, qual é a característica do sumo sacerdote que convinha a nós?", answer: "Santo, inocente, imaculado, separado dos pecadores", distractors: ["Rico em misericórdia e longanime", "Poderoso e glorioso"] },
      { question: "Segundo Hebreus 7, ao contrário dos sumo sacerdotes levíticos, Jesus ofereceu o sacrifício quantas vezes?", answer: "Uma única vez", distractors: ["Uma vez por ano", "Continuamente no céu"] },
    ],
    8: [
      { question: "Segundo Hebreus 8, onde está assentado o nosso sumo sacerdote?", answer: "À direita do trono da Majestade nos céus", distractors: ["No templo celestial", "Diante do altar de Deus"] },
      { question: "Em Hebreus 8, o ministério de Jesus é superior ao dos sacerdotes levíticos porque quê?", answer: "Ele é mediador de uma aliança melhor estabelecida em melhores promessas", distractors: ["Ele serve no templo real e não em cópia", "Ele intercede com palavras eternas"] },
      { question: "Hebreus 8 cita a profecia de Jeremias sobre a nova aliança. Onde Deus colocará suas leis?", answer: "Na mente e no coração deles", distractors: ["Nas pedras do templo", "Nos lábios dos sacerdotes"] },
      { question: "Segundo Hebreus 8, na nova aliança, o que todos saberão?", answer: "Todos me conhecerão, do menor ao maior", distractors: ["Todos guardarão o sábado", "Todos trarão ofertas ao templo"] },
      { question: "Em Hebreus 8, ao chamar de 'nova' a aliança, o que acontece com a primeira?", answer: "Ela se torna velha e está prestes a desaparecer", distractors: ["Ela é cumprida e permanece", "Ela é substituída mas ainda válida"] },
      { question: "Segundo Hebreus 8, o tabernáculo que os sacerdotes levíticos servem é cópia e sombra de quê?", answer: "Das coisas celestiais", distractors: ["Do templo de Salomão", "Da tenda de Moisés no Sinai"] },
    ],
    9: [
      { question: "Segundo Hebreus 9, o que estava no lugar santíssimo do tabernáculo?", answer: "A arca da aliança com o propiciatório de ouro", distractors: ["O altar de incenso de ouro", "O candelabro de ouro"] },
      { question: "Em Hebreus 9, com que frequência o sumo sacerdote entrava no lugar santíssimo?", answer: "Uma vez por ano", distractors: ["Uma vez por mês", "Apenas no Dia da Expiação de dez anos"] },
      { question: "Segundo Hebreus 9, o sangue de Cristo limpará a consciência de obras mortas para servir ao quê?", answer: "Ao Deus vivo", distractors: ["À lei de Moisés", "À comunidade dos santos"] },
      { question: "Em Hebreus 9, assim como os homens morrem uma vez e depois vem o julgamento, Cristo também foi oferecido quantas vezes?", answer: "Uma única vez", distractors: ["Sete vezes", "Continuamente no céu"] },
      { question: "Segundo Hebreus 9, por que um testamento só tem validade após a morte do testador?", answer: "Porque enquanto o testador vive, o testamento não tem força", distractors: ["Porque a lei exige confirmação por sacerdotes", "Porque os herdeiros precisam aceitar"] },
      { question: "Em Hebreus 9, com o que Moisés aspergiu o povo e o livro da lei?", answer: "Com sangue misturado com água, lã escarlate e hissopo", distractors: ["Com azeite e sangue de boi", "Com sangue de cordeiro e sal"] },
    ],
    10: [
      { question: "Segundo Hebreus 10, a lei é sombra dos bens vindouros, não a própria imagem. O que isso significa?", answer: "Os sacrifícios repetidos não podiam aperfeiçoar os adoradores", distractors: ["A lei foi dada provisoriamente", "Os profetas superavam a lei"] },
      { question: "Em Hebreus 10, o que Jesus disse ao entrar no mundo, citando o Salmo 40?", answer: "'Eis que venho para fazer a tua vontade'", distractors: ["'Eis que subo ao templo para me oferecer'", "'Eis que vim abolir a lei e os profetas'"] },
      { question: "Segundo Hebreus 10, após o único sacrifício de Cristo, o que ele fez?", answer: "Assentou-se para sempre à direita de Deus", distractors: ["Voltou ao mundo por quarenta dias", "Entrou no lugar santíssimo celestial"] },
      { question: "Hebreus 10 exorta a não abandonar a assembleia dos crentes. Com o que compara quem persiste no pecado deliberado?", answer: "Não resta mais sacrifício pelos pecados, mas expectativa terrível de julgamento", distractors: ["Será entregue ao diabo para correção", "Perderá a herança mas será salvo"] },
      { question: "Em Hebreus 10, qual é a exortação ao ver o dia se aproximando?", answer: "Estimular uns aos outros ao amor e às boas obras, não abandonando a assembleia", distractors: ["Dobrar os joelhos e jejuar quarenta dias", "Oferecer sacrifícios de louvor continuamente"] },
      { question: "Segundo Hebreus 10, 'Minha é a vingança; eu darei a recompensa' é citado para demonstrar quê?", answer: "Que é terrível cair nas mãos do Deus vivo", distractors: ["Que Deus protegerá os crentes", "Que o julgamento final pertence a Cristo"] },
    ],
    11: [
      { question: "Como Hebreus 11 define a fé?", answer: "A certeza das coisas que se esperam e a convicção das coisas que não se veem", distractors: ["A confiança plena em Deus e em sua palavra", "O amor que supera o entendimento humano"] },
      { question: "Segundo Hebreus 11, Abel ofereceu a Deus um sacrifício mais excelente que Caim por quê?", answer: "Pela fé", distractors: ["Pela obediência à lei", "Por ser o primogênito"] },
      { question: "Em Hebreus 11, o que aconteceu com Enoque por causa da fé?", answer: "Foi trasladado para não ver a morte", distractors: ["Foi levado ao céu em carruagem de fogo", "Recebeu vida eterna sem morrer"] },
      { question: "Segundo Hebreus 11, Abraão obedeceu, saindo sem saber para onde ia. O que esperava?", answer: "A cidade que tem fundamentos, cujo arquiteto e construtor é Deus", distractors: ["A terra prometida de Canaã para seus descendentes", "A ressurreição dos mortos"] },
      { question: "Em Hebreus 11, o que Moisés escolheu suportar, preferindo ao invés dos prazeres temporários do pecado?", answer: "Os maus-tratos com o povo de Deus", distractors: ["A pobreza e o exílio no deserto", "A perseguição dos faraós"] },
      { question: "Hebreus 11 menciona heroínas e heróis que 'não receberam o que foi prometido'. Por quê?", answer: "Porque Deus proveu algo melhor para nós, para que não fossem aperfeiçoados sem nós", distractors: ["Porque morreram antes do cumprimento", "Porque não tiveram fé suficiente"] },
    ],
    12: [
      { question: "Hebreus 12 nos exorta a correr a corrida com perseverança, olhando para quem?", answer: "Para Jesus, autor e consumador da fé", distractors: ["Para os heróis da fé do capítulo 11", "Para os apóstolos e profetas"] },
      { question: "Segundo Hebreus 12, por que o Senhor disciplina aqueles que ama?", answer: "Porque disciplina todo filho que recebe", distractors: ["Para que não pequem mais gravemente", "Para que se lembrem de suas obrigações"] },
      { question: "Em Hebreus 12, para qual monte nos aproximamos sob a nova aliança, em contraste com o Sinai?", answer: "Ao monte Sião e à cidade do Deus vivo, a Jerusalém celestial", distractors: ["Ao monte das Oliveiras", "Ao monte Carmelo"] },
      { question: "Hebreus 12 cita a história de Esaú como advertência. O que ele vendeu?", answer: "Seu direito de primogenitura por uma única refeição", distractors: ["Sua herança por prata", "Sua bênção por comida e bebida"] },
      { question: "Segundo Hebreus 12, busquemos a santidade sem a qual ninguém verá quê?", answer: "O Senhor", distractors: ["O reino de Deus", "A glória celestial"] },
      { question: "Em Hebreus 12, 'nosso Deus é um fogo consumidor' é usada como exortação a quê?", answer: "A servir a Deus com reverência e temor", distractors: ["A temer o julgamento dos ímpios", "A oferecer sacrifícios com fervor"] },
    ],
    13: [
      { question: "Segundo Hebreus 13, como deve ser o amor fraternal?", answer: "Permanente", distractors: ["Condicional", "Crescente"] },
      { question: "Em Hebreus 13, qual é a exortação sobre o casamento?", answer: "Que o casamento seja honrado por todos e o leito matrimonial imaculado", distractors: ["Que os casados obedeçam aos líderes da igreja", "Que os casados jejuem e orem juntos"] },
      { question: "Hebreus 13 diz: 'O Senhor é o meu ajudador; não temerei.' Isso nos liberta do quê?", answer: "Do amor ao dinheiro e da avareza", distractors: ["Do temor dos inimigos", "Da preocupação com o futuro"] },
      { question: "Segundo Hebreus 13, Jesus sofreu fora das portas da cidade para quê?", answer: "Para santificar o povo pelo próprio sangue", distractors: ["Para cumprir a profecia de Isaías 53", "Para ser visto por toda a multidão"] },
      { question: "Em Hebreus 13, qual sacrifício agrada a Deus?", answer: "O sacrifício de louvor — fruto dos lábios que confessam o seu nome", distractors: ["O sacrifício de animais no templo", "O sacrifício do jejum e da oração"] },
      { question: "Segundo Hebreus 13, obedecei aos vossos líderes e sede submissos a eles porque quê?", answer: "Eles velam por vossas almas como quem há de prestar contas", distractors: ["Eles foram ungidos por Deus para governar", "Eles receberam o Espírito Santo em plenitude"] },
    ],
  },

  tiago: {
    1: [
      { question: "Segundo Tiago 1, como devemos encarar as diversas provações?", answer: "Com toda alegria", distractors: ["Com paciência e silêncio", "Com oração e jejum"] },
      { question: "Em Tiago 1, a quem Deus dá sabedoria?", answer: "A todo aquele que pede com fé, sem dubitar", distractors: ["Aos humildes e mansos", "Aos que estudam as Escrituras"] },
      { question: "Segundo Tiago 1, qual é a origem da tentação?", answer: "A própria concupiscência do homem que o atrai e seduz", distractors: ["O diabo que tenta os fiéis", "O mundo e seus prazeres"] },
      { question: "Em Tiago 1, qual é o processo que leva da concupiscência à morte?", answer: "A concupiscência concebe e dá à luz o pecado; o pecado consumado produz a morte", distractors: ["O pecado se enraíza e produz amargura e morte", "A tentação vence e gera rebeldia, e a rebeldia gera morte"] },
      { question: "Segundo Tiago 1, o que é ser 'ouvintes da palavra' sem praticá-la?", answer: "É enganar a si mesmo", distractors: ["É ser como a areia sem fundamento", "É como o ramo que não produz frutos"] },
      { question: "Em Tiago 1, a religião pura e imaculada diante de Deus inclui quê?", answer: "Visitar os órfãos e as viúvas na sua tribulação e guardar-se sem mácula do mundo", distractors: ["Orar, jejuar e dar esmolas em segredo", "Guardar o sábado e os mandamentos"] },
    ],
    2: [
      { question: "Segundo Tiago 2, o que é fazer acepção de pessoas?", answer: "É pecar e ser condenado pela lei como transgressor", distractors: ["É tratar os ricos melhor que os pobres", "É julgar pelos costumes e aparência"] },
      { question: "Em Tiago 2, Deus escolheu os pobres deste mundo para serem quê?", answer: "Ricos em fé e herdeiros do reino", distractors: ["Servos do evangelho", "Primeiros no reino dos céus"] },
      { question: "Segundo Tiago 2, qual é o mandamento real segundo a Escritura?", answer: "'Amarás o teu próximo como a ti mesmo'", distractors: ["'Amarás ao Senhor teu Deus de todo o coração'", "'Não farás mal ao próximo'"] },
      { question: "Em Tiago 2, a fé sem obras está morta. Qual exemplo é dado com Abraão?", answer: "Ele ofereceu seu filho Isaque no altar, e sua fé agiu junto com suas obras", distractors: ["Ele saiu de Ur pela fé sem saber o destino", "Ele circuncidou toda sua casa pela fé"] },
      { question: "Segundo Tiago 2, que exemplo de fé sem obras é dado para mostrar que os demônios também creem?", answer: "Os demônios creem e tremem, mas isso não os salva", distractors: ["Quem não pratica a misericórdia será julgado", "A fé morta não pode mover montanhas"] },
      { question: "Em Tiago 2, qual outro exemplo além de Abraão é citado sobre fé e obras?", answer: "Raabe, a meretriz, que hospedou os espias", distractors: ["Noé, que construiu a arca por fé", "Moisés, que creu e tirou Israel do Egito"] },
    ],
    3: [
      { question: "Segundo Tiago 3, nem todos devem se tornar o quê?", answer: "Mestres", distractors: ["Líderes da congregação", "Profetas"] },
      { question: "Em Tiago 3, a língua é comparada a quê para ilustrar seu poder destruidor?", answer: "A uma faísca de fogo que incendeia uma grande floresta", distractors: ["A uma espada de dois gumes", "A um veneno mortal que contamina o corpo"] },
      { question: "Segundo Tiago 3, qual é a contradição sobre a língua?", answer: "Com ela bendizemos a Deus e com ela amaldiçoamos os homens feitos à sua imagem", distractors: ["Ela é indomável mas devemos controlá-la", "Ela ora em línguas mas ofende o próximo"] },
      { question: "Em Tiago 3, a sabedoria que vem do alto é descrita com quais características?", answer: "Pura, pacífica, moderada, tratável, cheia de misericórdia e de bons frutos, sem parcialidade e sem hipocrisia", distractors: ["Poderosa, santa, justa e sem falha", "Humilde, mansa, generosa e fiel"] },
      { question: "Segundo Tiago 3, a língua é um mundo de iniquidade entre os membros do corpo. O que ela faz?", answer: "Contamina todo o corpo, inflama o curso da vida e é inflamada pelo inferno", distractors: ["Destrói amizades e famílias com sua maldade", "Engana o coração e perverte o entendimento"] },
      { question: "Em Tiago 3, a sabedoria terrena é descrita como quê?", answer: "Animal, diabólica", distractors: ["Vã e passageira", "Cega e orgulhosa"] },
    ],
    4: [
      { question: "Segundo Tiago 4, de onde vêm as guerras e contendas entre os crentes?", answer: "Das concupiscências que guerreiam nos membros", distractors: ["Da influência do diabo sobre os crentes", "Da falta de amor fraternal"] },
      { question: "Em Tiago 4, 'Deus resiste aos soberbos' e quê?", answer: "Dá graça aos humildes", distractors: ["Abençoa os mansos", "Exalta os humilhados"] },
      { question: "Segundo Tiago 4, o que significa ser 'amigo do mundo'?", answer: "Constituir-se inimigo de Deus", distractors: ["Amar as coisas materiais acima de Deus", "Servir a dois senhores"] },
      { question: "Em Tiago 4, qual é a exortação ao fazer planos para o futuro?", answer: "Dizer 'se o Senhor quiser' e vivermos e fizermos isso ou aquilo", distractors: ["Confiar em Deus e não fazer planos humanos", "Pedir sabedoria antes de qualquer decisão"] },
      { question: "Segundo Tiago 4, qual é o resultado de humilhar-se diante do Senhor?", answer: "Ele vos exaltará", distractors: ["Ele vos dará sabedoria", "Ele vos abençoará com riquezas"] },
      { question: "Em Tiago 4, aproximai-vos de Deus e quê acontecerá?", answer: "Ele se aproximará de vós", distractors: ["Ele vos ouvirá", "Ele vos dará o que pedirdes"] },
    ],
    5: [
      { question: "Segundo Tiago 5, a oração de fé cura o enfermo e quem o levantará?", answer: "O Senhor", distractors: ["O Espírito Santo", "Os anciãos da igreja"] },
      { question: "Em Tiago 5, quem é citado como exemplo de perseverança e sofrimento?", answer: "Jó", distractors: ["Abraão", "Moisés"] },
      { question: "Segundo Tiago 5, Elias era homem de igual natureza que nós. Quanto tempo suas orações fecharam o céu?", answer: "Três anos e seis meses", distractors: ["Quarenta dias e noites", "Sete anos"] },
      { question: "Em Tiago 5, qual é a instrução para os que estão enfermos na congregação?", answer: "Que chamem os anciãos da igreja para que orem por eles e os unjem com azeite", distractors: ["Que jejuem e orem pedindo cura", "Que confessem seus pecados ao sumo sacerdote"] },
      { question: "Segundo Tiago 5, o que os lavradores aguardam com paciência?", answer: "O precioso fruto da terra, esperando as chuvas temporã e serôdia", distractors: ["A colheita da primavera", "O vento favorável para a semeadura"] },
      { question: "Em Tiago 5, acima de tudo não jureis. O que deve ser dito?", answer: "O vosso 'sim' seja sim e o vosso 'não' seja não", distractors: ["Jurar somente pelo nome do Senhor", "Confirmar com testemunhas fiéis"] },
    ],
  },

  "1pedro": {
    1: [
      { question: "Segundo 1 Pedro 1, para que fomos regenerados para uma esperança viva?", answer: "Pela ressurreição de Jesus Cristo dos mortos", distractors: ["Pelo sangue de Cristo derramado na cruz", "Pela fé e pelo batismo"] },
      { question: "Em 1 Pedro 1, a herança que nos é reservada nos céus é descrita como quê?", answer: "Incorruptível, imaculada e imarcescível", distractors: ["Eterna, gloriosa e perfeita", "Santa, abundante e segura"] },
      { question: "Segundo 1 Pedro 1, com que fomos remidos da nossa vã maneira de viver?", answer: "Com o precioso sangue de Cristo, como de um cordeiro sem defeito e sem mácula", distractors: ["Com a graça de Deus por meio da fé", "Com o sacrifício de Cristo e a obediência da fé"] },
      { question: "Em 1 Pedro 1, toda a carne é como quê?", answer: "Como a erva, e toda a sua glória como a flor da erva", distractors: ["Como o vapor que logo se desvanece", "Como a sombra que passa"] },
      { question: "Segundo 1 Pedro 1, o que os profetas investigaram diligentemente sobre a salvação?", answer: "O tempo e as circunstâncias que o Espírito de Cristo neles indicava", distractors: ["Os sofrimentos de Cristo e a glória que se seguiria", "As profecias sobre o reino de Israel"] },
      { question: "Em 1 Pedro 1, qual é a exortação baseada no caráter de Deus?", answer: "'Sede santos, porque eu sou santo'", distractors: ["'Sede perfeitos como vosso Pai celestial é perfeito'", "'Sede misericordiosos como eu sou misericordioso'"] },
    ],
    2: [
      { question: "Segundo 1 Pedro 2, Jesus é a pedra angular escolhida e preciosa. O que acontece com quem crê nela?", answer: "Não será confundido", distractors: ["Será salvo e glorificado", "Receberá vida eterna"] },
      { question: "Em 1 Pedro 2, os crentes são chamados de quê?", answer: "Pedras vivas, sacerdócio real, nação santa, povo adquirido por Deus", distractors: ["Templo do Espírito Santo e povo eleito", "Filhos da luz e herdeiros do reino"] },
      { question: "Segundo 1 Pedro 2, qual é o propósito de ser 'povo adquirido por Deus'?", answer: "Proclamar as virtudes daquele que nos chamou das trevas para a sua luz maravilhosa", distractors: ["Guardar os mandamentos e fazer boas obras", "Ser testemunho entre as nações da terra"] },
      { question: "Em 1 Pedro 2, como devemos viver entre os gentios?", answer: "Com boa conduta para que, vendo as nossas boas obras, glorifiquem a Deus", distractors: ["Separados do mundo e de suas práticas", "Com humildade e serviço ao próximo"] },
      { question: "Segundo 1 Pedro 2, Cristo, quando era ultrajado, como respondia?", answer: "Não revidava o ultraje", distractors: ["Orava pelos seus perseguidores", "Confiava ao Pai que julgaria"] },
      { question: "Em 1 Pedro 2, 'pelas suas feridas fostes sarados' se refere a quê?", answer: "À cura espiritual pelo sacrifício de Cristo que levou nossos pecados na cruz", distractors: ["À cura física prometida aos fiéis", "À libertação dos sofrimentos eternos"] },
    ],
    3: [
      { question: "Segundo 1 Pedro 3, qual é a exortação às esposas sobre o comportamento com os maridos?", answer: "Que sejam submissas para ganhar os maridos sem palavras, pela conduta", distractors: ["Que orem pelo marido e o sirvam fielmente", "Que estudem as Escrituras juntos"] },
      { question: "Em 1 Pedro 3, o enfeite verdadeiro da mulher não deve ser externo, mas quê?", answer: "O homem interior e oculto do coração, com o espírito manso e quieto", distractors: ["A bondade e a fidelidade ao marido", "A sabedoria e o temor de Deus"] },
      { question: "Segundo 1 Pedro 3, como os maridos devem tratar as esposas?", answer: "Com consideração, como o vaso mais fraco, dando-lhes honra", distractors: ["Com amor e sacrifício como Cristo amou a Igreja", "Com paciência e ensinando a palavra"] },
      { question: "Em 1 Pedro 3, qual é a promessa para quem ama a vida e quer ver dias bons?", answer: "Que refreie a língua do mal, aparte-se do mal, faça o bem e busque a paz", distractors: ["Que ore continuamente e confie no Senhor", "Que guarde os mandamentos e seja fiel"] },
      { question: "Segundo 1 Pedro 3, estarmos prontos para dar resposta a todo que nos pede razão da esperança que há em nós deve ser feito com quê?", answer: "Com mansidão e reverência", distractors: ["Com firmeza e sabedoria", "Com amor e paciência"] },
      { question: "Em 1 Pedro 3, Cristo morreu uma vez pelos pecados, o justo pelos injustos, para nos quê?", answer: "Para nos apresentar a Deus", distractors: ["Para nos libertar da condenação eterna", "Para nos dar vida abundante"] },
    ],
    4: [
      { question: "Segundo 1 Pedro 4, qual é a ideia central sobre o sofrimento físico?", answer: "Quem sofreu na carne cessou do pecado", distractors: ["Quem sofre por Cristo recebe recompensa no céu", "O sofrimento purifica a fé do crente"] },
      { question: "Em 1 Pedro 4, como devemos ser em relação às orações?", answer: "Sóbrios e moderados", distractors: ["Persistentes e fervorosos", "Humildes e confiantes"] },
      { question: "Segundo 1 Pedro 4, o amor cobre o quê?", answer: "Multidão de pecados", distractors: ["Todas as ofensas do passado", "Os erros e fraquezas do próximo"] },
      { question: "Em 1 Pedro 4, se alguém sofre como cristão, o que deve fazer?", answer: "Não se envergonhe, mas glorifique a Deus nesse nome", distractors: ["Rejoice e suporte com paciência", "Ore e confie na proteção divina"] },
      { question: "Segundo 1 Pedro 4, o julgamento começa por quem?", answer: "Pela casa de Deus", distractors: ["Pelos ímpios e pecadores", "Pelos que negam o nome de Cristo"] },
      { question: "Em 1 Pedro 4, qual é a exortação sobre a hospitalidade?", answer: "Sede hospitaleiros uns para com os outros, sem murmuração", distractors: ["Recebei os irmãos com alegria e boa vontade", "Abri vossas casas para os necessitados"] },
    ],
    5: [
      { question: "Segundo 1 Pedro 5, como os anciãos devem apascentar o rebanho de Deus?", answer: "Não por obrigação, mas de boa vontade; não por ganância, mas com prontidão", distractors: ["Com autoridade e sabedoria das Escrituras", "Com oração e ensino fiel da palavra"] },
      { question: "Em 1 Pedro 5, os jovens devem se sujeitar a quem?", answer: "Aos anciãos", distractors: ["Aos líderes espirituais designados", "Aos pais e mestres da lei"] },
      { question: "Segundo 1 Pedro 5, o diabo anda em derredor como quê?", answer: "Como leão que ruge, procurando alguém para devorar", distractors: ["Como serpente que engana", "Como lobo que ataca o rebanho"] },
      { question: "Em 1 Pedro 5, lançai sobre ele toda a vossa ansiedade. Por quê?", answer: "Porque ele tem cuidado de vós", distractors: ["Porque ele é poderoso para ajudar", "Porque ele conhece todas as nossas necessidades"] },
      { question: "Segundo 1 Pedro 5, depois de haverdes sofrido um pouco, o Deus de toda a graça fará quê?", answer: "Ele mesmo vos aperfeiçoará, confirmará, fortalecerá e estabelecerá", distractors: ["Vos libertará de todo sofrimento e angústia", "Vos dará vitória sobre os inimigos"] },
      { question: "Em 1 Pedro 5, a saudação final é enviada de quê lugar?", answer: "De Babilônia (provavelmente Roma)", distractors: ["De Jerusalém, mãe de todas as igrejas", "De Antioquia, onde eram chamados cristãos"] },
    ],
  },

  "2pedro": {
    1: [
      { question: "Segundo 2 Pedro 1, por meio de que nos foram dadas as preciosas e grandíssimas promessas?", answer: "Para que por elas sejamos participantes da natureza divina", distractors: ["Para que vivamos segundo a vontade de Deus", "Para que sejamos salvos e santificados"] },
      { question: "Em 2 Pedro 1, qual é a escada de virtudes que devemos acrescentar à fé?", answer: "Virtude, conhecimento, domínio próprio, perseverança, piedade, fraternidade e amor", distractors: ["Humildade, oração, serviço, fidelidade e esperança", "Graça, paz, fé, esperança e amor"] },
      { question: "Segundo 2 Pedro 1, Pedro diz que em breve deixará o seu tabernáculo. O que isso significa?", answer: "Que ele morreria em breve", distractors: ["Que partiria em viagem missionária", "Que se afastaria do ministério"] },
      { question: "Em 2 Pedro 1, a profecia da Escritura não é de interpretação particular porque quê?", answer: "Homens santos falaram da parte de Deus movidos pelo Espírito Santo", distractors: ["Ela pertence à toda a Igreja de Cristo", "Somente os apóstolos podem interpretá-la"] },
      { question: "Segundo 2 Pedro 1, qual experiência confirma a majestade de Cristo que Pedro testemunhou?", answer: "A transfiguração no monte santo", distractors: ["A ressurreição de Cristo no terceiro dia", "Os milagres que Jesus realizou na Galileia"] },
      { question: "Em 2 Pedro 1, a palavra profética é como quê para nós?", answer: "Como uma lâmpada que brilha em lugar escuro", distractors: ["Como fogo que purifica o coração", "Como água que sacia a alma sedienta"] },
    ],
    2: [
      { question: "Segundo 2 Pedro 2, como os falsos profetas introduzirão heresias destruidoras?", answer: "Dissimuladamente, negando o Senhor que os resgatou", distractors: ["Abertamente, com doutrinas de demônios", "Com sinais e maravilhas enganosas"] },
      { question: "Em 2 Pedro 2, qual exemplo de julgamento divino no passado é citado primeiro?", answer: "Os anjos que pecaram, lançados para o inferno", distractors: ["Adão e Eva expulsos do paraíso", "Caim que matou Abel e foi amaldiçoado"] },
      { question: "Segundo 2 Pedro 2, Ló era um homem justo que se afligia com quê?", answer: "Com a dissoluta conduta dos ímpios de Sodoma", distractors: ["Com a violência dos cananeus ao redor", "Com a idolatria dos habitantes da planície"] },
      { question: "Em 2 Pedro 2, os falsos mestres são comparados a quê?", answer: "A cão que volta ao próprio vômito e a porca lavada que se volta a revolver no charco", distractors: ["A lobos em pele de ovelha", "A árvores sem fruto duas vezes mortas"] },
      { question: "Segundo 2 Pedro 2, os falsos mestres prometem liberdade mas eles mesmos são quê?", answer: "Escravos da corrupção", distractors: ["Servos do diabo", "Prisioneiros de suas próprias cobiças"] },
      { question: "Em 2 Pedro 2, qual é o estado final do que conheceu o caminho da justiça e se afastou?", answer: "O último estado lhe é pior do que o primeiro", distractors: ["Não terá mais possibilidade de arrependimento", "Será julgado mais severamente no último dia"] },
    ],
    3: [
      { question: "Segundo 2 Pedro 3, os escarnecedores do fim dos tempos dirão quê?", answer: "'Onde está a promessa da sua vinda? Pois desde que os pais dormiram, tudo permanece como desde o princípio'", distractors: ["'Deus não intervém nos assuntos dos homens'", "'A ressurreição dos mortos é um conto de fadas'"] },
      { question: "Em 2 Pedro 3, mil anos são como o quê diante do Senhor?", answer: "Como um dia", distractors: ["Como uma hora", "Como uma vigília na noite"] },
      { question: "Segundo 2 Pedro 3, por que o Senhor não retarda a promessa?", answer: "Porque é longânimo para convosco, não querendo que nenhum pereça, mas que todos se arrependam", distractors: ["Porque o tempo de Deus é diferente do tempo humano", "Porque aguarda o número completo dos eleitos"] },
      { question: "Em 2 Pedro 3, como virá o dia do Senhor?", answer: "Como ladrão", distractors: ["Com grande estrondo e trovões", "Com sinais no sol, lua e estrelas"] },
      { question: "Segundo 2 Pedro 3, o que acontecerá com os céus e a terra no dia do Senhor?", answer: "Os céus passarão com grande estrépito e os elementos se desfarão abrasados", distractors: ["Serão renovados por fogo purificador", "Desaparecerão e darão lugar ao novo céu e nova terra"] },
      { question: "Em 2 Pedro 3, o que esperamos segundo a promessa de Deus?", answer: "Novos céus e nova terra, nos quais habita a justiça", distractors: ["A ressurreição dos mortos e o julgamento final", "A volta de Cristo em glória e poder"] },
    ],
  },

  "1joao": {
    1: [
      { question: "Segundo 1 João 1, o que João declara ter visto, ouvido e tocado com as mãos?", answer: "O Verbo da vida — Jesus Cristo", distractors: ["As maravilhas do Espírito Santo", "As palavras proféticas cumpridas em Cristo"] },
      { question: "Em 1 João 1, Deus é luz e nele não há trevas nenhumas. O que significa andar na luz?", answer: "Ter comunhão uns com os outros e o sangue de Jesus nos purificar de todo pecado", distractors: ["Guardar os mandamentos e evitar o pecado", "Viver em amor e serviço ao próximo"] },
      { question: "Segundo 1 João 1, se dissermos que não temos pecado, o que fazemos?", answer: "Enganamos a nós mesmos e a verdade não está em nós", distractors: ["Blasfemamos contra o Espírito Santo", "Negamos a necessidade do sacrifício de Cristo"] },
      { question: "Em 1 João 1, se confessarmos os nossos pecados, Deus é fiel e justo para quê?", answer: "Para nos perdoar e nos purificar de toda injustiça", distractors: ["Para nos restituir a comunhão com ele", "Para nos livrar do poder do pecado"] },
      { question: "Segundo 1 João 1, qual é o propósito de João ao escrever essas coisas?", answer: "Para que a nossa alegria seja completa", distractors: ["Para que não pequemos contra Deus", "Para que permaneçamos na fé"] },
      { question: "Em 1 João 1, ter comunhão com Deus enquanto andamos nas trevas é quê?", answer: "Mentira — não praticamos a verdade", distractors: ["Hipocrisia religiosa", "Incredulidade disfarçada"] },
    ],
    2: [
      { question: "Segundo 1 João 2, se alguém pecar, quem é o nosso advogado junto ao Pai?", answer: "Jesus Cristo, o justo", distractors: ["O Espírito Santo intercessor", "Os anjos que ministram diante de Deus"] },
      { question: "Em 1 João 2, como sabemos que conhecemos a Cristo?", answer: "Se guardarmos os seus mandamentos", distractors: ["Se tivermos o Espírito Santo em nós", "Se amarmos os irmãos de coração"] },
      { question: "Segundo 1 João 2, o amor ao mundo inclui quê?", answer: "A concupiscência da carne, a concupiscência dos olhos e a soberba da vida", distractors: ["O dinheiro, o prazer e o poder", "As riquezas, a glória e os prazeres"] },
      { question: "Em 1 João 2, o que é o anticristo?", answer: "Quem nega o Pai e o Filho", distractors: ["Quem se opõe à Igreja de Cristo", "O inimigo que virá no fim dos tempos"] },
      { question: "Segundo 1 João 2, quem é o mentiroso?", answer: "Quem nega que Jesus é o Cristo", distractors: ["Quem pratica o pecado continuamente", "Quem rejeita o testemunho dos apóstolos"] },
      { question: "Em 1 João 2, não ameis o mundo nem as coisas do mundo. Por quê?", answer: "Porque se alguém ama o mundo, o amor do Pai não está nele", distractors: ["Porque o mundo passará com todos os seus desejos", "Porque o amor ao mundo nos afasta da oração"] },
    ],
    3: [
      { question: "Segundo 1 João 3, qual é o grande amor que o Pai nos manifestou?", answer: "Que nos chamemos filhos de Deus — e de fato o somos", distractors: ["Que nos deu seu Filho unigênito para nos salvar", "Que nos adotou por meio do Espírito Santo"] },
      { question: "Em 1 João 3, todo aquele que pratica o pecado também pratica a iniquidade, pois o pecado é quê?", answer: "A iniquidade (transgressão da lei)", distractors: ["A rebeldia contra Deus", "A negação da graça divina"] },
      { question: "Segundo 1 João 3, como sabemos que passamos da morte para a vida?", answer: "Porque amamos os irmãos", distractors: ["Porque cremos no nome de Jesus Cristo", "Porque o Espírito Santo habita em nós"] },
      { question: "Em 1 João 3, quem não ama permanece na quê?", answer: "Na morte", distractors: ["Nas trevas", "No julgamento"] },
      { question: "Segundo 1 João 3, como devemos amar?", answer: "Não de palavra nem de língua, mas em ação e em verdade", distractors: ["Com todo o coração, alma e força", "Como Cristo nos amou, com sacrifício"] },
      { question: "Em 1 João 3, se o nosso coração nos condena, Deus é quê?", answer: "Maior do que o nosso coração e conhece todas as coisas", distractors: ["Misericordioso e perdoa o arrependido", "Justo e julgará segundo as obras"] },
    ],
    4: [
      { question: "Segundo 1 João 4, como provamos os espíritos para saber se são de Deus?", answer: "Todo espírito que confessa que Jesus Cristo veio em carne é de Deus", distractors: ["Pelo fruto que produzem na vida dos crentes", "Pela palavra de Deus que confirma ou nega"] },
      { question: "Em 1 João 4, 'Deus é amor'. Isso foi manifesto em quê?", answer: "Em que Deus enviou seu Filho unigênito ao mundo para que vivêssemos por ele", distractors: ["Em que Cristo morreu pelos pecadores na cruz", "Em que o Espírito Santo habita nos crentes"] },
      { question: "Segundo 1 João 4, 'nós amamos a Deus' por quê?", answer: "Porque ele nos amou primeiro", distractors: ["Porque conhecemos a sua bondade e graça", "Porque ele nos criou à sua imagem"] },
      { question: "Em 1 João 4, quem diz que ama a Deus e odeia o irmão é quê?", answer: "Mentiroso", distractors: ["Hipócrita", "Incrédulo"] },
      { question: "Segundo 1 João 4, o amor perfeito lança fora o quê?", answer: "O temor", distractors: ["A dúvida", "O pecado"] },
      { question: "Em 1 João 4, quem é maior — o que está em vós ou o que está no mundo?", answer: "O que está em vós (Deus/Espírito Santo)", distractors: ["O que está nos céus e governa tudo", "O Filho de Deus que venceu o mundo"] },
    ],
    5: [
      { question: "Segundo 1 João 5, quem é aquele que vence o mundo?", answer: "O que crê que Jesus é o Filho de Deus", distractors: ["O que guarda os mandamentos de Deus", "O que ama a Deus acima de todas as coisas"] },
      { question: "Em 1 João 5, quais são os três que dão testemunho na terra?", answer: "O Espírito, a água e o sangue", distractors: ["O Pai, o Filho e o Espírito Santo", "A lei, os profetas e o evangelho"] },
      { question: "Segundo 1 João 5, o que Deus nos deu referente ao Filho?", answer: "A vida eterna, e essa vida está no seu Filho", distractors: ["O perdão dos pecados e a adoção como filhos", "A promessa do Espírito Santo e da ressurreição"] },
      { question: "Em 1 João 5, se pedirmos alguma coisa segundo a sua vontade, o que sabemos?", answer: "Que ele nos ouve e teremos o que pedimos", distractors: ["Que ele responderá no tempo certo", "Que ele cumprirá a sua promessa"] },
      { question: "Segundo 1 João 5, para que João escreveu essas coisas aos que creem no nome do Filho de Deus?", answer: "Para que saibam que têm a vida eterna", distractors: ["Para que não pequem contra Deus", "Para que permaneçam na fé até o fim"] },
      { question: "Em 1 João 5, 'todo aquele que é nascido de Deus não pratica o pecado' porque quê?", answer: "A semente de Deus permanece nele e não pode pecar, porque nasceu de Deus", distractors: ["O Espírito Santo o guarda de todo mal", "A nova natureza em Cristo supera o pecado"] },
    ],
  },

  "2joao": {
    1: [
      { question: "Segundo 2 João 1, para quem o ancião escreve esta carta?", answer: "À senhora eleita e a seus filhos", distractors: ["À igreja de Éfeso e seus líderes", "Aos irmãos escolhidos de toda a Ásia"] },
      { question: "Em 2 João 1, qual é o mandamento antigo que o ancião rememora?", answer: "Que andemos segundo os mandamentos de Deus — especialmente o amor", distractors: ["Que guardemos a verdade e evitemos o erro", "Que não abandonemos a assembleia dos crentes"] },
      { question: "Segundo 2 João 1, qual é o engano dos muitos que saíram pelo mundo?", answer: "Que não confessam que Jesus Cristo veio em carne (o espírito do anticristo)", distractors: ["Que negam a ressurreição corporal de Cristo", "Que ensinam que a graça cobre todo pecado"] },
      { question: "Em 2 João 1, qual é a advertência sobre receber em casa alguém que não traz a doutrina de Cristo?", answer: "Não o recebais em casa nem lhe deis saudação", distractors: ["Exortai-o com mansidão e sabedoria", "Evitai-o mas orai por sua conversão"] },
      { question: "Segundo 2 João 1, quem dá saudação ao que traz doutrina falsa torna-se quê?", answer: "Participante das suas obras más", distractors: ["Responsável pelo erro que ele espalha", "Cúmplice do engano dos anticristos"] },
    ],
  },

  "3joao": {
    1: [
      { question: "Segundo 3 João 1, por qual razão o ancião regozija-se com Gaio?", answer: "Porque sua alma prospera e ele anda na verdade", distractors: ["Porque ele serve fielmente à congregação", "Porque ele sustenta os missionários"] },
      { question: "Em 3 João 1, quem é criticado por não receber os irmãos e expulsar da igreja os que querem recebê-los?", answer: "Diótrefes", distractors: ["Demétrio", "Nicolau"] },
      { question: "Segundo 3 João 1, de quem o ancião dá bom testemunho?", answer: "De Demétrio", distractors: ["De Gaio", "De Tíquico"] },
      { question: "Em 3 João 1, qual é a exortação central da carta?", answer: "Não imites o mal, mas imita o bem", distractors: ["Recebe os irmãos com hospitalidade e amor", "Afasta-te dos que causam divisão"] },
      { question: "Segundo 3 João 1, quem faz o bem é de Deus; quem faz o mal quê?", answer: "Não viu a Deus", distractors: ["Está sob o domínio do maligno", "Não conhece a verdade"] },
    ],
  },

  judas: {
    1: [
      { question: "Segundo Judas 1, por qual razão Judas foi compelido a escrever sobre a fé?", answer: "Por causa de certas pessoas que se introduziram furtivamente e pervertem a graça de Deus em libertinagem", distractors: ["Para exortar os crentes à perseverança na fé", "Para advertir sobre a falsa profecia nos últimos tempos"] },
      { question: "Em Judas 1, quem é citado como exemplo de rebeldia angélica punida por Deus?", answer: "Os anjos que não guardaram o seu estado original, mas abandonaram a própria morada", distractors: ["Satanás e os demônios que seguiram sua rebeldia", "Os filhos de Deus que se uniram às filhas dos homens"] },
      { question: "Segundo Judas 1, o que o arcanjo Miguel fez quando disputou com o diabo pelo corpo de Moisés?", answer: "Não proferiu julgamento insultuoso, mas disse: 'O Senhor te repreenda'", distractors: ["Invocou o poder de Deus para vencer o diabo", "Ordenou ao diabo que se afastasse em nome de Deus"] },
      { question: "Em Judas 1, qual é a exortação sobre a fé?", answer: "Edificai-vos sobre a vossa santíssima fé", distractors: ["Perseverai na fé que foi dada aos santos", "Guardai a fé com toda vigilância e oração"] },
      { question: "Segundo Judas 1, qual é a doxologia final da carta?", answer: "'Àquele que é poderoso para vos guardar de tropeçar e para vos apresentar imaculados diante da sua glória'", distractors: ["'A Deus, nosso Salvador, que nos amou e nos libertou do pecado'", "'Ao único Deus sábio e eterno, seja honra e glória pelos séculos'"] },
    ],
  },

  apocalipse: {
    1: [
      { question: "Segundo Apocalipse 1, quem recebeu a revelação de Jesus Cristo?", answer: "João, na ilha de Patmos", distractors: ["Paulo, em sua terceira viagem missionária", "Pedro, em Jerusalém antes de ser preso"] },
      { question: "Em Apocalipse 1, Jesus é descrito como quê no meio dos sete candelabros de ouro?", answer: "Semelhante ao Filho do Homem, vestido com uma roupa talar e com um cinto de ouro ao peito", distractors: ["Um leão poderoso com sete cornos e sete olhos", "Um anjo com rosto como o sol e voz como trovão"] },
      { question: "Segundo Apocalipse 1, o que Jesus tem em sua mão direita?", answer: "Sete estrelas", distractors: ["Uma espada de dois gumes", "Uma chave de ouro"] },
      { question: "Em Apocalipse 1, o que representam as sete estrelas e os sete candelabros?", answer: "As sete estrelas são os anjos das sete igrejas; os candelabros são as sete igrejas", distractors: ["As sete estrelas são os apóstolos; os candelabros são as nações", "As sete estrelas são os profetas; os candelabros são os sete espíritos"] },
      { question: "Segundo Apocalipse 1, qual é a descrição dos cabelos de Cristo?", answer: "Brancos como lã branca ou como neve", distractors: ["Dourados como ouro refinado", "Negros como a noite"] },
      { question: "Em Apocalipse 1, Jesus diz: 'Eu sou o Alfa e o Ômega.' O que mais ele acrescenta?", answer: "'O que era, e que é, e que há de vir, o Todo-Poderoso'", distractors: ["'O primeiro e o último, o vivo e o eterno'", "'O Senhor dos exércitos, o Rei dos reis e Senhor dos senhores'"] },
    ],
    2: [
      { question: "Segundo Apocalipse 2, qual é a crítica à igreja de Éfeso?", answer: "Abandonou o primeiro amor", distractors: ["Tolerava a imoralidade entre os membros", "Havia esfriado no serviço a Deus"] },
      { question: "Em Apocalipse 2, qual é a promessa ao vencedor na igreja de Esmirna?", answer: "Não será ofendido pela segunda morte", distractors: ["Receberá a coroa da vida", "Será escrito no livro da vida"] },
      { question: "Segundo Apocalipse 2, qual é a crítica à igreja de Pérgamo?", answer: "Tinha alguns que seguiam o ensino de Balaão e dos nicolaítas", distractors: ["Havia deixado o amor fraternal esfriar", "Tolerava uma profetisa falsa"] },
      { question: "Em Apocalipse 2, qual é a crítica à igreja de Tiatira?", answer: "Tolerava a mulher Jezabel que se dizia profetisa e ensinava imoralidade", distractors: ["Havia abandonado a verdade do evangelho", "Tinha membros que negavam a ressurreição"] },
      { question: "Segundo Apocalipse 2, o que Cristo promete ao vencedor em Pérgamo?", answer: "Pedra branca com um nome novo gravado que ninguém conhece", distractors: ["A coroa da vida e o manto branco", "Autoridade sobre as nações"] },
      { question: "Em Apocalipse 2, quem tem a espada afiada de dois gumes, segundo o remetente da carta a Pérgamo?", answer: "Cristo Jesus", distractors: ["O anjo da igreja", "O arcanjo Miguel"] },
    ],
    3: [
      { question: "Segundo Apocalipse 3, qual é o estado espiritual da igreja de Sardes?", answer: "Tem nome de que vive, mas está morta", distractors: ["É morna — nem fria nem quente", "Tem fé mas abandonou as obras"] },
      { question: "Em Apocalipse 3, qual é a promessa ao vencedor na igreja de Filadélfia?", answer: "Será coluna no templo de Deus e terá nele escrito o nome de Deus, da nova Jerusalém e o nome novo de Cristo", distractors: ["Receberá a chave de Davi para abrir e fechar", "Será recompensado com manto branco e nome no livro da vida"] },
      { question: "Segundo Apocalipse 3, qual é a crítica à igreja de Laodiceia?", answer: "É morna — nem fria nem quente", distractors: ["Tolerava falsos apóstolos em seu meio", "Havia abandonado a fé dos primeiros dias"] },
      { question: "Em Apocalipse 3, Cristo diz que está à porta batendo. O que promete ao que abrir?", answer: "Entrará e cenará com ele e ele com Cristo", distractors: ["Receberá o Espírito Santo em plenitude", "Será salvo e terá a vida eterna"] },
      { question: "Segundo Apocalipse 3, qual é a autoimagem enganosa de Laodiceia?", answer: "Rica, próspera e sem necessidade de nada", distractors: ["Sábia, conhecedora e instruída na lei", "Fiel, santa e agradável a Deus"] },
      { question: "Em Apocalipse 3, quem Cristo repreende e disciplina?", answer: "Os que ama", distractors: ["Os que perseveram na fé", "Os que voltaram do erro"] },
    ],
    4: [
      { question: "Segundo Apocalipse 4, o que João viu ao subir ao céu pela porta aberta?", answer: "Um trono posto no céu e alguém assentado nele, resplandecente como jaspe e sardio", distractors: ["Os vinte e quatro anciãos prostrados diante de Deus", "O cordeiro em pé como se tivesse sido imolado"] },
      { question: "Em Apocalipse 4, quantos anciãos estavam assentados ao redor do trono?", answer: "Vinte e quatro", distractors: ["Doze", "Setenta"] },
      { question: "Segundo Apocalipse 4, os quatro seres viventes têm características de quais animais?", answer: "Leão, boi, homem e águia", distractors: ["Leão, leopardo, urso e águia", "Touro, cordeiro, homem e serpente"] },
      { question: "Em Apocalipse 4, qual é o cântico dos quatro seres viventes?", answer: "'Santo, santo, santo é o Senhor Deus Todo-Poderoso, que era, que é e que há de vir'", distractors: ["'Digno és tu, Senhor nosso Deus, de receber a glória e a honra'", "'Aleluia, porque o Senhor nosso Deus Todo-Poderoso reina'"] },
      { question: "Segundo Apocalipse 4, ao redor do trono havia um arco-íris semelhante a quê?", answer: "A esmeralda", distractors: ["A safira", "A rubi"] },
      { question: "Em Apocalipse 4, o que os vinte e quatro anciãos fazem ao adorar?", answer: "Lançam suas coroas diante do trono", distractors: ["Prostram-se e tocam o chão com o rosto", "Cantam hinos com harpas de ouro"] },
    ],
    5: [
      { question: "Segundo Apocalipse 5, quem é digno de abrir o livro selado com sete selos?", answer: "O Cordeiro, o Leão da tribo de Judá, a Raiz de Davi", distractors: ["O arcanjo Miguel, príncipe do exército celestial", "O Pai, único que conhece todos os segredos"] },
      { question: "Em Apocalipse 5, como o Cordeiro aparece diante do trono?", answer: "Em pé como se tivesse sido imolado, com sete chifres e sete olhos", distractors: ["Glorioso e resplandecente, vestido de branco", "Com espada na boca e coroa na cabeça"] },
      { question: "Segundo Apocalipse 5, o que representam os sete chifres e os sete olhos do Cordeiro?", answer: "Os sete espíritos de Deus enviados a toda a terra", distractors: ["O poder completo e a onisciência divina", "As sete igrejas e seus anjos guardiões"] },
      { question: "Em Apocalipse 5, qual é o cântico novo cantado ao Cordeiro?", answer: "'Digno és de tomar o livro e de abrir os seus selos, porque foste imolado'", distractors: ["'Santo és tu, Senhor, que reinas sobre toda a criação'", "'Aleluia, porque o Cordeiro reina e venceu a morte'"] },
      { question: "Segundo Apocalipse 5, quantos milhares de anjos havia ao redor do trono?", answer: "Miríades de miríades e milhares de milhares", distractors: ["Sete mil e setecentos", "Cento e quarenta e quatro mil"] },
      { question: "Em Apocalipse 5, o que os vinte e quatro anciãos tinham em suas mãos, além das harpas?", answer: "Taças de ouro cheias de incenso, que são as orações dos santos", distractors: ["Livros abertos com os nomes dos redimidos", "Selos de ouro para selar os servos de Deus"] },
    ],
    6: [
      { question: "Segundo Apocalipse 6, qual é o cavaleiro do cavalo branco no primeiro selo?", answer: "Um conquistador armado com arco, que saiu para vencer", distractors: ["Cristo glorioso, Rei dos reis", "Um anjo poderoso enviado para guerra"] },
      { question: "Em Apocalipse 6, o cavaleiro do cavalo vermelho representa quê?", answer: "A guerra — tirar a paz da terra e fazer os homens se matarem", distractors: ["A fome que devasta as nações", "A morte que ceifa os povos"] },
      { question: "Segundo Apocalipse 6, o cavaleiro do cavalo preto carregava quê?", answer: "Uma balança na mão — representando a escassez de alimentos e a fome", distractors: ["Uma espada de dois gumes para julgamento", "Uma foice para colher os ímpios da terra"] },
      { question: "Em Apocalipse 6, qual é o nome do cavaleiro do cavalo amarelo?", answer: "Morte", distractors: ["Destruição", "Hades"] },
      { question: "Segundo Apocalipse 6, no quinto selo, onde estavam as almas dos mártires?", answer: "Debaixo do altar", distractors: ["Diante do trono de Deus", "No paraíso, aguardando a ressurreição"] },
      { question: "Em Apocalipse 6, o sexto selo provoca quais fenômenos?", answer: "Grande terremoto, sol negro, lua vermelha como sangue, estrelas caindo", distractors: ["Trovões, relâmpagos, granizo e fogo misturado com sangue", "Escuridão, pragas e morte dos primogênitos"] },
    ],
    7: [
      { question: "Segundo Apocalipse 7, quantos foram selados das tribos de Israel?", answer: "Cento e quarenta e quatro mil", distractors: ["Doze mil de cada tribo, totalizando cento e quarenta e quatro mil", "Um número que ninguém podia contar"] },
      { question: "Em Apocalipse 7, a grande multidão vestida de branco diante do trono veio de onde?", answer: "Da grande tribulação", distractors: ["Das nações que nunca ouviram o evangelho", "Das doze tribos de Israel reunidas"] },
      { question: "Segundo Apocalipse 7, o que a grande multidão vestida de branco clamava?", answer: "'A salvação pertence ao nosso Deus, que está assentado no trono, e ao Cordeiro'", distractors: ["'Santo, santo, santo é o Senhor Deus Todo-Poderoso'", "'Digno é o Cordeiro que foi imolado de receber o poder'"] },
      { question: "Em Apocalipse 7, os que lavaram suas vestes as tornaram brancas em quê?", answer: "No sangue do Cordeiro", distractors: ["Na água pura que flui do trono de Deus", "Na graça que purifica toda impureza"] },
      { question: "Segundo Apocalipse 7, quais promessas são feitas à grande multidão redimida?", answer: "Não terão mais fome nem sede; o sol não os ferirá; o Cordeiro os apascentará e os guiará", distractors: ["Receberão coroas de glória e reinarão com Cristo", "Viverão no templo celestial e adorarão Deus eternamente"] },
      { question: "Em Apocalipse 7, quatro anjos estavam retendo quê?", answer: "Os quatro ventos da terra", distractors: ["As sete trombetas do julgamento", "Os cavaleiros do apocalipse"] },
    ],
    8: [
      { question: "Segundo Apocalipse 8, após a abertura do sétimo selo, o que houve no céu?", answer: "Silêncio por cerca de meia hora", distractors: ["Grande adoração e louvor dos vinte e quatro anciãos", "Trovões, relâmpagos e vozes"] },
      { question: "Em Apocalipse 8, na primeira trombeta, o que foi lançado sobre a terra?", answer: "Granizo e fogo misturados com sangue — um terço da terra foi queimado", distractors: ["Uma montanha ardente lançada no mar", "Uma estrela chamada Absinto caiu sobre os rios"] },
      { question: "Segundo Apocalipse 8, na segunda trombeta, o que aconteceu ao mar?", answer: "Um terço tornou-se sangue e um terço das criaturas do mar morreu", distractors: ["Secou completamente por trinta dias", "Foi transformado em fogo e enxofre"] },
      { question: "Em Apocalipse 8, qual é o nome da estrela que caiu sobre os rios na terceira trombeta?", answer: "Absinto", distractors: ["Lúcifer", "Estrela da Morte"] },
      { question: "Segundo Apocalipse 8, na quarta trombeta, o que aconteceu com o sol, lua e estrelas?", answer: "Um terço foi atingido e ficou sem luz", distractors: ["Caíram sobre a terra causando escuridão total", "Tornaram-se vermelhos como sangue"] },
      { question: "Em Apocalipse 8, qual ave voava pelo meio do céu clamando 'Ai, ai, ai'?", answer: "Uma águia", distractors: ["Um anjo com asas brancas", "Um querubim com quatro faces"] },
    ],
    9: [
      { question: "Segundo Apocalipse 9, na quinta trombeta, quem recebeu a chave do poço do abismo?", answer: "Uma estrela que caiu do céu (um ser angelical)", distractors: ["O arcanjo Miguel, general do exército celestial", "O anjo mensageiro enviado por Deus"] },
      { question: "Em Apocalipse 9, qual é o nome do rei dos gafanhotos do abismo em hebraico?", answer: "Abadom (em grego, Apoliom)", distractors: ["Belzebu", "Moloque"] },
      { question: "Segundo Apocalipse 9, por quanto tempo os gafanhotos podiam atormentar os homens, mas não matá-los?", answer: "Cinco meses", distractors: ["Quarenta dias", "Três anos e meio"] },
      { question: "Em Apocalipse 9, qual é a descrição dos gafanhotos apocalípticos?", answer: "Semelhantes a cavalos preparados para a guerra, com coroas de ouro, faces humanas, cabelos de mulher, dentes de leão", distractors: ["Enormes como elefantes, com asas de abutre e cauda de escorpião", "Pequenos mas mortais, com veneno nas asas e fogo na boca"] },
      { question: "Segundo Apocalipse 9, na sexta trombeta, quantos da cavalaria mataram um terço dos homens?", answer: "Duzentos milhões", distractors: ["Cento e quarenta e quatro mil", "Sete mil guerreiros celestiais"] },
      { question: "Em Apocalipse 9, os que sobreviveram às pragas ainda assim não se arrependeram. De quê?", answer: "Da idolatria, dos homicídios, das feitiçarias, da imoralidade e dos furtos", distractors: ["Do orgulho e da rebeldia contra Deus", "De rejeitarem os profetas e o evangelho"] },
    ],
    10: [
      { question: "Segundo Apocalipse 10, o que João recebeu do anjo poderoso para comer?", answer: "Um livrinho aberto", distractors: ["Um pergaminho com sete selos", "Um rolo com profecias escritas"] },
      { question: "Em Apocalipse 10, qual era o sabor do livrinho na boca de João?", answer: "Doce como mel na boca, mas amargo no ventre", distractors: ["Amargo como fel na boca, mas doce por dentro", "Sem sabor na boca, mas fogo no ventre"] },
      { question: "Segundo Apocalipse 10, o anjo poderoso estava em pé sobre o quê?", answer: "Sobre o mar e sobre a terra", distractors: ["Sobre as nuvens do céu", "Sobre o monte Sião"] },
      { question: "Em Apocalipse 10, o arco-íris estava sobre a cabeça do anjo. Como era seu rosto?", answer: "Como o sol", distractors: ["Como a lua cheia", "Como estrelas resplandecentes"] },
      { question: "Segundo Apocalipse 10, quando os sete trovões falaram, o que João foi impedido de fazer?", answer: "De escrever o que ouviu — foi mandado selar o que os trovões disseram", distractors: ["De se aproximar do anjo por causa da glória", "De proclamar as palavras ao povo"] },
      { question: "Em Apocalipse 10, o anjo jurou que no tempo da sétima trombeta o mistério de Deus se cumpriria como quê?", answer: "Como anunciou aos seus servos os profetas", distractors: ["Como escrito nos livros proféticos de Daniel", "Como revelado a João no monte Sião"] },
    ],
    11: [
      { question: "Segundo Apocalipse 11, por quanto tempo as duas testemunhas profetizarão?", answer: "Mil duzentos e sessenta dias", distractors: ["Quarenta e dois meses", "Três anos e meio"] },
      { question: "Em Apocalipse 11, o que as duas testemunhas podem fazer?", answer: "Fechar o céu para não chover, transformar as águas em sangue e ferir a terra com pragas", distractors: ["Ressuscitar os mortos e curar os enfermos", "Invocar fogo do céu e partir o mar"] },
      { question: "Segundo Apocalipse 11, após serem mortas pela besta do abismo, por quanto tempo seus corpos ficaram expostos?", answer: "Três dias e meio", distractors: ["Sete dias", "Quarenta dias"] },
      { question: "Em Apocalipse 11, após ressuscitarem, o que as duas testemunhas ouviram do céu?", answer: "'Subi para cá'", distractors: ["'Bem-aventurados os que morrem no Senhor'", "'A vitória pertence ao nosso Deus'"] },
      { question: "Segundo Apocalipse 11, na sétima trombeta, o que as vozes do céu proclamaram?", answer: "'O reino do mundo tornou-se o reino do nosso Senhor e do seu Cristo'", distractors: ["'Santo, santo, santo é o Senhor Deus Todo-Poderoso'", "'Digno é o Cordeiro que foi imolado'"] },
      { question: "Em Apocalipse 11, o templo de Deus no céu foi aberto e o que apareceu?", answer: "A arca da sua aliança", distractors: ["O trono do Cordeiro resplandecente", "Os sete candelabros de ouro acesos"] },
    ],
    12: [
      { question: "Segundo Apocalipse 12, quem é a mulher vestida do sol, com a lua debaixo dos pés e coroa de doze estrelas?", answer: "Um sinal no céu representando o povo de Deus (Israel/Igreja) que deu à luz o Messias", distractors: ["Maria, mãe de Jesus, exaltada no céu", "A Igreja de Cristo aguardando a vitória final"] },
      { question: "Em Apocalipse 12, o dragão arrastou com sua cauda um terço de quê?", answer: "Das estrelas do céu, lançando-as à terra", distractors: ["Das nações da terra para a guerra", "Dos anjos que serviram a Deus"] },
      { question: "Segundo Apocalipse 12, quem é o grande dragão vermelho com sete cabeças e dez chifres?", answer: "A antiga serpente chamada Diabo e Satanás, que engana o mundo inteiro", distractors: ["O Anticristo que governará no fim dos tempos", "A besta que sobe do abismo"] },
      { question: "Em Apocalipse 12, os irmãos venceram o dragão por quê?", answer: "Pelo sangue do Cordeiro e pela palavra do seu testemunho, não amando a sua vida até à morte", distractors: ["Pela oração e pelo jejum nos últimos dias", "Pela fé inabalável e pela obediência aos mandamentos"] },
      { question: "Segundo Apocalipse 12, por quanto tempo a mulher foi sustentada no deserto?", answer: "Mil duzentos e sessenta dias (um tempo, dois tempos e metade de um tempo)", distractors: ["Quarenta anos como Israel no deserto", "Três anos e meio de tribulação"] },
      { question: "Em Apocalipse 12, Miguel e seus anjos guerrearam contra o dragão. Qual foi o resultado?", answer: "O dragão e seus anjos foram derrotados e não tiveram mais lugar no céu", distractors: ["O dragão foi preso por mil anos no abismo", "O dragão foi lançado ao lago de fogo"] },
    ],
    13: [
      { question: "Segundo Apocalipse 13, a besta que sobe do mar tinha quantas cabeças e chifres?", answer: "Sete cabeças e dez chifres", distractors: ["Dez cabeças e sete chifres", "Três cabeças e seis chifres"] },
      { question: "Em Apocalipse 13, qual é o número da besta?", answer: "Seiscentos e sessenta e seis (666)", distractors: ["Setecentos e setenta e sete (777)", "Quatrocentos e quarenta e quatro (444)"] },
      { question: "Segundo Apocalipse 13, a segunda besta (o falso profeta) subia de onde?", answer: "Da terra", distractors: ["Do mar", "Do abismo"] },
      { question: "Em Apocalipse 13, o que a segunda besta fazia para enganar os habitantes da terra?", answer: "Fazia grandes sinais, até fazer descer fogo do céu à vista dos homens", distractors: ["Proclamava mentiras e negava que Jesus é o Cristo", "Realizava ressurreições falsas para enganar o povo"] },
      { question: "Segundo Apocalipse 13, quem adorou a besta?", answer: "Todos cujos nomes não estão escritos no livro da vida do Cordeiro", distractors: ["Os que não receberam o Espírito Santo", "Os que abandonaram a fé nos últimos dias"] },
      { question: "Em Apocalipse 13, a marca da besta era necessária para quê?", answer: "Para comprar ou vender", distractors: ["Para entrar nas cidades e sinagogas", "Para receber proteção do governo da besta"] },
    ],
    14: [
      { question: "Segundo Apocalipse 14, os 144.000 estavam em pé no Monte Sião com quem?", answer: "Com o Cordeiro", distractors: ["Com os vinte e quatro anciãos", "Com os quatro seres viventes"] },
      { question: "Em Apocalipse 14, qual cântico somente os 144.000 podiam aprender?", answer: "O cântico novo diante do trono", distractors: ["O cântico de Moisés e do Cordeiro", "O aleluia dos remidos das nações"] },
      { question: "Segundo Apocalipse 14, o primeiro anjo voou pelo meio do céu proclamando o quê?", answer: "O evangelho eterno — 'Temei a Deus e dai-lhe glória, porque chegou a hora do seu julgamento'", distractors: ["A queda de Babilônia, a grande meretriz", "A colheita dos remidos da terra"] },
      { question: "Em Apocalipse 14, o segundo anjo proclamou quê?", answer: "'Caiu, caiu a grande Babilônia'", distractors: ["'Chegou o dia da ira do Senhor'", "'O reino do mundo passou ao nosso Senhor'"] },
      { question: "Segundo Apocalipse 14, qual é a bem-aventurança proclamada para os que morrem no Senhor?", answer: "'Bem-aventurados os mortos que daqui em diante morrem no Senhor'", distractors: ["'Bem-aventurados os que perseveraram até o fim'", "'Bem-aventurados os que lavaram suas vestes no sangue do Cordeiro'"] },
      { question: "Em Apocalipse 14, a colheita da terra é descrita como quê?", answer: "Um filho do homem ceifando a terra com uma foice afiada", distractors: ["Anjos colhendo os redimidos das quatro extremidades da terra", "O Cordeiro reunindo os seus eleitos de todas as nações"] },
    ],
    15: [
      { question: "Segundo Apocalipse 15, o que os vencedores da besta cantavam às margens do mar de vidro?", answer: "O cântico de Moisés e o cântico do Cordeiro", distractors: ["O cântico novo dos 144.000", "O aleluia da grande multidão"] },
      { question: "Em Apocalipse 15, de onde saíram os sete anjos com as sete últimas pragas?", answer: "Do templo celestial", distractors: ["Do altar de ouro diante de Deus", "Das nuvens do céu"] },
      { question: "Segundo Apocalipse 15, o que encheu o templo celestial a ponto de ninguém poder entrar?", answer: "A fumaça da glória de Deus e do seu poder", distractors: ["A glória resplandecente do trono do Altíssimo", "O incenso das orações dos santos subindo ao céu"] },
      { question: "Em Apocalipse 15, quais são os sete anjos que saíram do templo?", answer: "Os que tinham as sete últimas pragas — as taças da ira de Deus", distractors: ["Os anjos das sete igrejas com as cartas de julgamento", "Os sete arcanjos que estão diante de Deus"] },
      { question: "Segundo Apocalipse 15, o cântico de Moisés glorificava a Deus por quê?", answer: "'Grandes e maravilhosas são as tuas obras, Senhor Deus Todo-Poderoso; justos e verdadeiros são os teus caminhos'", distractors: ["'Tu és o único santo; todas as nações virão adorar-te'", "'Santo és tu, e digno de receber glória e honra e poder'"] },
      { question: "Em Apocalipse 15, o mar de vidro estava misturado com quê?", answer: "Com fogo", distractors: ["Com sangue", "Com cristal"] },
    ],
    16: [
      { question: "Segundo Apocalipse 16, qual praga trouxe a primeira taça derramada sobre a terra?", answer: "Uma chaga maligna e terrível sobre os que tinham a marca da besta", distractors: ["A água dos rios tornada sangue", "Escuridão sobre o reino da besta"] },
      { question: "Em Apocalipse 16, o que aconteceu ao mar quando a segunda taça foi derramada?", answer: "Tornou-se como sangue de um morto e todo ser vivo no mar morreu", distractors: ["As ondas do mar destruíram as costas das nações", "O mar secou revelando o leito de areia"] },
      { question: "Segundo Apocalipse 16, a sexta taça secou quê?", answer: "O rio Eufrates, preparando o caminho para os reis do oriente", distractors: ["O mar Mediterrâneo para a batalha final", "Os rios do meio-oriente para a invasão"] },
      { question: "Em Apocalipse 16, onde os reis da terra se reunirão para a batalha final?", answer: "Armagedom", distractors: ["Megido", "Vale de Josafá"] },
      { question: "Segundo Apocalipse 16, a sétima taça foi derramada no ar. O que proclamou a voz do trono?", answer: "'Está feito!'", distractors: ["'Chegou o dia do julgamento!'", "'A ira de Deus está consumada!'"] },
      { question: "Em Apocalipse 16, qual foi o maior terremoto da história que ocorreu com a sétima taça?", answer: "A grande Babilônia foi lembrada diante de Deus para lhe ser dado o cálice do vinho da ira", distractors: ["Jerusalém foi dividida em três partes e destruída", "Roma foi completamente arrasada em um só dia"] },
    ],
    17: [
      { question: "Segundo Apocalipse 17, como é chamada a grande meretriz?", answer: "Babilônia, a grande, mãe das meretrizes e das abominações da terra", distractors: ["A mulher da iniquidade, rainha das nações", "A cidade do pecado, senhora dos reis da terra"] },
      { question: "Em Apocalipse 17, sobre o que estava assentada a mulher?", answer: "Sobre uma besta escarlate cheia de nomes de blasfêmia, com sete cabeças e dez chifres", distractors: ["Sobre as muitas águas que representam os povos", "Sobre o dragão vermelho com dez chifres"] },
      { question: "Segundo Apocalipse 17, o que representam as águas onde a meretriz estava sentada?", answer: "Povos, multidões, nações e línguas", distractors: ["Os mares e oceanos do mundo", "Os rios de sangue derramados pelos mártires"] },
      { question: "Em Apocalipse 17, o que representam as sete cabeças da besta?", answer: "Sete montes sobre os quais a mulher está sentada, e também sete reis", distractors: ["Sete impérios que perseguiram o povo de Deus", "Sete poderes mundiais que adoraram a besta"] },
      { question: "Segundo Apocalipse 17, o Cordeiro vencerá a besta porque quê?", answer: "Porque é Senhor dos senhores e Rei dos reis", distractors: ["Porque o poder de Deus supera todo poder humano", "Porque os seus escolhidos fiéis lutarão com ele"] },
      { question: "Em Apocalipse 17, os dez chifres (dez reis) darão seu poder à besta por quanto tempo?", answer: "Por uma hora", distractors: ["Por três anos e meio", "Por quarenta e dois meses"] },
    ],
    18: [
      { question: "Segundo Apocalipse 18, qual é a exortação do céu ao povo de Deus sobre Babilônia?", answer: "'Saí dela, povo meu, para que não sejais participantes dos seus pecados'", distractors: ["'Orai pela sua destruição para que a justiça seja cumprida'", "'Testemunhai contra ela e proclamai seu julgamento'"] },
      { question: "Em Apocalipse 18, em quanto tempo a destruição de Babilônia ocorreu, segundo os reis que lamentaram?", answer: "Em uma hora", distractors: ["Em um dia", "Em um momento"] },
      { question: "Segundo Apocalipse 18, quem lamenta a queda de Babilônia?", answer: "Os reis da terra, os mercadores e os marinheiros", distractors: ["Os falsos profetas e os sacerdotes idólatras", "Os poderosos da terra e seus exércitos"] },
      { question: "Em Apocalipse 18, os mercadores enriqueceram com o quê de Babilônia?", answer: "Com o luxo e o excesso dos seus produtos", distractors: ["Com o comércio de escravos e almas humanas", "Com as riquezas dos templos e santuários"] },
      { question: "Segundo Apocalipse 18, o que o forte anjo fez para simbolizar a queda de Babilônia?", answer: "Lançou ao mar uma grande pedra como mó", distractors: ["Tocou a trombeta do julgamento final", "Derramou fogo do céu sobre a cidade"] },
      { question: "Em Apocalipse 18, Babilônia será achada não mais por quê?", answer: "Porque nela foi achado o sangue de profetas, santos e de todos os que foram mortos na terra", distractors: ["Porque sua iniquidade chegou até os céus e não pôde mais ser tolerada", "Porque rejeitou o evangelho e perseguiu os servos de Deus"] },
    ],
    19: [
      { question: "Segundo Apocalipse 19, qual é o cântico 'Aleluia' que ecoa no céu após a queda de Babilônia?", answer: "'Aleluia! A salvação, a glória e o poder pertencem ao nosso Deus, porque verdadeiros e justos são os seus juízos'", distractors: ["'Santo, santo, santo é o Senhor; o céu e a terra estão cheios da sua glória'", "'Digno és de receber glória, porque criaste todas as coisas'"] },
      { question: "Em Apocalipse 19, o casamento do Cordeiro: quem é a noiva?", answer: "A Igreja — os que foram chamados para a ceia das bodas do Cordeiro", distractors: ["A cidade de Jerusalém reconstruída por Deus", "Os 144.000 virgens que seguiram o Cordeiro"] },
      { question: "Segundo Apocalipse 19, qual é o nome do cavaleiro do cavalo branco que lidera os exércitos do céu?", answer: "Fiel e Verdadeiro", distractors: ["Senhor dos Exércitos", "Rei da Glória"] },
      { question: "Em Apocalipse 19, o que o cavaleiro do cavalo branco tinha na boca?", answer: "Uma espada afiada para ferir as nações", distractors: ["Fogo que consumia seus inimigos", "Palavras de julgamento que nunca falham"] },
      { question: "Segundo Apocalipse 19, qual é o nome escrito na veste e na coxa do cavaleiro?", answer: "Rei dos reis e Senhor dos senhores", distractors: ["Alfa e Ômega, o Primeiro e o Último", "Fiel e Verdadeiro, o Juiz Justo"] },
      { question: "Em Apocalipse 19, qual foi o destino da besta e do falso profeta?", answer: "Foram lançados vivos no lago de fogo que arde com enxofre", distractors: ["Foram destruídos pela espada do cavaleiro do cavalo branco", "Foram acorrentados no abismo por mil anos"] },
    ],
    20: [
      { question: "Segundo Apocalipse 20, por quanto tempo Satanás foi acorrentado no abismo?", answer: "Mil anos", distractors: ["Setecentos anos", "Até o julgamento final"] },
      { question: "Em Apocalipse 20, o que acontece com Satanás após os mil anos?", answer: "É solto por um pouco de tempo, engana as nações e depois é lançado no lago de fogo", distractors: ["É julgado diante do grande trono branco", "É destruído juntamente com seus seguidores"] },
      { question: "Segundo Apocalipse 20, quem reinou com Cristo durante os mil anos?", answer: "Os que não adoraram a besta nem receberam sua marca — os mártires ressuscitados", distractors: ["Os 144.000 selados das tribos de Israel", "Todos os salvos desde Abraão até o fim"] },
      { question: "Em Apocalipse 20, o que é a 'segunda morte'?", answer: "O lago de fogo", distractors: ["A separação eterna de Deus", "A morte do corpo e da alma"] },
      { question: "Segundo Apocalipse 20, no julgamento do grande trono branco, pelo que os mortos foram julgados?", answer: "Pelas suas obras, segundo o que estava escrito nos livros", distractors: ["Por terem aceitado ou rejeitado o evangelho", "Pela fé e pelas obras praticadas em vida"] },
      { question: "Em Apocalipse 20, quem foi lançado no lago de fogo além de Satanás, da besta e do falso profeta?", answer: "A morte e o Hades, e todos cujos nomes não foram achados no livro da vida", distractors: ["Os anjos rebeldes e os demônios que os seguiram", "Os ímpios de todas as gerações"] },
    ],
    21: [
      { question: "Segundo Apocalipse 21, como é descrita a nova Jerusalém?", answer: "Como uma noiva adornada para o seu marido, descendo do céu de Deus", distractors: ["Como um templo de ouro puro com doze portas de pérola", "Como a cidade eterna onde habita toda a glória de Deus"] },
      { question: "Em Apocalipse 21, 'Deus enxugará de seus olhos toda lágrima' — o que mais não haverá?", answer: "Não haverá mais morte, nem pranto, nem clamor, nem dor", distractors: ["Não haverá mais noite, nem trevas, nem sofrimento", "Não haverá mais pecado, nem tentação, nem maldade"] },
      { question: "Segundo Apocalipse 21, qual é o material das doze portas da nova Jerusalém?", answer: "Cada porta era uma única pérola", distractors: ["Ouro puro como vidro transparente", "Pedras preciosas de cada tribo de Israel"] },
      { question: "Em Apocalipse 21, qual é a medida do muro da nova Jerusalém?", answer: "Cento e quarenta e quatro côvados", distractors: ["Setecentos e setenta côvados", "Doze mil estádios de comprimento"] },
      { question: "Segundo Apocalipse 21, a nova Jerusalém não precisava de sol nem lua porque quê?", answer: "A glória de Deus a ilumina e o Cordeiro é a sua lâmpada", distractors: ["Deus criou uma nova luz para iluminar a cidade eterna", "O Espírito Santo é a luz que brilha para sempre"] },
      { question: "Em Apocalipse 21, o que Deus diz: 'Eis que faço novas todas as coisas'?", answer: "É a declaração de Deus assentado no trono ao início da nova criação", distractors: ["É a promessa feita aos profetas do Antigo Testamento", "É o cântico entoado pelos redimidos na nova Jerusalém"] },
    ],
    22: [
      { question: "Segundo Apocalipse 22, de onde procedia o rio da água da vida?", answer: "Do trono de Deus e do Cordeiro", distractors: ["Da fonte no meio da nova Jerusalém", "Do templo celestial onde Deus habita"] },
      { question: "Em Apocalipse 22, a árvore da vida produzia quantos frutos por ano?", answer: "Doze frutos, um por mês", distractors: ["Frutos em todas as estações sem cessar", "Sete frutos correspondendo aos sete espíritos"] },
      { question: "Segundo Apocalipse 22, o que as folhas da árvore da vida serviam para fazer?", answer: "Para a cura das nações", distractors: ["Para o alimento dos remidos eternamente", "Para a adoração diante do trono de Deus"] },
      { question: "Em Apocalipse 22, qual é a advertência sobre acrescentar ou tirar palavras do livro desta profecia?", answer: "Quem acrescentar, Deus lhe acrescentará as pragas; quem tirar, Deus lhe tirará a parte na árvore da vida", distractors: ["Quem alterar será julgado perante o grande trono branco", "Quem falsificar perderá o seu nome do livro da vida"] },
      { question: "Segundo Apocalipse 22, qual é a última promessa de Jesus no livro?", answer: "'Sim, venho em breve.' E a resposta é: 'Amém! Vem, Senhor Jesus!'", distractors: ["'Eu sou o Alfa e o Ômega, o princípio e o fim'", "'Bem-aventurados os que guardam as palavras desta profecia'"] },
      { question: "Em Apocalipse 22, quem tem direito à árvore da vida e pode entrar pelas portas da cidade?", answer: "Os que lavam as suas vestes (os redimidos pelo sangue do Cordeiro)", distractors: ["Os que guardaram os mandamentos de Deus até o fim", "Os 144.000 que não se contaminaram"] },
    ],
  },
};
