import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_GOSPELS: Record<string, Record<number, BankQuestion[]>> = {
  mateus: {
    1: [
      { question: "Com quem começa a genealogia de Jesus em Mateus 1?", answer: "Abraão", distractors: ["Adão", "Noé"] },
      { question: "Quem era o pai adotivo de Jesus segundo Mateus 1?", answer: "José", distractors: ["Zacarias", "Simeão"] },
      { question: "Qual foi o nome dado ao filho de Maria conforme o anjo instruiu José?", answer: "Jesus", distractors: ["Emanuel", "João"] },
      { question: "O que significa 'Emanuel' segundo Mateus 1?", answer: "Deus conosco", distractors: ["Deus salva", "Rei dos reis"] },
      { question: "Qual profeta anunciou que uma virgem conceberia e daria à luz um filho?", answer: "Isaías", distractors: ["Jeremias", "Miquéias"] },
      { question: "Quantas gerações são listadas de Abraão a Davi em Mateus 1?", answer: "Quatorze", distractors: ["Doze", "Sete"] },
      { question: "O que o anjo disse a José sobre Maria em sonho?", answer: "O que nela foi gerado é do Espírito Santo", distractors: ["Ela estava com outro homem", "Ela deveria ser repudiada"] },
    ],
    2: [
      { question: "Em que cidade Jesus nasceu segundo Mateus 2?", answer: "Belém da Judeia", distractors: ["Nazaré", "Jerusalém"] },
      { question: "Quem eram os visitantes vindos do Oriente que buscaram Jesus?", answer: "Magos", distractors: ["Pastores", "Sacerdotes"] },
      { question: "Qual estrela guiou os magos até Jesus?", answer: "A estrela que apareceu no Oriente", distractors: ["A estrela da manhã", "A estrela de Davi"] },
      { question: "Para qual país José fugiu com Maria e Jesus para escapar de Herodes?", answer: "Egito", distractors: ["Síria", "Babilônia"] },
      { question: "Qual rei ordenou a matança dos meninos de dois anos para baixo em Belém?", answer: "Herodes", distractors: ["Arquelau", "Pilatos"] },
      { question: "Em qual cidade Jesus foi criado após o retorno do Egito?", answer: "Nazaré", distractors: ["Cafarnaum", "Belém"] },
      { question: "Que presentes os magos trouxeram ao menino Jesus?", answer: "Ouro, incenso e mirra", distractors: ["Prata, perfume e trigo", "Ouro, prata e incenso"] },
    ],
    3: [
      { question: "Quem pregava no deserto da Judeia em Mateus 3?", answer: "João Batista", distractors: ["Elias", "Isaías"] },
      { question: "Qual era a mensagem principal de João Batista?", answer: "Arrependei-vos, porque é chegado o reino dos céus", distractors: ["O Filho do Homem virá nas nuvens", "Amai uns aos outros"] },
      { question: "O que João Batista comia no deserto?", answer: "Gafanhotos e mel silvestre", distractors: ["Pão e água", "Figos e uvas"] },
      { question: "No que João Batista batizava as pessoas?", answer: "Água", distractors: ["Fogo", "Azeite"] },
      { question: "Quem Jesus disse que batizaria com o Espírito Santo e fogo?", answer: "O que vem após João", distractors: ["Elias", "Pedro"] },
      { question: "O que aconteceu quando Jesus foi batizado por João?", answer: "Os céus se abriram e o Espírito desceu como pomba", distractors: ["Houve um terremoto", "Uma nuvem cobriu o lugar"] },
      { question: "O que disse a voz do céu no batismo de Jesus?", answer: "Este é o meu Filho amado, em quem me comprazo", distractors: ["Este é o profeta prometido", "Levantem-se e não temam"] },
    ],
    4: [
      { question: "Quantos dias Jesus jejuou no deserto antes de ser tentado?", answer: "Quarenta dias e quarenta noites", distractors: ["Trinta dias", "Sete dias"] },
      { question: "Qual foi a primeira tentação que o diabo fez a Jesus?", answer: "Transformar pedras em pão", distractors: ["Jogar-se do templo", "Adorar o diabo"] },
      { question: "Com que palavras Jesus respondeu à tentação do pão?", answer: "Nem só de pão viverá o homem", distractors: ["Vai-te, Satanás", "O Senhor teu Deus adorarás"] },
      { question: "De qual monte o diabo mostrou a Jesus todos os reinos do mundo?", answer: "Um monte muito alto", distractors: ["Monte das Oliveiras", "Monte Sinai"] },
      { question: "Quais foram os primeiros discípulos chamados por Jesus em Mateus 4?", answer: "Pedro e André", distractors: ["Tiago e João", "Filipe e Natanael"] },
      { question: "O que Pedro e André faziam quando Jesus os chamou?", answer: "Lançavam redes no mar", distractors: ["Consertavam redes", "Vendiam peixes"] },
      { question: "Em que região Jesus começou seu ministério após a prisão de João?", answer: "Galileia", distractors: ["Judeia", "Samaria"] },
    ],
    5: [
      { question: "Como começa o Sermão do Monte em Mateus 5?", answer: "Com as bem-aventuranças", distractors: ["Com o Pai-Nosso", "Com os mandamentos"] },
      { question: "Qual é a primeira bem-aventurança em Mateus 5?", answer: "Bem-aventurados os pobres de espírito", distractors: ["Bem-aventurados os puros de coração", "Bem-aventurados os misericordiosos"] },
      { question: "Jesus disse que os cristãos são o sal da terra e também o quê?", answer: "A luz do mundo", distractors: ["O pão da vida", "A água viva"] },
      { question: "Jesus disse que não veio abolir a lei, mas sim:", answer: "Cumpri-la", distractors: ["Reformá-la", "Simplificá-la"] },
      { question: "Segundo Jesus em Mateus 5, o que se deve fazer aos inimigos?", answer: "Amá-los e orar por eles", distractors: ["Evitá-los", "Perdoá-los em segredo"] },
      { question: "Qual metáfora Jesus usou para descrever os discípulos no mundo?", answer: "Sal da terra e luz do mundo", distractors: ["Trigo entre o joio", "Árvore frutífera"] },
      { question: "O que Jesus disse sobre quem se irar contra seu irmão?", answer: "Estará sujeito a julgamento", distractors: ["Perderá sua herança", "Não será ouvido em oração"] },
    ],
    6: [
      { question: "Qual oração Jesus ensinou em Mateus 6?", answer: "O Pai-Nosso", distractors: ["O Salmo 23", "A Oração do Getsêmani"] },
      { question: "Como começa o Pai-Nosso segundo Mateus 6?", answer: "Pai nosso que estás nos céus, santificado seja o teu nome", distractors: ["Senhor, ensina-nos a orar", "Deus meu, Deus meu, por que me abandonaste"] },
      { question: "Onde Jesus disse que os hipócritas gostam de orar?", answer: "Nas sinagogas e esquinas das ruas", distractors: ["No templo", "Em lugares altos"] },
      { question: "O que Jesus disse sobre acumular tesouros?", answer: "Acumulem tesouros no céu, não na terra", distractors: ["O rico nunca entrará no reino", "Vendei tudo e dai aos pobres"] },
      { question: "Segundo Jesus, ninguém pode servir a dois senhores. Quais?", answer: "A Deus e ao dinheiro", distractors: ["A Deus e ao imperador", "Ao bem e ao mal"] },
      { question: "Qual é o pássaro que Jesus cita para falar sobre não se preocupar com a vida?", answer: "Aves do céu", distractors: ["Pombas", "Andorinhas"] },
      { question: "O que Jesus mandou buscar em primeiro lugar em Mateus 6:33?", answer: "O reino de Deus e a sua justiça", distractors: ["A paz e o amor", "A sabedoria e o entendimento"] },
    ],
    7: [
      { question: "Qual regra de ouro Jesus ensinou em Mateus 7?", answer: "Tudo o que quereis que os homens vos façam, fazei-o também a eles", distractors: ["Amai a Deus e ao próximo", "Não faças ao outro o que não queres para ti"] },
      { question: "Jesus disse que a porta que leva à vida é:", answer: "Estreita", distractors: ["Larga", "Dupla"] },
      { question: "Como Jesus disse que se conhece uma árvore?", answer: "Pelos seus frutos", distractors: ["Pela sua sombra", "Por suas raízes"] },
      { question: "O que acontece com a casa construída sobre areia?", answer: "Cai com grande queda", distractors: ["Fica de pé mas balança", "É destruída pelo fogo"] },
      { question: "Jesus disse 'Pedi e dar-se-vos-á; buscai e _____':", answer: "Achareis", distractors: ["Encontrareis a paz", "Sereis saciados"] },
      { question: "O que Jesus disse sobre os falsos profetas?", answer: "Vêm disfarçados de ovelhas, mas por dentro são lobos", distractors: ["Pregam em meu nome mas não me conhecem", "Fazem milagres para enganar"] },
      { question: "Qual é o fundamento da casa que não caiu segundo Mateus 7?", answer: "Rocha", distractors: ["Pedras", "Cimento"] },
    ],
    8: [
      { question: "Qual doença tinha o homem curado por Jesus no início de Mateus 8?", answer: "Lepra", distractors: ["Paralisia", "Cegueira"] },
      { question: "De quem era o servo que Jesus curou à distância em Mateus 8?", answer: "Centurião", distractors: ["Fariseu", "Sacerdote"] },
      { question: "O que Jesus disse sobre o centurião?", answer: "Em ninguém em Israel achei tanta fé", distractors: ["Este homem me seguiu de longe", "Vai e não peques mais"] },
      { question: "O que Jesus acalmou com seu comando no barco?", answer: "A tempestade", distractors: ["As ondas apenas", "O vento apenas"] },
      { question: "O que os discípulos disseram ao ver Jesus acalmar a tempestade?", answer: "Que homem é este que até os ventos e o mar lhe obedecem?", distractors: ["Verdadeiramente és o Filho de Deus", "Nunca vimos coisa assim"] },
      { question: "Quantos endemoninhados Jesus encontrou na região dos gadarenos?", answer: "Dois", distractors: ["Um", "Três"] },
      { question: "Para onde Jesus mandou os demônios expulsos dos gadarenos?", answer: "Para uma manada de porcos", distractors: ["Para o abismo", "Para o deserto"] },
    ],
    9: [
      { question: "A quem Jesus disse 'Filho, os teus pecados te são perdoados' em Mateus 9?", answer: "Ao paralítico", distractors: ["Ao cego", "Ao leproso"] },
      { question: "Quem era Mateus antes de ser chamado por Jesus?", answer: "Cobrador de impostos", distractors: ["Pescador", "Carpinteiro"] },
      { question: "O que os fariseus reclamaram ao ver Jesus comer com pecadores?", answer: "Por que vosso Mestre come com publicanos e pecadores?", distractors: ["Ele viola o sábado", "Ele não lava as mãos"] },
      { question: "Jesus disse que não veio chamar os justos, mas sim:", answer: "Os pecadores ao arrependimento", distractors: ["Os pobres ao reino", "Os enfermos à cura"] },
      { question: "Qual mulher tocou a barra do manto de Jesus e foi curada?", answer: "Uma mulher que sofria de hemorragia há doze anos", distractors: ["A sogra de Pedro", "A filha de Jairo"] },
      { question: "O que Jesus disse sobre a filha do chefe da sinagoga que parecia morta?", answer: "A menina não está morta, mas dorme", distractors: ["Ela logo ressuscitará", "Vossa fé a salvará"] },
      { question: "O que Jesus disse aos dois cegos curados em Mateus 9?", answer: "Segundo a vossa fé vos seja feito", distractors: ["Ide e não pequeis mais", "Vossa cura é completa"] },
    ],
    10: [
      { question: "Quantos discípulos Jesus enviou em Mateus 10?", answer: "Doze", distractors: ["Sete", "Setenta"] },
      { question: "A quem Jesus disse que os discípulos deveriam ir primeiro?", answer: "Às ovelhas perdidas da casa de Israel", distractors: ["Aos gentios", "Aos samaritanos"] },
      { question: "O que Jesus disse que os discípulos deveriam fazer com as cidades que não os recebessem?", answer: "Sacudir o pó dos pés ao sair", distractors: ["Orar por elas e seguir", "Voltar depois"] },
      { question: "Como Jesus disse que enviava os discípulos?", answer: "Como ovelhas no meio de lobos", distractors: ["Como leões entre ovelhas", "Como luz nas trevas"] },
      { question: "O que Jesus disse sobre quem o negar diante dos homens?", answer: "Também o negará diante do Pai celestial", distractors: ["Será expulso do reino", "Perderá sua salvação"] },
      { question: "Jesus disse que não veio trazer paz, mas sim:", answer: "Espada", distractors: ["Divisão", "Fogo"] },
      { question: "Quem achar a própria vida a perderá, mas quem a perder por Jesus:", answer: "A achará", distractors: ["Ganhará a vida eterna", "Será salvo"] },
    ],
    11: [
      { question: "João Batista enviou discípulos perguntar a Jesus se ele era quem?", answer: "O que estava para vir (o Messias)", distractors: ["O profeta prometido", "Elias"] },
      { question: "O que Jesus disse sobre João Batista entre os nascidos de mulher?", answer: "Não se levantou maior do que João Batista", distractors: ["Ele é o maior profeta", "Nenhum igual a ele existiu"] },
      { question: "Jesus comparou sua geração a crianças que:", answer: "Tocam flauta e não dançam, fazem lamentação e não choram", distractors: ["Brincam mas não trabalham", "Ouvem mas não entendem"] },
      { question: "Que cidades Jesus repreendeu por não se arrependeram apesar dos milagres?", answer: "Corazim, Betsaida e Cafarnaum", distractors: ["Jericó, Samaria e Nain", "Belém, Nazaré e Caná"] },
      { question: "Jesus disse 'Vinde a mim todos os que estais cansados e sobrecarregados' e prometeu:", answer: "Descanso", distractors: ["Salvação", "Cura"] },
      { question: "Como Jesus descreveu seu jugo?", answer: "Suave e leve", distractors: ["Fácil e breve", "Simples e curto"] },
      { question: "A quem Jesus disse que revelou as coisas escondidas dos sábios?", answer: "Aos pequeninos", distractors: ["Aos humildes de coração", "Aos pobres de espírito"] },
    ],
    12: [
      { question: "Por que os fariseus acusaram os discípulos em Mateus 12?", answer: "Por colherem espigas no sábado", distractors: ["Por não lavarem as mãos", "Por comerem com pecadores"] },
      { question: "Jesus curou o homem de mão ressequida em que dia?", answer: "No sábado", distractors: ["Na Páscoa", "No dia da expiação"] },
      { question: "De que pecado Jesus disse que não haveria perdão?", answer: "A blasfêmia contra o Espírito Santo", distractors: ["O homicídio premeditado", "A apostasia"] },
      { question: "Qual sinal Jesus disse que daria à geração má?", answer: "O sinal do profeta Jonas", distractors: ["O sinal da cruz", "O sinal de Davi"] },
      { question: "Quantos dias Jonas ficou no ventre do grande peixe segundo Jesus?", answer: "Três dias e três noites", distractors: ["Dois dias", "Quarenta dias"] },
      { question: "Quem Jesus disse serem sua mãe e irmãos?", answer: "Quem faz a vontade do Pai celestial", distractors: ["Seus discípulos próximos", "Os que o seguem"] },
      { question: "Jesus disse que a árvore boa dá frutos bons e a má dá frutos:", answer: "Maus", distractors: ["Amargos", "Podres"] },
    ],
    13: [
      { question: "Na parábola do semeador, o que representa a semente que caiu na boa terra?", answer: "Quem ouve a palavra e a entende, dando fruto", distractors: ["Quem recebe a palavra com alegria mas não tem raiz", "Quem ouve mas os cuidados do mundo sufocam"] },
      { question: "O que representa a semente que caiu entre espinhos?", answer: "Quem ouve a palavra, mas os cuidados do mundo a sufocam", distractors: ["Quem a recebe com alegria mas cai na tribulação", "Quem não entende e o maligno a arrebata"] },
      { question: "Na parábola do joio, quem planta o joio entre o trigo?", answer: "O inimigo (o diabo)", distractors: ["Os fariseus", "Os servos descuidados"] },
      { question: "A que Jesus comparou o reino dos céus na parábola da semente de mostarda?", answer: "Ao menor de todos os grãos que se torna grande árvore", distractors: ["A um grão de trigo que multiplica", "A uma semente que demora a crescer"] },
      { question: "Na parábola da pérola preciosa, o que o mercador fez ao encontrá-la?", answer: "Vendeu tudo o que tinha e a comprou", distractors: ["Escondeu-a e ficou guardando", "Vendeu metade de seus bens"] },
      { question: "Na parábola da rede, o que os anjos farão no fim do século?", answer: "Separar os maus dos justos", distractors: ["Recolher os escolhidos", "Queimar o joio"] },
      { question: "Por que Jesus falava em parábolas segundo Mateus 13?", answer: "Para que vendo não vissem e ouvindo não entendessem", distractors: ["Para ensinar de forma simples", "Para cumprir a lei de Moisés"] },
    ],
    14: [
      { question: "Quem mandou matar João Batista?", answer: "Herodes Antipas, a pedido da filha de Herodias", distractors: ["Herodes o Grande", "Pilatos"] },
      { question: "O que Herodes prometeu dar à filha de Herodias?", answer: "O que ela pedisse, até metade do reino", distractors: ["Qualquer presente que quisesse", "Ouro e joias"] },
      { question: "Quantas pessoas Jesus alimentou com cinco pães e dois peixes em Mateus 14?", answer: "Cinco mil homens, além de mulheres e crianças", distractors: ["Quatro mil pessoas", "Cinco mil pessoas"] },
      { question: "O que sobrou após a multiplicação dos pães em Mateus 14?", answer: "Doze cestos cheios", distractors: ["Sete cestos", "Alguns pedaços"] },
      { question: "Quem andou sobre as águas em Mateus 14?", answer: "Jesus e Pedro", distractors: ["Apenas Jesus", "Jesus e João"] },
      { question: "Por que Pedro começou a afundar?", answer: "Porque duvidou", distractors: ["Porque tinha medo das ondas", "Porque o vento era forte demais"] },
      { question: "O que os discípulos disseram ao ver Jesus andar sobre a água?", answer: "Verdadeiramente és o Filho de Deus", distractors: ["Senhor, salva-nos!", "Que visão é esta?"] },
    ],
    15: [
      { question: "O que os fariseus criticaram nos discípulos de Jesus em Mateus 15?", answer: "Não lavavam as mãos antes de comer", distractors: ["Comiam alimentos impuros", "Trabalhavam no sábado"] },
      { question: "O que torna o homem impuro segundo Jesus em Mateus 15?", answer: "O que sai da boca (do coração)", distractors: ["O que entra pela boca", "O contato com impuros"] },
      { question: "De que região era a mulher que pediu a Jesus a cura da filha em Mateus 15?", answer: "Cananeia", distractors: ["Síria", "Fenícia"] },
      { question: "O que a mulher cananeia disse a Jesus que a convenceu a ajudá-la?", answer: "Os cachorrinhos comem das migalhas que caem da mesa dos seus donos", distractors: ["Senhor, tem misericórdia de mim", "Eu creio que tu podes curar"] },
      { question: "Quantas pessoas foram alimentadas na segunda multiplicação de pães em Mateus 15?", answer: "Quatro mil homens, além de mulheres e crianças", distractors: ["Cinco mil pessoas", "Três mil pessoas"] },
      { question: "Quantos pães e peixes havia na segunda multiplicação?", answer: "Sete pães e alguns peixinhos", distractors: ["Cinco pães e dois peixes", "Doze pães e três peixes"] },
      { question: "Quantos cestos sobraram na segunda multiplicação em Mateus 15?", answer: "Sete", distractors: ["Doze", "Cinco"] },
    ],
    16: [
      { question: "O que Pedro confessou sobre Jesus em Mateus 16?", answer: "Tu és o Cristo, o Filho do Deus vivo", distractors: ["Tu és o Profeta que havia de vir", "Tu és o Rei dos reis"] },
      { question: "O que Jesus disse que edificaria sobre a rocha (Pedro)?", answer: "A sua igreja", distractors: ["O seu reino", "O seu templo"] },
      { question: "O que Jesus disse que daria a Pedro?", answer: "As chaves do reino dos céus", distractors: ["Poder sobre demônios", "Autoridade sobre os apóstolos"] },
      { question: "O que Jesus começou a explicar após a confissão de Pedro?", answer: "Que deveria ir a Jerusalém, sofrer, morrer e ressuscitar", distractors: ["Que o reino de Deus estava próximo", "Que seria traído por um dos doze"] },
      { question: "O que Pedro disse quando Jesus falou de sua morte?", answer: "Isso, Senhor, de modo nenhum te acontecerá", distractors: ["Nós nunca te abandonaremos", "Morreremos contigo"] },
      { question: "O que Jesus disse que o Filho do Homem viria fazer em glória?", answer: "Pagar a cada um segundo as suas obras", distractors: ["Estabelecer o reino eterno", "Julgar as nações"] },
      { question: "Quem Jesus chamou de Satanás em Mateus 16?", answer: "Pedro", distractors: ["Judas", "Os fariseus"] },
    ],
    17: [
      { question: "Quem subiu com Jesus ao monte da transfiguração?", answer: "Pedro, Tiago e João", distractors: ["Pedro, André e João", "Tiago, João e Mateus"] },
      { question: "Quem apareceu com Jesus na transfiguração?", answer: "Moisés e Elias", distractors: ["Abraão e Elias", "Davi e Moisés"] },
      { question: "O que a voz da nuvem disse na transfiguração?", answer: "Este é o meu Filho amado, em quem me comprazo; ouvi-o", distractors: ["Este é o Filho do Homem glorificado", "Levantem-se e não temam"] },
      { question: "O que Jesus curou ao descer do monte da transfiguração?", answer: "Um menino epilético (lunático) endemoniado", distractors: ["Um cego de nascença", "Um surdo-mudo"] },
      { question: "Por que os discípulos não puderam expulsar o demônio?", answer: "Por causa da pequenez da fé deles", distractors: ["Porque não tinham autoridade suficiente", "Porque o demônio era muito forte"] },
      { question: "Qual fé Jesus disse que movia montanhas?", answer: "Fé como um grão de mostarda", distractors: ["Fé perfeita", "Fé sem dúvida"] },
      { question: "Como Jesus pagou o imposto do templo?", answer: "Pedro pescou um peixe com uma moeda na boca", distractors: ["Pediu a um discípulo que contribuísse", "Usou do dinheiro comum dos discípulos"] },
    ],
    18: [
      { question: "O que Jesus disse sobre quem recebe uma criança em seu nome?", answer: "Recebe a Jesus", distractors: ["Recebe o reino dos céus", "Agrada ao Pai"] },
      { question: "Que deve fazer a ovelha que se perde segundo a parábola de Mateus 18?", answer: "O pastor deixa as noventa e nove e vai buscar a perdida", distractors: ["A ovelha perdida encontra o caminho de volta", "O pastor chama e ela ouve"] },
      { question: "Quantas vezes Pedro perguntou se deveria perdoar — até sete vezes?", answer: "Sim, Pedro propôs sete vezes", distractors: ["Pedro propôs três vezes", "Pedro propôs dez vezes"] },
      { question: "Quantas vezes Jesus disse que devemos perdoar?", answer: "Setenta vezes sete", distractors: ["Sete vezes sete", "Sem limite definido"] },
      { question: "Na parábola do servo que não perdoou, qual era a sua dívida inicial?", answer: "Dez mil talentos", distractors: ["Cem denários", "Mil talentos"] },
      { question: "O que o rei fez com o servo que não perdoou o companheiro?", answer: "O entregou aos verdugos", distractors: ["Retirou-lhe o perdão e o prendeu", "O expulsou do reino"] },
      { question: "Onde Jesus disse que estaria quando dois ou três se reunissem em seu nome?", answer: "No meio deles", distractors: ["Ao lado deles", "Ouvindo do céu"] },
    ],
    19: [
      { question: "O que Jesus ensinou sobre divórcio em Mateus 19?", answer: "O que Deus uniu o homem não separe", distractors: ["O divórcio é permitido por qualquer causa", "Só o pecado separa o que Deus uniu"] },
      { question: "Qual a única exceção que Jesus deu para o divórcio?", answer: "Infidelidade conjugal (fornicação)", distractors: ["Abandono do lar", "Violência doméstica"] },
      { question: "O que Jesus disse sobre as crianças quando os discípulos as reprovaram?", answer: "Deixai as crianças virem a mim, pois delas é o reino dos céus", distractors: ["As crianças são inocentes diante de Deus", "Não as impeçais de orar"] },
      { question: "O que o jovem rico perguntou a Jesus?", answer: "Que bem farei para ter a vida eterna?", distractors: ["Como posso herdar o reino de Deus?", "O que devo fazer para ser salvo?"] },
      { question: "O que Jesus pediu que o jovem rico fizesse?", answer: "Vendesse tudo, desse aos pobres e o seguisse", distractors: ["Guardasse todos os mandamentos", "Doasse metade de seus bens"] },
      { question: "Jesus disse que é mais fácil um camelo passar pelo quê do que um rico entrar no reino?", answer: "Pelo fundo de uma agulha", distractors: ["Pela porta estreita", "Por um buraco pequeno"] },
      { question: "O que Pedro disse que eles tinham deixado para seguir a Jesus?", answer: "Tudo", distractors: ["Suas famílias", "Seus bens e ofícios"] },
    ],
    20: [
      { question: "Na parábola dos trabalhadores na vinha, a que horas foram contratados os primeiros?", answer: "Às seis da manhã (hora prima)", distractors: ["Às nove da manhã", "Ao meio-dia"] },
      { question: "Quanto o dono da vinha pagou a todos os trabalhadores, independente das horas?", answer: "Um denário", distractors: ["O salário justo por hora", "O dobro para os que chegaram cedo"] },
      { question: "O que a mãe de Tiago e João pediu a Jesus para seus filhos?", answer: "Que sentassem à direita e à esquerda no seu reino", distractors: ["Que fossem os principais apóstolos", "Que fossem protegidos durante a missão"] },
      { question: "Jesus disse que quem quiser ser grande entre vós deve ser:", answer: "Servo de todos", distractors: ["Humilde de coração", "O último de todos"] },
      { question: "Jesus disse que o Filho do Homem não veio para ser servido, mas para:", answer: "Servir e dar a sua vida em resgate por muitos", distractors: ["Ensinar e salvar os perdidos", "Cumprir a lei e os profetas"] },
      { question: "O que Jesus fez ao entrar em Jericó em Mateus 20?", answer: "Curou dois cegos à beira do caminho", distractors: ["Curou um leproso", "Encontrou Zaqueu"] },
      { question: "O que os dois cegos gritaram para Jesus em Jericó?", answer: "Senhor, Filho de Davi, tem misericórdia de nós!", distractors: ["Jesus, salva-nos!", "Filho de Deus, cura-nos!"] },
    ],
    21: [
      { question: "Em que animal Jesus entrou em Jerusalém?", answer: "Jumento e seu jumentinho", distractors: ["Cavalo branco", "Somente um jumentinho"] },
      { question: "O que o povo gritou ao ver Jesus entrar em Jerusalém?", answer: "Hosana ao Filho de Davi!", distractors: ["Bendito o que vem!", "Rei de Israel!"] },
      { question: "O que Jesus fez no templo ao chegar a Jerusalém?", answer: "Expulsou os vendilhões e cambistas", distractors: ["Ensinou o povo por três dias", "Curou os enfermos e cegos"] },
      { question: "Na maldição da figueira, o que aconteceu com ela?", answer: "Secou imediatamente", distractors: ["Secou no dia seguinte", "Nunca mais deu frutos"] },
      { question: "Na parábola dos dois filhos, qual deles fez a vontade do pai?", answer: "O que disse não mas depois se arrependeu e foi", distractors: ["O que disse sim e foi", "Ambos fizeram a vontade do pai"] },
      { question: "O que os lavradores da vinha fizeram com o filho do dono?", answer: "Mataram-no", distractors: ["Expulsaram-no da vinha", "Prenderam-no"] },
      { question: "Que pedra tornou-se a pedra angular segundo Jesus citando os salmos?", answer: "A que os construtores rejeitaram", distractors: ["A pedra do templo", "A pedra do alicerce"] },
    ],
    22: [
      { question: "Na parábola do banquete de casamento, o que o rei fez com o homem sem vestes nupciais?", answer: "Mandou lançá-lo nas trevas exteriores", distractors: ["Expulsou-o do banquete", "Mandou prendê-lo"] },
      { question: "Quais dois grupos tentaram armar uma cilada a Jesus em Mateus 22?", answer: "Fariseus e herodianos (e depois saduceus)", distractors: ["Escribas e sacerdotes", "Fariseus e saduceus"] },
      { question: "A quem Jesus mandou dar o que era dele no episódio do imposto?", answer: "A César o que é de César, e a Deus o que é de Deus", distractors: ["Ao rei o que é do rei", "Ao imperador o que ele cobra"] },
      { question: "Os saduceus não criam em quê?", answer: "Na ressurreição", distractors: ["Nos anjos", "Na vida após a morte"] },
      { question: "Qual é o maior mandamento segundo Jesus em Mateus 22?", answer: "Amar a Deus de todo o coração, alma e mente", distractors: ["Honrar pai e mãe", "Não matar"] },
      { question: "Qual é o segundo mandamento semelhante ao maior segundo Jesus?", answer: "Amar o próximo como a si mesmo", distractors: ["Não cobiçar", "Fazer ao outro o que quer para si"] },
      { question: "De quem Jesus disse ser filho o Cristo, perguntando aos fariseus?", answer: "De Davi", distractors: ["De Abraão", "De Salomão"] },
    ],
    23: [
      { question: "O que Jesus disse sobre os escribas e fariseus que fazem mas não cumprem?", answer: "Fazei o que dizem, mas não façais o que fazem", distractors: ["Ouvi-os mas não os sigais", "Desconfiai de seus ensinamentos"] },
      { question: "Quantas 'ais' Jesus pronunciou contra os escribas e fariseus em Mateus 23?", answer: "Sete", distractors: ["Cinco", "Oito"] },
      { question: "Jesus chamou os fariseus de 'sepulcros caiados' porque:", answer: "Por fora parecem belos mas por dentro estão cheios de corrupção", distractors: ["Enganam a todos com suas vestes brancas", "Constroem túmulos dos profetas mas os perseguiram"] },
      { question: "Jesus lamentou sobre qual cidade ao final de Mateus 23?", answer: "Jerusalém", distractors: ["Cafarnaum", "Betânia"] },
      { question: "A que animal Jesus comparou seu desejo de proteger os filhos de Jerusalém?", answer: "Galinha que ajunta seus pintinhos sob as asas", distractors: ["Leão que protege seus filhotes", "Águia que cuida de seus ovos"] },
      { question: "O que Jesus disse que os fariseus fecham com suas ações?", answer: "O reino dos céus diante dos homens", distractors: ["A porta da salvação", "O caminho da verdade"] },
      { question: "Jesus chamou os guias cegos de hipócritas porque coavam:", answer: "O mosquito mas engoliam o camelo", distractors: ["O pequeno mas ignoravam o grande", "A lei mas esqueciam a misericórdia"] },
    ],
    24: [
      { question: "O que Jesus predisse sobre o templo de Jerusalém?", answer: "Não ficará pedra sobre pedra que não seja derrubada", distractors: ["Será destruído pelo fogo", "Os gentios o profanarão"] },
      { question: "Qual sinal Jesus mencionou como 'abominação da desolação'?", answer: "O que foi falado pelo profeta Daniel no lugar santo", distractors: ["O ídolo erigido no templo", "A invasão de exércitos pagãos"] },
      { question: "Jesus disse que os eleitos seriam reunidos de onde?", answer: "Dos quatro ventos, de uma extremidade dos céus à outra", distractors: ["De toda a terra habitada", "Dos confins da terra"] },
      { question: "Jesus disse que ninguém sabe o dia e a hora, nem os anjos, nem o Filho, mas apenas:", answer: "O Pai", distractors: ["Deus Pai e o Espírito Santo", "Somente o Pai celestial"] },
      { question: "Jesus comparou os dias antes de sua vinda aos dias de quem?", answer: "Noé", distractors: ["Ló", "Moisés"] },
      { question: "Na parábola do servo fiel, o que o servo mau fez?", answer: "Começou a espancar os companheiros e a comer e beber com os ébrios", distractors: ["Desperdiçou os bens do senhor", "Abandonou a casa do senhor"] },
      { question: "Jesus disse que passaria o quê antes que esta geração passasse?", answer: "Todas estas coisas", distractors: ["O fim do mundo", "O julgamento final"] },
    ],
    25: [
      { question: "Na parábola das dez virgens, quantas eram sábias?", answer: "Cinco", distractors: ["Sete", "Três"] },
      { question: "O que distinguia as virgens sábias das insensatas?", answer: "As sábias levaram azeite extra em seus vasos", distractors: ["As sábias ficaram acordadas toda a noite", "As sábias chegaram mais cedo"] },
      { question: "Na parábola dos talentos, quantos talentos recebeu cada servo?", answer: "Cinco, dois e um respectivamente", distractors: ["Dez, cinco e dois", "Três, dois e um"] },
      { question: "O que o senhor disse aos servos fiéis na parábola dos talentos?", answer: "Bem está, servo bom e fiel", distractors: ["Muito bem, servo leal", "Parabéns, servo diligente"] },
      { question: "O que o servo que recebeu um talento fez com ele?", answer: "Enterrou na terra", distractors: ["Guardou num baú", "Emprestou a juros"] },
      { question: "Na separação das ovelhas e cabras, o que as ovelhas fizeram ao Rei?", answer: "Deram comida, água, hospedagem, roupas, visitaram os doentes e presos", distractors: ["Oraram por ele e o serviram no templo", "Deram esmolas e jejuaram"] },
      { question: "Quando Jesus disse que os justos entrarão?", answer: "Na vida eterna", distractors: ["No reino preparado desde a fundação do mundo", "No descanso eterno"] },
    ],
    26: [
      { question: "Quem derramou perfume precioso sobre Jesus em Betânia em Mateus 26?", answer: "Uma mulher (com um vaso de alabastro)", distractors: ["Maria, irmã de Lázaro", "Maria Madalena"] },
      { question: "Por quantas moedas de prata Judas concordou em trair Jesus?", answer: "Trinta", distractors: ["Vinte", "Cinquenta"] },
      { question: "O que Jesus disse sobre o pão na Última Ceia?", answer: "Isto é o meu corpo", distractors: ["Este pão representa minha carne", "Comei em memória de mim"] },
      { question: "O que Jesus disse sobre o cálice na Última Ceia?", answer: "Isto é o meu sangue do novo pacto", distractors: ["Este vinho é o símbolo do meu sangue", "Bebei e lembrai de mim"] },
      { question: "Onde Jesus orou na noite da prisão?", answer: "Getsêmani", distractors: ["Monte das Oliveiras", "Vale do Cédron"] },
      { question: "Como Judas identificou Jesus para os guardas?", answer: "Com um beijo", distractors: ["Apontando o dedo para ele", "Chamando-o pelo nome"] },
      { question: "Quantas vezes Pedro negou Jesus antes do galo cantar?", answer: "Três", distractors: ["Duas", "Quatro"] },
    ],
    27: [
      { question: "Quem se arrependeu e devolveu as moedas de prata em Mateus 27?", answer: "Judas Iscariotes", distractors: ["Pedro", "Caifás"] },
      { question: "O que Pilatos fez simbolicamente antes de condenar Jesus?", answer: "Lavou as mãos", distractors: ["Orou em silêncio", "Rasgou suas vestes"] },
      { question: "Quem foi solto no lugar de Jesus?", answer: "Barrabás", distractors: ["Simão de Cirene", "Um ladrão desconhecido"] },
      { question: "Quem foi obrigado a carregar a cruz de Jesus?", answer: "Simão de Cirene", distractors: ["João", "Um soldado romano"] },
      { question: "O que estava escrito no letreiro sobre a cabeça de Jesus na cruz?", answer: "Este é Jesus, o Rei dos Judeus", distractors: ["Jesus Nazareno, o Crucificado", "Jesus Cristo, o Filho de Deus"] },
      { question: "O que rasgou ao meio quando Jesus morreu na cruz?", answer: "O véu do templo", distractors: ["As vestes do sumo sacerdote", "O manto de Jesus"] },
      { question: "Quem pediu o corpo de Jesus a Pilatos?", answer: "José de Arimateia", distractors: ["Nicodemos", "João, o discípulo amado"] },
    ],
    28: [
      { question: "Quem foi primeiro ao sepulcro no domingo de manhã segundo Mateus 28?", answer: "Maria Madalena e a outra Maria", distractors: ["Pedro e João", "As três Marias"] },
      { question: "O que o anjo disse às mulheres no sepulcro?", answer: "Ele não está aqui, porque ressuscitou", distractors: ["Por que buscais o vivo entre os mortos?", "O Senhor ressuscitou como disse"] },
      { question: "Onde Jesus disse que se encontraria com os discípulos após a ressurreição?", answer: "Na Galileia", distractors: ["Em Jerusalém", "No Monte das Oliveiras"] },
      { question: "O que os chefes dos sacerdotes mandaram os soldados dizer sobre o sepulcro vazio?", answer: "Que os discípulos roubaram o corpo enquanto dormiam", distractors: ["Que o corpo foi levado por anjos", "Que houve um terremoto que moveu o corpo"] },
      { question: "Qual é a Grande Comissão dada por Jesus em Mateus 28?", answer: "Ide e fazei discípulos de todas as nações, batizando-os e ensinando-os", distractors: ["Pregai o evangelho a toda criatura", "Amareis uns aos outros como eu vos amei"] },
      { question: "Em nome de quem Jesus mandou batizar os discípulos?", answer: "Do Pai, do Filho e do Espírito Santo", distractors: ["Em nome de Jesus Cristo", "Em nome do Senhor"] },
      { question: "Com que promessa Jesus encerrou o evangelho de Mateus?", answer: "Eis que estou convosco todos os dias até a consumação dos séculos", distractors: ["Voltarei em breve para buscar-vos", "O Espírito Santo será vosso guia"] },
    ],
  },
  marcos: {
    1: [
      { question: "Como começa o evangelho de Marcos?", answer: "Com o ministério de João Batista no deserto", distractors: ["Com a genealogia de Jesus", "Com o nascimento de Jesus"] },
      { question: "O que João Batista dizia sobre o que vinha após ele?", answer: "Não sou digno de desatar a correia das suas sandálias", distractors: ["Eu devo diminuir e ele crescer", "Ele vem com poder e glória"] },
      { question: "O que aconteceu imediatamente após o batismo de Jesus em Marcos 1?", answer: "O Espírito o levou ao deserto", distractors: ["Ele chamou seus primeiros discípulos", "Ele pregou na sinagoga"] },
      { question: "Quais foram os primeiros discípulos chamados em Marcos 1?", answer: "Simão, André, Tiago e João", distractors: ["Pedro, João, Filipe e Natanael", "Simão, André, Mateus e Levi"] },
      { question: "O que Jesus expulsou na sinagoga de Cafarnaum?", answer: "Um espírito imundo (demônio)", distractors: ["Um endemoniado furioso", "Cambistas do templo"] },
      { question: "A quem Jesus curou na casa de Simão em Marcos 1?", answer: "A sogra de Simão (Pedro), que tinha febre", distractors: ["Um leproso", "Um paralítico"] },
      { question: "Por que Jesus se retirava para lugares desertos?", answer: "Para orar", distractors: ["Para descansar", "Para jejuar"] },
    ],
    2: [
      { question: "Como os amigos trouxeram o paralítico a Jesus em Marcos 2?", answer: "Descobriram o telhado e o baixaram em sua maca", distractors: ["Passaram pela multidão empurrando", "Esperaram Jesus sair da casa"] },
      { question: "O que Jesus primeiro disse ao paralítico?", answer: "Filho, os teus pecados te são perdoados", distractors: ["Levanta-te e anda", "Tua fé te curou"] },
      { question: "Por que os escribas se escandalizaram com Jesus em Marcos 2?", answer: "Porque ele perdoou pecados, o que só Deus pode fazer", distractors: ["Por comer com publicanos", "Por curar no sábado"] },
      { question: "Quem era Levi, chamado por Jesus em Marcos 2?", answer: "Filho de Alfeu, cobrador de impostos", distractors: ["Pescador no lago de Genesaré", "Sacerdote do templo"] },
      { question: "Jesus disse que não veio chamar os justos, mas:", answer: "Os pecadores", distractors: ["Os doentes e os pobres", "Os humildes de coração"] },
      { question: "O que Jesus disse sobre colocar vinho novo em odres velhos?", answer: "O vinho novo rompe os odres velhos", distractors: ["O vinho novo deve ser guardado com cuidado", "Os odres velhos não aceitam o novo"] },
      { question: "Jesus disse que o sábado foi feito para quem?", answer: "Para o homem", distractors: ["Para o povo de Israel", "Para honrar a Deus"] },
    ],
    3: [
      { question: "O que Jesus curou na sinagoga no sábado em Marcos 3?", answer: "A mão ressequida de um homem", distractors: ["Um cego", "Um surdo"] },
      { question: "Quantos apóstolos Jesus escolheu em Marcos 3?", answer: "Doze", distractors: ["Sete", "Setenta"] },
      { question: "Quem Jesus chamou de 'filhos do trovão'?", answer: "Tiago e João", distractors: ["Pedro e André", "Simão e Judas"] },
      { question: "O que a família de Jesus pensava sobre ele em Marcos 3?", answer: "Que estava fora de si (louco)", distractors: ["Que estava em perigo", "Que estava sendo perseguido"] },
      { question: "Os escribas disseram que Jesus expulsava demônios por meio de quem?", answer: "Belzebu, o príncipe dos demônios", distractors: ["Por poder próprio", "Por magia egípcia"] },
      { question: "Qual pecado Jesus disse que não teria perdão?", answer: "A blasfêmia contra o Espírito Santo", distractors: ["O homicídio intencional", "A apostasia definitiva"] },
      { question: "Quem Jesus disse ser sua mãe e irmãos em Marcos 3?", answer: "Quem faz a vontade de Deus", distractors: ["Seus discípulos mais próximos", "Os que creem nele"] },
    ],
    4: [
      { question: "Na parábola do semeador, o que representa a semente no caminho?", answer: "Os que ouvem mas Satanás lhes arrebata a palavra", distractors: ["Os que recebem com alegria mas não têm raiz", "Os que são sufocados pelos cuidados do mundo"] },
      { question: "Jesus disse que nada está escondido que não venha a ser:", answer: "Manifesto", distractors: ["Revelado ao seu tempo", "Descoberto no julgamento"] },
      { question: "Qual parábola exclusiva de Marcos fala da semente que cresce sozinha?", answer: "A parábola do crescimento silencioso (semente que germina)", distractors: ["A parábola do semeador", "A parábola do joio"] },
      { question: "A que Jesus comparou o reino de Deus em relação ao seu crescimento?", answer: "A um grão de mostarda que cresce e se torna a maior das ervas", distractors: ["A um fermento que cresce na massa", "A uma semente que cresce lentamente"] },
      { question: "O que Jesus fez durante a tempestade no barco?", answer: "Dormia na popa sobre um travesseiro", distractors: ["Orava em silêncio", "Segurava o mastro"] },
      { question: "Com que palavras Jesus acalmou a tempestade em Marcos 4?", answer: "Cala-te, aquieta-te!", distractors: ["Paz, esteja quieto!", "Silêncio, obedeça!"] },
      { question: "O que os discípulos sentiram após Jesus acalmar a tempestade?", answer: "Grande temor", distractors: ["Grande alegria", "Admiração e gratidão"] },
    ],
    5: [
      { question: "Quantos demônios foram expulsos do endemoninhado gadareno?", answer: "Legião (muitos)", distractors: ["Sete", "Doze"] },
      { question: "Para onde os demônios pediram para ir ao ser expulsos?", answer: "Para a manada de porcos", distractors: ["Para o abismo", "Para o deserto"] },
      { question: "Como estava o homem liberto dos demônios após a cura?", answer: "Vestido e em perfeito juízo", distractors: ["Tremendo e prostrado", "Calmo mas com medo"] },
      { question: "Qual era o nome do chefe da sinagoga que pediu cura para sua filha?", answer: "Jairo", distractors: ["Simão", "Levi"] },
      { question: "Há quantos anos a mulher sofria de hemorragia?", answer: "Doze anos", distractors: ["Sete anos", "Vinte anos"] },
      { question: "O que Jesus disse ao tocar a mão da filha de Jairo?", answer: "Talitá cumi (menina, a ti o digo, levanta-te)", distractors: ["Efatá (abre-te)", "Abba (pai)"] },
      { question: "Quantos anos tinha a filha de Jairo?", answer: "Doze anos", distractors: ["Sete anos", "Quinze anos"] },
    ],
    6: [
      { question: "Por que Jesus não pôde fazer muitos milagres em Nazaré?", answer: "Devido à incredulidade deles", distractors: ["Porque o tempo não era propício", "Porque havia poucos doentes"] },
      { question: "Como Jesus enviou os doze em Marcos 6?", answer: "Dois a dois", distractors: ["Individualmente", "Em grupos de quatro"] },
      { question: "Quem mandou matar João Batista?", answer: "Herodes, a pedido da filha de Herodias", distractors: ["Herodias diretamente", "Os chefes dos sacerdotes"] },
      { question: "O que Jesus disse aos discípulos ao ver a multidão faminta?", answer: "Dai-lhes vós mesmos de comer", distractors: ["Ide comprar pão para todos", "A multidão pode ir à cidade"] },
      { question: "Quantos pães e peixes havia na alimentação dos cinco mil em Marcos 6?", answer: "Cinco pães e dois peixes", distractors: ["Sete pães e dois peixes", "Cinco pães e cinco peixes"] },
      { question: "Após a alimentação dos cinco mil, Jesus foi ao monte para:", answer: "Orar", distractors: ["Descansar", "Ensinar a multidão restante"] },
      { question: "Quando os discípulos viram Jesus andando sobre o mar, o que pensaram?", answer: "Que era um fantasma", distractors: ["Que era uma visão", "Que estava sonhando"] },
    ],
    7: [
      { question: "O que os fariseus criticaram nos discípulos de Jesus em Marcos 7?", answer: "Comer pão com mãos impuras (não lavadas)", distractors: ["Não guardar o sábado", "Comer alimentos proibidos"] },
      { question: "Jesus disse que os fariseus honravam Deus com os lábios mas:", answer: "O coração estava longe dele", distractors: ["As obras não correspondiam", "O culto era vão"] },
      { question: "Como se chamava a tradição que os fariseus seguiam em detrimento dos pais?", answer: "Corbã (oferta dedicada a Deus)", distractors: ["Shekiná", "Mizpá"] },
      { question: "O que Jesus disse que entra no homem e o contamina?", answer: "Nada que entra de fora o contamina; o que sai do coração contamina", distractors: ["Somente a impureza espiritual", "As palavras e os pensamentos"] },
      { question: "Qual era a doença do homem curado em Marcos 7 na região da Decápolis?", answer: "Surdo e gago", distractors: ["Cego e surdo", "Paralítico"] },
      { question: "Que palavra Jesus disse ao curar o surdo-gago em Marcos 7?", answer: "Efatá (abre-te)", distractors: ["Talitá cumi", "Eloí, Eloí"] },
      { question: "De qual região vinha a mulher cujo filha Jesus libertou em Marcos 7?", answer: "Síro-fenícia", distractors: ["Cananeia", "Decápolis"] },
    ],
    8: [
      { question: "Quantas pessoas foram alimentadas na segunda multiplicação em Marcos 8?", answer: "Quatro mil", distractors: ["Cinco mil", "Três mil"] },
      { question: "O que Jesus advertiu sobre o fermento dos fariseus e de Herodes?", answer: "Que se guardassem do fermento (ensino hipócrita)", distractors: ["Que não comessem pão deles", "Que evitassem sua companhia"] },
      { question: "Como Jesus curou o cego de Betsaida?", answer: "Em duas etapas, pondo saliva nos olhos e depois impondo as mãos", distractors: ["Com uma palavra somente", "Tocando os olhos uma vez"] },
      { question: "Quem Pedro disse que Jesus era em Marcos 8?", answer: "Tu és o Cristo", distractors: ["Tu és o Filho de Deus", "Tu és o profeta que havia de vir"] },
      { question: "O que Jesus disse que quem o seguir deve fazer?", answer: "Negar-se a si mesmo, tomar sua cruz e seguir-me", distractors: ["Abandonar tudo e me seguir", "Obedecer a todos os mandamentos"] },
      { question: "O que aproveita ao homem ganhar o mundo inteiro mas perder a alma?", answer: "Nada", distractors: ["Muito pouco", "Tudo se perde"] },
      { question: "De quem Jesus disse ter vergonha terá vergonha dele no julgamento?", answer: "De quem tem vergonha de Jesus e suas palavras", distractors: ["De quem o negou publicamente", "De quem não o seguiu"] },
    ],
    9: [
      { question: "Quem apareceu com Jesus na transfiguração em Marcos 9?", answer: "Moisés e Elias", distractors: ["Abraão e Elias", "Moisés e Abraão"] },
      { question: "O que Pedro propôs fazer na transfiguração?", answer: "Fazer três tendas: uma para Jesus, uma para Moisés e uma para Elias", distractors: ["Registrar o acontecimento", "Adorar em silêncio"] },
      { question: "Qual questão os discípulos discutiam no caminho em Marcos 9?", answer: "Quem era o maior", distractors: ["Quem trairia Jesus", "Quem ficaria ao lado de Jesus no reino"] },
      { question: "O que Jesus disse sobre quem quiser ser o primeiro?", answer: "Será o último de todos e o servo de todos", distractors: ["Deve humilhar-se como uma criança", "Deve colocar os outros acima de si"] },
      { question: "O que Jesus disse sobre quem recebe uma criança em seu nome?", answer: "Recebe a Jesus, e a quem enviou Jesus", distractors: ["Agrada ao Pai celestial", "Recebe a bênção do reino"] },
      { question: "O que Jesus disse sobre o sal em Marcos 9?", answer: "O sal é bom, mas se perder o sabor, com o que o temperar?", distractors: ["Sede como o sal: preservadores do mundo", "O sal representa a sabedoria do evangelho"] },
      { question: "Qual parte do corpo Jesus disse ser melhor cortar para não ir ao inferno?", answer: "Mão, pé ou olho (se causar escândalo)", distractors: ["A língua", "O coração impuro"] },
    ],
    10: [
      { question: "O que Jesus ensinou sobre divórcio em Marcos 10?", answer: "Quem repudiar a esposa e casar com outra comete adultério", distractors: ["O divórcio é tolerado por dureza de coração", "A lei de Moisés permite o divórcio"] },
      { question: "O que Jesus disse sobre as crianças ao repreender os discípulos?", answer: "De tais é o reino de Deus", distractors: ["As crianças são puras diante de Deus", "Não impeçais os pequeninos"] },
      { question: "O que o jovem rico não conseguiu fazer ao seguir Jesus?", answer: "Vender tudo o que tinha e dar aos pobres", distractors: ["Guardar todos os mandamentos", "Abandonar sua família"] },
      { question: "O que Jesus disse ser o propósito do Filho do Homem em Marcos 10:45?", answer: "Não para ser servido, mas para servir e dar a vida em resgate por muitos", distractors: ["Trazer o reino de Deus à terra", "Cumprir a lei e os profetas"] },
      { question: "Como se chamava o cego curado por Jesus em Jericó em Marcos 10?", answer: "Bartimeu, filho de Timeu", distractors: ["Zaqueu", "Simão de Cirene"] },
      { question: "O que Bartimeu fez quando Jesus o curou?", answer: "Seguiu Jesus pelo caminho", distractors: ["Voltou para casa", "Foi ao templo dar graças"] },
      { question: "Quem pediu para sentar à direita e esquerda de Jesus no seu reino?", answer: "Tiago e João", distractors: ["Pedro e André", "Filipe e Bartolomeu"] },
    ],
    11: [
      { question: "Em que animal Jesus entrou em Jerusalém segundo Marcos 11?", answer: "Um jumentinho que nunca havia sido montado", distractors: ["Um cavalo branco", "Uma égua com seu potro"] },
      { question: "O que Jesus fez no templo em Marcos 11?", answer: "Expulsou os que compravam e vendiam e derrubou as mesas dos cambistas", distractors: ["Ensinou por três dias seguidos", "Curou os enfermos no pátio"] },
      { question: "O que Jesus disse que era a sua casa?", answer: "Casa de oração para todas as nações", distractors: ["O lugar onde Deus habita", "A casa do meu Pai"] },
      { question: "O que aconteceu com a figueira amaldiçoada por Jesus?", answer: "Secou desde as raízes", distractors: ["Secou no dia seguinte", "Perdeu todas as folhas"] },
      { question: "Sobre o que Jesus falou usando o exemplo da figueira seca?", answer: "Sobre a fé e o poder da oração", distractors: ["Sobre o juízo que virá sobre Israel", "Sobre os hipócritas que aparentam frutificar"] },
      { question: "Com qual pergunta Jesus desafiou a autoridade dos chefes religiosos?", answer: "O batismo de João era do céu ou dos homens?", distractors: ["Quem é mais importante, Moisés ou Abraão?", "Por que autoridade vocês ensinam no templo?"] },
      { question: "Quando os líderes não responderam à pergunta de Jesus, ele disse:", answer: "Também eu não vos digo com que autoridade faço estas coisas", distractors: ["Minha autoridade vem do Pai dos céus", "Vós mesmos sois testemunhas do que faço"] },
    ],
    12: [
      { question: "Na parábola dos lavradores, o que eles fizeram com o filho do dono?", answer: "Mataram-no e lançaram-no fora da vinha", distractors: ["Expulsaram-no da vinha", "Prenderam-no e enviaram-no ao pai"] },
      { question: "O que Jesus disse sobre o imposto a César em Marcos 12?", answer: "Dai a César o que é de César e a Deus o que é de Deus", distractors: ["Pagai ao rei o que lhe é devido", "O imposto é justo, pagai-o"] },
      { question: "O que os saduceus não acreditavam?", answer: "Na ressurreição", distractors: ["Em anjos", "Na vida após a morte"] },
      { question: "Qual mandamento Jesus apontou como o maior em Marcos 12?", answer: "Amar a Deus de todo o coração, alma, mente e força", distractors: ["Não matar", "Honrar pai e mãe"] },
      { question: "O que a viúva pobre colocou no cofre do templo?", answer: "Duas pequenas moedas (dois óbolos)", distractors: ["Uma moeda de prata", "Tudo o que tinha para o dia"] },
      { question: "Por que Jesus disse que a viúva deu mais que todos?", answer: "Porque deu tudo o que tinha para viver", distractors: ["Porque deu com amor", "Porque seu sacrifício era maior"] },
      { question: "Na ressurreição, de quem a mulher que teve sete maridos será esposa?", answer: "De nenhum deles, pois serão como anjos", distractors: ["Do primeiro marido", "Não haverá casamento na ressurreição"] },
    ],
    13: [
      { question: "O que Jesus predisse sobre o templo em Marcos 13?", answer: "Não ficará pedra sobre pedra que não seja derrubada", distractors: ["O templo será profanado pelos gentios", "Fogo consumirá o templo"] },
      { question: "Qual é o início das dores segundo Jesus em Marcos 13?", answer: "Guerras, rumores de guerras, terremotos e fomes", distractors: ["A perseguição dos crentes", "A aparição de falsos cristos"] },
      { question: "O que Jesus prometeu aos que o pregassem diante de governadores?", answer: "O Espírito Santo os ensinaria o que dizer", distractors: ["Nenhum mal lhes aconteceria", "Anjos os defenderiam"] },
      { question: "Como Jesus descreveu a tribulação que viria?", answer: "Como nunca houve desde o princípio da criação", distractors: ["Como os dias de Noé", "Como a destruição de Sodoma"] },
      { question: "Quem Jesus disse que ninguém conhece o dia e hora de sua vinda?", answer: "Nem os anjos, nem o Filho, mas somente o Pai", distractors: ["Somente o Pai e o Filho", "Somente os profetas designados"] },
      { question: "Com que parábola Jesus encerrou o discurso apocalíptico em Marcos 13?", answer: "A do porteiro vigilante", distractors: ["A das dez virgens", "A do senhor que saiu em viagem"] },
      { question: "Jesus disse para vigiarmos porque:", answer: "Não sabemos quando o Senhor da casa voltará", distractors: ["O fim está próximo", "Os sinais já estão aparecendo"] },
    ],
    14: [
      { question: "Onde Jesus foi ungido com perfume precioso em Marcos 14?", answer: "Em Betânia, na casa de Simão o leproso", distractors: ["No templo de Jerusalém", "Na casa de Lázaro"] },
      { question: "Que combinação Judas fez com os chefes dos sacerdotes?", answer: "Entregá-los Jesus por dinheiro", distractors: ["Revelar onde Jesus estava", "Testemunhar contra Jesus"] },
      { question: "Quem Jesus identificou como o traidor na Última Ceia?", answer: "O que mergulhava o pão com ele no prato", distractors: ["O que estava à sua esquerda", "Judas, diretamente pelo nome"] },
      { question: "Que oração Jesus fez no Getsêmani?", answer: "Abba, Pai, afasta de mim este cálice; contudo, não o que eu quero, mas o que tu queres", distractors: ["Pai, glorifica o teu nome", "Pai, que eles sejam um como nós somos um"] },
      { question: "Quantas vezes Jesus encontrou os discípulos dormindo no Getsêmani?", answer: "Três vezes", distractors: ["Duas vezes", "Uma vez"] },
      { question: "Quem cortou a orelha do servo do sumo sacerdote?", answer: "Um dos presentes (com espada)", distractors: ["Pedro, conforme identificado em João", "Simão Zelote"] },
      { question: "Perante quem Pedro negou Jesus pela terceira vez?", answer: "Diante dos que estavam perto, no pátio", distractors: ["Diante de uma criada", "Diante dos soldados"] },
    ],
    15: [
      { question: "Quem Pilatos ofereceu soltar na Páscoa?", answer: "Barrabás ou Jesus", distractors: ["Um prisioneiro qualquer ou Jesus", "Simão ou Jesus"] },
      { question: "O que os soldados puseram na cabeça de Jesus antes da crucificação?", answer: "Uma coroa de espinhos", distractors: ["Um manto de escárnio", "Um capuz de soldado"] },
      { question: "Que horas Jesus foi crucificado segundo Marcos 15?", answer: "Hora terça (nove da manhã)", distractors: ["Hora sexta (meio-dia)", "Hora nona (três da tarde)"] },
      { question: "O que Jesus exclamou na cruz em Marcos 15?", answer: "Eloí, Eloí, lamá sabactâni? (Deus meu, Deus meu, por que me abandonaste?)", distractors: ["Pai, em tuas mãos entrego o meu espírito", "Está consumado"] },
      { question: "O que o centurião disse ao ver Jesus morrer?", answer: "Verdadeiramente este homem era Filho de Deus", distractors: ["Este era um homem justo", "Certamente este era inocente"] },
      { question: "Quem pediu o corpo de Jesus a Pilatos?", answer: "José de Arimateia", distractors: ["Nicodemos", "João o discípulo"] },
      { question: "O que rasgou no momento da morte de Jesus em Marcos 15?", answer: "O véu do templo de alto a baixo", distractors: ["O manto de Jesus", "As vestes do sumo sacerdote"] },
    ],
    16: [
      { question: "Quem foi ao sepulcro no primeiro dia da semana em Marcos 16?", answer: "Maria Madalena, Maria mãe de Tiago e Salomé", distractors: ["Maria Madalena e a outra Maria", "As três Marias e João"] },
      { question: "O que as mulheres levavam ao sepulcro?", answer: "Especiarias para ungir o corpo de Jesus", distractors: ["Flores e óleos", "Pão e vinho para uma oferta"] },
      { question: "O que as mulheres perguntavam enquanto iam?", answer: "Quem nos removerá a pedra da entrada do sepulcro?", distractors: ["Estará o corpo ainda lá?", "O que faremos se os guardas estiverem lá?"] },
      { question: "O que o jovem vestido de branco disse sobre Jesus?", answer: "Ressuscitou, não está aqui. Ide dizer aos discípulos e a Pedro.", distractors: ["Ele não está aqui; ressuscitou como disse.", "Por que buscais o vivo entre os mortos?"] },
      { question: "A quem Jesus apareceu primeiro após ressuscitar segundo Marcos 16?", answer: "Maria Madalena", distractors: ["Pedro", "Os dois que iam para o campo"] },
      { question: "Qual comissão Jesus deu aos discípulos em Marcos 16?", answer: "Ide por todo o mundo e pregai o evangelho a toda criatura", distractors: ["Fazei discípulos de todas as nações", "Sede minhas testemunhas até os confins da terra"] },
      { question: "O que Jesus disse que acompanharia os que creem segundo Marcos 16?", answer: "Expulsariam demônios, falariam novas línguas, curariam enfermos", distractors: ["Nunca lhes faltaria nada", "Seriam protegidos de todo mal"] },
    ],
  },
  lucas: {
    1: [
      { question: "Para quem Lucas dedicou seu evangelho?", answer: "Teófilo", distractors: ["Tito", "Timóteo"] },
      { question: "Quem apareceu a Zacarias para anunciar o nascimento de João?", answer: "O anjo Gabriel", distractors: ["O anjo Miguel", "Um anjo não identificado"] },
      { question: "Por que Zacarias ficou mudo após a visão?", answer: "Por não ter crido nas palavras do anjo", distractors: ["Por ter tocado no altar sagrado", "Por ter caído no solo por medo"] },
      { question: "A quem o anjo Gabriel anunciou a concepção de Jesus?", answer: "À virgem Maria", distractors: ["A Isabel", "A Ana"] },
      { question: "O que Maria disse em resposta ao anúncio do anjo?", answer: "Eis aqui a serva do Senhor; faça-se em mim segundo a tua palavra", distractors: ["Como será isso, se não conheço varão?", "Louvado seja o Senhor que se lembrou de mim"] },
      { question: "O que João fez no ventre de Isabel quando Maria a saudou?", answer: "Saltou de alegria", distractors: ["Moveu-se fortemente", "Ficou quieto"] },
      { question: "Como se chama o cântico de Maria em Lucas 1?", answer: "Magnificat (Minha alma engrandece ao Senhor)", distractors: ["Benedictus", "Nunc Dimittis"] },
    ],
    2: [
      { question: "Por que José e Maria foram a Belém?", answer: "Para o recenseamento decretado por César Augusto", distractors: ["Para a festa da Páscoa", "Para visitar parentes"] },
      { question: "Onde Jesus nasceu em Belém?", answer: "Em uma manjedoura, pois não havia lugar na hospedaria", distractors: ["Em uma casa de parentes", "Em uma caverna fora da cidade"] },
      { question: "Quem recebeu primeiro a notícia do nascimento de Jesus?", answer: "Pastores que estavam no campo", distractors: ["Magos do Oriente", "O sumo sacerdote"] },
      { question: "O que o anjo disse aos pastores?", answer: "Hoje vos nasceu o Salvador, que é Cristo o Senhor, na cidade de Davi", distractors: ["O Filho de Deus nasceu esta noite em Belém", "Ide adorar o Rei que nasceu"] },
      { question: "Quem era Simeão e o que disse ao ver Jesus no templo?", answer: "Um homem justo que aguardava a consolação de Israel; disse o Nunc Dimittis", distractors: ["Um sacerdote que abençoou Jesus", "Um profeta que anunciou seu ministério"] },
      { question: "O que a profetisa Ana fez ao ver Jesus no templo?", answer: "Deu graças a Deus e falou de Jesus a todos que esperavam a redenção de Jerusalém", distractors: ["Profetizou sobre a morte de Jesus", "Anunciou que ele seria o Messias"] },
      { question: "O que aconteceu quando Jesus tinha doze anos e os pais foram ao templo?", answer: "Ficou no templo entre os doutores ouvindo-os e fazendo perguntas", distractors: ["Foi encontrado orando no jardim", "Ensinou na sinagoga"] },
    ],
    3: [
      { question: "Quem pregava no deserto de Judeia em Lucas 3?", answer: "João Batista, filho de Zacarias", distractors: ["Um profeta desconhecido", "Elias ressuscitado"] },
      { question: "O que João dizia aos publicanos que vinham ser batizados?", answer: "Não exijais mais do que o que vos está ordenado", distractors: ["Arrependei-vos e dai esmolas", "Deixai a profissão e segui a Deus"] },
      { question: "O que João disse aos soldados?", answer: "Não maltrateis ninguém, não acuseis falsamente, contentai-vos com vosso soldo", distractors: ["Deixai as armas e segui a paz", "Protegei os oprimidos e os pobres"] },
      { question: "O que aconteceu quando Jesus foi batizado em Lucas 3?", answer: "O céu se abriu, o Espírito desceu em forma corporal como pomba e uma voz do céu falou", distractors: ["João o ungiu com óleo", "Uma nuvem brilhante o cobriu"] },
      { question: "O que a voz do céu disse no batismo de Jesus em Lucas 3?", answer: "Tu és o meu Filho amado; em ti me comprazo", distractors: ["Este é meu servo escolhido", "O Espírito do Senhor está sobre ele"] },
      { question: "A genealogia de Jesus em Lucas 3 sobe até quem?", answer: "Adão, filho de Deus", distractors: ["Abraão", "Noé"] },
      { question: "Quem foi preso antes do batismo de Jesus, mencionado em Lucas 3?", answer: "João Batista", distractors: ["Zacarias", "Herodes o tetrarca"] },
    ],
    4: [
      { question: "Quantos dias Jesus jejuou no deserto em Lucas 4?", answer: "Quarenta dias", distractors: ["Trinta dias", "Vinte dias"] },
      { question: "Qual foi a última tentação do diabo a Jesus em Lucas 4?", answer: "Lançar-se do ponto mais alto do templo", distractors: ["Adorar o diabo", "Transformar pedras em pão"] },
      { question: "Em qual sinagoga Jesus leu o rolo de Isaías?", answer: "Na sinagoga de Nazaré", distractors: ["Na sinagoga de Cafarnaum", "No templo de Jerusalém"] },
      { question: "O que Jesus disse após ler Isaías 61 na sinagoga?", answer: "Hoje se cumpriu esta escritura em vossos ouvidos", distractors: ["Esta profecia fala de mim", "O reino de Deus está próximo"] },
      { question: "Por que os nazarenos quiseram atirar Jesus de um precipício?", answer: "Por não aceitarem seus ensinamentos e se lembrarem de que era filho de José", distractors: ["Por ele curar no sábado", "Por blasfêmia"] },
      { question: "O que Jesus curou na sinagoga de Cafarnaum em Lucas 4?", answer: "Um homem com espírito imundo", distractors: ["Um cego", "Um paralítico"] },
      { question: "O que Jesus fez na casa de Simão Pedro em Cafarnaum?", answer: "Curou a sogra de Pedro que estava com febre", distractors: ["Ensinou os discípulos", "Orou pela família de Pedro"] },
    ],
    5: [
      { question: "O que Jesus disse a Simão Pedro após a pesca milagrosa em Lucas 5?", answer: "Não temas; doravante serás pescador de homens", distractors: ["Levanta-te e me segue", "Abandonai vossas redes e vinde"] },
      { question: "Qual foi a reação de Pedro à pesca milagrosa?", answer: "Caiu aos joelhos de Jesus dizendo: Afasta-te de mim, Senhor, porque sou pecador", distractors: ["Ficou maravilhado e adorou Jesus", "Chamou seus companheiros para ver"] },
      { question: "Como o paralítico foi trazido a Jesus em Lucas 5?", answer: "Desceu pelo telhado numa maca", distractors: ["Foi carregado pela multidão", "Entrou pela janela"] },
      { question: "Quem Jesus chamou do posto de arrecadação de impostos em Lucas 5?", answer: "Levi (Mateus)", distractors: ["Zaqueu", "Bartolomeu"] },
      { question: "Jesus comparou o novo ensinamento ao vinho novo que:", answer: "Deve ser posto em odres novos", distractors: ["Não mistura com o velho", "É mais forte que o velho"] },
      { question: "Por que Jesus disse que não curava o pano novo em veste velha?", answer: "Para não fazer pior rasgão", distractors: ["Para não misturar o velho com o novo", "Para que a roupa velha não se destruísse"] },
      { question: "O que Jesus disse aos fariseus sobre os doentes?", answer: "Os que são sãos não precisam de médico, mas os que estão enfermos", distractors: ["Vim curar os doentes de corpo e alma", "Todos precisam da graça de Deus"] },
    ],
    6: [
      { question: "Quantos apóstolos Jesus escolheu em Lucas 6?", answer: "Doze", distractors: ["Sete", "Setenta"] },
      { question: "Como começa o Sermão da Planície em Lucas 6?", answer: "Com as bem-aventuranças aos pobres, famintos, que choram e perseguidos", distractors: ["Com o mandamento do amor", "Com a lei da oração"] },
      { question: "Quem Jesus disse que eram abençoados no Sermão da Planície?", answer: "Os pobres, os que têm fome, os que choram, os perseguidos por causa de Jesus", distractors: ["Os mansos, os misericordiosos, os puros de coração", "Os humildes, os sofridos, os que buscam a paz"] },
      { question: "O que Jesus disse sobre amar inimigos em Lucas 6?", answer: "Amai vossos inimigos, fazei bem aos que vos odeiam", distractors: ["Tolerai vossos inimigos com paciência", "Perdoai vossos inimigos setenta vezes sete"] },
      { question: "Qual parábola do cego guiando cego Jesus usou em Lucas 6?", answer: "Se um cego guiar outro cego, ambos cairão no fosso", distractors: ["O cego que vê mais que o vidente", "O guia que não conhece o caminho"] },
      { question: "Com que Jesus comparou o hipócrita que critica o irmão em Lucas 6?", answer: "Alguém que vê o cisco no olho alheio mas não vê a trave no próprio", distractors: ["Alguém que julga sem conhecer", "Um cego que critica o que vê"] },
      { question: "Qual é a regra de ouro ensinada por Jesus em Lucas 6?", answer: "Como quereis que os homens vos façam, assim fazei-lhes vós também", distractors: ["Amai uns aos outros como eu vos amei", "Não façais ao próximo o que não quereis para vós"] },
    ],
    7: [
      { question: "De quem Jesus curou o servo em Cafarnaum em Lucas 7?", answer: "De um centurião romano", distractors: ["De um fariseu", "De um oficial do rei"] },
      { question: "O que o centurião disse sobre si mesmo ao pedir a cura?", answer: "Não sou digno de que entres sob o meu teto", distractors: ["Sou homem de autoridade e sei que podes curar", "Tua palavra basta para curar meu servo"] },
      { question: "Quem Jesus ressuscitou na cidade de Naim?", answer: "O filho único de uma viúva", distractors: ["A filha de um chefe da sinagoga", "O servo de um comerciante"] },
      { question: "O que João Batista mandou perguntar a Jesus?", answer: "És tu o que havia de vir ou esperamos outro?", distractors: ["Quando virá o reino de Deus?", "Devo continuar batizando?"] },
      { question: "Quem Jesus disse ser maior entre os nascidos de mulher?", answer: "João Batista", distractors: ["Moisés", "Elias"] },
      { question: "O que a mulher pecadora fez aos pés de Jesus na casa de Simão o fariseu?", answer: "Lavou com suas lágrimas, enxugou com os cabelos e ungiu com perfume", distractors: ["Prostrou-se e adorou em silêncio", "Lavou os pés e colocou flores"] },
      { question: "Qual parábola Jesus usou para falar do perdão da mulher pecadora?", answer: "A dos dois devedores (um que devia quinhentos e outro cinquenta denários)", distractors: ["A do filho pródigo", "A da ovelha perdida"] },
    ],
    8: [
      { question: "Quem acompanhava Jesus e os doze nas viagens segundo Lucas 8?", answer: "Várias mulheres que os serviam com seus bens", distractors: ["Multidões de seguidores", "Apenas os doze apóstolos"] },
      { question: "Quem era Maria Madalena segundo Lucas 8?", answer: "Mulher de quem Jesus expulsara sete demônios", distractors: ["Mulher pecadora arrependida", "Irmã de Marta e Lázaro"] },
      { question: "O que Jesus fez ao ser acordado pelos discípulos na tempestade?", answer: "Repreendeu o vento e as ondas e tudo se acalmou", distractors: ["Orou e o vento cessou", "Ordenou que os discípulos tivessem fé"] },
      { question: "Qual mulher foi curada ao tocar a borda da veste de Jesus em Lucas 8?", answer: "Uma mulher que tinha fluxo de sangue há doze anos", distractors: ["A sogra de Pedro", "A mulher cananeia"] },
      { question: "O que Jesus disse ao entrar na casa de Jairo onde choravam pela filha?", answer: "Não choreis; ela não está morta, mas dorme", distractors: ["Afastai-vos; ela logo se levantará", "Vossa fé a restaurará"] },
      { question: "Com que palavras Jesus ressuscitou a filha de Jairo?", answer: "Menina, levanta-te!", distractors: ["Talitá cumi", "Levanta-te em meu nome"] },
      { question: "Segundo a parábola do semeador em Lucas 8, o que representa a semente na boa terra?", answer: "Os que ouvem a palavra com coração honesto e bom, a retêm e dão fruto com perseverança", distractors: ["Os que ouvem e imediatamente obedecem", "Os que guardam a palavra no coração"] },
    ],
    9: [
      { question: "O que Jesus deu de autoridade aos doze quando os enviou em Lucas 9?", answer: "Poder e autoridade sobre todos os demônios e para curar enfermidades", distractors: ["Autoridade para pregar em seu nome", "Poder de batizar e ensinar"] },
      { question: "Quem Herodes pensava que Jesus poderia ser?", answer: "João Batista ressuscitado", distractors: ["Elias", "Um dos antigos profetas"] },
      { question: "Quantos pães e peixes havia na alimentação dos cinco mil em Lucas 9?", answer: "Cinco pães e dois peixes", distractors: ["Sete pães e dois peixes", "Doze pães e cinco peixes"] },
      { question: "O que Pedro confessou sobre Jesus em Lucas 9?", answer: "Tu és o Cristo de Deus", distractors: ["Tu és o Filho do Deus vivo", "Tu és o Salvador do mundo"] },
      { question: "Quem subiu com Jesus ao monte da transfiguração em Lucas 9?", answer: "Pedro, Tiago e João", distractors: ["Pedro, André e João", "Os três discípulos mais próximos"] },
      { question: "O que Jesus disse sobre quem olha para trás depois de pôr a mão no arado?", answer: "Não é apto para o reino de Deus", distractors: ["Não pode ser meu discípulo", "Será como a mulher de Ló"] },
      { question: "O que a voz da nuvem disse na transfiguração em Lucas 9?", answer: "Este é o meu Filho escolhido; ouvi-o", distractors: ["Este é o meu Filho amado, em quem me comprazo", "Este é o profeta prometido, ouçam-no"] },
    ],
    10: [
      { question: "Quantos Jesus enviou na missão de Lucas 10?", answer: "Setenta (ou setenta e dois)", distractors: ["Doze", "Quarenta"] },
      { question: "O que Jesus disse que havia visto quando os setenta voltaram com alegria?", answer: "Satanás caindo do céu como um relâmpago", distractors: ["O reino de Deus chegando", "Os demônios sendo derrotados"] },
      { question: "Quem é o próximo na parábola do bom samaritano?", answer: "O que mostrou misericórdia", distractors: ["O samaritano", "O viajante ferido"] },
      { question: "O que o samaritano fez pelo homem ferido na estrada?", answer: "Curou suas feridas, o colocou em seu animal, o levou à hospedaria e pagou sua estadia", distractors: ["Chamou ajuda e ficou com ele", "O levou à cidade mais próxima"] },
      { question: "Quem passou pelo lado do ferido sem ajudar antes do samaritano?", answer: "Um sacerdote e um levita", distractors: ["Um fariseu e um escriba", "Dois mercadores"] },
      { question: "O que Marta reclamou de Maria em Lucas 10?", answer: "Que a deixava servir sozinha enquanto ficava aos pés de Jesus", distractors: ["Que não ajudava nos afazeres domésticos", "Que passava o tempo inteiro fora de casa"] },
      { question: "O que Jesus disse sobre a escolha de Maria?", answer: "Maria escolheu a boa parte que não lhe será tirada", distractors: ["Maria fez bem em ouvir antes de servir", "A parte de Maria é a mais importante"] },
    ],
    11: [
      { question: "Onde Jesus estava quando os discípulos pediram que ensinasse a orar em Lucas 11?", answer: "Em um lugar, orando", distractors: ["Na sinagoga", "No templo"] },
      { question: "Qual versão do Pai-Nosso está em Lucas 11?", answer: "Pai, santificado seja o teu nome; venha o teu reino", distractors: ["Pai nosso que estás nos céus, santificado seja o teu nome", "Nosso Pai celestial, glorificado seja o teu nome"] },
      { question: "Na parábola do amigo importuno, o que o amigo obteve pela persistência?", answer: "O que precisava, pela insistência", distractors: ["A amizade renovada", "Pão suficiente para a festa"] },
      { question: "Jesus disse que quem pede recebe, quem busca acha, e quem bate:", answer: "Abre-se-lhe a porta", distractors: ["Encontra o que procura", "Receberá resposta"] },
      { question: "Se um filho pedir peixe ao pai, este não lhe dará:", answer: "Serpente", distractors: ["Pedra", "Escorpião"] },
      { question: "Jesus disse que o sinal dado à geração má seria:", answer: "O sinal de Jonas", distractors: ["O sinal do templo destruído", "O sinal do Filho do Homem"] },
      { question: "Jesus chamou os fariseus de hipócritas porque limpavam o quê?", answer: "O exterior do copo e do prato, mas por dentro estavam cheios de rapina", distractors: ["Purificavam as mãos mas não o coração", "Lavavam as vestes mas não a alma"] },
    ],
    12: [
      { question: "Jesus chamou de insensato o rico que disse 'alma, tens muitos bens'. Por quê?", answer: "Porque naquela noite sua alma seria exigida", distractors: ["Porque acumulava tesouros mas não era rico para com Deus", "Porque bens materiais não têm valor eterno"] },
      { question: "O que Jesus disse sobre o blasfemo contra o Filho do Homem em Lucas 12?", answer: "Ser-lhe-á perdoado; mas ao que blasfemar contra o Espírito Santo não será perdoado", distractors: ["Todo pecado pode ser perdoado se houver arrependimento", "Blasfemar contra o Filho é o pecado imperdoável"] },
      { question: "Jesus disse que não devia haver ansiedade sobre o quê?", answer: "O que comer, beber e vestir", distractors: ["O futuro e a morte", "As tribulações que viriam"] },
      { question: "Jesus chamou seus discípulos de que animaizinhos em Lucas 12?", answer: "Pequeno rebanho", distractors: ["Cordeiros", "Ovelhas mansas"] },
      { question: "Jesus disse que veio lançar fogo sobre a terra. O que desejava?", answer: "Que já estivesse aceso", distractors: ["Purificar a terra do pecado", "Trazer julgamento aos ímpios"] },
      { question: "O que Jesus disse sobre interpretar os sinais dos tempos?", answer: "Sabeis interpretar o aspecto do céu e da terra, mas não sabeis interpretar este tempo", distractors: ["Os sinais já estão aqui, buscai o reino", "Os que têm olhos verão os sinais"] },
      { question: "Jesus disse para não temer os que matam o corpo mas não podem:", answer: "Matar a alma", distractors: ["Fazer mais nada", "Tirar a vida eterna"] },
    ],
    13: [
      { question: "Sobre os galileus mortos por Pilatos, Jesus disse:", answer: "Se não vos arrependerdes, todos igualmente perecereis", distractors: ["Eles sofreram por seus pecados maiores", "Deus permite o sofrimento dos justos"] },
      { question: "Quantos anos a mulher encurvada estava assim antes de ser curada em Lucas 13?", answer: "Dezoito anos", distractors: ["Doze anos", "Sete anos"] },
      { question: "Por que o chefe da sinagoga ficou indignado com a cura?", answer: "Porque Jesus curou no sábado", distractors: ["Porque Jesus curou sem permissão", "Porque a mulher não havia pedido cura"] },
      { question: "A que Jesus comparou o reino de Deus na parábola da semente de mostarda em Lucas 13?", answer: "Um grão de mostarda que se torna árvore onde as aves fazem ninhos", distractors: ["Uma árvore grande que dá sombra", "Um jardim que cresce de uma semente pequena"] },
      { question: "A que Jesus comparou o reino de Deus usando o exemplo da mulher?", answer: "Ao fermento que a mulher misturou em três medidas de farinha", distractors: ["Ao pão que cresce lentamente", "À colheita que a mulher guarda"] },
      { question: "Por qual porta Jesus disse que devemos nos esforçar para entrar?", answer: "Pela porta estreita", distractors: ["Pela porta da vida", "Pela porta do reino"] },
      { question: "Como Jesus chamou Herodes quando avisado que o queria matar?", answer: "Esta raposa", distractors: ["Este hipócrita", "Este tirano"] },
    ],
    14: [
      { question: "O que Jesus curou num banquete de fariseus no sábado em Lucas 14?", answer: "Um homem hidrópico", distractors: ["Um cego", "Um paralítico"] },
      { question: "O que Jesus aconselhou sobre escolher lugares nos banquetes?", answer: "Sentar-se nos lugares inferiores para não ser humilhado", distractors: ["Esperar para ser convidado a sentar", "Deixar os outros escolherem primeiro"] },
      { question: "Na parábola do grande banquete, quem foi convidado quando os primeiros recusaram?", answer: "Os pobres, aleijados, cegos e coxos das ruas e becos, depois os das estradas", distractors: ["Os estrangeiros e gentios", "Os pecadores e publicanos"] },
      { question: "Por que os convidados originais recusaram o banquete?", answer: "Compraram terra, bois e se casaram", distractors: ["Estavam doentes", "Não queriam ir à festa"] },
      { question: "O que Jesus disse sobre o custo de ser discípulo em Lucas 14?", answer: "Deve-se contar o custo antes de começar, como um construtor ou um rei que vai à guerra", distractors: ["Todo seguidor deve estar pronto para morrer", "A cruz é pesada mas o jugo é suave"] },
      { question: "Quem Jesus disse que não pode ser seu discípulo?", answer: "Quem não renuncia a tudo o que tem", distractors: ["Quem não ama a Deus acima de tudo", "Quem não toma sua cruz"] },
      { question: "Se o sal perder o sabor, para que serve?", answer: "Para nada; é lançado fora", distractors: ["Para adubar a terra", "Para nada mais vale"] },
    ],
    15: [
      { question: "O que a mulher fez ao encontrar a moeda perdida em Lucas 15?", answer: "Chamou as amigas e vizinhas para festejar", distractors: ["Guardou-a com cuidado", "Deu graças a Deus em silêncio"] },
      { question: "O que o pai fez ao ver o filho pródigo voltando de longe?", answer: "Correu, caiu sobre seu pescoço e o beijou", distractors: ["Esperou que chegasse e o recebeu", "Mandou um servo ao seu encontro"] },
      { question: "O que o filho pródigo pediu ao pai quando voltou?", answer: "Que o fizesse como um de seus servos assalariados", distractors: ["Que lhe desse comida e abrigo", "Que o perdoasse e o recebesse de volta"] },
      { question: "O que o pai ordenou ao receber o filho pródigo?", answer: "Vestes, anel, sandálias e matar o novilho cevado para festejar", distractors: ["Uma festa simples de boas-vindas", "Que o banhassem e o vestissem"] },
      { question: "Por que o irmão mais velho ficou irado?", answer: "Porque nunca lhe foi dado um cabrito para festejar com amigos, mas ao irmão que voltou fizeram festa", distractors: ["Porque o pai amava mais ao irmão caçula", "Porque o irmão havia desperdiçado a herança"] },
      { question: "O que o pastor fez ao encontrar a ovelha perdida?", answer: "Colocou-a nos ombros com alegria e chamou amigos para festejar", distractors: ["Trouxe-a de volta ao rebanho", "Curou seus ferimentos e a devolveu"] },
      { question: "Qual é o tema central das três parábolas de Lucas 15?", answer: "A alegria de encontrar o que estava perdido", distractors: ["O perdão incondicional de Deus", "O arrependimento que leva à salvação"] },
    ],
    16: [
      { question: "O que Jesus disse sobre o mordomia infiel e o dinheiro em Lucas 16?", answer: "Usai do dinheiro iníquo para ganhar amigos para a eternidade", distractors: ["O dinheiro é raiz de todo mal", "Nenhum servo pode servir a dois senhores"] },
      { question: "Como se chamava o rico na parábola em Lucas 16?", answer: "Não é nomeado (apenas chamado de 'um certo homem rico')", distractors: ["Dives", "Midas"] },
      { question: "Como se chamava o mendigo na parábola do rico e Lázaro?", answer: "Lázaro", distractors: ["Bartimeu", "Simão"] },
      { question: "Onde Lázaro foi depois de morrer?", answer: "Para o seio de Abraão", distractors: ["Para o paraíso", "Para o céu"] },
      { question: "O que o rico pediu a Abraão?", answer: "Que enviasse Lázaro para molhar seu dedo e refrescar sua língua", distractors: ["Que o tirasse do tormento", "Que enviasse Lázaro para avisar sua família"] },
      { question: "Por que não era possível cruzar entre o rico e Lázaro?", answer: "Havia um grande abismo fixo entre eles", distractors: ["Era proibido por decreto divino", "As fronteiras do além não podem ser atravessadas"] },
      { question: "O que Abraão disse sobre os irmãos do rico?", answer: "Têm Moisés e os profetas; ouçam-nos", distractors: ["Cada um será responsável por suas escolhas", "O tempo de arrependimento deles já passou"] },
    ],
    17: [
      { question: "Jesus curou dez leprosos em Lucas 17, mas quantos voltaram para agradecer?", answer: "Um", distractors: ["Três", "Dois"] },
      { question: "De qual nação era o leproso que voltou para agradecer?", answer: "Samaritano", distractors: ["Galileu", "Judeu"] },
      { question: "O que Jesus disse ao leproso grato?", answer: "Levanta-te e vai; a tua fé te salvou", distractors: ["Sua gratidão te curou completamente", "Vai e mostra-te ao sacerdote"] },
      { question: "Como Jesus disse que o reino de Deus viria segundo Lucas 17?", answer: "Não com aparência exterior; está dentro de vós", distractors: ["Com sinais nos céus e na terra", "Com poder e grande glória"] },
      { question: "A quem Jesus comparou os dias do Filho do Homem?", answer: "Aos dias de Noé e de Ló", distractors: ["Aos dias de Moisés", "Aos dias de Elias"] },
      { question: "O que Jesus disse sobre quem procurar salvar a vida?", answer: "A perderá; mas quem a perder a salvará", distractors: ["Não encontrará a vida verdadeira", "Nunca conhecerá o reino de Deus"] },
      { question: "O que Jesus disse sobre o escandaloso que faz tropeçar pequeninos?", answer: "Melhor lhe seria que se lançasse ao mar com uma pedra de moinho ao pescoço", distractors: ["Seria expulso do reino de Deus", "Sofreria julgamento severo"] },
    ],
    18: [
      { question: "O que a viúva pedia repetidamente ao juiz injusto em Lucas 18?", answer: "Que lhe fizesse justiça contra seu adversário", distractors: ["Que a protegesse dos opressores", "Que julgasse seu caso com equidade"] },
      { question: "O que fez o fariseu na oração do fariseu e do publicano?", answer: "Orou agradecendo a Deus que não era como os outros homens", distractors: ["Pediu bênçãos e prosperidade", "Listou suas boas obras para Deus"] },
      { question: "O que o publicano orou em Lucas 18?", answer: "Deus, tem misericórdia de mim, que sou pecador!", distractors: ["Senhor, perdoa os meus pecados", "Não me abandones, pois sou fraco"] },
      { question: "Quem Jesus disse que saiu justificado da oração?", answer: "O publicano", distractors: ["O fariseu", "Os dois, mas em graus diferentes"] },
      { question: "O que Jesus disse sobre receber o reino como criança?", answer: "Quem não receber o reino de Deus como uma criança não entrará nele", distractors: ["Os pequenos são os maiores no reino", "Torna-se como criança para entrar"] },
      { question: "O que aconteceu ao cego às margens de Jericó que gritou para Jesus?", answer: "Jesus o curou e ele o seguiu glorificando a Deus", distractors: ["Jesus o mandou ao sacerdote", "O cego foi curado e voltou para casa"] },
      { question: "Qual era a oração do cego de Jericó em Lucas 18?", answer: "Jesus, Filho de Davi, tem misericórdia de mim!", distractors: ["Senhor, faze que eu veja!", "Filho de Deus, cura-me!"] },
    ],
    19: [
      { question: "Quem era Zaqueu em Lucas 19?", answer: "Chefe dos publicanos e homem rico em Jericó", distractors: ["Um fariseu influente", "Um mercador rico de Jericó"] },
      { question: "Por que Zaqueu subiu numa amoreira?", answer: "Porque era de pequena estatura e queria ver Jesus", distractors: ["Para escapar da multidão", "Para chamar a atenção de Jesus"] },
      { question: "O que Jesus disse ao ver Zaqueu?", answer: "Zaqueu, desce depressa; hoje é necessário que eu fique em tua casa", distractors: ["Vem a mim, Zaqueu, quero falar contigo", "Desça, que hoje trarei salvação à sua casa"] },
      { question: "O que Zaqueu prometeu fazer após receber Jesus?", answer: "Dar metade dos bens aos pobres e restituir quatro vezes o que tivesse tirado injustamente", distractors: ["Deixar o trabalho de publicano", "Dar todos os seus bens ao templo"] },
      { question: "Por que Jesus disse que a salvação chegou à casa de Zaqueu?", answer: "Porque ele também é filho de Abraão", distractors: ["Porque demonstrou fé verdadeira", "Porque se arrependeu publicamente"] },
      { question: "Na parábola das minas em Lucas 19, quantas minas recebeu cada servo?", answer: "Uma mina cada", distractors: ["Cinco para o primeiro, duas para o segundo", "Dez, cinco e uma"] },
      { question: "Jesus disse que veio buscar e salvar:", answer: "O que estava perdido", distractors: ["Os pecadores arrependidos", "Os pobres e os marginalizados"] },
    ],
    20: [
      { question: "O que Jesus respondeu sobre o imposto a César em Lucas 20?", answer: "Dai a César o que é de César e a Deus o que é de Deus", distractors: ["Pagai o imposto pois a lei assim exige", "O imposto é justo; cumpri a lei do rei"] },
      { question: "Na parábola dos lavradores maus, o que eles fizeram com o filho do dono?", answer: "Lançaram-no fora da vinha e o mataram", distractors: ["Espancaram-no e o enviaram de volta", "Prenderam-no na vinha"] },
      { question: "Que texto Jesus citou ao falar da pedra angular?", answer: "A pedra que os construtores rejeitaram tornou-se a pedra angular", distractors: ["Sobre esta rocha edificarei minha igreja", "Vejam a pedra que escolhi para o fundamento"] },
      { question: "O que Jesus disse sobre Deus ser o Deus dos vivos ao refutar os saduceus?", answer: "Deus é Deus de Abraão, Isaque e Jacó; e Deus não é de mortos, mas de vivos", distractors: ["Os mortos ressuscitarão pois Deus os tem em memória", "Deus criou a vida e a preserva para sempre"] },
      { question: "Na ressurreição, como são os que ressuscitam?", answer: "Como anjos, e são filhos de Deus", distractors: ["Serão espíritos sem corpo", "Serão como eram em vida, mas glorificados"] },
      { question: "Jesus alertou sobre os escribas que gostam de:", answer: "Andar em vestes compridas, receber saudações nas praças e os primeiros lugares", distractors: ["Fazer longas orações em público", "Mostrar sua sabedoria e conhecimento"] },
      { question: "Quem perguntou a Jesus sobre a autoridade com que ele agia?", answer: "Os principais sacerdotes, escribas e anciãos", distractors: ["Os fariseus e herodianos", "Os saduceus e doutores da lei"] },
    ],
    21: [
      { question: "A viúva pobre lançou quanto no cofre do templo em Lucas 21?", answer: "Duas moedas pequenas (dois óbolos)", distractors: ["Uma moeda de ouro", "Tudo o que tinha exceto uma moeda"] },
      { question: "Por que Jesus disse que a viúva deu mais que todos?", answer: "Ela deu tudo o que tinha para viver; os outros deram do que lhes sobrava", distractors: ["Sua oferta foi a mais sacrificial", "Deus viu seu coração e multiplicou o valor"] },
      { question: "O que Jesus predisse sobre o templo em Lucas 21?", answer: "Não ficará pedra sobre pedra que não seja derrubada", distractors: ["O templo será destruído pelos gentios", "Fogo descerá do céu sobre o templo"] },
      { question: "O que Jesus disse que aconteceria com Jerusalém?", answer: "Seria cercada por exércitos e destruída", distractors: ["Os gentios a tomariam por um tempo", "Seria sitiada mas não destruída"] },
      { question: "Jesus disse que os seus cabelos da cabeça não pereceriam. O que quis dizer?", answer: "Os discípulos seriam preservados espiritualmente mesmo sofrendo", distractors: ["Nenhum discípulo morreria perseguido", "Deus os protegeria de todo perigo"] },
      { question: "O que Jesus disse para fazer quando virem os sinais se cumprirem?", answer: "Levantar a cabeça, pois a redenção se aproxima", distractors: ["Orar e jejuar pelo fim", "Aguardar com paciência"] },
      { question: "Jesus disse que o céu e a terra passariam, mas o que não passaria?", answer: "As suas palavras", distractors: ["O amor de Deus", "A verdade de Deus"] },
    ],
    22: [
      { question: "O que Satanás entrou em Judas para que ele fizesse em Lucas 22?", answer: "Entregar Jesus aos principais sacerdotes", distractors: ["Negar Jesus publicamente", "Abandonar os apóstolos"] },
      { question: "Como os discípulos prepararam a Páscoa em Lucas 22?", answer: "Pedro e João foram preparar o aposento alto indicado por um homem com um cântaro de água", distractors: ["Compraram o cordeiro no templo", "Foram a casa de um rico fariseu"] },
      { question: "O que Jesus disse sobre o cálice na Última Ceia em Lucas 22?", answer: "Este cálice é a nova aliança no meu sangue, derramado por vós", distractors: ["Este vinho é o símbolo da nova aliança", "Bebei disto em memória de mim"] },
      { question: "Quem Jesus disse que seria o maior entre os discípulos?", answer: "O que serve, como o que está à mesa é servido pelo que serve", distractors: ["O mais humilde de coração", "O que lidera com sabedoria"] },
      { question: "O que Jesus disse que Satanás pedira para fazer com os discípulos?", answer: "Peneirá-los como o trigo", distractors: ["Tentá-los um a um", "Separar os verdadeiros dos falsos"] },
      { question: "Quantas vezes o galo cantou antes de Pedro negar a Jesus três vezes em Lucas 22?", answer: "Uma vez (após a terceira negação)", distractors: ["Duas vezes", "Três vezes"] },
      { question: "O que Jesus fez no Monte das Oliveiras antes de ser preso?", answer: "Orou com sudor como gotas de sangue", distractors: ["Ensinou os discípulos pela última vez", "Abençoou os doze apóstolos"] },
    ],
    23: [
      { question: "A quem Pilatos enviou Jesus quando soube que era galileu?", answer: "A Herodes", distractors: ["Ao sumo sacerdote", "Ao conselho dos anciãos"] },
      { question: "O que Jesus disse às mulheres que choravam no caminho para a cruz?", answer: "Não choreis por mim; chorai por vós mesmas e por vossos filhos", distractors: ["Não me pranteis; em breve ressuscitarei", "Vossas lágrimas agradam ao Pai"] },
      { question: "O que Jesus pediu a Deus sobre os que o crucificaram?", answer: "Pai, perdoa-lhes, porque não sabem o que fazem", distractors: ["Pai, não lhes imputes este pecado", "Senhor, tem misericórdia deles"] },
      { question: "O que o ladrão arrependido pediu a Jesus na cruz?", answer: "Lembra-te de mim quando entrares no teu reino", distractors: ["Salva-nos a nós e a ti mesmo", "Se és o Cristo, salva-te e a nós"] },
      { question: "O que Jesus prometeu ao ladrão arrependido?", answer: "Hoje estarás comigo no paraíso", distractors: ["Serás salvo por tua fé", "No último dia ressuscitarás"] },
      { question: "Que horas houve trevas sobre toda a terra em Lucas 23?", answer: "Da hora sexta à hora nona (meio-dia às três)", distractors: ["Da hora terça à hora sexta", "Da hora nona ao pôr do sol"] },
      { question: "Com que palavras Jesus morreu segundo Lucas 23?", answer: "Pai, nas tuas mãos entrego o meu espírito", distractors: ["Está consumado", "Deus meu, por que me abandonaste?"] },
    ],
    24: [
      { question: "Quem foi ao sepulcro no primeiro dia da semana em Lucas 24?", answer: "As mulheres que tinham vindo com Jesus da Galileia", distractors: ["Pedro e João", "Maria Madalena sozinha"] },
      { question: "O que os dois homens vestidos de branco perguntaram às mulheres?", answer: "Por que buscais o vivo entre os mortos?", distractors: ["Ele não está aqui, mas ressuscitou", "Ide depressa e anunciai a ressurreição"] },
      { question: "Para onde iam os dois discípulos no caminho de Emaús?", answer: "Para a aldeia de Emaús, a sessenta estádios de Jerusalém", distractors: ["Para a Galileia", "Para Betânia"] },
      { question: "O que fez os discípulos de Emaús reconhecerem Jesus?", answer: "Ao partir o pão", distractors: ["Ao ouvir sua voz", "Ao ver suas mãos feridas"] },
      { question: "O que Jesus disse sobre si mesmo usando Moisés e todos os profetas em Lucas 24?", answer: "Era necessário que o Cristo padecesse e ressuscitasse ao terceiro dia", distractors: ["Todas as escrituras falam de mim", "O Messias devia sofrer antes de reinar"] },
      { question: "O que Jesus mostrou aos discípulos para provar que não era fantasma em Lucas 24?", answer: "Suas mãos e seus pés, e comeu peixe assado na frente deles", distractors: ["Suas chagas e seu lado ferido", "Sua aparência física e voz reconhecível"] },
      { question: "Com o que Jesus disse que os discípulos seriam revestidos ao aguardarem em Jerusalém?", answer: "Poder do alto (o Espírito Santo)", distractors: ["A presença de Deus", "Autoridade para pregar"] },
    ],
  },
};
