import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_JOB: Record<string, Record<number, BankQuestion[]>> = {
    job: {
        1: [
            { question: "Onde vivia o homem chamado Jó?", answer: "Na terra de Uz", distractors: ["Em Ur dos Caldeus", "No deserto de Zur"], reference: "Jó 1:1" },
            { question: "O que Deus disse a Satanás sobre o caráter de Jó?", answer: "Homem íntegro, reto, temente a Deus", distractors: ["O homem mais rico", "Aquele que nunca pecou"], reference: "Jó 1:8" },
            { question: "Quantos filhos e filhas Jó tinha antes das provações?", answer: "Sete filhos e três filhas", distractors: ["Dez de cada", "Cinco de cada"], reference: "Jó 1:2" },
            { question: "Qual foi a primeira tragédia que atingiu os filhos de Jó?", answer: "Um vento derrubou a casa sobre eles", distractors: ["Levaram cativos os sabeus", "Morreram de praga"], reference: "Jó 1:19" },
            { question: "O que Jó fez ao saber da perda de bens e filhos?", answer: "Rasgou o manto, rapou a cabeça e adorou", distractors: ["Amaldiçoou o dia em que nasceu", "Pediu vingança"], reference: "Jó 1:20" },
            { question: "Qual foi a frase famosa de Jó após as perdas?", answer: "O Senhor o deu, e o Senhor o tomou...", distractors: ["Deus é injusto", "Nada restou de mim"], reference: "Jó 1:21" },
            { question: "Quem atacou os bois e jumentos de Jó no primeiro desastre?", answer: "Os sabeus", distractors: ["Os caldeus", "Os amalequitas"], reference: "Jó 1:15" },
        ],
        2: [
            { question: "Com que enfermidade Satanás feriu o corpo de Jó na segunda prova?", answer: "Chagas malignas da planta do pé ao alto da cabeça", distractors: ["Cegueira", "Paralisia"], reference: "Jó 2:7" },
            { question: "O que a mulher de Jó disse a ele no auge do sofrimento?", answer: "Amaldiçoa a Deus e morre", distractors: ["Pede perdão", "Foge de Uz"], reference: "Jó 2:9" },
            { question: "Como Jó respondeu à sugestão de sua mulher?", answer: "Como fala qualquer doida, falas tu; receberemos o bem...", distractors: ["Tens razão", "Deus me abandonou"], reference: "Jó 2:10" },
            { question: "Quem eram os três amigos de Jó que foram consolá-lo?", answer: "Elifas, Bildade e Zofar", distractors: ["Eliú, Arão e Naor", "Naamã e Elifaz"], reference: "Jó 2:11" },
            { question: "Por quantos dias os amigos de Jó ficaram em silêncio com ele?", answer: "Sete dias e sete noites", distractors: ["Três dias", "Cento e oitenta dias"], reference: "Jó 2:13" },
            { question: "O que Jó usava para se coçar sentado entre a cinza?", answer: "Um caco de cerâmica", distractors: ["Uma pedra", "Sua mão"], reference: "Jó 2:8" },
            { question: "Por que os amigos não falaram palavra alguma inicialmente?", answer: "Viam que a dor era muito grande", distractors: ["Proibição", "Não o reconheceram"], reference: "Jó 2:13" },
        ],
        3: [
            { question: "O que Jó amaldiçoou quando abriu a boca no capítulo 3?", answer: "O dia do seu nascimento", distractors: ["O nome dos pais", "A terra de Uz"], reference: "Jó 3:1" },
            { question: "O que Jó desejava que tivesse acontecido no dia em que nasceu?", answer: "Que as trevas o tivessem coberto", distractors: ["Que fosse rico", "Que houvesse luz"], reference: "Jó 3:4-5" },
            { question: "Qual o destino daqueles que deitam na sepultura, segundo Jó?", answer: "Dormiria com os reis da terra", distractors: ["Viveria em jardim", "Se tornariam anjos"], reference: "Jó 3:14" },
            { question: "O que os presos fazem na sepultura, segundo Jó?", answer: "Eles gozam de sossego e não ouvem a voz do feitor", distractors: ["Trabalham sempre", "Buscam luz"], reference: "Jó 3:18" },
            { question: "Como Jó descreve o seu gemido?", answer: "Derrama-se como a água", distractors: ["Como o trovão", "Como o vento"], reference: "Jó 3:24" },
            { question: "O que Jó disse que lhe sobreveio no capítulo 3?", answer: "Aquilo que eu temia", distractors: ["A sorte esperada", "A alegria"], reference: "Jó 3:25" },
            { question: "Jó tinha paz no final do capítulo 3?", answer: "Não tenho sossego, nem descanso, nem paz", distractors: ["Sim, muita paz", "Sentia a cura"], reference: "Jó 3:26" },
        ],
        4: [
            { question: "Quem foi o primeiro amigo a falar com Jó?", answer: "Elifas, o temanita", distractors: ["Bildade", "Zofar"], reference: "Jó 4:1" },
            { question: "Qual a pergunta de Elifas a Jó sobre inocência?", answer: "Quem jamais pereceu sendo inocente?", distractors: ["Onde está o Senhor?", "Por que sofres?"], reference: "Jó 4:7" },
            { question: "O que Elifas viu em uma visão noturna?", answer: "Um espírito que passou diante dele", distractors: ["Anjos", "O rei Assuero"], reference: "Jó 4:15" },
            { question: "O que a voz na visão de Elifas perguntou?", answer: "Seria o homem mortal mais justo do que Deus?", distractors: ["Por que gemes?", "Onde estás?"], reference: "Jó 4:17" },
            { question: "Segundo Elifas, quem semeia o mal, o que colhe?", answer: "O mesmo mal", distractors: ["Arrependimento", "Paz"], reference: "Jó 4:8" },
            { question: "Como Elifas descreve o fôlego de Deus sobre os perversos?", answer: "Pelo sopro de Deus perecem", distractors: ["Lentamente", "Fogo e água"], reference: "Jó 4:9" },
            { question: "De onde vem a palavra que Elifas recebeu?", answer: "Foi-me trazida em segredo; meu ouvido percebeu um sussurro", distractors: ["De um livro antigo", "Da praça central"], reference: "Jó 4:12" },
        ],
        5: [
            { question: "Segundo Elifas, o que a ira faz com o insensato?", answer: "Mata o insensato", distractors: ["Dá força", "Traz paz"], reference: "Jó 5:2" },
            { question: "Como Elifas descreve o nascimento do homem para o sofrimento?", answer: "Como as faúlhas voam para cima", distractors: ["Como o sol nasce", "Como o rio corre"], reference: "Jó 5:7" },
            { question: "O que sucede com o homem a quem Deus corrige?", answer: "Bem-aventurado é o homem", distractors: ["Ele morre logo", "Ele deve fugir"], reference: "Jó 5:17" },
            { question: "Se Deus fere, o que Suas mãos também fazem?", answer: "Elas curam", distractors: ["Não fazem nada", "Trazem trevas"], reference: "Jó 5:18" },
            { question: "Em quantas angústias Deus livra o homem, segundo Elifas?", answer: "Em seis, e na sétima o mal não te tocará", distractors: ["Doze", "Nenhuma"], reference: "Jó 5:19" },
            { question: "Que animal não temerás, segundo Elifas?", answer: "As feras da terra", distractors: ["O leviatã", "O unicórnio"], reference: "Jó 5:22" },
            { question: "Qual o fim do homem justo, segundo Elifas?", answer: "Irás para a sepultura em plena idade", distractors: ["Desaparecerás", "Será eterno"], reference: "Jó 5:26" },
        ],
        6: [
            { question: "Como Jó descreve o peso de sua angústia no capítulo 6?", answer: "Mais pesada que a areia dos mares", distractors: ["Leve perante o pecado", "Como montanha"], reference: "Jó 6:3" },
            { question: "O que Jó deseja que Deus fizesse com ele?", answer: "Que Deus se agradasse em esmagá-lo", distractors: ["Dasse ouro", "Fizesse rei"], reference: "Jó 6:9" },
            { question: "A que Jó comparou as palavras de seus amigos?", answer: "Ao sabor da clara do ovo (insosso)", distractors: ["Mel doce", "Espadas"], reference: "Jó 6:6" },
            { question: "Como Jó descreve o desapontamento com os amigos?", answer: "Foram desleais como um ribeiro que seca", distractors: ["São rochas", "São árvores"], reference: "Jó 6:15" },
            { question: "O que Jó quer que seus amigos fizessem em vez de condená-lo?", answer: "Ensinai-me, e calar-me-ei", distractors: ["Ide embora", "Trazei comida"], reference: "Jó 6:24" },
            { question: "Jó pediu riquezas por seu resgate aos amigos?", answer: "Não, ele questionou se pedira alguma coisa", distractors: ["Sim, ouro", "Sim, gado"], reference: "Jó 6:22" },
            { question: "O que Jó diz sobre 'palavras retas'?", answer: "Como as palavras retas são fortes!", distractors: ["Não servem", "São fracas"], reference: "Jó 6:25" },
        ],
        7: [
            { question: "A que Jó comparou a vida na terra?", answer: "Ao serviço militar ou labor forçado", distractors: ["Ao banquete", "Ao sono"], reference: "Jó 7:1" },
            { question: "Como Jó descreveu a rapidez de seus dias no capítulo 7?", answer: "Mais velozes que a lançadeira do tecelão", distractors: ["Lentos como carruagem", "Como a sombra"], reference: "Jó 7:6" },
            { question: "Por que Jó disse que não pouparia a sua boca?", answer: "Falará a minha angústia e amargura", distractors: ["Desejo louvar", "Tenho sede"], reference: "Jó 7:11" },
            { question: "O que Jó perguntou a Deus sobre ser vigiado?", answer: "Por que fizeste de mim o teu alvo?", distractors: ["Deus me odeia?", "Onde estás?"], reference: "Jó 7:20" },
            { question: "O que Jó sente quando se deita no leito?", answer: "Diz: 'Quando me levantarei? A noite se faz longa'", distractors: ["Paz absoluta", "Dormia logo"], reference: "Jó 7:4" },
            { question: "Qual a alma de Jó escolheu em vez dos seus ossos?", answer: "A morte", distractors: ["Paciência", "Ouro"], reference: "Jó 7:15" },
            { question: "O que Jó deseja antes de morrer e ser buscado sem ser achado?", answer: "Perdão da sua transgressão", distractors: ["Mais gado", "Novos filhos"], reference: "Jó 7:21" },
        ],
        8: [
            { question: "Quem foi o segundo amigo a falar com Jó?", answer: "Bildade, o suíta", distractors: ["Elifas", "Zofar"], reference: "Jó 8:1" },
            { question: "O que Bildade sugeriu sobre o castigo dos filhos de Jó?", answer: "Pecaram e foram entregues ao seu castigo", distractors: ["Foram vítimas", "Deus errou"], reference: "Jó 8:4" },
            { question: "A que Bildade comparou a esperança do ímpio?", answer: "A uma teia de aranha", distractors: ["A muro de pedra", "Ao ouro"], reference: "Jó 8:14" },
            { question: "Segundo Bildade, onde Jó deve buscar sabedoria?", answer: "Nas gerações passadas", distractors: ["Nos jovens", "No mar"], reference: "Jó 8:8" },
            { question: "Se Jó fosse puro e reto, o que Deus faria por de?", answer: "Restauraria a sua morada justa", distractors: ["Lhe daria asas", "Faria dele rei"], reference: "Jó 8:6" },
            { question: "O que acontece com o que esquece a Deus?", answer: "Sua esperança perecerá", distractors: ["Ficará rico", "Será ignorado"], reference: "Jó 8:13" },
            { question: "Deus rejeita o íntegro, segundo Bildade?", answer: "Eis que Deus não rejeita o íntegro", distractors: ["Sim, por vezes", "Apenas por teste"], reference: "Jó 8:20" },
        ],
        9: [
            { question: "Jó aceita que o homem pode ser justo diante de Deus?", answer: "Como pode o homem ser justo para com Deus?", distractors: ["Sim, sendo bom", "Sim, orando"], reference: "Jó 9:2" },
            { question: "O que Deus faz com as montanhas e o sol, segundo Jó?", answer: "Remove montanhas e o sol não nasce se ele manda", distractors: ["Ele as ignora", "As move com ouro"], reference: "Jó 9:5-7" },
            { question: "A que Jó comparou a rapidez de seus dias no capítulo 9?", answer: "Mais velozes que um correio", distractors: ["Lentos como caracol", "Sombras"], reference: "Jó 9:25" },
            { question: "Como Jó descreve seus dias passando em relação a navios?", answer: "Passam como navios de junco", distractors: ["Grandes galés", "Ancorados"], reference: "Jó 9:26" },
            { question: "O que Jó diz sobre se tentar se justificar?", answer: "Minha própria boca me condenaria", distractors: ["Daria confiança", "Anjos ouviriam"], reference: "Jó 9:20" },
            { question: "Deus destrói o reto e o ímpio igualmente, segundo Jó 9?", answer: "Ele destrói tanto o íntegro como o perverso", distractors: ["Não, só o injusto", "O justo é rico"], reference: "Jó 9:22" },
            { question: "O que Jó deseja entre ele e Deus?", answer: "Um árbitro que pudesse pôr a mão sobre ambos", distractors: ["Um muro alto", "Um rio largo"], reference: "Jó 9:33" },
        ],
        10: [
            { question: "O que Jó pede que Deus não faça no capítulo 10?", answer: "Não me condenes; faze-me saber por que contendes", distractors: ["Não me olhes", "Não tragas sol"], reference: "Jó 10:2" },
            { question: "A que Jó comparou a forma como foi concebido?", answer: "Como queijo me coalhaste", distractors: ["Como pão assado", "Como mel"], reference: "Jó 10:10" },
            { question: "Jó sente que Deus o caça como a qual animal?", answer: "Como a um leão", distractors: ["Como ovelha", "Como águia"], reference: "Jó 10:16" },
            { question: "O que Jó pediu sobre o tempo que lhe resta?", answer: "Deixa-me, para que tome um pouco de alento", distractors: ["Dá-me cem anos", "Faz-me rei"], reference: "Jó 10:20" },
            { question: "Como Jó descreve o lugar pós-morte?", answer: "Terra de trevas e sombra da morte", distractors: ["Paraíso de luz", "Festa eterna"], reference: "Jó 10:21" },
            { question: "Deus se agrada em oprimir, pergunta Jó?", answer: "Tens prazer em oprimir e desprezar o trabalho de tuas mãos?", distractors: ["Deus nunca oprime", "O homem oprime Deus"], reference: "Jó 10:3" },
            { question: "Jó desejava ter morrido no ventre?", answer: "Sim, para que nenhum olho me visse", distractors: ["Não, queria viver", "Queria ser príncipe"], reference: "Jó 10:18" },
        ],
        11: [
            { question: "Quem foi o terceiro amigo a falar com Jó?", answer: "Zofar, o naamatita", distractors: ["Elifas", "Eliú"], reference: "Jó 11:1" },
            { question: "O que Zofar disse sobre a iniquidade de Jó?", answer: "Deus te exige menos do que merece a tua iniquidade", distractors: ["Deus é injusto", "Tu és um santo"], reference: "Jó 11:6" },
            { question: "Pode o homem descobrir as profundezas de Deus?", answer: "Poderás descobrir as profundezas de Deus?", distractors: ["Sim, estudando", "Sim, meditando"], reference: "Jó 11:7" },
            { question: "Como Zofar descreve a sabedoria divina?", answer: "Mais alta que o céu e mais profunda que o abismo", distractors: ["Pequena", "Baixa"], reference: "Jó 11:8" },
            { question: "O que Zofar sugere para Jó ser restaurado?", answer: "Lança para longe de ti a iniquidade", distractors: ["Compra gado", "Ora por reis"], reference: "Jó 11:14" },
            { question: "Como seria a vida de Jó arrependido?", answer: "Tua vida seria mais clara que o meio-dia", distractors: ["Faria sol frio", "Ouro cairia"], reference: "Jó 11:17" },
            { question: "O que acontece com os olhos dos perversos?", answer: "Eles desfalecerão", distractors: ["Brilharão", "Verão anjos"], reference: "Jó 11:20" },
        ],
        12: [
            { question: "Que ironia Jó usou contra os amigos no cap 12?", answer: "Vós sois o povo, e convosco morrerá a sabedoria!", distractors: ["Sois anjos", "Sois humildes"], reference: "Jó 12:2" },
            { question: "Quem também sabe as coisas que os amigos dizem?", answer: "Até os animais e as aves o declaram", distractors: ["Só o rei", "Os anjos"], reference: "Jó 12:7" },
            { question: "O que está na mão de Deus, segundo Jó 12?", answer: "A alma de tudo o que vive", distractors: ["Só o ouro", "O destino de Uz"], reference: "Jó 12:10" },
            { question: "Com quem está a sabedoria e força?", answer: "Com Deus; d'Ele é o conselho e entendimento", distractors: ["Com os idosos", "Com guerreiros"], reference: "Jó 12:13" },
            { question: "O que Deus faz com conselheiros e juízes?", answer: "Leva-os despojados e faz deles tolos", distractors: ["Dá coroas", "Ouve-os"], reference: "Jó 12:17" },
            { question: "Deus aumenta as nações e as faz o quê?", answer: "Aumenta e as faz perecer", distractors: ["As deixa ricas", "As ignora"], reference: "Jó 12:23" },
            { question: "O que Deus faz com o coração dos chefes do povo?", answer: "Tira o coração e os faz andar vagabundos pelo deserto", distractors: ["Dá força a eles", "Dá sabedoria"], reference: "Jó 12:24" },
        ],
        13: [
            { question: "O que Jó chama seus amigos por causa de seus conselhos?", answer: "Forjadores de mentiras e médicos sem valor", distractors: ["Mestres", "Irmãos"], reference: "Jó 13:4" },
            { question: "O que Jó desejava que seus amigos fizessem?", answer: "Oxalá vos calásseis de todo!", distractors: ["Orassem mais", "Trouxessem gado"], reference: "Jó 13:5" },
            { question: "Qual a declaração de fé de Jó no verso 15?", answer: "Ainda que ele me mate, nele esperarei", distractors: ["Eu vencerei só", "Deus nunca fere"], reference: "Jó 13:15" },
            { question: "O que Jó pediu que Deus retirasse de cima dele?", answer: "Retira a tua mão e não me espante o teu terror", distractors: ["Retira o ouro", "Afasta o frio"], reference: "Jó 13:21" },
            { question: "Como Jó descreve sua fragilidade perante Deus?", answer: "Como uma folha arrebatada pelo vento", distractors: ["Rocha inquebrável", "Cedro forte"], reference: "Jó 13:25" },
            { question: "Deus escreve o quê contra Jó?", answer: "Escreves contra mim amarguras", distractors: ["Louvem-me", "Dá-me ouro"], reference: "Jó 13:26" },
            { question: "Jó herda o que no seu sofrimento, segundo ele?", answer: "As iniquidades da minha mocidade", distractors: ["Bens de reis", "Paz de anjos"], reference: "Jó 13:26" },
        ],
        14: [
            { question: "Como Jó descreve o homem nascido de mulher?", answer: "Vive poucos dias e cheio de inquietação", distractors: ["Vive cem anos", "Forte como anjo"], reference: "Jó 14:1" },
            { question: "A que Jó compara o destino do homem em relação à flor?", answer: "Brota como flor e murcha", distractors: ["É eterno", "Cresce como cedro"], reference: "Jó 14:2" },
            { question: "Há esperança para uma árvore cortada?", answer: "Sim, ao cheiro das águas brotará de novo", distractors: ["Não, morre já", "Só se for regada"], reference: "Jó 14:7-9" },
            { question: "E o homem que morre, acorda da sepultura sozinho?", answer: "Não acordará até que não haja mais céus", distractors: ["Sim, logo", "Vive como espírito"], reference: "Jó 14:12" },
            { question: "O que Jó deseja que Deus fizesse com ele na sepultura?", answer: "Que me escondesses até se desviar a tua ira", distractors: ["Que me destruísse", "Que me lavasse"], reference: "Jó 14:13" },
            { question: "Deus vigia os passos de Jó?", answer: "Sim, tu contas os meus passos", distractors: ["Não", "Às vezes"], reference: "Jó 14:16" },
            { question: "O que Deus faz com a esperança do homem mortal?", answer: "Tu destróis a esperança do homem", distractors: ["Aumenta", "Ignora"], reference: "Jó 14:19" },
        ],
        15: [
            { question: "Qual a acusação de Elifas no seu segundo discurso?", answer: "Que Jó aniquilava o temor de Deus e a oração", distractors: ["Roubo", "Falsidade"], reference: "Jó 15:4" },
            { question: "O que Elifas diz que condena Jó no capítulo 15?", answer: "A tua própria boca te condena", distractors: ["Os amigos", "O rei"], reference: "Jó 15:6" },
            { question: "Elifas diz que Jó é o primeiro homem que nasceu?", answer: "Pergunta ironicamente: 'És tu o primeiro homem?'", distractors: ["Sim", "Ele diz ser Adão"], reference: "Jó 15:7" },
            { question: "De onde vem a sabedoria que os amigos dizem ter no cap 15?", answer: "Dos sábios ancestrais e seus pais", distractors: ["Anjos", "Livros gregos"], reference: "Jó 15:18" },
            { question: "O que acontece com o perverso em seus dias, segundo Elifas?", answer: "Passa todos os dias em angústia", distractors: ["Festa constante", "Ignora a Deus"], reference: "Jó 15:20" },
            { question: "O perverso acredita que voltará das trevas?", answer: "Não crê que voltará das trevas", distractors: ["Sim", "Não teme"], reference: "Jó 15:22" },
            { question: "Segundo Elifas, o que o fogo consumirá no cap 15?", answer: "As tendas do suborno", distractors: ["Ovelhas", "O justo"], reference: "Jó 15:34" },
        ],
        16: [
            { question: "Como Jó descreveu a atitude de seus amigos no capítulo 16?", answer: "Consoladores molestos sois todos vós", distractors: ["Amigos reais", "Sábios de Uz"], reference: "Jó 16:2" },
            { question: "O que Jó disse sobre falar ou calar-se no capítulo 16?", answer: "Se falar, a dor não se aquieta; e se me calar?", distractors: ["Falar ajuda", "Calar-se cura"], reference: "Jó 16:6" },
            { question: "O que Jó disse que Deus fez com ele no cap 16?", answer: "Deus me entregou ao perverso e ao ímpio", distractors: ["Deu-me paz", "Limpou-me"], reference: "Jó 16:11" },
            { question: "Como Jó descreveu a sua oração no capítulo 16?", answer: "A minha oração é pura", distractors: ["Culpada", "Vazia"], reference: "Jó 16:17" },
            { question: "Onde está a testemunha de Jó, segundo ele diz no cap 16?", answer: "Lá no céu está a minha testemunha", distractors: ["Em Uz", "Enterrada"], reference: "Jó 16:19" },
            { question: "O que Jó faz diante da zombaria dos amigos no cap 16?", answer: "Os meus olhos derramam lágrimas a Deus", distractors: ["Ri deles", "Grita muito"], reference: "Jó 16:20" },
            { question: "Jó sente-se cansado de tudo no capítulo 16?", answer: "Sim, afirma que Deus o cansa", distractors: ["Não", "Forte"], reference: "Jó 16:7" },
        ],
        17: [
            { question: "Como está o espírito de Jó no capítulo 17?", answer: "O meu espírito está quebrantado", distractors: ["Alegre", "Forte"], reference: "Jó 17:1" },
            { question: "O que Jó disse sobre seus planos no capítulo 17?", answer: "Meus planos e esperanças se aniquilaram", distractors: ["Estão firmes", "Aumentam"], reference: "Jó 17:11" },
            { question: "Quem faria troça de Jó, segundo ele diz no cap 17?", answer: "Os zombadores estão comigo", distractors: ["Só seus filhos", "O rei"], reference: "Jó 17:2" },
            { question: "Para onde iria a esperança de Jó no capítulo 17?", answer: "Às barras da sepultura, ao pó", distractors: ["Ao céu", "Ao mar"], reference: "Jó 17:16" },
            { question: "Deus pôs Jó por qual figura perante o povo no cap 17?", answer: "Pôs-me por provérbio dos povos", distractors: ["Rei amado", "Guerreiro"], reference: "Jó 17:6" },
            { question: "O que houve com os olhos de Jó devido ao pesar?", answer: "Eles escureceram-se", distractors: ["Brilharam", "Curaram"], reference: "Jó 17:7" },
            { question: "O justo deveria persistir no seu caminho, diz Jó?", answer: "Sim, e quem é limpo de mãos crescerá em força", distractors: ["Não", "Apenas rico"], reference: "Jó 17:9" },
        ],
        18: [
            { question: "Qual o tema do segundo discurso de Bildade no capítulo 18?", answer: "O destino terrível e escuro do ímpio", distractors: ["O perdão", "As leis"], reference: "Jó 18:5" },
            { question: "O que acontece com a luz do perverso, segundo Bildade?", answer: "A luz do perverso se apagará", distractors: ["Sempre brilha", "Como sol"], reference: "Jó 18:5" },
            { question: "O que prenderá o ímpio no capítulo 18, diz Bildade?", answer: "Uma armadilha e um laço", distractors: ["Ouro", "Amigos"], reference: "Jó 18:9" },
            { question: "O que espantará o perverso de todos os lados no cap 18?", answer: "Terrores o espantarão", distractors: ["Riquezas", "Anjos"], reference: "Jó 18:11" },
            { question: "Onde o ímpio não terá nome nem descendência no cap 18?", answer: "Não terá posteridade sobre a terra nem nas praças", distractors: ["No Egito", "No mar"], reference: "Jó 18:17-19" },
            { question: "Como Bildade chama as moradas do perverso no cap 18?", answer: "O lugar daquele que não conhece a Deus", distractors: ["Palácio de ouro", "Beira-rio"], reference: "Jó 18:21" },
            { question: "O ímpio terá herança eterna, segundo Bildade?", answer: "Não terá posteridade no seu povo", distractors: ["Sim", "Muitos bens"], reference: "Jó 18:19" },
        ],
        19: [
            { question: "O que Jó perguntou aos amigos sobre o sofrimento deles?", answer: "Até quando amargurareis a minha alma?", distractors: ["Ficareis ricos?", "Matarão o gado?"], reference: "Jó 19:2" },
            { question: "Qual a declaração profética de Jó sobre seu Redentor?", answer: "Eu sei que o meu Redentor vive", distractors: ["Deus me odeia", "Tudo acabou"], reference: "Jó 19:25" },
            { question: "O que acontecerá com Jó mesmo após sua pele ser consumida?", answer: "Ainda em minha carne verei a Deus", distractors: ["Serei pó", "Sumirei"], reference: "Jó 19:26" },
            { question: "Como Jó descreveu o tratamento de seus irmãos e parentes?", answer: "Meus irmãos se retiraram e parentes me ignoraram", distractors: ["Amam mais", "Dão comida"], reference: "Jó 19:13-14" },
            { question: "O que Jó desejava sobre suas palavras no capítulo 19?", answer: "Que fossem escritas e gravadas com ferro para sempre", distractors: ["Esquecidas", "Censuradas"], reference: "Jó 19:23-24" },
            { question: "Como os seus servos agora tratavam Jó no capítulo 19?", answer: "Como a um estrangeiro aos seus olhos", distractors: ["Como rei", "Como pai"], reference: "Jó 19:15" },
            { question: "Qual o apelo desesperado de Jó aos seus amigos?", answer: "Compadecei-vos de mim, amigos meus, a mão de Deus me tocou", distractors: ["Trazei ouro", "Cuidai gado"], reference: "Jó 19:21" },
        ],
        20: [
            { question: "Qual tema do segundo discurso de Zofar no capítulo 20?", answer: "Brevidade da alegria do perverso e seu fim", distractors: ["Perdão", "Riquezas"], reference: "Jó 20:5" },
            { question: "Segundo Zofar, quanto tempo dura o triunfo dos maus?", answer: "O triunfo é breve (momentâneo)", distractors: ["Eterno", "Cem anos"], reference: "Jó 20:5" },
            { question: "O que o perverso vomitará, segundo Zofar no cap 20?", answer: "Vomitará as riquezas que engoliu", distractors: ["Pecados", "Ouro"], reference: "Jó 20:15" },
            { question: "O perverso desfrutará do mel e manteiga, diz Zofar?", answer: "Não verá a doçura dos rios de mel e manteiga", distractors: ["Sim", "Bastante"], reference: "Jó 20:17" },
            { question: "O que Deus enviará sobre o ímpio no capítulo 20?", answer: "Derramará o furor da Sua ira", distractors: ["Bênçãos", "Paz"], reference: "Jó 20:23" },
            { question: "O perverso fugirá das armas, segundo Zofar?", answer: "Fugirá das armas de ferro mas o bronze o atravessará", distractors: ["Sim", "Para Uz"], reference: "Jó 20:24" },
            { question: "O que acontecerá com sua herança e segredos?", answer: "O céu descobrirá a sua iniquidade", distractors: ["Sumirão", "Aparecerão"], reference: "Jó 20:27" },
        ],
        21: [
            { question: "O que Jó observou sobre a vida dos ímpios no capítulo 21?", answer: "Vivem, envelhecem e tornam-se poderosos", distractors: ["Morrem cedo", "São pobres"], reference: "Jó 21:7" },
            { question: "As casas dos ímpios estão em segurança, diz Jó?", answer: "Sim, estão livres de medo e sem a vara de Deus", distractors: ["Não", "Vão cair"], reference: "Jó 21:9" },
            { question: "O que os ímpios dizem a Deus, segundo Jó no cap 21?", answer: "Retira-te de nós, não desejamos teus caminhos", distractors: ["Ouve-nos", "Dá leis"], reference: "Jó 21:14" },
            { question: "Quantas vezes se apaga a lâmpada dos ímpios, pergunta Jó?", answer: "Pergunta ironicamente indicando que raramente sucede", distractors: ["Sempre", "Nunca"], reference: "Jó 21:17" },
            { question: "Como Jó descreve as mortes desiguais de homens no cap 21?", answer: "Uns na força e outros na amargura, mas ambos vão ao pó", distractors: ["Igual", "Apenas ricos"], reference: "Jó 21:23-26" },
            { question: "Jó aceita o consolo dos amigos no capítulo 21?", answer: "Não, só falsidade resta nas respostas", distractors: ["Sim", "Mais ou menos"], reference: "Jó 21:34" },
            { question: "O ímpio é levado para a sepultura com qual honra, diz Jó?", answer: "Diz que é levado para a sepultura e sobre ele vigiam", distractors: ["Nenhuma", "Simples"], reference: "Jó 21:32" },
        ],
        22: [
            { question: "Acaso o homem é útil a Deus, pergunta Elifas no cap 22?", answer: "Pergunta: 'Acaso será útil a Deus?'", distractors: ["Sim", "Sempre"], reference: "Jó 22:2" },
            { question: "De que Elifas acusa Jó injustamente no capítulo 22?", answer: "Ter tomado penhor sem causa e despido os nus", distractors: ["Furtar gado", "Matar rei"], reference: "Jó 22:6" },
            { question: "O que Jó fez ao sedento e faminto, acusa Elifas?", answer: "Não deu água ao cansado nem pão ao faminto", distractors: ["Deu pão", "Ajudou"], reference: "Jó 22:7" },
            { question: "Qual conselho Elifas dá a Jó no verso 21?", answer: "Apega-te a Deus e tem paz", distractors: ["Foge", "Cala-te"], reference: "Jó 22:21" },
            { question: "O que acontece com o ouro de Jó se ele se converter?", answer: "Põe o ouro no pó (deixa o amor ao ouro)", distractors: ["Terá mais", "Ouro cairá"], reference: "Jó 22:24" },
            { question: "A oração de Jó será ouvida se ele se converter, diz Elifas?", answer: "Sim, tu orarás a Ele, e Ele te ouvirá", distractors: ["Não", "Talvez"], reference: "Jó 22:27" },
            { question: "Como as viúvas foram tratadas por Jó, segundo a acusação?", answer: "Enviadas vazias, e os braços dos órfãos quebrados", distractors: ["Ricamente", "Justamente"], reference: "Jó 22:9" },
        ],
        23: [
            { question: "O que Jó deseja fazer em relação a Deus no capítulo 23?", answer: "Saber onde encontrá-lO e chegar ao tribunal", distractors: ["Não ver", "Fugir"], reference: "Jó 23:3" },
            { question: "O que Jó diz sobre não encontrar Deus visivelmente?", answer: "Vou para o oriente e não está lá; ocidente e não percebo", distractors: ["Está aqui", "Mora no mar"], reference: "Jó 23:8" },
            { question: "Qual a confiança de Jó sobre ser provado por Deus?", answer: "Prova-me, e sairei como o ouro", distractors: ["Cinza", "Barro"], reference: "Jó 23:10" },
            { question: "Jó guardou as palavras da boca de Deus no cap 23?", answer: "Escondi as palavras mais que meu alimento", distractors: ["Esqueci", "Ignorei"], reference: "Jó 23:12" },
            { question: "Com quem Deus se importa em mudar Seu propósito, sente Jó?", answer: "Deus é um: quem o pode desviar? Ele faz o que deseja", distractors: ["Ouvindo homens", "Ouvindo reis"], reference: "Jó 23:13" },
            { question: "Como Jó se sente perante a face de Deus no cap 23?", answer: "Aterrado e temeroso", distractors: ["Alegre", "Poderoso"], reference: "Jó 23:15" },
            { question: "Jó admite ter se desviado dos passos de Deus?", answer: "Não, afirma: 'os meus pés se mantiveram nos seus passos'", distractors: ["Sim", "Só um pouco"], reference: "Jó 23:11" },
        ],
        24: [
            { question: "Quais injustiças Jó cita no cap 24 que parecem impunes?", answer: "Removem limites, roubam rebanhos e oprimem órfãos", distractors: ["Leis severas", "Impostos"], reference: "Jó 24:2-3" },
            { question: "O que os pobres fazem no deserto, segundo Jó no cap 24?", answer: "Buscam alimento como jumentos selvagens", distractors: ["Dançam", "Riem"], reference: "Jó 24:5" },
            { question: "Como os necessitados passam a noite no capítulo 24?", answer: "Nus, sem roupa para se cobrir no frio", distractors: ["Em tendas", "Palácios"], reference: "Jó 24:7" },
            { question: "Deus ouve o grito dos feridos, sente Jó?", answer: "Diz que clama a alma dos feridos mas Deus não responde", distractors: ["Sim, logo", "Não há feridos"], reference: "Jó 24:12" },
            { question: "Quem são os 'rebeldes contra a luz' no capítulo 24?", answer: "Não conhecem os caminhos de Deus nem neles permanecem", distractors: ["Fugitivos", "Idólatras"], reference: "Jó 24:13" },
            { question: "O que o assassino faz ao cair da noite no cap 24?", answer: "Ao cair da noite, torna-se como ladrão", distractors: ["Dorme", "Reza"], reference: "Jó 24:14" },
            { question: "O perverso faz o que com a vinha da viúva no cap 24?", answer: "Saqueia a vinha do necessitado", distractors: ["Dá vinho", "Planta mais"], reference: "Jó 24:21" },
        ],
        25: [
            { question: "Quem deu o curto terceiro discurso no capítulo 25?", answer: "Bildade, o suíta", distractors: ["Elifas", "Zofar"], reference: "Jó 25:1" },
            { question: "O que Bildade diz sobre o domínio e pavor de Deus?", answer: "O domínio e o pavor estão com Deus", distractors: ["Não tem", "São do rei"], reference: "Jó 25:2" },
            { question: "Pode o homem ser puro perante Deus, pergunta Bildade?", answer: "Como seria puro o que nasce de mulher?", distractors: ["Sim sendo justo", "Sim orando"], reference: "Jó 25:4" },
            { question: "A que Bildade comparou o homem no verso 6 do cap 25?", answer: "Ao verme e ao bicho", distractors: ["Anjo", "Rei"], reference: "Jó 25:6" },
            { question: "Como é o exército de Deus, segundo Bildade no cap 25?", answer: "Acaso têm número os Seus exércitos? (Incontáveis)", distractors: ["Pequeno", "Dez anjos"], reference: "Jó 25:3" },
            { question: "Até a lua e as estrelas são impuras perante Deus?", answer: "Sim, a lua não tem brilho e estrelas não são limpas perante Ele", distractors: ["Não", "Sagradas"], reference: "Jó 25:5" },
            { question: "Qual a visão de Bildade sobre a justiça humana perante Deus?", answer: "O homem não pode ser justo para com Deus", distractors: ["Pode sim", "Só os ricos"], reference: "Jó 25:4" },
        ],
        26: [
            { question: "Como Jó ironiza o conselho de Bildade no capítulo 26?", answer: "Como ajudaste o que não tem força!", distractors: ["És o maior", "Obrigado"], reference: "Jó 26:2" },
            { question: "Onde Deus estende o norte e suspende a terra?", answer: "Sobre o vazio e sobre o nada", distractors: ["Mar e rocha", "Água e fogo"], reference: "Jó 26:7" },
            { question: "O que Deus faz com as águas nas nuvens no cap 26?", answer: "Encerra as águas nas nuvens e elas não se rompem", distractors: ["Fura-as", "Bebe delas"], reference: "Jó 26:8" },
            { question: "O que acontece com as colunas do céu perante Deus?", answer: "Tremem e se espantam com a Sua repreensão", distractors: ["Firmes", "Quebram"], reference: "Jó 26:11" },
            { question: "Pode o homem entender o trovão do poder de Deus?", answer: "Não, quem o entenderia?", distractors: ["Sim sábios", "Sim reis"], reference: "Jó 26:14" },
            { question: "O que Jó chama de 'apenas as orlas dos caminhos'?", answer: "O que vemos e ouvimos d'Ele", distractors: ["As leis", "As ovelhas"], reference: "Jó 26:14" },
            { question: "Pelo Seu Espírito, Deus fez o que ao céu no cap 26?", answer: "Pelo Seu Espírito ornamentou os céus", distractors: ["Escondeu", "Limpou"], reference: "Jó 26:13" },
        ],
        27: [
            { question: "Jó jurou afastar a sua integridade no capítulo 27?", answer: "Até que eu morra nunca afastarei a minha integridade", distractors: ["Sim confesso", "Não sei"], reference: "Jó 27:5" },
            { question: "O que Jó jurou sobre seus lábios no capítulo 27?", answer: "Não falarão iniquidade nem engano", distractors: ["Gritarão", "Matarão"], reference: "Jó 27:4" },
            { question: "Qual o destino do filho do perverso, sugere Jó no cap 27?", answer: "Será para a espada e descendentes não terão pão", distractors: ["Reis", "Ricos"], reference: "Jó 27:14" },
            { question: "A herança do perverso é dada por quem?", answer: "Do Todo-Poderoso a recebem por herança", distractors: ["Do diabo", "Do rei de Uz"], reference: "Jó 27:13" },
            { question: "A casa do ímpio é comparada a quê no cap 27?", answer: "À casa da traça e cabana do vigia", distractors: ["Castelo", "Montanha"], reference: "Jó 27:18" },
            { question: "O que o ímpio fará diante do furor de Deus no cap 27?", answer: "Quererá fugir da Sua mão mas Deus o atingirá", distractors: ["Rirá", "Orará"], reference: "Jó 27:22" },
            { question: "O perverso se alegra em invocar Deus sempre?", answer: "Não, acaso invocará a Deus em todo tempo?", distractors: ["Sim sempre", "Só rindo"], reference: "Jó 27:10" },
        ],
        28: [
            { question: "O que o homem sabe extrair das minas no capítulo 28?", answer: "Prata, ouro, ferro e bronze", distractors: ["Só água", "Fogo"], reference: "Jó 28:1-2" },
            { question: "Pode o homem saber o valor e lugar da sabedoria?", answer: "Não, o homem não conhece o seu valor", distractors: ["Sim valor", "Sim lugar"], reference: "Jó 28:13" },
            { question: "O abismo e o mar possuem a sabedoria no cap 28?", answer: "Dizem: 'Não está em mim' e 'Não está comigo'", distractors: ["Sim possuem", "Só o mar"], reference: "Jó 28:14" },
            { question: "A sabedoria pode ser trocada por ouro de Ofir?", answer: "Nem o ouro de Ofir se pode comparar com ela", distractors: ["Sim troca", "Sim por gado"], reference: "Jó 28:16" },
            { question: "Quem conhece o caminho e lugar da sabedoria?", answer: "Deus entende o seu caminho", distractors: ["Anjos", "Rei Egito"], reference: "Jó 28:23" },
            { question: "Qual a definição de sabedoria em Jó 28:28?", answer: "O temor do Senhor é a sabedoria, e apartar do mal é entendimento", distractors: ["Ler astros", "Ter gado"], reference: "Jó 28:28" },
            { question: "Onde se procura a sabedoria que não é achada na terra?", answer: "Está escondida aos olhos de todo vivente", distractors: ["Na praça", "No deserto"], reference: "Jó 28:21" },
        ],
        29: [
            { question: "Como Jó descreveu seus dias passados no capítulo 29?", answer: "Quando a lâmpada de Deus brilhava sobre minha cabeça", distractors: ["Sempre tristes", "Como escravo"], reference: "Jó 29:3" },
            { question: "Como os jovens e idosos reagiam a Jó no passado?", answer: "Jovens se escondiam e idosos se levantavam", distractors: ["Riam dele", "Ignoravam"], reference: "Jó 29:8" },
            { question: "O que Jó fazia pelo pobre e órfão no capítulo 29?", answer: "Livrava o pobre que clamava e o órfão", distractors: ["Cobrava impostos", "Dava ordens"], reference: "Jó 29:12" },
            { question: "Jó era 'olhos' para quem no capítulo 29?", answer: "Eu era os olhos do cego e pés do coxo", distractors: ["Do rei", "Dos amigos"], reference: "Jó 29:15" },
            { question: "Como era a justiça de Jó, segundo ele diz no cap 29?", answer: "Vestia-me da justiça como de um manto", distractors: ["Era secreta", "Era fraca"], reference: "Jó 29:14" },
            { question: "Como as pessoas ouviam o conselho de Jó no passado?", answer: "Esperavam por mim como pela chuva", distractors: ["Dormiam", "Zombavam"], reference: "Jó 29:21-23" },
            { question: "Jó sentava-se como qual autoridade no capítulo 29?", answer: "Sentava-me como chefe e rei entre as tropas", distractors: ["Como escravo", "Como guia"], reference: "Jó 29:25" },
        ],
        30: [
            { question: "Como as pessoas mais jovens tratam Jó no capítulo 30?", answer: "Agora zombam de mim", distractors: ["Ainda o honram", "Dão-lhe gado"], reference: "Jó 30:1" },
            { question: "Quem são esses que agora zombam de Jó?", answer: "Filhos de doidos, gente sem nome", distractors: ["Príncipes de Uz", "Anjos de Deus"], reference: "Jó 30:8" },
            { question: "Jó tornou-se o quê para esses jovens no cap 30?", answer: "Tornei-me a sua canção e o seu provérbio", distractors: ["Seu mestre", "Seu herói"], reference: "Jó 30:9" },
            { question: "O que Deus fez com a vida de Jó, segundo ele clama no cap 30?", answer: "Lançou-me no lamaçal", distractors: ["Deu-me luz", "Fez-me voar"], reference: "Jó 30:19" },
            { question: "Jó clama a Deus e o que acontece no cap 30?", answer: "Clamo a ti e não me respondes", distractors: ["Deus responde logo", "Cura-me"], reference: "Jó 30:20" },
            { question: "Como Jó descreve seu corpo no capítulo 30?", answer: "Minha pele se enegreceu e ossos queimam", distractors: ["Forte e belo", "Branco como leite"], reference: "Jó 30:30" },
            { question: "A que Jó comparou o seu lamento no capítulo 30?", answer: "Tornei-me irmão dos chacais e companheiro de avestruzes", distractors: ["Ao riso", "Ao trovão"], reference: "Jó 30:29" },
        ],
        31: [
            { question: "Qual o pacto que Jó fez com seus olhos no cap 31?", answer: "Fiz aliança de não olhar para uma virgem", distractors: ["De não dormir", "De não chorar"], reference: "Jó 31:1" },
            { question: "Jó admite ter andado com a falsidade no cap 31?", answer: "Não, clama para ser pesado em balança fiel", distractors: ["Sim, muito", "Só por medo"], reference: "Jó 31:5-6" },
            { question: "O que Jó diz sobre ter negado o que os pobres desejavam?", answer: "Se neguei, que meu braço caia da espádua", distractors: ["Não me importo", "Fiz por justiça"], reference: "Jó 31:16,22" },
            { question: "Jó pôs no ouro a sua esperança no capítulo 31?", answer: "Não, nunca disse ao ouro: 'Tu és minha confiança'", distractors: ["Sim sempre", "Só no início"], reference: "Jó 31:24" },
            { question: "Jó se alegrou com a desgraça de quem o odiava?", answer: "Não me alegrei com a destruição do que me odiava", distractors: ["Sim muito", "Fiz festa"], reference: "Jó 31:29" },
            { question: "Jó encobriu suas transgressões como Adão?", answer: "Não, nunca ocultei minha iniquidade no seio", distractors: ["Sim escondi", "Deus permitiu"], reference: "Jó 31:33" },
            { question: "O que Jó deseja no final do capítulo 31?", answer: "Que o Todo-Poderoso me responda!", distractors: ["Mais ouro", "Ver seus filhos"], reference: "Jó 31:35" },
        ],
        32: [
            { question: "Por que os três amigos pararam de responder a Jó?", answer: "Porque ele era justo aos seus próprios olhos", distractors: ["Estavam com sono", "Foram embora"], reference: "Jó 32:1" },
            { question: "Quem ficou furioso com Jó e com os amigos no cap 32?", answer: "Eliú, filho de Baraquel", distractors: ["O rei Assuero", "Moisés"], reference: "Jó 32:2" },
            { question: "Por que Eliú esperou para falar no capítulo 32?", answer: "Porque os outros eram mais velhos que ele", distractors: ["Estava mudo", "Tinha medo"], reference: "Jó 32:4" },
            { question: "Onde está a inteligência no homem, segundo Eliú?", answer: "No espírito do homem e o sopro do Todo-Poderoso", distractors: ["No coração", "No sangue"], reference: "Jó 32:8" },
            { question: "Os velhos são sempre sábios, segundo Eliú no cap 32?", answer: "Os de muita idade nem sempre são sábios", distractors: ["Sim sempre", "Só os ricos"], reference: "Jó 32:9" },
            { question: "Eliú achou resposta nos três amigos para Jó?", answer: "Não, nenhum de vós convenceu a Jó", distractors: ["Sim todos", "Só Elifas"], reference: "Jó 32:12" },
            { question: "Como Eliú se sentia por não falar no cap 32?", answer: "Como vinho que não tem respiradouro e quer romper", distractors: ["Calmo", "Triste"], reference: "Jó 32:19" },
        ],
        33: [
            { question: "De que Eliú foi feito, segundo ele disse a Jó?", answer: "Também eu fui formado do barro", distractors: ["De fogo", "De luz"], reference: "Jó 33:6" },
            { question: "Eliú pretende aterrorizar Jó com seu pavor?", answer: "Não, o meu pavor não te espantará", distractors: ["Sim muito", "Só um pouco"], reference: "Jó 33:7" },
            { question: "De que maneira Deus fala ao homem no capítulo 33?", answer: "Pelo sonho ou visão noturna", distractors: ["Pelo trovão apenas", "Só por reis"], reference: "Jó 33:14-15" },
            { question: "O que Deus deseja afastar do homem ao falar-lhe?", answer: "Afastar o homem do seu desígnio e o orgulho", distractors: ["Da riqueza", "Da família"], reference: "Jó 33:17" },
            { question: "Quem livra a alma do homem de ir para a cova no cap 33?", answer: "Um intérprete ou anjo entre mil", distractors: ["O rei", "O próprio Jó"], reference: "Jó 33:23-24" },
            { question: "O que acontece com a carne de quem Deus perdoa no cap 33?", answer: "Sua carne se tornará mais fresca que a de um menino", distractors: ["Fica velha", "Some"], reference: "Jó 33:25" },
            { question: "Deus faz essas coisas quantas vezes ao homem?", answer: "Duas ou três vezes", distractors: ["Mil vezes", "Sempre"], reference: "Jó 33:29" },
        ],
        34: [
            { question: "Eliú diz que Deus pratica a injustiça no cap 34?", answer: "Longe de Deus o praticar a iniquidade", distractors: ["Sim às vezes", "Só com Jó"], reference: "Jó 34:10" },
            { question: "O que aconteceria se Deus retirasse Seu Espírito da terra?", answer: "Toda carne juntamente expiraria", distractors: ["Faria sol", "Haveria paz"], reference: "Jó 34:14-15" },
            { question: "Deus faz acepção de pessoas ou príncipes no cap 34?", answer: "Não faz acepção de príncipes nem prefere o rico", distractors: ["Sim sempre", "Só em Uz"], reference: "Jó 34:19" },
            { question: "Deus vê os caminhos do homem no capítulo 34?", answer: "Seus olhos estão sobre os caminhos de cada um", distractors: ["Não vê", "Vê de longe"], reference: "Jó 34:21" },
            { question: "Há trevas onde se escondam os que praticam o mal?", answer: "Não há trevas nem sombra onde se escondam", distractors: ["Sim muitas", "No mar"], reference: "Jó 34:22" },
            { question: "Eliú diz que Jó fala com conhecimento no cap 34?", answer: "Jó falou sem conhecimento e sem prudência", distractors: ["Sim muito", "É um gênio"], reference: "Jó 34:35" },
            { question: "Segundo Eliú, por que Jó deve ser provado até o fim?", answer: "Porque respondeu como os homens iníquos", distractors: ["Para ser rico", "Deus o odeia"], reference: "Jó 34:36" },
        ],
        35: [
            { question: "A justiça do homem traz algum lucro a Deus, pergunta Eliú?", answer: "Se fores justo, que lhe dás Tu?", distractors: ["Sim muito", "Metade do céu"], reference: "Jó 35:7" },
            { question: "A quem atinge a maldade do homem, segundo Eliú?", answer: "A um homem como tu", distractors: ["A Deus", "Aos anjos"], reference: "Jó 35:8" },
            { question: "Por que muitos clamam e não são ouvidos, diz Eliú no cap 35?", answer: "Por causa da soberba dos maus", distractors: ["Deus é surdo", "Falam baixo"], reference: "Jó 35:12" },
            { question: "Deus atende a vaidade, pergunta Eliú no capítulo 35?", answer: "Deus não ouvirá a vaidade", distractors: ["Sim sempre", "Só no templo"], reference: "Jó 35:13" },
            { question: "Quem é Deus, segundo Eliú no verso 10?", answer: "Deus meu Fazedor, que dá canções de noite", distractors: ["Rei de Uz", "Juiz severo"], reference: "Jó 35:10" },
            { question: "Deus nos ensina mais que a quais seres no cap 35?", answer: "Mais que aos animais da terra e aves do céu", distractors: ["Aos peixes", "Aos vermes"], reference: "Jó 35:11" },
            { question: "Jó abre a boca para dizer o quê, segundo Eliú no cap 35?", answer: "Abre a boca para dizer vaidades", distractors: ["Verdades", "Leis"], reference: "Jó 35:16" },
        ],
        36: [
            { question: "O que Eliú diz que Deus não despreza no cap 36?", answer: "Deus é grande mas não despreza a ninguém", distractors: ["Riqueza", "Força"], reference: "Jó 36:5" },
            { question: "Deus conserva a vida do ímpio, segundo Eliú?", answer: "Não conserva a vida do ímpio", distractors: ["Sim sempre", "Só em Uz"], reference: "Jó 36:6" },
            { question: "O que acontece se os homens forem presos em grilhões?", answer: "Deus lhes faz saber a sua obra e transgressões", distractors: ["Eles morrem", "Eles fogem"], reference: "Jó 36:8-9" },
            { question: "Deus abre o ouvido para qual propósito no cap 36?", answer: "Abre o ouvido deles para a disciplina", distractors: ["Para música", "Para fofoca"], reference: "Jó 36:10" },
            { question: "Que perigo corre quem se recusa a ouvir a Deus?", answer: "Perecerão à espada e morrerão sem conhecimento", distractors: ["Ficarão pobres", "Terão sono"], reference: "Jó 36:12" },
            { question: "Eliú diz que Jó deve se desviar do quê no cap 36?", answer: "Guarda-te, não te dês à iniquidade", distractors: ["Do sol", "Das águas"], reference: "Jó 36:21" },
            { question: "Pode o homem contar as nuvens ou o trovão?", answer: "Quem pode entender o estender das nuvens?", distractors: ["Sim todos", "Só sábios"], reference: "Jó 36:29" },
        ],
        37: [
            { question: "A que Eliú compara a voz de Deus no capítulo 37?", answer: "Ao trovão e ao estrondo da Sua voz", distractors: ["Ao sussurro", "Ao silêncio"], reference: "Jó 37:2" },
            { question: "Deus faz coisas grandes que não podemos o quê?", answer: "Não podemos compreender", distractors: ["Ver", "Ouvir"], reference: "Jó 37:5" },
            { question: "De que direção vem o frio, segundo Eliú no cap 37?", answer: "Dos ventos que limpam o céu (norte)", distractors: ["Do sul", "Do mar"], reference: "Jó 37:9" },
            { question: "Como se faz o gelo, segundo o capítulo 37?", answer: "Pelo sopro de Deus se dá a geada", distractors: ["Pela chuva", "Pelo sol"], reference: "Jó 37:10" },
            { question: "Eliú pergunta a Jó se ele sabe como Deus faz o quê?", answer: "Como equilibra as nuvens", distractors: ["Como faz pão", "Como cria gado"], reference: "Jó 37:16" },
            { question: "Como Jó deve se portar perante a majestade de Deus?", answer: "Deveria calar-se e considerar as maravilhas", distractors: ["Gritar alto", "Fugir"], reference: "Jó 37:14" },
            { question: "De onde vem a majestade de ouro, segundo o cap 37?", answer: "Do norte vem o áureo resplendor", distractors: ["Do Egito", "Do templo"], reference: "Jó 37:22" },
        ],
        38: [
            { question: "De onde o Senhor respondeu a Jó no capítulo 38?", answer: "Do meio de um redemoinho", distractors: ["Do céu azul", "De um arbusto"], reference: "Jó 38:1" },
            { question: "Qual a primeira pergunta de Deus a Jó?", answer: "Onde estavas tu quando eu fundava a terra?", distractors: ["Por que pecaste?", "Quem te feriu?"], reference: "Jó 38:4" },
            { question: "Quem cantou alegremente na fundação do mundo?", answer: "As estrelas da alva e os filhos de Deus", distractors: ["Os anjos de fogo", "Adão e Eva"], reference: "Jó 38:7" },
            { question: "Quem pôs limites ao mar dizendo 'até aqui virás'?", answer: "O próprio Deus", distractors: ["Jó", "Leviatã"], reference: "Jó 38:10-11" },
            { question: "Jó deu ordens à alva ou à manhã?", answer: "Deus pergunta: 'Deste tu ordens à manhã?'", distractors: ["Sim", "Às vezes"], reference: "Jó 38:12" },
            { question: "Jó entrou nos tesouros da neve e da saraiva?", answer: "Deus pergunta: 'Entraste nos tesouros da neve?'", distractors: ["Sim todo dia", "Nunca"], reference: "Jó 38:22" },
            { question: "Quem preparou o caminho para o relâmpago e o trovão?", answer: "Deus preparou", distractors: ["A natureza", "Os gigantes"], reference: "Jó 38:25" },
        ],
        39: [
            { question: "Deus pergunta se Jó sabe o tempo de qual animal parir?", answer: "Das cabras monteses e das cervas", distractors: ["Dos leões", "Das serpentes"], reference: "Jó 39:1" },
            { question: "Qual animal Deus soltou e deu liberdade no cap 39?", answer: "O jumento selvagem", distractors: ["O camelo", "O cavalo"], reference: "Jó 39:5" },
            { question: "O unicórnio (boi selvagem) quererá servir a Jó?", answer: "Quererá o boi selvagem servir-te?", distractors: ["Sim", "Só com comida"], reference: "Jó 39:9" },
            { question: "O que o avestruz faz com seus ovos na terra?", answer: "Abandona-os no pó e esquece que pés os podem pisar", distractors: ["Guarda-os", "Leva-os"], reference: "Jó 39:14-15" },
            { question: "Quem deu força ao cavalo e revestiu seu pescoço?", answer: "O próprio Deus", distractors: ["O homem", "A guerra"], reference: "Jó 39:19" },
            { question: "O cavalo teme o som da trombeta ou da espada?", answer: "Não teme, morde o freio e corre ao encontro das armas", distractors: ["Foge", "Trema"], reference: "Jó 39:21-25" },
            { question: "É pela inteligência de Jó que voa o gavião?", answer: "Pergunta: 'Voa o gavião pela tua inteligência?'", distractors: ["Sim", "Só em Uz"], reference: "Jó 39:26" },
        ],
        40: [
            { question: "O que Jó respondeu a Deus no início do capítulo 40?", answer: "Eis que sou vil; que te responderia eu? Ponho a mão na boca", distractors: ["Tenho razão", "Sou justo"], reference: "Jó 40:4" },
            { question: "Deus pergunta se Jó pode anular o quê no cap 40?", answer: "Acaso anularás tu o meu juízo?", distractors: ["O sol", "A chuva"], reference: "Jó 38:8 - context ref 40:8" },
            { question: "Qual animal 'comedor de erva' Deus cita no cap 40?", answer: "O Beemote", distractors: ["O leviatã", "O unicórnio"], reference: "Jó 40:15" },
            { question: "A força do Beemote está em qual parte do corpo?", answer: "Nos seus lombos e nos músculos do ventre", distractors: ["Na cabeça", "Nas patas"], reference: "Jó 40:16" },
            { question: "A cauda do Beemote é comparada a qual árvore?", answer: "Ao cedro", distractors: ["À palmeira", "Ao carvalho"], reference: "Jó 40:17" },
            { question: "O Beemote é a obra prima de quem?", answer: "É obra prima dos caminhos de Deus", distractors: ["Da natureza", "Dos homens"], reference: "Jó 40:19" },
            { question: "O Beemote teme se o rio Jordão transbordar?", answer: "Não, ele está confiante ainda que o Jordão se levante", distractors: ["Sim foge", "Esconde-se"], reference: "Jó 40:23" },
        ],
        41: [
            { question: "Pode Jó pescar qual animal com anzol no cap 41?", answer: "O Leviatã", distractors: ["A baleia", "O tubarão"], reference: "Jó 41:1" },
            { question: "Alguém é tão ousado que o Leviatã se atreva a despertá-lo?", answer: "Ninguém é tão ousado que se atreva a despertá-lo", distractors: ["Sim Jó", "Sim Eliú"], reference: "Jó 41:10" },
            { question: "Como são as escamas do Leviatã no capítulo 41?", answer: "Fortes como escudos, cerradas como selo", distractors: ["Moles", "De ouro"], reference: "Jó 41:15" },
            { question: "O que sai da boca do Leviatã, segundo o cap 41?", answer: "Tochas de fogo e faíscas", distractors: ["Água fria", "Veneno"], reference: "Jó 41:19" },
            { question: "O Leviatã teme a espada, a lança ou o dardo?", answer: "Rri-se do brandir da lança e dardo é para ele como palha", distractors: ["Sim morre", "Foge deles"], reference: "Jó 41:26-29" },
            { question: "O Leviatã faz o mar ferver como o quê?", answer: "Como uma panela", distractors: ["Como sol", "Como gelo"], reference: "Jó 41:31" },
            { question: "O Leviatã é rei sobre quem no cap 41?", answer: "É rei sobre todos os filhos da soberba", distractors: ["Sobre os peixes", "Sobre Uz"], reference: "Jó 41:34" },
        ],
        42: [
            { question: "O que Jó reconheceu no início do capítulo 42?", answer: "Bem sei que tudo podes e nenhum plano pode ser impedido", distractors: ["Sou o melhor", "Fui injustiçado"], reference: "Jó 42:2" },
            { question: "O que Jó disse sobre o que falou sem entender?", answer: "Falei de coisas maravilhosas demais para mim", distractors: ["Falei verdades", "Deus errou"], reference: "Jó 42:3" },
            { question: "Como Jó conhecia a Deus antes e como conhece agora?", answer: "Antes de ouvir falar, mas agora meus olhos te vêem", distractors: ["Sempre soube", "Não o vejo"], reference: "Jó 42:5" },
            { question: "Como Deus reagiu aos três amigos de Jó no final?", answer: "Minha ira se acendeu contra vós pois não falastes o que era reto", distractors: ["Ficou alegre", "Premiou-os"], reference: "Jó 42:7" },
            { question: "O que Jó teve que fazer pelos seus amigos no cap 42?", answer: "Orar por eles para que Deus não os tratasse conforme a loucura", distractors: ["Matá-los", "Dar-lhes ouro"], reference: "Jó 42:8" },
            { question: "Quando Deus mudou a sorte de Jó?", answer: "Quando ele orou pelos seus amigos", distractors: ["Quando chorou", "Quando calou"], reference: "Jó 42:10" },
            { question: "Quanto Deus deu a Jó em relação ao que tinha antes?", answer: "O dobro de tudo o que dantes possuía", distractors: ["A mesma coisa", "Metade"], reference: "Jó 42:10" },
        ],
    },
};
