import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_2REIS: Record<string, Record<number, BankQuestion[]>> = {
  "2reis": {
    1: [
      { question: "Por que o rei Acazias enviou mensageiros a Baal-Zebube?", answer: "Para perguntar se ele se recuperaria de sua queda", distractors: ["Para pedir vitória em batalha", "Para saber quem seria seu sucessor"], reference: "2 Reis 1:2" },
      { question: "Quem interceptou os mensageiros de Acazias e os mandou de volta?", answer: "Elias", distractors: ["Eliseu", "Um anjo do Senhor"], reference: "2 Reis 1:3" },
      { question: "O que Elias disse que aconteceria a Acazias?", answer: "Que não se levantaria da cama e morreria", distractors: ["Que seria curado se se arrependesse", "Que seu reino seria dividido"], reference: "2 Reis 1:4" },
      { question: "Quantos capitães com cinquenta homens o rei enviou a Elias?", answer: "Três capitães", distractors: ["Dois capitães", "Cinco capitães"], reference: "2 Reis 1:9-13" },
      { question: "O que aconteceu com os dois primeiros grupos enviados contra Elias?", answer: "Fogo desceu do céu e os consumiu", distractors: ["Elias os fez adormecer miraculosamente", "Foram afugentados por um anjo"], reference: "2 Reis 1:10-12" },
      { question: "O que o terceiro capitão fez diferente dos outros dois?", answer: "Ajoelhou-se diante de Elias e suplicou misericórdia", distractors: ["Trouxe presentes ao profeta", "Disse que não queria prender Elias"], reference: "2 Reis 1:13" },
    ],
    2: [
      { question: "O que Elias e Eliseu atravessaram a pé quando as águas se dividiram?", answer: "O rio Jordão", distractors: ["O mar Vermelho", "O rio Arnon"], reference: "2 Reis 2:8" },
      { question: "O que Eliseu pediu a Elias antes de ser arrebatado?", answer: "Uma porção dupla do espírito de Elias", distractors: ["O manto de Elias", "A capacidade de fazer milagres maiores"], reference: "2 Reis 2:9" },
      { question: "Como Elias foi arrebatado aos céus?", answer: "Num redemoinho, com carros e cavalos de fogo", distractors: ["Numa nuvem de luz", "Levado por anjos diante de Eliseu"], reference: "2 Reis 2:11" },
      { question: "O que Eliseu pegou quando Elias foi arrebatado?", answer: "O manto de Elias que caíra", distractors: ["A cajado de Elias", "O chapéu de Elias"], reference: "2 Reis 2:13" },
      { question: "Como Eliseu purificou as águas ruins de Jericó?", answer: "Lançando sal numa vasilha nova nas águas", distractors: ["Orando sobre as águas por três dias", "Mergulhando sete vezes na fonte"], reference: "2 Reis 2:19-22" },
      { question: "O que aconteceu com os rapazes que zombaram de Eliseu chamando-o de 'cabeça calva'?", answer: "Duas ursas saíram do bosque e despedaçaram quarenta e dois deles", distractors: ["Foram fulminados por raio", "Adoeceram e morreram em sete dias"], reference: "2 Reis 2:23-24" },
    ],
    3: [
      { question: "Quem foi o rei de Israel que consultou Eliseu durante a campanha contra Moabe?", answer: "Jorão, filho de Acabe", distractors: ["Jeú", "Jeoacaz"], reference: "2 Reis 3:1-12" },
      { question: "Por que os reis de Israel, Judá e Edom buscaram Eliseu?", answer: "Porque não havia água para o exército e seus animais", distractors: ["Para saber se venceriam a batalha", "Porque um profeta falso havia enganado Jorão"], reference: "2 Reis 3:9-12" },
      { question: "O que Eliseu pediu antes de profetizar para os reis?", answer: "Um músico para tocar", distractors: ["Que os reis jejuassem três dias", "Que o rei se humilhasse diante do Senhor"], reference: "2 Reis 3:15" },
      { question: "O que Eliseu profetizou que aconteceria com os vales?", answer: "Que seriam cheios de água sem vento nem chuva", distractors: ["Que floresceriam com mantimentos", "Que serviriam de refúgio contra Moabe"], reference: "2 Reis 3:16-17" },
      { question: "O que os moabitas pensaram quando viram a água vermelha ao amanhecer?", answer: "Que os reis se tinham matado uns aos outros", distractors: ["Que Israel havia se rendido", "Que era um sinal dos seus deuses"], reference: "2 Reis 3:22-23" },
      { question: "O que o rei de Moabe fez em desespero durante a batalha?", answer: "Sacrificou seu filho primogênito como holocausto sobre o muro", distractors: ["Pediu paz e se rendeu", "Fugiu para o deserto com sua família"], reference: "2 Reis 3:27" },
    ],
    4: [
      { question: "O que Eliseu multiplicou para salvar a viúva da dívida com os credores?", answer: "O azeite de uma vasilha que encheu todos os recipientes da casa", distractors: ["O pão de um cesto", "A farinha de uma vasilha"], reference: "2 Reis 4:1-7" },
      { question: "O que a sunamita construiu para Eliseu?", answer: "Um quarto no terraço com cama, mesa, cadeira e lamparina", distractors: ["Uma tenda no jardim", "Uma casa pequena ao lado da sua"], reference: "2 Reis 4:10" },
      { question: "O que Eliseu prometeu à sunamita como recompensa?", answer: "Que ela teria um filho", distractors: ["Que seu marido seria curado", "Que suas terras seriam abençoadas"], reference: "2 Reis 4:16" },
      { question: "O que aconteceu ao filho da sunamita?", answer: "Morreu após sentir dores de cabeça no campo", distractors: ["Caiu de uma árvore e quebrou o pescoço", "Afogou-se no rio"], reference: "2 Reis 4:18-20" },
      { question: "Como Eliseu ressuscitou o filho da sunamita?", answer: "Deitou-se sobre o menino, colocando sua boca, olhos e mãos sobre os dele", distractors: ["Orou sobre ele por sete horas e lançou sal", "Tocou-o com o manto de Elias"], reference: "2 Reis 4:32-35" },
      { question: "O que aconteceu com o ensopado envenenado que Eliseu purificou?", answer: "Jogou farinha na panela e o ensopado ficou bom", distractors: ["Mandou jogar fora e preparar outro", "Orou sobre ele e o veneno desapareceu"], reference: "2 Reis 4:40-41" },
    ],
    5: [
      { question: "Quem era Naamã?", answer: "O comandante do exército do rei da Síria, leproso", distractors: ["O rei de Samaria que adoeceu", "Um sacerdote israelita exilado na Síria"], reference: "2 Reis 5:1" },
      { question: "Quem indicou a Naamã que fosse até o profeta em Israel?", answer: "Uma menina israelita que servia a sua mulher", distractors: ["O próprio rei da Síria", "Um comerciante que havia visitado Israel"], reference: "2 Reis 5:2-3" },
      { question: "O que Eliseu mandou Naamã fazer para ser curado?", answer: "Lavar-se sete vezes no rio Jordão", distractors: ["Jejuar por sete dias e orar", "Oferecer um sacrifício no templo de Jerusalém"], reference: "2 Reis 5:10" },
      { question: "Por que Naamã ficou irritado com as instruções de Eliseu?", answer: "Porque esperava que Eliseu saísse e o curasse pessoalmente", distractors: ["Porque o Jordão era um rio sujo", "Porque achava que sete vezes era humilhante"], reference: "2 Reis 5:11-12" },
      { question: "O que Naamã disse após ser curado?", answer: "Que não havia Deus em toda a terra senão em Israel", distractors: ["Que Eliseu era o maior profeta do mundo", "Que voltaria para ser discípulo de Eliseu"], reference: "2 Reis 5:15" },
      { question: "O que Geazi fez após a cura de Naamã e qual foi sua punição?", answer: "Correu atrás de Naamã para pedir prata e roupas, e ficou leproso", distractors: ["Roubou parte dos presentes de Naamã e foi expulso", "Mentiu para Eliseu sobre Naamã e foi amaldiçoado"], reference: "2 Reis 5:20-27" },
    ],
    6: [
      { question: "Que milagre Eliseu fez com o machado que caiu no rio?", answer: "Fez o ferro flutuar lançando um pedaço de pau na água", distractors: ["Mergulhou no rio e o recuperou", "Orou e a água recuou revelando o machado"], reference: "2 Reis 6:5-6" },
      { question: "Por que o rei da Síria queria prender Eliseu?", answer: "Porque Eliseu revelava ao rei de Israel os planos militares sírios", distractors: ["Porque Eliseu havia humilhado Naamã", "Porque Eliseu profetizava a queda da Síria"], reference: "2 Reis 6:8-12" },
      { question: "O que Eliseu pediu a Deus para seu servo que ficou com medo do exército sírio?", answer: "Que abrisse os olhos do servo para ver os cavalos e carros de fogo", distractors: ["Que enviasse anjos para protegê-los", "Que cegasse o exército sírio imediatamente"], reference: "2 Reis 6:15-17" },
      { question: "O que Eliseu fez com os soldados sírios que foram enviados para capturá-lo?", answer: "Pediu a Deus que os cegasse e os conduziu a Samaria", distractors: ["Fez fogo descer sobre eles", "Os fez adormecer até o amanhecer"], reference: "2 Reis 6:18-19" },
      { question: "O que o rei de Israel fez com os soldados sírios após serem entregues a ele?", answer: "Deu-lhes comida e água e os mandou embora", distractors: ["Os matou como prisioneiros de guerra", "Os converteu à fé de Israel"], reference: "2 Reis 6:21-23" },
      { question: "O que as mães famintas durante o cerco de Samaria fizeram?", answer: "Combinaram comer seus próprios filhos", distractors: ["Renderam-se aos sírios por comida", "Fugiram da cidade à noite"], reference: "2 Reis 6:26-29" },
    ],
    7: [
      { question: "O que Eliseu profetizou que aconteceria em Samaria no dia seguinte ao cerco?", answer: "Que o alimento seria barato e abundante às portas da cidade", distractors: ["Que os sírios levantariam o cerco", "Que chuva e mantimentos chegariam milagrosamente"], reference: "2 Reis 7:1" },
      { question: "Quem foi descobrir que os sírios tinham fugido do acampamento?", answer: "Quatro leprosos que estavam à entrada da cidade", distractors: ["Um espião do rei de Israel", "Três soldados enviados pelo rei"], reference: "2 Reis 7:3-10" },
      { question: "Por que o exército sírio fugiu precipitadamente?", answer: "Porque o Senhor fez ouvirem barulho de grande exército", distractors: ["Porque um anjo apareceu em chamas no campo deles", "Porque um terremoto destruiu seu acampamento"], reference: "2 Reis 7:6-7" },
      { question: "O que os leprosos encontraram no acampamento sírio abandonado?", answer: "Tendas cheias de prata, ouro, roupas e alimentos", distractors: ["Armas e cavalos abandonados", "Apenas restos de comida e equipamentos velhos"], reference: "2 Reis 7:8" },
      { question: "O que aconteceu com o oficial que duvidou da profecia de Eliseu?", answer: "Foi pisoteado e morreu às portas da cidade", distractors: ["Adoeceu e morreu três dias depois", "Foi exilado pelo rei por sua incredulidade"], reference: "2 Reis 7:17-20" },
      { question: "O que os leprosos decidiram fazer com a descoberta do acampamento sírio?", answer: "Ir anunciar ao rei de Israel", distractors: ["Guardar a notícia para negociar sua entrada na cidade", "Dividir os tesouros entre si antes de contar"], reference: "2 Reis 7:9" },
    ],
    8: [
      { question: "O que a sunamita cujo filho Eliseu havia ressuscitado fez por instrução do profeta?", answer: "Foi com sua família para a terra dos filisteus por sete anos por causa da fome", distractors: ["Construiu um santuário para o Senhor", "Emigrou para o Egito com seus servos"], reference: "2 Reis 8:1-2" },
      { question: "Quem Eliseu profetizou que seria rei da Síria?", answer: "Hazael", distractors: ["Ben-Hadade", "Rezom"], reference: "2 Reis 8:13" },
      { question: "Como Hazael tornou-se rei da Síria após a visita de Eliseu?", answer: "Sufocou Ben-Hadade com um pano molhado enquanto ele dormia", distractors: ["Envenenou Ben-Hadade num banquete", "Liderou um golpe militar contra Ben-Hadade"], reference: "2 Reis 8:15" },
      { question: "Por que Eliseu chorou ao profetizar sobre Hazael?", answer: "Porque sabia que Hazael faria muito mal a Israel", distractors: ["Porque Hazael era um homem perverso desde a infância", "Porque via a destruição de Damasco"], reference: "2 Reis 8:11-12" },
      { question: "Quem foi o rei de Judá que caminhou nos caminhos da casa de Acabe?", answer: "Jorão, filho de Josafá", distractors: ["Acazias, filho de Jorão", "Joás, filho de Acazias"], reference: "2 Reis 8:16-18" },
      { question: "De quem Acazias, rei de Judá, era neto do lado materno?", answer: "De Onri, rei de Israel", distractors: ["De Josafá, rei de Judá", "De Acabe, rei de Israel"], reference: "2 Reis 8:26" },
    ],
    9: [
      { question: "Quem ungiu Jeú como rei de Israel por ordem de Eliseu?", answer: "Um dos filhos dos profetas enviado por Eliseu", distractors: ["O próprio Eliseu", "O sacerdote do templo"], reference: "2 Reis 9:1-6" },
      { question: "O que Jeú foi fazer a Jezreel após ser ungido rei?", answer: "Matar Jorão, rei de Israel", distractors: ["Proclamar-se rei diante do povo", "Atacar o exército de Hazael"], reference: "2 Reis 9:14-24" },
      { question: "Como Jeú matou Jorão, rei de Israel?", answer: "Com uma flecha nas costas enquanto Jorão fugia de carro", distractors: ["Com uma espada num combate direto", "Ordenou a seus soldados que o cercassem e matassem"], reference: "2 Reis 9:24" },
      { question: "O que Jeú fez com o corpo de Jorão?", answer: "Lançou-o no campo de Nabote, o jezreelita", distractors: ["Mandou enterrá-lo na tumba de seus pais", "O deixou no campo para os animais"], reference: "2 Reis 9:25-26" },
      { question: "Como morreu Jezabel?", answer: "Foi jogada pela janela por seus eunucos e os cavalos a pisotearam", distractors: ["Foi apedrejada pelo povo de Jezreel", "Eliseu a amaldiçoou e ela morreu instantaneamente"], reference: "2 Reis 9:32-33" },
      { question: "O que os cães fizeram com o corpo de Jezabel, cumprindo a profecia?", answer: "Devoraram-no, restando apenas o crânio, os pés e as palmas das mãos", distractors: ["Carregaram os ossos para fora da cidade", "Deixaram o corpo intocado como sinal"], reference: "2 Reis 9:35-37" },
    ],
    10: [
      { question: "O que Jeú fez com os setenta filhos de Acabe em Samaria?", answer: "Mandou cortarem suas cabeças e enviarem em cestos", distractors: ["Exilou-os para o Egito", "Poupou-os e os colocou sob guarda"], reference: "2 Reis 10:1-7" },
      { question: "Como Jeú matou todos os adoradores de Baal?", answer: "Convocou-os para um grande sacrifício a Baal e os matou dentro do templo", distractors: ["Enviou soldados casa por casa pela cidade", "Reuniu-os numa praça e os executou publicamente"], reference: "2 Reis 10:18-25" },
      { question: "O que aconteceu com o templo de Baal após o massacre?", answer: "Foi demolido e transformado em latrina", distractors: ["Foi queimado até o chão", "Foi dedicado ao Senhor como santuário"], reference: "2 Reis 10:27" },
      { question: "Apesar de destruir Baal, em que pecado Jeú permaneceu?", answer: "Nos pecados de Jeroboão com os bezerros de ouro em Betel e Dã", distractors: ["Na adoração de Astarote", "Na aliança com os reis da Síria"], reference: "2 Reis 10:29" },
      { question: "Quantos anos Jeú reinou sobre Israel em Samaria?", answer: "Vinte e oito anos", distractors: ["Dezesseis anos", "Trinta e dois anos"], reference: "2 Reis 10:36" },
      { question: "O que Deus prometeu a Jeú por seu zelo em destruir a casa de Acabe?", answer: "Que seus filhos até a quarta geração sentariam no trono de Israel", distractors: ["Que seus inimigos seriam destruídos", "Que Israel prosperaria sob seu reinado"], reference: "2 Reis 10:30" },
    ],
    11: [
      { question: "Quem tentou matar todos os filhos do rei de Judá após a morte de Acazias?", answer: "Atalia, mãe de Acazias", distractors: ["Jezabel, mãe de Acabe", "A sacerdotisa de Baal"], reference: "2 Reis 11:1" },
      { question: "Quem escondeu Joás, o legítimo herdeiro, do massacre de Atalia?", answer: "Jeoseba, irmã de Acazias, e Joiada, o sacerdote", distractors: ["Um servo fiel do palácio", "O profeta Eliseu"], reference: "2 Reis 11:2" },
      { question: "Onde Joás foi escondido durante o reinado de Atalia?", answer: "No templo do Senhor por seis anos", distractors: ["No deserto de Judá", "Na casa de um sacerdote fiel em Belém"], reference: "2 Reis 11:3" },
      { question: "Quantos anos Atalia reinou sobre Judá?", answer: "Seis anos", distractors: ["Três anos", "Doze anos"], reference: "2 Reis 11:3" },
      { question: "Quem organizou a coroação de Joás e o golpe contra Atalia?", answer: "Joiada, o sacerdote", distractors: ["Os capitães do exército de Judá", "Os levitas do templo"], reference: "2 Reis 11:4-12" },
      { question: "O que aconteceu com Atalia quando viu Joás ser coroado?", answer: "Rasgou suas vestes e gritou 'Traição!' e depois foi morta", distractors: ["Fugiu para o Egito", "Se refugiou no templo de Baal"], reference: "2 Reis 11:13-16" },
    ],
    12: [
      { question: "Quantos anos tinha Joás quando começou a reinar em Judá?", answer: "Sete anos", distractors: ["Doze anos", "Quinze anos"], reference: "2 Reis 11:21" },
      { question: "Qual foi o grande projeto de Joás durante seu reinado?", answer: "A restauração do templo do Senhor", distractors: ["A construção de muros ao redor de Jerusalém", "A criação de um exército permanente"], reference: "2 Reis 12:4-5" },
      { question: "Como o dinheiro para o templo era recolhido?", answer: "Numa arca com um orifício, onde o povo depositava suas ofertas", distractors: ["Por um imposto anual sobre todas as famílias", "Pelos sacerdotes que iam de cidade em cidade"], reference: "2 Reis 12:9" },
      { question: "Quem invadiu Judá e ameaçou Jerusalém no tempo de Joás?", answer: "Hazael, rei da Síria", distractors: ["Salmaneser, rei da Assíria", "Fara, rei do Egito"], reference: "2 Reis 12:17" },
      { question: "Como Joás se livrou de Hazael?", answer: "Enviando-lhe todos os tesouros sagrados e do palácio", distractors: ["Derrotando-o em batalha no vale de Jezreel", "Fazendo aliança com Jeú de Israel"], reference: "2 Reis 12:18" },
      { question: "Como Joás morreu?", answer: "Seus servos conspiraram contra ele e o mataram", distractors: ["Morreu em batalha contra os sírios", "Adoeceu gravemente e faleceu"], reference: "2 Reis 12:20" },
    ],
    13: [
      { question: "Quem foi o rei de Israel filho de Jeú?", answer: "Jeoacaz", distractors: ["Joás de Israel", "Jeroboão II"], reference: "2 Reis 13:1" },
      { question: "O que Deus deu a Israel em resposta ao clamor de Jeoacaz?", answer: "Um libertador que os livrou do jugo da Síria", distractors: ["Um profeta que trouxe avivamento", "Vitórias militares contra a Síria"], reference: "2 Reis 13:4-5" },
      { question: "O que Eliseu disse a Joás, rei de Israel, quando estava doente?", answer: "Que flechasse pela janela para o leste como sinal de vitória sobre a Síria", distractors: ["Que construísse um altar no Jordão", "Que se arrependesse dos pecados de Jeroboão"], reference: "2 Reis 13:14-17" },
      { question: "Por que Eliseu ficou irado com Joás de Israel?", answer: "Porque ele bateu as flechas no chão apenas três vezes, em vez de cinco ou seis", distractors: ["Porque ele não obedeceu a instrução de atirar a flecha", "Porque ele saiu antes de terminar a profecia"], reference: "2 Reis 13:18-19" },
      { question: "Que milagre ocorreu após a morte de Eliseu?", answer: "Um morto ressuscitou ao tocar nos ossos de Eliseu", distractors: ["Fogo consumiu seu túmulo como sinal", "A vara de Eliseu floresceu sobre seu sepulcro"], reference: "2 Reis 13:21" },
      { question: "Quantas vezes Joás derrotou Ben-Hadade, filho de Hazael, conforme a profecia de Eliseu?", answer: "Três vezes", distractors: ["Cinco vezes", "Duas vezes"], reference: "2 Reis 13:25" },
    ],
    14: [
      { question: "Quem foi o rei de Judá que derrotou os edomitas no Vale do Sal?", answer: "Amazias", distractors: ["Ozias", "Joás de Judá"], reference: "2 Reis 14:7" },
      { question: "Por que Amazias desafiou Joás, rei de Israel, para uma batalha?", answer: "Após derrotar Edom, ficou arrogante e quis guerrear", distractors: ["Para recuperar territórios perdidos", "Para vingar uma ofensa diplomática"], reference: "2 Reis 14:8-10" },
      { question: "O que Joás de Israel respondeu ao desafio de Amazias numa parábola?", answer: "O cardo do Líbano pediu ao cedro que sua filha se casasse com o seu filho, mas uma fera pisou no cardo", distractors: ["O leão não tem medo do lobo que late de longe", "O rei que não conhece seus limites cava sua própria cova"], reference: "2 Reis 14:9" },
      { question: "O que Joás fez a Amazias após derrotá-lo em Bete-Semes?", answer: "Derrubou o muro de Jerusalém, saqueou o templo e levou reféns", distractors: ["Matou Amazias e colocou um rei vassalo em Jerusalém", "Exigiu tributo anual de Judá"], reference: "2 Reis 14:13-14" },
      { question: "Quem foi o rei de Israel que restaurou as fronteiras de Israel de Hamate até o Mar Arábico?", answer: "Jeroboão II, filho de Joás de Israel", distractors: ["Jeú", "Jeoacaz"], reference: "2 Reis 14:25" },
      { question: "Qual profeta profetizou as vitórias de Jeroboão II?", answer: "Jonas, filho de Amitai", distractors: ["Amós", "Oséias"], reference: "2 Reis 14:25" },
    ],
    15: [
      { question: "Que doença afligiu Azarias (Uzias), rei de Judá?", answer: "Lepra", distractors: ["Cegueira", "Paralisia"], reference: "2 Reis 15:5" },
      { question: "Quem foi o primeiro rei de Israel a ser morto por seu sucessor numa série de golpes rápidos?", answer: "Zacarias, filho de Jeroboão II, morto por Salum", distractors: ["Salum, morto por Menaém", "Peca, morto por Oséias"], reference: "2 Reis 15:8-10" },
      { question: "Quem pagou tributo a Pul (Tiglate-Pileser III), rei da Assíria, para fortalecer seu reino?", answer: "Menaém, rei de Israel", distractors: ["Peca, rei de Israel", "Oséias, rei de Israel"], reference: "2 Reis 15:19" },
      { question: "Quanto Menaém pagou de tributo à Assíria?", answer: "Mil talentos de prata", distractors: ["Quinhentos talentos de prata", "Dois mil talentos de prata"], reference: "2 Reis 15:19" },
      { question: "Quem assassinou Peca, rei de Israel, e tomou the trono?", answer: "Oséias, filho de Ela", distractors: ["Salum, filho de Jabes", "Menaém, filho de Gadi"], reference: "2 Reis 15:30" },
      { question: "Quem foi o rei de Judá que reinou cinquenta e dois anos, sendo o mais longo reinado de Judá?", answer: "Azarias (Uzias)", distractors: ["Manassés", "Josias"], reference: "2 Reis 15:1-2" },
    ],
    16: [
      { question: "O que Acaz, rei de Judá, fez de abominável segundo 2 Reis 16?", answer: "Fez seu filho passar pelo fogo", distractors: ["Construiu um templo a Baal", "Aliou-se com a Assíria contra Israel"], reference: "2 Reis 16:3" },
      { question: "Quem Acaz pediu ajuda contra a coalizão de Rezim e Peca?", answer: "Tiglate-Pileser III, rei da Assíria", distractors: ["O faraó do Egito", "O rei dos filisteus"], reference: "2 Reis 16:7" },
      { question: "O que Acaz enviou a Tiglate-Pileser como pagamento?", answer: "Prata e ouro do templo e do tesouro real", distractors: ["Soldados israelitas", "Cidades do sul de Judá"], reference: "2 Reis 16:8" },
      { question: "O que Acaz viu em Damasco que o impressionou?", answer: "Um altar pagão que copiou e mandou construir em Jerusalém", distractors: ["Um palácio que serviu de modelo ao seu", "Uma estátua de Deus que trouxe para o templo"], reference: "2 Reis 16:10-11" },
      { question: "O que Acaz fez com o altar de bronze que estava no templo?", answer: "Removeu-o do lugar de destaque e colocou o novo altar pagão no centro", distractors: ["Destruiu-o e fundiu o bronze para o novo altar", "Vendeu-o para pagar tributo à Assíria"], reference: "2 Reis 16:14-15" },
      { question: "Qual rei da Assíria capturou Damasco e matou Rezim, cumprindo a profecia?", answer: "Tiglate-Pileser III", distractors: ["Salmaneser V", "Senaqueribe"], reference: "2 Reis 16:9" },
    ],
    17: [
      { question: "Quem capturou Samaria e levou Israel para o exílio na Assíria?", answer: "Salmaneser V", distractors: ["Tiglate-Pileser III", "Sargão II"], reference: "2 Reis 17:3-6" },
      { question: "Quantos anos durou o cerco assírio a Samaria?", answer: "Três anos", distractors: ["Um ano", "Cinco anos"], reference: "2 Reis 17:5" },
      { question: "Por que Israel foi exilado segundo 2 Reis 17?", answer: "Por terem pecado contra o Senhor adorando outros deuses e rejeitado as advertências dos profetas", distractors: ["Por terem feito aliança com o Egito contra a Assíria", "Por terem abandonado a circuncisão e os sacrifícios"], reference: "2 Reis 17:7-18" },
      { question: "Que povos o rei da Assíria trouxe para habitar nas cidades de Samaria?", answer: "Povos de Babilônia, Cuté, Ava, Hamate e Sefarvaim", distractors: ["Povos da Síria, Moabe e Amom", "Povos da Pérsia, Media e Elão"], reference: "2 Reis 17:24" },
      { question: "Por que Deus enviou leões que matavam os colonos em Samaria?", answer: "Porque eles não sabiam adorar o Deus da terra", distractors: ["Como punição por perseguirem os israelitas que ficaram", "Para mostrar que a terra ainda pertencia a Israel"], reference: "2 Reis 17:25-26" },
      { question: "Como os samaritanos passaram a praticar sua religião sincretista?", answer: "Temiam o Senhor mas também adoravam seus próprios deuses", distractors: ["Abandonaram completamente seus deuses e adoravam só o Senhor", "Adoravam os deuses assírios e ignoravam o Senhor"], reference: "2 Reis 17:33" },
    ],
    18: [
      { question: "O que Ezequias fez em relação à serpente de bronze que Moisés havia feito?", answer: "Destruiu-a porque os israelitas queimavam incenso a ela", distractors: ["Colocou-a no templo como relíquia sagrada", "A enviou para o templo em Jerusalém"], reference: "2 Reis 18:4" },
      { question: "Qual rei assírio invadiu Judá no tempo de Ezequias?", answer: "Senaqueribe", distractors: ["Sargão II", "Tiglate-Pileser III"], reference: "2 Reis 18:13" },
      { question: "O que Ezequias enviou a Senaqueribe em Laquis?", answer: "Prata e ouro do templo e do tesouro real", distractors: ["Reféns da família real", "Um pedido formal de paz"], reference: "2 Reis 18:14-15" },
      { question: "Quem o rei da Assíria enviou para intimidar Ezequias e Jerusalém?", answer: "Rabsaqué", distractors: ["Tartan", "Rabsáris"], reference: "2 Reis 18:17" },
      { question: "Em que língua Rabsaqué falou com o povo de Jerusalém para intimidá-lo?", answer: "Em hebraico, para que o povo pudeese entender", distractors: ["Em aramaico, para falar diretamente com os oficiais", "Em assírio, mostrando desprezo por Israel"], reference: "2 Reis 18:26-28" },
      { question: "O que Rabsaqué disse sobre o Senhor ao povo de Jerusalém?", answer: "Que o Senhor não poderia livrar Jerusalém, assim como os deuses das outras nações não as livraram", distractors: ["Que o Senhor havia enviado a Assíria para punir Israel", "Que o Senhor era fraco comparado aos deuses assírios"], reference: "2 Reis 18:33-35" },
    ],
    19: [
      { question: "A quem Ezequias enviou mensageiros após ouvir as ameaças de Rabsaqué?", answer: "Ao profeta Isaías", distractors: ["Ao sacerdote Hilquias", "Ao profeta Miquéias"], reference: "2 Reis 19:1-2" },
      { question: "O que Isaías disse a Ezequias sobre o rei da Assíria?", answer: "Que Deus faria o rei voltar para sua terra e lá cair pela espada", distractors: ["Que Deus enviaria pragas sobre o exército assírio", "Que o anjo do Senhor destruiria o exército antes de chegar"], reference: "2 Reis 19:6-7" },
      { question: "O que Ezequias fez com a carta de Senaqueribe que ameaçava Jerusalém?", answer: "Foi ao templo e a estendeu diante do Senhor orando", distractors: ["Rasgou a carta em público diante do povo", "Respondeu por escrito recusando a rendição"], reference: "2 Reis 19:14" },
      { question: "O que aconteceu com the exército assírio durante a noite?", answer: "O anjo do Senhor feriu cento e oitenta e cinco mil soldados", distractors: ["Uma praga misteriosa matou metade do exército", "Uma tempestade destruiu o acampamento assírio"], reference: "2 Reis 19:35" },
      { question: "Como morreu Senaqueribe após retornar à Assíria?", answer: "Seus filhos Adrameleque e Sarezer o mataram com a espada", distractors: ["Morreu de doença logo após voltar de Judá", "Foi assassinado em conspiração de seus generais"], reference: "2 Reis 19:37" },
      { question: "O que Deus disse que defenderia Jerusalém 'por causa de mim e por causa de Davi, meu servo'?", answer: "Que protegeria e livraria a cidade", distractors: ["Que restauraria o templo e suas riquezas", "Que destruiria todos os inimigos de Judá"], reference: "2 Reis 19:34" },
    ],
    20: [
      { question: "Qual doença quase matou Ezequias no auge de sua vida?", answer: "Uma ferida grave (tumor)", distractors: ["Lepra", "Febre pestilenta"], reference: "2 Reis 20:1" },
      { question: "Quantos anos Deus acrescentou à vida de Ezequias após sua oração?", answer: "Quinze anos", distractors: ["Dez anos", "Vinte anos"], reference: "2 Reis 20:6" },
      { question: "Qual foi o sinal que Deus deu a Ezequias de que seria curado?", answer: "A sombra retrocedeu dez degraus no relógio de Acaz", distractors: ["O sol ficou parado por uma hora", "Uma estrela apareceu no céu diurno"], reference: "2 Reis 20:11" },
      { question: "Quem enviou embaixadores a Ezequias após sua recuperação?", answer: "Merodaque-Baladã, filho de Baladã, rei da Babilônia", distractors: ["Senaqueribe, rei da Assíria", "O faraó Tiraca do Egito"], reference: "2 Reis 20:12" },
      { question: "O que Ezequias mostrou aos embaixadores babilônios?", answer: "Todo o seu tesouro: prata, ouro, especiarias, azeite e todo seu arsenal", distractors: ["Apenas o templo e seus utensílios sagrados", "Seu exército e as fortalezas de Judá"], reference: "2 Reis 20:13" },
      { question: "O que Isaías profetizou que aconteceria por causa da visita dos babilônios?", answer: "Que tudo que estava no palácio seria levado para a Babilônia", distractors: ["Que a Babilônia seria aliada de Israel contra a Assíria", "Que Ezequias morreria antes de ver a ameaça babilônica"], reference: "2 Reis 20:17" },
    ],
    21: [
      { question: "Quantos anos tinha Manassés quando começou a reinar e quantos anos reinou?", answer: "Doze anos quando começou e reinou cinquenta e cinco anos", distractors: ["Oito anos quando começou e reinou quarenta anos", "Quinze anos quando começou e reinou quarenta e cinco anos"], reference: "2 Reis 21:1" },
      { question: "Que abominação Manassés reconstruiu que seu pai Ezequias havia destruído?", answer: "Os lugares altos", distractors: ["O templo de Baal", "A serpente de bronze"], reference: "2 Reis 21:3" },
      { question: "O que Manassés fez que foi considerado o maior crime de sua lista de pecados?", answer: "Fez seu filho passar pelo fogo e praticou adivinhação e feitiçaria", distractors: ["Matou os profetas do Senhor", "Colocou ídolos dentro do templo de Deus"], reference: "2 Reis 21:6" },
      { question: "O que Deus declarou que faria a Jerusalém por causa dos pecados de Manassés?", answer: "Limparia Jerusalém como se limpa um prato, de um lado e de outro", distractors: ["Destruiria o templo e dispersaria o povo", "Levantaria um rei inimigo para conquistar Judá"], reference: "2 Reis 21:13" },
      { question: "O que Manassés fez com os inocentes em Jerusalém?", answer: "Derramou muito sangue inocente, enchendo Jerusalém de ponta a ponta", distractors: ["Exilou os sacerdotes fiéis do templo", "Matou todos os profetas que profetizavam contra ele"], reference: "2 Reis 21:16" },
      { question: "Quem sucedeu Manassés e foi assassinado por seus servos?", answer: "Amom", distractors: ["Josias", "Jeoacaz"], reference: "2 Reis 21:18-23" },
    ],
    22: [
      { question: "Quantos anos tinha Josias quando começou a reinar em Judá?", answer: "Oito anos", distractors: ["Doze anos", "Cinco anos"], reference: "2 Reis 22:1" },
      { question: "O que foi encontrado no templo durante as obras de restauração no tempo de Josias?", answer: "O livro da Lei", distractors: ["O rolo dos profetas", "O livro das crônicas dos reis"], reference: "2 Reis 22:8" },
      { question: "Quem encontrou o livro da Lei no templo?", answer: "Hilquias, o sumo sacerdote", distractors: ["Safã, o escriba", "Josiás, o sacerdote"], reference: "2 Reis 22:8" },
      { question: "O que Josias fez ao ouvir as palavras do livro da Lei?", answer: "Rasgou suas vestes", distractors: ["Convocou o povo imediatamente", "Chorou e orou por três dias"], reference: "2 Reis 22:11" },
      { question: "A qual profetisa Josias enviou seus servos para consultar o Senhor?", answer: "Hulda", distractors: ["Débora", "Miriam"], reference: "2 Reis 22:14" },
      { question: "O que Hulda profetizou sobre o juízo de Deus sobre Judá?", answer: "Que o juízo viria, mas Josias não o veria porque seu coração foi sensível", distractors: ["Que o juízo seria adiado por cem anos", "Que se o povo se arrependesse Deus perdoaria"], reference: "2 Reis 22:15-20" },
    ],
    23: [
      { question: "O que Josias fez após ler o livro da Lei ao povo?", answer: "Fez uma aliança com o Senhor e o povo para guardar todos os seus mandamentos", distractors: ["Convocou um jejum nacional de sete dias", "Enviou sacerdotes para ensinar a Lei em todo Judá"], reference: "2 Reis 23:1-3" },
      { question: "O que Josias destruiu em sua grande reforma religiosa?", answer: "Lugares altos, ídolos, altares pagãos, e profanou os lugares de Baal", distractors: ["Apenas os templos de Baal e Astarote", "Os altares nos lugares altos de Judá e Israel"], reference: "2 Reis 23:4-20" },
      { question: "O que Josias fez em Betel com o altar de Jeroboão?", answer: "O destruiu, queimou e pulverizou, profanando-o com ossos humanos", distractors: ["O derrubou no rio Jordão", "O fundiu e fez utensílios para o templo"], reference: "2 Reis 23:15-16" },
      { question: "Que festa Josias reinstituiu que não havia sido celebrada desde os dias dos juízes?", answer: "A Páscoa", distractors: ["O Pentecostes", "A Festa dos Tabernáculos"], reference: "2 Reis 23:21-23" },
      { question: "O que o texto diz sobre Josias comparado a todos os reis de Judá?", answer: "Que não houve rei como ele que se voltou ao Senhor de todo seu coração, alma e força", distractors: ["Que foi o rei mais sábio depois de Salomão", "Que fez mais obras no templo que todos os reis antes dele"], reference: "2 Reis 23:25" },
      { question: "Como morreu Josias?", answer: "Numa batalha em Megido contra o faraó Neco do Egito", distractors: ["Assassinado por seus próprios servos", "De doença após retornar de uma campanha"], reference: "2 Reis 23:29" },
    ],
    24: [
      { question: "Quem foi o rei da Babilônia que invadiu Judá e fez Jeoaquim seu servo?", answer: "Nabucodonosor", distractors: ["Merodaque-Baladã", "Belsazar"], reference: "2 Reis 24:1" },
      { question: "O que o texto diz sobre por que Judá foi entregue ao domínio babilônico?", answer: "Por causa dos pecados de Manassés e do sangue inocente que ele derramou", distractors: ["Por causa da aliança de Jeoaquim com o Egito", "Por causa do abandono do templo"], reference: "2 Reis 24:3-4" },
      { question: "O que Nabucodonosor fez quando sitiou Jerusalém no tempo de Jeconias?", answer: "Levou Jeconias, sua mãe, seus servos e os tesouros do templo para a Babilônia", distractors: ["Destruiu o templo e matou os sacerdotes", "Fez Jeconias seu governador vassalo"], reference: "2 Reis 24:10-15" },
      { question: "Quem Nabucodonosor colocou como rei em Jerusalém no lugar de Jeconias?", answer: "Matatias, tio de Jeconias, que mudou o nome para Zedequias", distractors: ["Um general babilônico chamado Neriglisar", "Ismaías, filho de Nerias"], reference: "2 Reis 24:17" },
      { question: "Quantos homens de guerra Nabucodonosor levou de Jerusalém para a Babilônia?", answer: "Dez mil cativos, mais artífices e ferreiros", distractors: ["Cinco mil cativos, mais os sacerdotes", "Vinte mil cativos de todas as classes"], reference: "2 Reis 24:14" },
      { question: "Que aliança Zedequias fez que provocou a ira de Nabucodonosor?", answer: "Se rebelou contra o rei da Babilônia", distractors: ["Fez aliança secreta com os filisteus", "Tentou fugir para o Egito com o tesouro real"], reference: "2 Reis 24:20" },
    ],
    25: [
      { question: "O que Nabucodonosor fez a Jerusalém no nono ano de Zedequias?", answer: "Sitiou a cidade", distractors: ["Entrou na cidade sem resistência", "Destruiu o templo num ataque surpresa"], reference: "2 Reis 25:1" },
      { question: "O que aconteceu com Zedequias quando tentou fugir do cerco?", answer: "Foi capturado na planície de Jericó", distractors: ["Morreu tentando defender o muro da cidade", "Se entregou voluntariamente para salvar o povo"], reference: "2 Reis 25:4-5" },
      { question: "Qual foi a cruel punição aplicada a Zedequias pelos babilônios?", answer: "Mataram seus filhos diante dele e depois arrancaram seus olhos", distractors: ["Cortaram suas mãos e o exilaram", "O acorrentaram e o humilharam em Babilônia"], reference: "2 Reis 25:7" },
      { question: "O que Nebuzaradã, capitão da guarda, fez ao templo de Salomão?", answer: "Queimou-o e demoliu os muros de Jerusalém", distractors: ["Saqueou apenas os tesouros e o deixou de pé", "Desmontou pedra por pedra para construir em Babilônia"], reference: "2 Reis 25:8-10" },
      { question: "Quem Nabucodonosor nomeou como governador sobre o povo que ficou em Judá?", answer: "Gedalias, filho de Aicão", distractors: ["Jeremias, o profeta", "Seraiah, o sumo sacerdote"], reference: "2 Reis 25:22" },
      { question: "O que aconteceu a Jeconias (Joaquim) no trigésimo sétimo ano de seu exílio?", answer: "Evil-Merodaque libertou-o da prisão e lhe deu uma posição honrosa na Babilônia", distractors: ["Morreu na prisão de Babilônia", "Conseguiu escapar e voltar a Judá"], reference: "2 Reis 25:27-28" },
    ],
  },
};
