import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_1REIS: Record<string, Record<number, BankQuestion[]>> = {
  "1reis": {
    1: [
      { question: "Quem foi ungido rei de Israel no início de 1 Reis 1?", answer: "Salomão", distractors: ["Adonias", "Absalão"], reference: "1 Reis 1:39" },
      { question: "Quem tentou se proclamar rei antes de Salomão em 1 Reis 1?", answer: "Adonias", distractors: ["Joabe", "Abiatar"], reference: "1 Reis 1:5" },
      { question: "Quem aconselhou Bate-Seba a ir falar com Davi sobre a sucessão ao trono?", answer: "Natã", distractors: ["Sadoque", "Benaia"], reference: "1 Reis 1:11-13" },
      { question: "Onde Salomão foi ungido como rei por ordem de Davi?", answer: "Em Giom", distractors: ["Em Belém", "Em Hebrom"], reference: "1 Reis 1:33-34" },
      { question: "Quem ungiu Salomão como rei em Giom?", answer: "Sadoque, o sacerdote", distractors: ["Natã", "Benaia"], reference: "1 Reis 1:39" },
      { question: "O que Adonias fez ao saber que Salomão havia sido coroado rei?", answer: "Agarrou os chifres do altar", distractors: ["Fugiu para o Egito", "Se escondeu numa caverna"], reference: "1 Reis 1:50" },
    ],
    2: [
      { question: "O que Davi ordenou a Salomão antes de morrer sobre Joabe?", answer: "Que não deixasse seus cabelos brancos descerem em paz para o Seol", distractors: ["Que o recompensasse com riquezas", "Que o nomeasse general"], reference: "1 Reis 2:5-6" },
      { question: "Quem Salomão mandou matar por ter maldito Davi?", answer: "Simei", distractors: ["Adonias", "Joabe"], reference: "1 Reis 2:8-9, 46" },
      { question: "Por que Adonias foi morto por Salomão?", answer: "Por pedir Abisague, a sunamita, como esposa", distractors: ["Por conspirar com estrangeiros", "Por roubar do tesouro real"], reference: "1 Reis 2:13-25" },
      { question: "Quem Salomão colocou no lugar de Abiatar como sacerdote?", answer: "Sadoque", distractors: ["Natã", "Benaia"], reference: "1 Reis 2:35" },
      { question: "Quem matou Joabe no tabernáculo do Senhor?", answer: "Benaia", distractors: ["Salomão", "Simei"], reference: "1 Reis 2:29-34" },
      { question: "Quantos anos reinou Davi sobre Israel?", answer: "Quarenta anos", distractors: ["Trinta anos", "Cinquenta anos"], reference: "1 Reis 2:11" },
    ],
    3: [
      { question: "Com quem Salomão fez aliança ao casar-se?", answer: "Com o faraó do Egito", distractors: ["Com o rei da Fenícia", "Com o rei da Síria"], reference: "1 Reis 3:1" },
      { question: "O que Deus apareceu a Salomão em sonho e lhe disse que pedisse?", answer: "O que quisesse e Deus lhe daria", distractors: ["Que construísse o templo", "Que unisse as tribos"], reference: "1 Reis 3:5" },
      { question: "O que Salomão pediu a Deus em Gibeão?", answer: "Coração sábio para julgar o povo", distractors: ["Riquezas e glória", "Vida longa"], reference: "1 Reis 3:9" },
      { question: "Com o que Deus ficou agradado no pedido de Salomão?", answer: "Com o fato de Salomão não ter pedido riquezas nem longa vida", distractors: ["Com o fato de ter pedido vitória sobre inimigos", "Com o fato de ter pedido saúde"], reference: "1 Reis 3:10-14" },
      { question: "Qual caso famoso Salomão julgou envolvendo duas mulheres?", answer: "O caso do bebê disputado pelas duas mães", distractors: ["O caso da herança de terras", "O caso do assassinato no campo"], reference: "1 Reis 3:16-28" },
      { question: "Qual foi a solução proposta por Salomão para descobrir a verdadeira mãe do bebê?", answer: "Cortar o bebê ao meio", distractors: ["Fazer as mães jurarem pelo nome de Deus", "Perguntar às testemunhas"], reference: "1 Reis 3:24-27" },
    ],
    4: [
      { question: "Quem era o principal sacerdote de Salomão segundo 1 Reis 4?", answer: "Azarias", distractors: ["Sadoque", "Abiatar"], reference: "1 Reis 4:2" },
      { question: "Quantos distritos administrativos Salomão organizou em Israel?", answer: "Doze", distractors: ["Seis", "Dez"], reference: "1 Reis 4:7" },
      { question: "Qual era a provisão diária de Salomão segundo 1 Reis 4?", answer: "Trinta coros de flor de farinha e sessenta de farinha comum", distractors: ["Dez coros de flor de farinha e vinte de farinha comum", "Cinquenta coros de farinha"], reference: "1 Reis 4:22" },
      { question: "Quantos provérbios Salomão compôs segundo 1 Reis 4?", answer: "Três mil", distractors: ["Mil", "Cinco mil"], reference: "1 Reis 4:32" },
      { question: "Quantos cânticos Salomão compôs?", answer: "Mil e cinco", distractors: ["Quinhentos", "Dois mil"], reference: "1 Reis 4:32" },
      { question: "Sobre quais assuntos Salomão falou segundo 1 Reis 4?", answer: "Sobre árvores, animais, aves, répteis e peixes", distractors: ["Sobre astros e constelações", "Sobre guerras e conquistas"], reference: "1 Reis 4:33" },
    ],
    5: [
      { question: "Quem enviou seus servos a Salomão para ajudar na construção do templo?", answer: "Hirão, rei de Tiro", distractors: ["O faraó do Egito", "O rei da Síria"], reference: "1 Reis 5:1" },
      { question: "O que Salomão pediu a Hirão de Tiro?", answer: "Cedros do Líbano para construir o templo", distractors: ["Ouro e prata", "Escultores e artesãos"], reference: "1 Reis 5:6" },
      { question: "O que Salomão dava a Hirão em troca dos materiais?", answer: "Trigo e azeite", distractors: ["Prata e ouro", "Gado e animais"], reference: "1 Reis 5:11" },
      { question: "Quantos homens Salomão recrutou como trabalhadores forçados para a construção?", answer: "Trinta mil", distractors: ["Dez mil", "Cinquenta mil"], reference: "1 Reis 5:13" },
      { question: "Quem eram os supervisores dos trabalhadores de Salomão?", answer: "Três mil e trezentos supervisores", distractors: ["Mil e quinhentos supervisores", "Cinco mil supervisores"], reference: "1 Reis 5:16" },
      { question: "De onde vinha a madeira de cedro para o templo de Salomão?", answer: "Do Líbano", distractors: ["Do Egito", "Da Arábia"], reference: "1 Reis 5:6" },
    ],
    6: [
      { question: "Quantos anos após a saída do Egito Salomão começou a construir o templo?", answer: "Quatrocentos e oitenta anos", distractors: ["Trezentos anos", "Quinhentos anos"], reference: "1 Reis 6:1" },
      { question: "Quantos anos Salomão levou para construir o templo?", answer: "Sete anos", distractors: ["Três anos", "Dez anos"], reference: "1 Reis 6:38" },
      { question: "O que Deus prometeu a Salomão durante a construção do templo?", answer: "Que habitaria entre os israelitas e não os abandonaria", distractors: ["Que daria a Salomão vitória sobre todos os inimigos", "Que multiplicaria o reino para sempre"], reference: "1 Reis 6:11-13" },
      { question: "Com o que Salomão revestiu o interior do templo?", answer: "Com ouro puro", distractors: ["Com prata e bronze", "Com pedras preciosas"], reference: "1 Reis 6:21-22" },
      { question: "O que Salomão colocou no lugar santíssimo do templo?", answer: "Os querubins de oliveira", distractors: ["A arca da aliança", "O altar de incenso"], reference: "1 Reis 6:23-28" },
      { question: "Com o que Salomão revestiu o chão do templo?", answer: "Com ouro", distractors: ["Com cedro", "Com pedra polida"], reference: "1 Reis 6:30" },
    ],
    7: [
      { question: "Quantos anos Salomão levou para construir seu próprio palácio?", answer: "Treze anos", distractors: ["Sete anos", "Dez anos"], reference: "1 Reis 7:1" },
      { question: "Quem Salomão trouxe de Tiro para fazer as obras de bronze do templo?", answer: "Hirão (artífice)", distractors: ["Bezalel", "Aoliabe"], reference: "1 Reis 7:13-14" },
      { question: "Como se chamavam as duas colunas de bronze colocadas na entrada do templo?", answer: "Jaquim e Boaz", distractors: ["Urim e Tumim", "Querubim e Serafim"], reference: "1 Reis 7:21" },
      { question: "O que era o 'mar de fundição' construído por Hirão?", answer: "Uma grande bacia circular de bronze", distractors: ["Um tanque para rituais de purificação subterrâneo", "Uma piscina para os sacerdotes se lavarem"], reference: "1 Reis 7:23" },
      { question: "Quantos bois sustentavam o 'mar de fundição'?", answer: "Doze", distractors: ["Quatro", "Oito"], reference: "1 Reis 7:25" },
      { question: "O que Salomão colocou no templo que Davi havia dedicado?", answer: "Prata, ouro e utensílios sagrados", distractors: ["Os rolos da lei de Moisés", "Os estandartes das tribos"], reference: "1 Reis 7:51" },
    ],
    8: [
      { question: "O que Salomão trouxe para o templo ao inaugurá-lo?", answer: "A arca da aliança", distractors: ["O tabernáculo de Moisés", "Os rolos da Torá"], reference: "1 Reis 8:1-6" },
      { question: "O que aconteceu quando os sacerdotes saíram do lugar santo após colocar a arca?", answer: "Uma nuvem encheu o templo", distractors: ["Fogo desceu do céu", "O chão tremeu"], reference: "1 Reis 8:10-11" },
      { question: "Para que direção Salomão se voltou para abençoar o povo na dedicação do templo?", answer: "Para toda a assembleia de Israel", distractors: ["Para o leste", "Para o lugar santíssimo"], reference: "1 Reis 8:14" },
      { question: "Quantos dias durou a festa da dedicação do templo?", answer: "Catorze dias", distractors: ["Sete dias", "Quarenta dias"], reference: "1 Reis 8:65-66" },
      { question: "Quantos bois e ovelhas Salomão sacrificou na dedicação do templo?", answer: "Vinte e dois mil bois e cento e vinte mil ovelhas", distractors: ["Mil bois e dez mil ovelhas", "Cem bois e mil ovelhas"], reference: "1 Reis 8:63" },
      { question: "O que Salomão pediu a Deus na oração da dedicação do templo para os estrangeiros?", answer: "Que Deus também ouvisse suas orações", distractors: ["Que os afastasse da terra de Israel", "Que os convertesse à fé de Israel"], reference: "1 Reis 8:41-43" },
    ],
    9: [
      { question: "O que Deus prometeu a Salomão na segunda aparição em sonho?", answer: "Que havia ouvido sua oração e consagrado o templo", distractors: ["Que lhe daria mais sabedoria", "Que multiplicaria seu reino"], reference: "1 Reis 9:3" },
      { question: "O que Deus advertiu que aconteceria se Salomão se afastasse dele?", answer: "O templo seria destruído e Israel disperso", distractors: ["Salomão seria substituído por outro rei", "Uma praga viria sobre o povo"], reference: "1 Reis 9:6-9" },
      { question: "Quantas cidades Salomão deu a Hirão de Tiro?", answer: "Vinte cidades na Galileia", distractors: ["Dez cidades na Judeia", "Trinta cidades em Gilead"], reference: "1 Reis 9:11" },
      { question: "Como Hirão chamou as cidades que Salomão lhe deu?", answer: "Terra de Cabul", distractors: ["Terra de Neguebe", "Terra de Giléade"], reference: "1 Reis 9:13" },
      { question: "O que Salomão construiu em Ezion-Geber?", answer: "Uma frota de navios", distractors: ["Uma fortaleza militar", "Um depósito de armas"], reference: "1 Reis 9:26" },
      { question: "Qual povo Salomão usou como trabalhadores forçados para suas construções?", answer: "Os amorreus, hititas, ferezeus, heveus e jebuseus", distractors: ["Os israelitas de todas as tribos", "Os egípcios capturados em batalha"], reference: "1 Reis 9:20-21" },
    ],
    10: [
      { question: "Quem veio visitar Salomão para testar sua sabedoria com perguntas difíceis?", answer: "A rainha de Sabá", distractors: ["A rainha do Egito", "A rainha da Pérsia"], reference: "1 Reis 10:1" },
      { question: "O que a rainha de Sabá disse ao ver a sabedoria e riqueza de Salomão?", answer: "Que nem a metade lhe havia sido contada", distractors: ["Que Salomão era maior que todos os deuses", "Que ela voltaria para aprender mais"], reference: "1 Reis 10:7" },
      { question: "Quantos talentos de ouro a rainha de Sabá deu a Salomão?", answer: "Cento e vinte talentos", distractors: ["Cinquenta talentos", "Duzentos talentos"], reference: "1 Reis 10:10" },
      { question: "Quanto ouro Salomão recebia por ano?", answer: "Seiscentos e sessenta e seis talentos de ouro", distractors: ["Quinhentos talentos", "Mil talentos"], reference: "1 Reis 10:14" },
      { question: "Quantos escudos de ouro batido Salomão mandou fazer?", answer: "Duzentos grandes escudos e trezentos pequenos escudos", distractors: ["Cem escudos grandes e cem pequenos", "Mil escudos de ouro"], reference: "1 Reis 10:16-17" },
      { question: "De que material era o grande trono de Salomão?", answer: "Marfim coberto de ouro", distractors: ["Cedro coberto de ouro", "Pedra e bronze"], reference: "1 Reis 10:18" },
    ],
    11: [
      { question: "Quantas esposas Salomão teve?", answer: "Setecentas esposas e trezentas concubinas", distractors: ["Cem esposas e duzentas concubinas", "Trezentas esposas e trezentas concubinas"], reference: "1 Reis 11:3" },
      { question: "O que as esposas estrangeiras de Salomão o levaram a fazer?", answer: "A adorar outros deuses", distractors: ["A abandonar a construção do templo", "A guerrear contra nações vizinhas"], reference: "1 Reis 11:4" },
      { question: "Qual deusa Salomão adorou, de Sidon?", answer: "Astarote", distractors: ["Dagom", "Baal"], reference: "1 Reis 11:5" },
      { question: "Qual deus dos amonitas Salomão adorou?", answer: "Moloque", distractors: ["Quemós", "Dagom"], reference: "1 Reis 11:7" },
      { question: "Quem Deus levantou como adversário de Salomão, da linhagem real de Edom?", answer: "Hadade, o edomita", distractors: ["Rezom, da Síria", "Jeroboão, de Efraim"], reference: "1 Reis 11:14" },
      { question: "O que o profeta Aías disse a Jeroboão sobre o reino de Salomão?", answer: "Que dez tribos seriam arrancadas de Salomão e dadas a Jeroboão", distractors: ["Que o reino inteiro seria dado a Jeroboão", "Que duas tribos seriam dadas a Jeroboão"], reference: "1 Reis 11:29-31" },
    ],
    12: [
      { question: "Após a morte de Salomão, quem foi a Siquém para ser coroado rei de todo Israel?", answer: "Roboão", distractors: ["Jeroboão", "Abias"], reference: "1 Reis 12:1" },
      { question: "O que o povo pediu a Roboão que ele aliviasse?", answer: "O pesado jugo que seu pai Salomão lhes impôs", distractors: ["Os impostos sobre as colheitas", "O serviço militar obrigatório"], reference: "1 Reis 12:4" },
      { question: "Qual foi o conselho dos velhos a Roboão?", answer: "Que servisse ao povo e lhes falasse palavras boas", distractors: ["Que aumentasse os impostos gradualmente", "Que expulsasse os líderes rebeldes"], reference: "1 Reis 12:6-7" },
      { question: "Qual foi o conselho dos jovens a Roboão?", answer: "Que tornasse o jugo mais pesado ainda", distractors: ["Que dividisse o reino em dois", "Que convocasse o exército"], reference: "1 Reis 12:10-11" },
      { question: "Que conselho Roboão seguiu?", answer: "O conselho dos jovens", distractors: ["O conselho dos velhos", "O conselho do profeta Semaías"], reference: "1 Reis 12:13-14" },
      { question: "Quais tribos seguiram Jeroboão após a divisão do reino?", answer: "As dez tribos do norte", distractors: ["Benjamim e Judá", "Levi e Simeão"], reference: "1 Reis 12:20" },
    ],
    13: [
      { question: "Quem foi ao altar de Jeroboão em Betel para profetizar contra ele?", answer: "Um homem de Deus de Judá", distractors: ["O profeta Elias", "O profeta Aías"], reference: "1 Reis 13:1" },
      { question: "O que o homem de Deus profetizou sobre o altar de Betel?", answer: "Que um rei chamado Josias o profanaria", distractors: ["Que seria destruído por fogo", "Que afundaria no chão"], reference: "1 Reis 13:2" },
      { question: "O que aconteceu com a mão de Jeroboão quando ele a estendeu contra o homem de Deus?", answer: "Secou e ele não conseguia retirá-la", distractors: ["Foi cortada por um anjo", "Tremeu incontrolavelmente"], reference: "1 Reis 13:4" },
      { question: "Por que o leão matou o homem de Deus no caminho de volta?", answer: "Porque ele desobedeceu ao mandamento de Deus ao comer com o velho profeta", distractors: ["Porque ele aceitou presentes de Jeroboão", "Porque ele não completou sua missão"], reference: "1 Reis 13:18-24" },
      { question: "O que o velho profeta fez ao ver o corpo do homem de Deus morto?", answer: "Chorou e enterrou-o em seu próprio sepulcro", distractors: ["Voltou a Betel para contar a Jeroboão", "Deixou o corpo para os animais"], reference: "1 Reis 13:26-31" },
      { question: "Que bezerros de ouro Jeroboão fez e colocou em Betel e Dã?", answer: "Dois bezerros de ouro dizendo que eram os deuses que tiraram Israel do Egito", distractors: ["Dois touros de bronze representando o Senhor", "Dois ídolos de pedra simbolizando Baal"], reference: "1 Reis 12:28-29" },
    ],
    14: [
      { question: "Por que Jeroboão enviou sua esposa disfarçada ao profeta Aías?", answer: "Para perguntar se seu filho doente sobreviveria", distractors: ["Para saber se seu reino duraria", "Para pedir perdão pelos ídolos"], reference: "1 Reis 14:1-3" },
      { question: "O que Aías profetizou sobre o filho doente de Jeroboão?", answer: "Que morreria ao entrar sua mãe na cidade", distractors: ["Que seria curado por misericórdia de Deus", "Que sobreviveria, mas seria exilado"], reference: "1 Reis 14:12" },
      { question: "O que Aías profetizou sobre a casa de Jeroboão?", answer: "Que seria destruída como esterco", distractors: ["Que reinaria por três gerações", "Que seria salva se Jeroboão se arrependesse"], reference: "1 Reis 14:10" },
      { question: "Quem sucedeu a Jeroboão como rei de Israel?", answer: "Nadabe", distractors: ["Baasa", "Ela"], reference: "1 Reis 14:20" },
      { question: "O que Roboão, filho de Salomão, fez de errado em Judá?", answer: "Edificou lugares altos, estátuas e imagens de Aserá", distractors: ["Aliou-se com os reis de Israel", "Abandonou o templo de Jerusalém"], reference: "1 Reis 14:22-23" },
      { question: "Quem invadiu Judá e saqueou os tesouros do templo no reinado de Roboão?", answer: "Sisaque, rei do Egito", distractors: ["Hazael, rei da Síria", "Nadabe, rei de Israel"], reference: "1 Reis 14:25-26" },
    ],
    15: [
      { question: "Quem foi rei de Judá e foi considerado fiel como Davi?", answer: "Asa", distractors: ["Abias", "Josafá"], reference: "1 Reis 15:11" },
      { question: "O que Asa fez com a sua mãe Maaca?", answer: "A destituiu do cargo de rainha-mãe por causa de um ídolo", distractors: ["A honrou construindo um palácio para ela", "A exilou para o Egito"], reference: "1 Reis 15:13" },
      { question: "Quem matou Nadabe e tomou o trono de Israel?", answer: "Baasa", distractors: ["Ela", "Zimri"], reference: "1 Reis 15:27-28" },
      { question: "Qual profeta havia profetizado a destruição da casa de Jeroboão?", answer: "Aías, o silonita", distractors: ["Elias", "Semaías"], reference: "1 Reis 14:10" },
      { question: "O que Asa enviou ao rei da Síria Ben-Hadade para pedir ajuda?", answer: "Prata e ouro do tesouro do templo", distractors: ["Soldados e cavaleiros", "Cidades fronteiriças"], reference: "1 Reis 15:18" },
      { question: "Que mal fez Abias, rei de Judá, filho de Roboão?", answer: "Andou em todos os pecados de seu pai", distractors: ["Adorou Baal e Astarote", "Fez alianças com os reis pagãos"], reference: "1 Reis 15:3" },
    ],
    16: [
      { question: "Quem profetizou contra Baasa, rei de Israel?", answer: "Jeú, filho de Hanani", distractors: ["Elias", "Miquéias"], reference: "1 Reis 16:1" },
      { question: "Quem matou Ela, filho de Baasa, enquanto este se embriagava?", answer: "Zimri", distractors: ["Onri", "Tibni"], reference: "1 Reis 16:9-10" },
      { question: "Quantos dias durou o reinado de Zimri?", answer: "Sete dias", distractors: ["Trinta dias", "Um ano"], reference: "1 Reis 16:15" },
      { question: "Quem o povo de Israel escolher como rei após a morte de Zimri?", answer: "Onri", distractors: ["Tibni", "Ela"], reference: "1 Reis 16:16" },
      { question: "Que cidade Onri comprou e construiu, tornando-a capital de Israel?", answer: "Samaria", distractors: ["Siquém", "Tirsa"], reference: "1 Reis 16:24" },
      { question: "Quem foi o rei mais mau de Israel até então, segundo 1 Reis 16?", answer: "Acabe, filho de Onri", distractors: ["Jeroboão", "Zimri"], reference: "1 Reis 16:30" },
    ],
    17: [
      { question: "Quem foi o profeta de Tisbe, de Gileade?", answer: "Elias", distractors: ["Eliseu", "Miquéias"], reference: "1 Reis 17:1" },
      { question: "O que Elias anunciou ao rei Acabe em 1 Reis 17?", answer: "Que não choveria nem haveria orvalho nos próximos anos senão por sua palavra", distractors: ["Que Deus destruiria o reino de Israel", "Que uma praga de gafanhotos viria"], reference: "1 Reis 17:1" },
      { question: "Onde Deus mandou Elias se esconder após confrontar Acabe?", answer: "No ribeiro de Querite", distractors: ["No deserto do Sinai", "Na caverna do Carmelo"], reference: "1 Reis 17:2-3" },
      { question: "Quem alimentou Elias no ribeiro de Querite?", answer: "Os corvos", distractors: ["Um anjo", "Uma viúva"], reference: "1 Reis 17:4-6" },
      { question: "Para onde Deus enviou Elias quando o ribeiro secou?", answer: "A Sarepta, da Sidônia", distractors: ["Ao Egito", "A Beerseba"], reference: "1 Reis 17:8-9" },
      { question: "O que a viúva de Sarepta disse que iria fazer quando Elias a encontrou?", answer: "Preparar uma última refeição para ela e seu filho e depois morrer", distractors: ["Ir buscar água no poço distante", "Vender sua casa para comprar comida"], reference: "1 Reis 17:12" },
    ],
    18: [
      { question: "Quem Elias desafiou para o confronto no Monte Carmelo?", answer: "Os quatrocentos e cinquenta profetas de Baal", distractors: ["Os sacerdotes do templo de Betel", "Os profetas de Astarote"], reference: "1 Reis 18:19" },
      { question: "O que os profetas de Baal fizeram para tentar invocar seu deus?", answer: "Clamaram, dançaram e se cortaram com facas", distractors: ["Queimaram incenso e cantaram", "Sacrificaram crianças no altar"], reference: "1 Reis 18:26-28" },
      { question: "O que Elias fez antes de orar para que o fogo descesse?", answer: "Mandou encharcar o altar e a oferta com água três vezes", distractors: ["Jejuou por três dias", "Ungiu o altar com azeite"], reference: "1 Reis 18:33-35" },
      { question: "O que aconteceu quando Elias orou ao Senhor no Carmelo?", answer: "Fogo do Senhor desceu e consumiu o holocausto, a lenha e até a água", distractors: ["Chuva abundante caiu imediatamente", "A terra tremeu e um anjo apareceu"], reference: "1 Reis 18:38" },
      { question: "O que Elias fez com os profetas de Baal após o confronto?", answer: "Os matou no ribeiro de Quison", distractors: ["Os expulsou de Israel", "Os prendeu no palácio de Acabe"], reference: "1 Reis 18:40" },
      { question: "Quem Elias enviou sete vezes para ver se havia nuvem de chuva no mar?", answer: "Seu servo", distractors: ["Um dos filhos dos profetas", "Obadias"], reference: "1 Reis 18:43" },
    ],
    19: [
      { question: "Por que Elias fugiu para o deserto após o confronto no Carmelo?", answer: "Jezabel ameaçou matá-lo", distractors: ["Acabe ordenou sua execução", "O povo de Israel se voltou contra ele"], reference: "1 Reis 19:1-3" },
      { question: "O que Elias pediu a Deus no deserto, exausto?", answer: "Que tirasse sua vida", distractors: ["Que o transportasse ao céu", "Que lhe enviasse um substituto"], reference: "1 Reis 19:4" },
      { question: "Como um anjo acordou Elias no deserto e o alimentou?", answer: "Tocou-o e disse que se levantasse e comesse", distractors: ["Apareceu em visão e lhe trouxe maná", "Falou em voz alta e lhe deu água"], reference: "1 Reis 19:5-7" },
      { question: "Para qual montanha Elias foi após ser fortalecido pelo anjo?", answer: "Horebe, o monte de Deus", distractors: ["Sinai", "Carmelo"], reference: "1 Reis 19:8" },
      { question: "Como Deus se manifestou a Elias na caverna do Horebe?", answer: "Numa voz mansa e delicada, após vento forte, terremoto e fogo", distractors: ["Num fogo consumidor", "Num terremoto poderoso"], reference: "1 Reis 19:11-13" },
      { question: "Quem Deus mandou Elias ungir como profeta para sucedê-lo?", answer: "Eliseu, filho de Safate", distractors: ["Jeú, filho de Ninsi", "Hazael, da Síria"], reference: "1 Reis 19:16" },
    ],
    20: [
      { question: "Quem sitiou Samaria e exigiu prata, ouro e mulheres de Acabe?", answer: "Ben-Hadade, rei da Síria", distractors: ["Salmaneser, rei da Assíria", "Sisaque, rei do Egito"], reference: "1 Reis 20:1-3" },
      { question: "O que um profeta disse a Acabe antes da batalha contra Ben-Hadade?", answer: "Que Deus entregaria o exército sírio em suas mãos", distractors: ["Que Israel seria derrotado por seus pecados", "Que deveria fazer paz com Ben-Hadade"], reference: "1 Reis 20:13" },
      { question: "Como Acabe derrotou o exército sírio na primeira batalha?", answer: "Os jovens dos príncipes das províncias saíram primeiro e venceram", distractors: ["Com cavalaria pesada e carros de guerra", "Por uma emboscada no desfiladeiro"], reference: "1 Reis 20:14-21" },
      { question: "O que Ben-Hadade disse a Acabe para poupar sua vida após a derrota?", answer: "Que devolveria as cidades e faria mercados em Damasco", distractors: ["Que pagaria tributo anual a Israel", "Que se tornaria vassalo de Israel"], reference: "1 Reis 20:34" },
      { question: "Por que Deus ficou irado com Acabe após a batalha?", answer: "Porque Acabe deixou Ben-Hadade vivo quando devia matá-lo", distractors: ["Porque Acabe tomou o tesouro sírio para si", "Porque Acabe não construiu um altar de agradecimento"], reference: "1 Reis 20:42" },
      { question: "Como o profeta mostrou a Acabe que ele havia errado ao poupar Ben-Hadade?", answer: "Usando uma parábola do homem que perdeu um prisioneiro que lhe foi confiado", distractors: ["Mostrando sinais no céu", "Citando a lei de Moisés"], reference: "1 Reis 20:38-40" },
    ],
    21: [
      { question: "O que Acabe queria comprar de Nabote?", answer: "A vinha de Nabote que ficava perto do palácio", distractors: ["O campo de trigo de Nabote", "A casa de Nabote em Jezreel"], reference: "1 Reis 21:1-2" },
      { question: "Por que Nabote recusou vender a vinha a Acabe?", answer: "Porque era herança de seus pais e a lei proibia alienar a herança familiar", distractors: ["Porque não queria enriquecer o rei", "Porque a terra tinha valor sentimental"], reference: "1 Reis 21:3" },
      { question: "Como Jezabel conseguiu a vinha de Nabote para Acabe?", answer: "Acusando falsamente Nabote de blasfêmia, fazendo-o apedrejar até a morte", distractors: ["Pagando duas vezes o valor para convencer Nabote", "Forçando Nabote a vender sob ameaça de morte"], reference: "1 Reis 21:8-14" },
      { question: "Quem Deus enviou a Acabe após o assassinato de Nabote?", answer: "Elias", distractors: ["Eliseu", "Miquéias"], reference: "1 Reis 21:17-19" },
      { question: "O que Elias profetizou sobre Acabe no campo de Nabote?", answer: "Que onde os cães lamberam o sangue de Nabote, lamberia o de Acabe", distractors: ["Que Acabe morreria em batalha sem deixar herdeiros", "Que seu palácio seria destruído"], reference: "1 Reis 21:19" },
      { question: "Como Acabe reagiu à profecia de Elias?", answer: "Rasgou suas vestes, jejuou e andou abatido", distractors: ["Mandou prender Elias", "Ficou com raiva e planejou matá-lo"], reference: "1 Reis 21:27" },
    ],
    22: [
      { question: "Quem acompanhou Acabe na batalha de Ramote de Gileade?", answer: "Josafá, rei de Judá", distractors: ["Nadabe, rei de Israel", "Ela, rei de Israel"], reference: "1 Reis 22:2-4" },
      { question: "Quantos profetas consultaram Acabe e Josafá antes da batalha?", answer: "Quatrocentos profetas", distractors: ["Cem profetas", "Cinquenta profetas"], reference: "1 Reis 22:6" },
      { question: "Quem foi o único profeta que disse a verdade a Acabe sobre a batalha?", answer: "Miquéias, filho de Inlá", distractors: ["Elias", "Jeú, filho de Hanani"], reference: "1 Reis 22:8-9" },
      { question: "O que Miquéias profetizou sobre a batalha de Ramote de Gileade?", answer: "Que Acabe morreria e Israel se dispersaria como ovelhas sem pastor", distractors: ["Que Israel venceria com grandes baixas", "Que Acabe seria capturado mas depois libertado"], reference: "1 Reis 22:17-23" },
      { question: "Como Acabe morreu na batalha de Ramote de Gileade?", answer: "Foi ferido por uma flecha atirada ao acaso entre as juntas da armadura", distractors: ["Foi morto em combate direto com o rei sírio", "Caiu do cavalo e foi esmagado"], reference: "1 Reis 22:34" },
      { question: "O que aconteceu com the carro de Acabe após sua morte?", answer: "Cães lamberam o sangue e prostitutas se banharam nele em Samaria", distractors: ["Foi queimado no palácio", "Foi levado como troféu pelos sírios"], reference: "1 Reis 22:38" },
    ],
  },
};
