import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_ESTER: Record<string, Record<number, BankQuestion[]>> = {
    ester: {
        1: [
            { question: "Qual o nome do rei que reinou sobre 127 províncias, da Índia à Etiópia?", answer: "Assuero", distractors: ["Nabucodonosor", "Ciro"], reference: "Ester 1:1" },
            { question: "Onde se localizava o palácio real onde o rei deu o banquete?", answer: "Em Susã", distractors: ["Na Babilônia", "Em Persépolis"], reference: "Ester 1:2" },
            { question: "Por quantos dias durou o banquete dado a todo o povo em Susã?", answer: "Sete dias", distractors: ["Três dias", "Cento e oitenta dias"], reference: "Ester 1:5" },
            { question: "Qual o nome da rainha que recusou o convite do rei Assuero?", answer: "Vasti", distractors: ["Ester", "Jezabel"], reference: "Ester 1:9" },
            { question: "O que o rei queria que Vasti fizesse no banquete?", answer: "Viesse com a coroa real para mostrar sua beleza", distractors: ["Cantasse para os convidados", "Servisse vinho"], reference: "Ester 1:11" },
            { question: "Qual foi o conselho de Memucã sobre a recusa da rainha Vasti?", answer: "Que ela fosse deposta e sua dignidade dada a outra", distractors: ["Que fosse presa", "Que o rei pedisse desculpas"], reference: "Ester 1:19" },
            { question: "O que o decreto real enviado determinava após o caso de Vasti?", answer: "Que cada homem fosse senhor em sua casa", distractors: ["Proibição de banquetes", "Fim da monarquia"], reference: "Ester 1:22" },
        ],
        2: [
            { question: "Quem era o primo de Ester que a criou como filha?", answer: "Mordecai", distractors: ["Hamã", "Hegai"], reference: "Ester 2:7" },
            { question: "Qual era o nome hebraico de Ester?", answer: "Hadassa", distractors: ["Sara", "Débora"], reference: "Ester 2:7" },
            { question: "De qual tribo de Israel descendia Mordecai?", answer: "Benjamim", distractors: ["Judá", "Levi"], reference: "Ester 2:5" },
            { question: "Quem era o guarda das mulheres no palácio de Susã?", answer: "Hegai", distractors: ["Meumã", "Hataca"], reference: "Ester 2:3" },
            { question: "Quanto tempo as moças passavam por tratamentos de beleza?", answer: "Doze meses", distractors: ["Seis meses", "Três meses"], reference: "Ester 2:12" },
            { question: "O que Ester não revelou por ordem de Mordecai?", answer: "Seu povo e sua parentela", distractors: ["Seu verdadeiro nome", "Que sabia ler"], reference: "Ester 2:10" },
            { question: "Qual conspiração Mordecai descobriu à porta do rei?", answer: "Dois oficiais planejavam assassinar o rei", distractors: ["Um roubo ao tesouro", "Uma invasão grega"], reference: "Ester 2:21" },
        ],
        3: [
            { question: "Quem o rei Assuero exaltou acima de todos os príncipes?", answer: "Hamã, o agagita", distractors: ["Mordecai", "Memucã"], reference: "Ester 3:1" },
            { question: "Por que Hamã ficou furioso com Mordecai?", answer: "Porque Mordecai não se inclinava perante ele", distractors: ["Dívida de dinheiro", "Disputa por terras"], reference: "Ester 3:2" },
            { question: "Qual era the origem de Hamã mencionada no texto?", answer: "Agagita", distractors: ["Amalequita", "Babilônio"], reference: "Ester 3:1" },
            { question: "O que Hamã planejou fazer como vingança?", answer: "Destruir todos os judeus do reino", distractors: ["Prender Mordecai", "Expulsar Mordecai"], reference: "Ester 3:6" },
            { question: "Como foi escolhido o dia para a destruição dos judeus?", answer: "Lançando o Pur (sorte)", distractors: ["Consultando astros", "Escolha do rei"], reference: "Ester 3:7" },
            { question: "Quanto Hamã prometeu pagar para o extermínio ser assinado?", answer: "Dez mil talentos de prata", distractors: ["Cem mil moedas", "Cinco mil talentos"], reference: "Ester 3:9" },
            { question: "Para qual dia foi marcado o extermínio dos judeus?", answer: "Dia 13 do 12º mês (Adar)", distractors: ["Dia 1 de Janeiro", "Dia 7 do 7º mês"], reference: "Ester 3:13" },
        ],
        4: [
            { question: "O que Mordecai fez ao saber do decreto de Hamã?", answer: "Vestiu-se de saco e cinza e clamou", distractors: ["Fugiu de Susã", "Foi falar com o rei"], reference: "Ester 4:1" },
            { question: "Por que Ester temia ir falar com o rei sem ser chamada?", answer: "Havia pena de morte para quem o fizesse", distractors: ["O rei estava doente", "Ela estava presa"], reference: "Ester 4:11" },
            { question: "Qual a famosa pergunta de Mordecai a Ester sobre silêncio?", answer: "Quem sabe se para tal tempo como este chegaste?", distractors: ["Tu és uma rainha ou uma judia?", "Deus te perdoará se fugires?"], reference: "Ester 4:14" },
            { question: "O que Ester pediu que os judeus fizessem por ela?", answer: "Jejuassem por três dias e três noites", distractors: ["Fugissem para Uz", "Orassem no templo"], reference: "Ester 4:16" },
            { question: "Qual frase Ester disse ao decidir ir ao rei correndo risco?", answer: "Se perecer, pereci", distractors: ["Deus é comigo", "Justiça para o meu povo"], reference: "Ester 4:16" },
            { question: "Quem mediava a comunicação entre Ester e Mordecai?", answer: "Hataca", distractors: ["Hegai", "Meumã"], reference: "Ester 4:5" },
            { question: "Há quanto tempo Ester não era chamada pelo rei?", answer: "Trinta dias", distractors: ["Três meses", "Um ano"], reference: "Ester 4:11" },
        ],
        5: [
            { question: "O que o rei estendeu para Ester no pátio interior?", answer: "O cetro de ouro", distractors: ["Sua mão", "Um anel"], reference: "Ester 5:2" },
            { question: "Até quanto do reino o rei prometeu dar a Ester?", answer: "Até a metade do reino", distractors: ["Todo o tesouro", "Dez províncias"], reference: "Ester 5:3" },
            { question: "Qual foi o primeiro pedido de Ester ao rei?", answer: "Que o rei e Hamã viessem a um banquete", distractors: ["Revogação do decreto", "Prisão de Hamã"], reference: "Ester 5:4" },
            { question: "O que Hamã mandou construir por sugestão de sua mulher?", answer: "Uma forca de cinquenta côvados", distractors: ["Uma estátua", "Um novo palácio"], reference: "Ester 5:14" },
            { question: "Como se chamava a mulher de Hamã?", answer: "Zeres", distractors: ["Vasti", "Dalila"], reference: "Ester 5:10" },
            { question: "Por que a alegria de Hamã se tornou em ira ao sair?", answer: "Viu Mordecai à porta e este não se levantou", distractors: ["Ester o ignorou", "O rei o tratou mal"], reference: "Ester 5:9" },
            { question: "O que os amigos de Hamã sugeriram que ele pedisse ao rei?", answer: "Que enforcassem Mordecai nela", distractors: ["O cargo de Mordecai", "O exílio de Mordecai"], reference: "Ester 5:14" },
        ],
        6: [
            { question: "O que o rei fez na noite em que perdeu o sono?", answer: "Mandou ler o livro das crônicas", distractors: ["Ouviu harpa", "Saiu para caçar"], reference: "Ester 6:1" },
            { question: "O que o rei descobriu no livro que não fora recompensado?", answer: "Mordecai denunciara planos de assassinato", distractors: ["Hamã era um traidor", "Vasti queria voltar"], reference: "Ester 6:2" },
            { question: "O que Hamã viera pedir ao rei naquela manhã?", answer: "Para enforcar Mordecai na sua forca", distractors: ["Para ser rei", "Para cobrar impostos"], reference: "Ester 6:4" },
            { question: "Qual pergunta o rei fez a Hamã ao vê-lo?", answer: "Que se faria ao homem a quem o rei deseja honrar?", distractors: ["Quem deve ser enforcado?", "Onde está Mordecai?"], reference: "Ester 6:6" },
            { question: "O que Hamã sugeriu como honra, pensando em si mesmo?", answer: "Vestes reais, cavalo e coroa", distractors: ["Ouro e moedas", "Um novo título"], reference: "Ester 6:8" },
            { question: "A quem o rei mandou Hamã prestar essa honra?", answer: "A Mordecai, o judeu", distractors: ["A Hegai", "A Harbona"], reference: "Ester 6:10" },
            { question: "O que Hamã teve de fazer pelas ruas com Mordecai?", answer: "Passeá-lo a cavalo proclamando honras", distractors: ["Lavar seus pés", "Dar-lhe comida"], reference: "Ester 6:11" },
        ],
        7: [
            { question: "O que Ester pediu ao rei no segundo banquete?", answer: "Sua vida e a vida do seu povo", distractors: ["A cabeça de Hamã", "O cargo de Mordecai"], reference: "Ester 7:3" },
            { question: "Quem Ester denunciou como o inimigo?", answer: "Este mau Hamã", distractors: ["Vasti", "Os caldeus"], reference: "Ester 7:6" },
            { question: "Como o rei reagiu à denúncia de Ester?", answer: "Levantou-se furioso e foi ao jardim", distractors: ["Mandou Ester prender", "Riu de tudo"], reference: "Ester 7:7" },
            { question: "O que Hamã fez enquanto o rei estava no jardim?", answer: "Prostrou-se sobre leito de Ester por sua vida", distractors: ["Fugiu do palácio", "Matou Mordecai"], reference: "Ester 7:8" },
            { question: "O que o rei disse ao ver Hamã sobre o leito de Ester?", answer: "Quereria ele também forçar a rainha perante mim?", distractors: ["Leva este homem preso", "Estás perdoado"], reference: "Ester 7:8" },
            { question: "Qual foi o fim de Hamã?", answer: "Enforcado na forca que preparara para Mordecai", distractors: ["Decapitado", "Exilado"], reference: "Ester 7:10" },
            { question: "Quem avisou o rei sobre a forca que Hamã fizera?", answer: "Harbona, um dos oficiais", distractors: ["Mordecai", "Ester"], reference: "Ester 7:9" },
        ],
        8: [
            { question: "O que o rei deu a Ester após a morte de Hamã?", answer: "A casa e bens de Hamã", distractors: ["Um novo reino", "O anel de ouro"], reference: "Ester 8:1" },
            { question: "O que o rei deu a Mordecai?", answer: "O seu anel de sinete", distractors: ["O trono de Vasti", "Toda a prata"], reference: "Ester 8:2" },
            { question: "Por que o primeiro decreto de Hamã não podia ser revogado?", answer: "A escrita em nome do rei selada não se pode revogar", distractors: ["Deus não permitia", "O rei perdeu o selo"], reference: "Ester 8:8" },
            { question: "Qual foi o novo decreto do rei para os judeus?", answer: "Direito de se reunirem e se defenderem", distractors: ["Fugirem para Judá", "Esconderem o tesouro"], reference: "Ester 8:11" },
            { question: "Como os judeus reagiram ao novo decreto?", answer: "Houve luz, alegria, gozo e honra", distractors: ["Ficaram tristes", "Fugiram todos"], reference: "Ester 8:16" },
            { question: "Muitos povos se tornaram judeus por quê?", answer: "Porque o temor dos judeus caíra sobre eles", distractors: ["Por amor a Ester", "Por medo do rei"], reference: "Ester 8:17" },
            { question: "Como as cartas do novo decreto foram enviadas?", answer: "Por correios em cavalos e dromedários", distractors: ["Por navios", "Por pombos"], reference: "Ester 8:14" },
        ],
        9: [
            { question: "O que aconteceu no dia 13 de Adar?", answer: "Os judeus dominaram sobre os inimigos", distractors: ["Massacre dos judeus", "Festa Nacional Persa"], reference: "Ester 9:1" },
            { question: "Quantos homens os judeus mataram em Susã no primeiro dia?", answer: "Quinhentos homens", distractors: ["Cem", "Mil"], reference: "Ester 9:6" },
            { question: "O que aconteceu com os dez filhos de Hamã?", answer: "Foram mortos e enforcados", distractors: ["Foram exilados", "Tornaram-se judeus"], reference: "Ester 9:14" },
            { question: "Os judeus pegaram os despojos dos inimigos?", answer: "Não estenderam a mão ao despojo", distractors: ["Sim, ficaram ricos", "Apenas o gado"], reference: "Ester 9:10" },
            { question: "Qual o nome da festa instituída pelos judeus?", answer: "Purim", distractors: ["Páscoa", "Pentecostes"], reference: "Ester 9:26" },
            { question: "O que significa o nome Purim?", answer: "Vem de Pur, que significa sorte", distractors: ["Vitória de Deus", "Luz eterna"], reference: "Ester 9:26" },
            { question: "Como Purim deve ser celebrado?", answer: "Com alegria, banquetes e presentes aos pobres", distractors: ["Jejum total", "Sacrifício de gado"], reference: "Ester 9:22" },
        ],
        10: [
            { question: "O que o rei Assuero impôs sobre a terra e ilhas?", answer: "Tributo", distractors: ["Paz absoluta", "Leis gregas"], reference: "Ester 10:1" },
            { question: "Qual era a posição de Mordecai no reino final?", answer: "O segundo depois do rei Assuero", distractors: ["Terceiro príncipe", "Rei de Judá"], reference: "Ester 10:3" },
            { question: "Onde foram escritas as grandezas de Mordecai?", answer: "Nas Crônicas dos reis da Média e Pérsia", distractors: ["Na Torah", "Em placas de ouro"], reference: "Ester 10:2" },
            { question: "Por que Mordecai era aceito pelos seus irmãos judeus?", answer: "Buscava o bem do povo e paz para a linhagem", distractors: ["Era o mais rico", "Venceu guerras"], reference: "Ester 10:3" },
            { question: "Quantos versículos tem o capítulo 10 de Ester?", answer: "Três versículos", distractors: ["Cinco", "Dez"], reference: "Ester 10:1-3" },
            { question: "O rei Assuero dominava sobre as ilhas do mar?", answer: "Sim, impôs tributo sobre elas", distractors: ["Não", "Apenas sobre a terra"], reference: "Ester 10:1" },
            { question: "Como era a relação de Mordecai com a linhagem judeia?", answer: "Falava de paz para toda a sua linhagem", distractors: ["Dava ordens severas", "Era desconhecido"], reference: "Ester 10:3" },
        ],
    },
};
