import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_ESDRAS: Record<string, Record<number, BankQuestion[]>> = {
  "esdras": {
    1: [
      { question: "Qual rei persa emitiu o decreto permitindo que os judeus voltassem a Jerusalém?", answer: "Ciro, rei da Pérsia", distractors: ["Dario, rei da Pérsia", "Artaxerxes, rei da Pérsia"] },
      { question: "O que o decreto de Ciro ordenava que os judeus fizessem?", answer: "Voltarem a Jerusalém e reconstruírem o templo do Senhor", distractors: ["Pagarem tributo ao tesouro persa para financiar a reconstrução", "Enviarem representantes a Babilônia para planejar o retorno"] },
      { question: "O que o texto diz que moveu Ciro a emitir o decreto?", answer: "O Senhor despertou o espírito de Ciro", distractors: ["A influência de Daniel na corte persa", "Uma visão que Ciro teve durante a noite"] },
      { question: "O que Ciro devolveu aos judeus que retornavam?", answer: "Os utensílios do templo que Nabucodonosor havia levado de Jerusalém", distractors: ["Ouro e prata do tesouro real da Pérsia", "Terras e propriedades que haviam sido confiscadas"] },
      { question: "A quem Ciro entregou os utensílios do templo?", answer: "A Sesbassar, príncipe de Judá", distractors: ["A Zorobabel, governador de Judá", "A Josué, o sumo sacerdote"] },
      { question: "Quantos utensílios de ouro e prata foram devolvidos no total?", answer: "Cinco mil e quatrocentos", distractors: ["Dois mil e quatrocentos", "Dez mil utensílios"] },
    ],
    2: [
      { question: "Quem liderou o primeiro grupo de exilados que retornou a Jerusalém?", answer: "Zorobabel e Jesua", distractors: ["Esdras e Neemias", "Sesbassar e Zorobabel"] },
      { question: "Quantas pessoas retornaram na primeira leva de exilados segundo Esdras 2?", answer: "Quarenta e dois mil trezentos e sessenta", distractors: ["Vinte mil e duzentos", "Cem mil exilados ao todo"] },
      { question: "O que os cantores levitas faziam no retorno segundo Esdras 2?", answer: "Serviriam no templo como cantores", distractors: ["Ensinavam a Lei às famílias durante a jornada", "Registravam os nomes de todos que retornavam"] },
      { question: "Quais eram os 'netineus' mencionados em Esdras 2?", answer: "Servos do templo dados por Davi e pelos príncipes para assistir os levitas", distractors: ["Sacerdotes de segunda categoria que serviam nos portões", "Estrangeiros convertidos que acompanhavam os exilados"] },
      { question: "O que aconteceu com os sacerdotes que não podiam provar sua linhagem?", answer: "Foram excluídos do sacerdócio como impuros até que um sacerdote consultasse o Urim e Tumim", distractors: ["Foram aceitos provisoriamente até a reconstrução do templo", "Foram designados como levitas em vez de sacerdotes"] },
      { question: "O que os líderes das famílias ofertaram voluntariamente para o templo ao chegarem a Jerusalém?", answer: "Sessenta e um mil dracmas de ouro, cinco mil minas de prata e cem vestes sacerdotais", distractors: ["Mil talentos de prata e quinhentos de ouro", "Materiais de construção e ferramentas para o templo"] },
    ],
    3: [
      { question: "O que Jesua e Zorobabel reconstruíram primeiro ao chegarem a Jerusalém?", answer: "O altar de holocaustos", distractors: ["Os fundamentos do templo", "Os muros da cidade"] },
      { question: "Por que o povo reconstruiu o altar mesmo com medo dos povos vizinhos?", answer: "Para oferecer holocaustos ao Senhor conforme estava escrito na lei de Moisés", distractors: ["Para mostrar que não tinham medo dos inimigos", "Por ordem de Ciro que exigia culto regular ao Deus de Israel"] },
      { question: "No segundo ano do retorno, o que Zorobabel e Jesua iniciaram?", answer: "A reconstrução do templo, assentando os fundamentos", distractors: ["A reconstrução dos muros da cidade", "A distribuição das terras entre as famílias retornadas"] },
      { question: "O que os levitas faziam quando os fundamentos do templo eram assentados?", answer: "Cantavam louvores ao Senhor: 'Porque ele é bom, porque a sua misericórdia dura para sempre'", distractors: ["Tocavam trombetas e saltérios em procissão", "Liam a Lei de Moisés para o povo reunido"] },
      { question: "Como o povo reagiu ao lançamento dos fundamentos do templo?", answer: "Alguns gritavam de alegria e outros choravam ao lembrar do primeiro templo", distractors: ["Todo o povo gritou de alegria com uma só voz", "Silenciaram em reverência diante da obra sagrada"] },
      { question: "O que Esdras 3 diz sobre os sacerdotes durante a cerimônia dos fundamentos?", answer: "Estavam com suas vestes, trombetas, e os levitas com címbalos para louvar ao Senhor", distractors: ["Ofereciam sacrifícios contínuos por sete dias", "Oravam em silêncio enquanto os trabalhadores construíam"] },
    ],
    4: [
      { question: "Quem tentou impedir a reconstrução do templo em Esdras 4?", answer: "Os adversários de Judá e Benjamim, os povos da terra", distractors: ["O governador persa da região Trans-Eufrates", "Os samaritanos liderados por seus príncipes"] },
      { question: "O que os adversários ofereceram a Zorobabel para participar da construção?", answer: "Ajuda na construção, dizendo que também buscavam ao mesmo Deus", distractors: ["Materiais de construção e trabalhadores qualificados", "Proteção militar contra outros inimigos da região"] },
      { question: "Por que Zorobabel recusou a ajuda dos adversários?", answer: "Porque só eles, com Ciro, tinham autoridade para construir o templo ao Senhor", distractors: ["Porque a lei proibia trabalhar com estrangeiros no templo", "Porque desconfiava das intenções dos povos vizinhos"] },
      { question: "O que os adversários fizeram após serem recusados?", answer: "Contrataram conselheiros para frustrar o plano dos judeus e escreveram acusações aos reis persas", distractors: ["Atacaram militarmente os trabalhadores da construção", "Enviaram petições ao rei Ciro pedindo para cancelar o decreto"] },
      { question: "Qual rei persa ordenou que a reconstrução de Jerusalém fosse suspensa?", answer: "Artaxerxes", distractors: ["Cambises", "Dario"] },
      { question: "Por quanto tempo a construção do templo ficou paralisada?", answer: "Até o segundo ano do reinado de Dario, rei da Pérsia", distractors: ["Até o reinado de Ciro terminar", "Por vinte anos, até Neemias chegar"] },
    ],
    5: [
      { question: "Quais profetas exortaram o povo a reiniciar a construção do templo?", answer: "Ageu e Zacarias", distractors: ["Malaquias e Joel", "Isaías e Jeremias"] },
      { question: "Quem se levantou para reiniciar a construção após a palavra dos profetas?", answer: "Zorobabel e Jesua", distractors: ["Esdras e Neemias", "Os sacerdotes e levitas juntos"] },
      { question: "Quem foi o governador persa que foi ao local da construção perguntar sobre ela?", answer: "Tatenai, governador da região além do rio", distractors: ["Réum, o secretário real", "Sanbalate, o horonita"] },
      { question: "O que os líderes judeus responderam quando Tatenai perguntou quem autorizou a construção?", answer: "Que Ciro havia emitido um decreto autorizando a reconstrução", distractors: ["Que estavam apenas reparando as ruínas e não construindo algo novo", "Que tinham autorização do governador anterior da região"] },
      { question: "O que Tatenai pediu ao rei Dario?", answer: "Que verificasse nos arquivos reais se havia realmente um decreto de Ciro", distractors: ["Que mandasse um inspetor para avaliar a legalidade da construção", "Que paralisasse a obra até uma decisão oficial ser tomada"] },
      { question: "Como os líderes judeus são descritos quando Tatenai perguntou sobre a construção?", answer: "Continuaram construindo enquanto a questão era investigada", distractors: ["Pararam voluntariamente enquanto aguardavam a resposta real", "Mostraram a Tatenai o decreto original de Ciro"] },
    ],
    6: [
      { question: "Onde foi encontrado o decreto de Ciro nos arquivos persas?", answer: "Em Ecbátana, na cidadela", distractors: ["Em Susa, no palácio real", "Em Babilônia, na casa dos tesouros"] },
      { question: "O que o decreto de Ciro especificava sobre o templo?", answer: "As medidas: sessenta côvados de altura e sessenta de largura, com três fiadas de pedra e uma de madeira", distractors: ["Os materiais: ouro, prata e cedro do Líbano apenas", "O prazo: o templo deveria ser concluído em dez anos"] },
      { question: "O que Dario ordenou a Tatenai após encontrar o decreto de Ciro?", answer: "Que não interferisse na obra e ainda ajudasse com recursos do erário real", distractors: ["Que supervisionasse a construção para garantir que seguia o decreto", "Que enviasse trabalhadores persas para acelerar a construção"] },
      { question: "Quando o templo foi concluído segundo Esdras 6?", answer: "No sexto ano do reinado de Dario", distractors: ["No décimo ano do reinado de Dario", "No terceiro ano do reinado de Artaxerxes"] },
      { question: "Com que o povo celebrou a conclusão do templo?", answer: "Com alegria, oferecendo bois, carneiros, cordeiros e bodes pelo pecado de todo Israel", distractors: ["Com sete dias de festa e música", "Com a leitura de toda a lei de Moisés"] },
      { question: "Que festa os judeus celebraram logo após a dedicação do templo?", answer: "A Páscoa", distractors: ["O Pentecostes", "A Festa dos Tabernáculos"] },
    ],
    7: [
      { question: "Quem era Esdras segundo a genealogia de Esdras 7?", answer: "Escriba habilidoso na lei de Moisés, descendente de Arão pelo sumo sacerdote Seraiah", distractors: ["Um profeta descendente de Samuel", "Um levita descendente de Merari"] },
      { question: "O que o rei Artaxerxes concedeu a Esdras?", answer: "Tudo que pediu, pois a mão do Senhor estava sobre ele", distractors: ["Permissão para voltar a Jerusalém com ouro para o templo", "Autoridade de governador sobre toda Judá"] },
      { question: "O que Esdras tinha determinado em seu coração fazer?", answer: "Estudar a lei do Senhor, praticá-la e ensinar seus estatutos em Israel", distractors: ["Reconstruir os muros de Jerusalém que estavam em ruínas", "Purificar o sacerdócio dos casamentos mistos"] },
      { question: "O que a carta de Artaxerxes a Esdras permitia?", answer: "Que todo israelita em seu reino que quisesse pudesse voltar com Esdras", distractors: ["Apenas que Esdras e os sacerdotes retornassem", "Que os judeus voltassem somente se pagassem um tributo especial"] },
      { question: "Que recursos Artaxerxes colocou à disposição de Esdras para o templo?", answer: "Prata e ouro do rei e das ofertas voluntárias, mais autoridade para requisitar do erário da região", distractors: ["Materiais de construção e trabalhadores especializados", "Um contingente de soldados para proteger a comitiva"] },
      { question: "O que Esdras disse ao receber a carta do rei?", answer: "Louvou ao Senhor, Deus de seus pais, que pôs tal coisa no coração do rei", distractors: ["Organizou imediatamente a lista dos que retornariam", "Convocou os líderes judeus para planejar a viagem"] },
    ],
    8: [
      { question: "O que Esdras percebeu ao reunir o povo para a viagem?", answer: "Que não havia levitas entre o grupo", distractors: ["Que faltavam sacerdotes para servir no templo", "Que havia poucos homens em idade militar para proteger a caravana"] },
      { question: "O que Esdras fez para ter levitas na caravana?", answer: "Enviou mensageiros a Idobo pedindo que enviasse ministros para o templo", distractors: ["Convocou voluntários entre as famílias dispostas a servir", "Esperou até que levitas suficientes se apresentassem"] },
      { question: "Por que Esdras se envergonhou de pedir ao rei escolta de soldados?", answer: "Porque havia dito ao rei que a mão de Deus era favorável a todos que o buscavam", distractors: ["Porque a lei judaica proibia usar soldados gentios como escolta", "Porque confiava que os sacerdotes eram proteção suficiente"] },
      { question: "O que Esdras fez antes de partir, em vez de pedir escolta militar?", answer: "Proclamou um jejum para que humilhassem a si mesmos e pedissem a Deus boa viagem", distractors: ["Orou sozinho por três dias no templo de Babilônia", "Consultou os profetas Ageu e Zacarias sobre a viagem"] },
      { question: "Quanto ouro e prata Esdras levou para Jerusalém?", answer: "Seiscentos e cinquenta talentos de prata, utensílios de prata, cem talentos de ouro e outros presentes", distractors: ["Mil talentos de prata e cinquenta de ouro", "Todo o tesouro do templo que ainda estava na Pérsia"] },
      { question: "Quanto tempo durou a viagem de Babilônia a Jerusalém?", answer: "Quatro meses", distractors: ["Dois meses", "Seis meses"] },
    ],
    9: [
      { question: "Qual grave pecado os líderes reportaram a Esdras logo após sua chegada?", answer: "Que israelitas, sacerdotes e levitas haviam se casado com mulheres das nações pagãs", distractors: ["Que muitos haviam voltado à idolatria durante o exílio", "Que os dízimos e ofertas do templo não estavam sendo pagos"] },
      { question: "O que Esdras fez ao ouvir da mistura com os povos pagãos?", answer: "Rasgou suas vestes e manto, arrancou cabelos da cabeça e barba e ficou assentado desolado", distractors: ["Convocou imediatamente uma assembleia para resolver o problema", "Foi ao templo e ficou em oração até o entardecer"] },
      { question: "Quando Esdras orou diante do templo, quem se juntou a ele?", answer: "Todo aquele que temia as palavras do Deus de Israel por causa da infidelidade dos exilados", distractors: ["Os sacerdotes e levitas que haviam se casado corretamente", "Os líderes e anciãos que haviam denunciado o pecado"] },
      { question: "O que Esdras confessou na sua oração em Esdras 9?", answer: "As iniquidades de Israel desde os antepassados, reconhecendo que mereciam o castigo que tiveram", distractors: ["Apenas o pecado dos casamentos mistos dos que retornaram", "Que o povo havia falhado em manter as festas e os sacrifícios"] },
      { question: "O que Esdras reconheceu que Deus havia feito misericordiosamente?", answer: "Que deixou um remanescente, deu estabilidade no lugar santo e levantou seus olhos", distractors: ["Que acabou o exílio mais cedo do que mereciam", "Que protegeu Israel de ser completamente destruído pelos assírios"] },
      { question: "O que Esdras temia ao final de sua oração?", answer: "Que Deus os destruísse completamente sem deixar remanescente por causa dos pecados presentes", distractors: ["Que os reis persas revogassem o decreto de Ciro", "Que os povos vizinhos atacassem antes que os muros fossem reconstruídos"] },
    ],
    10: [
      { question: "Quem se aproximou de Esdras enquanto ele orava e chorava diante do templo?", answer: "Uma grande assembleia de homens, mulheres e crianças do povo de Israel que também choravam", distractors: ["Os anciãos e líderes das famílias", "Apenas os sacerdotes e levitas"] },
      { question: "O que Secanias disse a Esdras em nome do povo?", answer: "Que fariam aliança com Deus para mandar embora todas as mulheres estrangeiras e seus filhos", distractors: ["Que o povo prometia não se casar mais com estrangeiras dali em diante", "Que pediriam perdão às famílias das mulheres enviadas embora"] },
      { question: "O que Esdras pediu aos líderes e sacerdotes que fizessem?", answer: "Que jurassem que agiriam conforme a proposta de Secanias", distractors: ["Que fizessem uma lista completa de todos os casamentos mistos", "Que consultassem primeiro o rei da Pérsia sobre o assunto"] },
      { question: "Como o povo foi convocado para a assembleia em Jerusalém?", answer: "Por proclamação que todo exilado deveria se reunir em Jerusalém em três dias, sob pena de perder seus bens", distractors: ["Por cartas enviadas a cada chefe de família nas cidades de Judá", "Por trombetas tocadas nos portões de todas as cidades"] },
      { question: "O que o povo fez na assembleia diante do templo?", answer: "Estremeceu por causa do assunto e da chuva forte, e concordou em mandar as mulheres estrangeiras embora", distractors: ["Prometeu por juramento nunca mais se casar com estrangeiras", "Eleitos representantes de cada família para resolver os casos individualmente"] },
      { question: "Quanto tempo levou para examinar todos os casos de casamentos mistos?", answer: "Três meses, do primeiro ao primeiro do mês seguinte", distractors: ["Sete dias, durante a Festa dos Tabernáculos", "Um ano completo para verificar todos os registros"] },
    ],
  },
};
