import { BankQuestion } from "./quiz-data";

export const QUIZ_BANK_1CRON: Record<string, Record<number, BankQuestion[]>> = {
  "1cronicas": {
    1: [
      { question: "Com quem começa a genealogia de 1 Crônicas 1?", answer: "Adão", distractors: ["Noé", "Abraão"], reference: "1 Crônicas 1:1" },
      { question: "Quem eram os filhos de Noé listados em 1 Crônicas 1?", answer: "Sem, Cam e Jafé", distractors: ["Sem, Jafé e Canaã", "Cam, Jafé e Arfaxade"], reference: "1 Crônicas 1:4" },
      { question: "Qual descendente de Sem foi pai de Abraão?", answer: "Tera", distractors: ["Naor", "Arfaxade"], reference: "1 Crônicas 1:26-27" },
      { question: "Quem foram os filhos de Abraão listados em 1 Crônicas 1?", answer: "Isaque e Ismael", distractors: ["Isaque e Jacó", "Ismael e Quetura"], reference: "1 Crônicas 1:28" },
      { question: "Quais foram os gêmeos filhos de Isaque?", answer: "Esaú e Israel (Jacó)", distractors: ["Esaú e Edom", "Jacó e Labão"], reference: "1 Crônicas 1:34" },
      { question: "Quais reis de Edom são listados em 1 Crônicas 1 antes de haver rei em Israel?", answer: "Oito reis de Edom", distractors: ["Cinco reis de Edom", "Doze reis de Edom"], reference: "1 Crônicas 1:43-50" },
    ],
    2: [
      { question: "Quantos filhos de Israel (Jacó) são listados em 1 Crônicas 2?", answer: "Doze", distractors: ["Dez", "Treze"], reference: "1 Crônicas 2:1-2" },
      { question: "De qual tribo descendia Davi segundo a genealogia de 1 Crônicas 2?", answer: "Judá", distractors: ["Benjamim", "Efraim"], reference: "1 Crônicas 2:3-15" },
      { question: "Quem foi o pai de Davi segundo 1 Crônicas 2?", answer: "Jessé", distractors: ["Boaz", "Obed"], reference: "1 Crônicas 2:13-15" },
      { question: "Quem foi a mãe de Salomão segundo 1 Crônicas 2?", answer: "Bate-Seba, filha de Amiél", distractors: ["Abigail", "Mical"], reference: "1 Crônicas 3:5" },
      { question: "Quem era Er, o primogênito de Judá, segundo 1 Crônicas 2?", answer: "Foi mau aos olhos do Senhor e ele o matou", distractors: ["Morreu em batalha contra os cananeus", "Partiu para o Egito e nunca voltou"], reference: "1 Crônicas 2:3" },
      { question: "Quem foi Calebe, filho de Heçrom, em relação à genealogia de Judá?", answer: "Um dos antepassados dos clãs de Judá", distractors: ["O fundador da cidade de Hebrom", "O pai de Boaz"], reference: "1 Crônicas 2:18" },
    ],
    3: [
      { question: "Quantos filhos Davi teve em Hebrom?", answer: "Seis", distractors: ["Quatro", "Oito"], reference: "1 Crônicas 3:1-4" },
      { question: "Qual foi o primeiro filho de Davi nascido em Hebrom?", answer: "Amnom, de Ainoã, a jezreelita", distractors: ["Absalão, de Maaca", "Adonias, de Agite"], reference: "1 Crônicas 3:1" },
      { question: "Qual filho de Davi foi seu sucessor no trono?", answer: "Salomão", distractors: ["Adonias", "Absalão"], reference: "1 Crônicas 3:5" },
      { question: "Quantos filhos Salomão teve listados em 1 Crônicas 3?", answer: "Um filho principal listado: Roboão", distractors: ["Três filhos", "Sete filhos"], reference: "1 Crônicas 3:10" },
      { question: "Quem foi Zorobabel segundo a genealogia de 1 Crônicas 3?", answer: "Descendente de Davi que liderou o retorno do exílio", distractors: ["Filho de Salomão que dividiu o reino", "Sacerdote no tempo de Esdras"], reference: "1 Crônicas 3:19" },
      { question: "Qual rei de Judá foi levado ao exílio na Babilônia segundo 1 Crônicas 3?", answer: "Jeconias (Joaquim)", distractors: ["Zedequias", "Jeoaquim"], reference: "1 Crônicas 3:16" },
    ],
    4: [
      { question: "Qual oração famosa está registrada em 1 Crônicas 4?", answer: "A oração de Jabez pedindo bênção e ampliação de território", distractors: ["A oração de Calebe pela cidade de Hebrom", "A oração de Judá pela vitória sobre Canaã"], reference: "1 Crônicas 4:9-10" },
      { question: "O que Jabez pediu a Deus em sua oração?", answer: "Que o abençoasse, ampliasse seus limites, que sua mão estivesse com ele e o guardasse do mal", distractors: ["Que lhe desse sabedoria para governar seu povo", "Que o protegesse de seus inimigos e lhe desse filhos"], reference: "1 Crônicas 4:10" },
      { question: "Como Jabez era mais honrado que seus irmãos?", answer: "O texto diz que era mais ilustre que seus irmãos", distractors: ["Era o mais corajoso guerreiro de seu clã", "Era o mais sábio entre os líderes de Judá"], reference: "1 Crônicas 4:9" },
      { question: "Por que Jabez recebeu esse nome?", answer: "Porque sua mãe o gerou com dor", distractors: ["Porque nasceu durante uma guerra", "Porque foi dedicado ao Senhor desde o nascimento"], reference: "1 Crônicas 4:9" },
      { question: "Quais clãs de Judá trabalhavam como artesãos e oleiros segundo 1 Crônicas 4?", answer: "Os de Reca e os oleiros que habitavam em Netaim e Guederas", distractors: ["Os de Belém e os de Hebrom", "Os de Tecoa e os de Zanoá"], reference: "1 Crônicas 4:12,23" },
      { question: "Quais descendentes de Simeão conquistaram terras adicionais segundo 1 Crônicas 4?", answer: "Homens de Simeão que foram ao monte Seir e derrotaram os amalequitas restantes", distractors: ["Guerreiros de Simeão que tomaram cidades dos filisteus", "Clãs de Simeão que colonizaram o Neguebe"], reference: "1 Crônicas 4:42-43" },
    ],
    5: [
      { question: "Por que Rúben perdeu o direito de primogenitura segundo 1 Crônicas 5?", answer: "Por ter contaminado o leito de seu pai", distractors: ["Por ter vendido José como escravo", "Por ter se casado com uma cananeia"], reference: "1 Crônicas 5:1" },
      { question: "A quem foi transferido o direito de primogenitura de Rúben?", answer: "A José", distractors: ["A Judá", "A Levi"], reference: "1 Crônicas 5:1-2" },
      { question: "Quem foram os guerreiros da tribo de Rúben que guerrearam contra os hagarenos?", answer: "Valentes guerreiros que contavam com quarenta e quatro mil e setecentos e sessenta", distractors: ["Cinquenta mil guerreiros com armadura completa", "Trinta mil soldados de elite"], reference: "1 Crônicas 5:18-19" },
      { question: "Como os rubenitas venceram os hagarenos segundo 1 Crônicas 5?", answer: "Clamaram a Deus durante a batalha e foram ouvidos porque confiaram nele", distractors: ["Por superioridade numérica e cavalaria", "Por uma estratégia de emboscada no deserto"], reference: "1 Crônicas 5:20" },
      { question: "Por que as tribos de Rúben, Gade e a meia tribo de Manassés foram exiladas?", answer: "Por terem se prostituído atrás dos deuses das nações", distractors: ["Por terem feito aliança com os reis da Assíria", "Por terem abandonado o tabernáculo do Senhor"], reference: "1 Crônicas 5:25" },
      { question: "Qual rei assírio levou as tribos transjordânicas ao exílio?", answer: "Tiglate-Pileser, rei da Assíria", distractors: ["Salmaneser", "Senaqueribe"], reference: "1 Crônicas 5:26" },
    ],
    6: [
      { question: "De qual filho de Levi descendia a linhagem sacerdotal?", answer: "Coate", distractors: ["Gérsom", "Merari"], reference: "1 Crônicas 6:1-3" },
      { question: "Qual profeta famoso era descendente de Levi pela linhagem de Coate?", answer: "Samuel", distractors: ["Isaías", "Jeremias"], reference: "1 Crônicas 6:27-28" },
      { question: "O que os levitas faziam no tabernáculo segundo 1 Crônicas 6?", answer: "Serviam com canto e música diante do tabernáculo", distractors: ["Ofereciam os sacrifícios no altar", "Guardavam as entradas do santuário"], reference: "1 Crônicas 6:31-32" },
      { question: "Quem Davi designou para liderar o canto no tabernáculo?", answer: "Hemã, Asafe e Etã", distractors: ["Samuel, Zadoque e Abiatar", "Quenanias, Obede-Edom e Jeiel"], reference: "1 Crônicas 6:31-48" },
      { question: "Quantas cidades foram dadas aos levitas segundo 1 Crônicas 6?", answer: "Quarenta e oito cidades", distractors: ["Vinte e quatro cidades", "Trinta e seis cidades"], reference: "Josué 21:41" },
      { question: "Quais cidades de refúgio foram dadas aos levitas entre as cidades levíticas?", answer: "Hebrom, Siquém, Quedes e outras", distractors: ["Jericó, Beerseba e Dã", "Gibeão, Mispa e Mambré"], reference: "1 Crônicas 6:54-81" },
    ],
    7: [
      { question: "Quem foi o famoso descendente de Efraim que construiu Bete-Horom e Uzém-Seera?", answer: "Seera, filha de Efraim", distractors: ["Josué, filho de Num", "Nunca, filho de Efraim"], reference: "1 Crônicas 7:24" },
      { question: "De qual tribo era Josué, o sucessor de Moisés, segundo 1 Crônicas 7?", answer: "Efraim", distractors: ["Manassés", "Benjamim"], reference: "1 Crônicas 7:27" },
      { question: "Qual tribo tinha cinquenta e seis mil guerreiros segundo o recenseamento em 1 Crônicas 7?", answer: "Manassés (com sua meia tribo)", distractors: ["Issacar", "Naftali"], reference: "1 Crônicas 7:2" },
      { question: "Quantos guerreiros valentes tinha a tribo de Aser segundo 1 Crônicas 7?", answer: "Vinte e seis mil homens", distractors: ["Quarenta mil homens", "Dezoito mil homens"], reference: "1 Crônicas 7:40" },
      { question: "O que aconteceu com os filhos de Efraim que foram a Gate roubar gado?", answer: "Os homens de Gate os mataram", distractors: ["Foram capturados e escravizados", "Fugiram envergonhados de volta"], reference: "1 Crônicas 7:21" },
      { question: "Quantos guerreiros tinha a tribo de Benjamim segundo 1 Crônicas 7?", answer: "Vinte e dois mil homens", distractors: ["Quinze mil homens", "Trinta mil homens"], reference: "1 Crônicas 7:9" },
    ],
    8: [
      { question: "De qual tribo era o rei Saul segundo a genealogia de 1 Crônicas 8?", answer: "Benjamim", distractors: ["Judá", "Efraim"], reference: "1 Crônicas 8:1-33" },
      { question: "Quem foi o pai de Saul segundo 1 Crônicas 8?", answer: "Quis", distractors: ["Abiel", "Ner"], reference: "1 Crônicas 8:33" },
      { question: "Como se chamava o filho de Saul que foi seu sucessor imediato e amigo de Davi?", answer: "Jônatas", distractors: ["Isbe-Benobe", "Abinadabe"], reference: "1 Crônicas 8:33" },
      { question: "Onde a família de Benjamim se estabeleceu principalmente segundo 1 Crônicas 8?", answer: "Em Gibeão e Jerusalém", distractors: ["Em Betel e Siquém", "Em Jericó e Ai"], reference: "1 Crônicas 8:28-29" },
      { question: "Quem era Ulão, descendente de Benjamim mencionado em 1 Crônicas 8?", answer: "Chefe de família cujos filhos eram valentes guerreiros arqueiros", distractors: ["O último rei de Benjamim antes do exílio", "O sumo sacerdote dos benjaminitas"], reference: "1 Crônicas 8:40" },
      { question: "Qual cidade importante foi habitada por benjaminitas segundo 1 Crônicas 8?", answer: "Jerusalém", distractors: ["Hebrom", "Belém"], reference: "1 Crônicas 8:28" },
    ],
    9: [
      { question: "Por que Israel foi levado cativo para a Babilônia segundo 1 Crônicas 9?", answer: "Por causa de suas transgressões", distractors: ["Pela fraqueza militar de seus reis", "Por causa de epidemias e secas"], reference: "1 Crônicas 9:1" },
      { question: "Quem foram os primeiros a habitar novamente em suas possessões após o exílio?", answer: "Israelitas, sacerdotes, levitas e netineus", distractors: ["Apenas os sacerdotes e o rei", "Os exilados de Judá e Benjamim"], reference: "1 Crônicas 9:2" },
      { question: "Qual era a função dos porteiros levitas no templo?", answer: "Guardar as portas e os tesouros do templo", distractors: ["Oferecer os sacrifícios diários", "Cantar e tocar instrumentos nas cerimônias"], reference: "1 Crônicas 9:22-26" },
      { question: "O que os porteiros levitas faziam em relação aos utensílios do templo?", answer: "Os contavam quando entravam e saíam", distractors: ["Os poliam e guardavam no lugar santo", "Os carregavam nas procissões religiosas"], reference: "1 Crônicas 9:28" },
      { question: "Quem era responsável pelo pão da proposição no templo segundo 1 Crônicas 9?", answer: "Levitas da família dos coatitas", distractors: ["Os filhos de Arão, os sacerdotes", "Os porteiros da tribo de Benjamim"], reference: "1 Crônicas 9:32" },
      { question: "Quantos porteiros havia no templo segundo 1 Crônicas 9?", answer: "Cento e doze", distractors: ["Duzentos e doze", "Setenta e dois"], reference: "1 Crônicas 9:22" },
    ],
    10: [
      { question: "Contra quem os filisteus guerrearam e mataram os filhos de Saul?", answer: "Jônatas, Abinadabe e Malquisua", distractors: ["Jônatas, Isvi e Meribe-Baal", "Jônatas, Isvi e Abinadabe"], reference: "1 Crônicas 10:1-2" },
      { question: "Como Saul morreu segundo 1 Crônicas 10?", answer: "Caiu sobre sua própria espada após ser gravemente ferido pelos flecheiros", distractors: ["Foi morto por um flecheiro filisteu", "Seu escudeiro o matou a pedido do rei"], reference: "1 Crônicas 10:3-4" },
      { question: "Por que o escudeiro de Saul não o matou quando pedido?", answer: "Porque tinha muito medo", distractors: ["Porque respeitava a unção de Saul como rei", "Porque os filisteus já chegavam"], reference: "1 Crônicas 10:4" },
      { question: "O que os filisteus fizeram com o corpo de Saul?", answer: "Cortaram sua cabeça, colocaram suas armas no templo de seus deuses e penduraram seu corpo no muro de Bete-Seã", distractors: ["Sepultaram-no com honras militares em Gibeão", "Lançaram seu corpo ao rio Jordão"], reference: "1 Crônicas 10:9-10" },
      { question: "Por que Saul morreu segundo a interpretação de 1 Crônicas 10?", answer: "Por ter sido infiel ao Senhor, não guardar sua palavra e consultar uma necromante", distractors: ["Por causa dos pecados de seus filhos", "Por ter poupado Agague, o rei amalequita"], reference: "1 Crônicas 10:13-14" },
      { question: "O que os homens de Jabes-Gileade fizeram pelos corpos de Saul e seus filhos?", answer: "Os sepultaram sob um carvalho em Jabes", distractors: ["Os levaram para Gibeão e os sepultaram com honras", "Os trouxeram para Jerusalém e os enterraram na tumba real"], reference: "1 Crônicas 10:11-12" },
    ],
    11: [
      { question: "Onde Davi foi ungido rei de todo Israel após a morte de Saul?", answer: "Em Hebrom", distractors: ["Em Gibeão", "Em Belém"], reference: "1 Crônicas 11:1-3" },
      { question: "Qual fortaleza Davi capturou e tornou sua cidade real?", answer: "A fortaleza de Sião (Cidade de Davi)", distractors: ["A fortaleza de Gibeão", "A fortaleza de Hebrom"], reference: "1 Crônicas 11:5" },
      { question: "Quem Davi nomeou como chefe do exército por ter subido primeiro ao ataque de Jerusalém?", answer: "Joabe, filho de Zeruia", distractors: ["Abisai, irmão de Joabe", "Benaia, filho de Joiada"], reference: "1 Crônicas 11:6" },
      { question: "Qual foi o feito heroico dos três valentes de Davi em Belém?", answer: "Romperam pelas fileiras dos filisteus para trazer água da cisterna de Belém", distractors: ["Mataram trezentos inimigos sozinhos numa batalha", "Capturaram o estandarte do rei dos filisteus"], reference: "1 Crônicas 11:17-19" },
      { question: "Quantos filisteus Abisai matou sozinho numa batalha, tornando-se chefe dos três?", answer: "Trezentos", distractors: ["Quinhendos", "Duzentos"], reference: "1 Crônicas 11:20" },
      { question: "Qual feito tornou Benaia, filho de Joiada, famoso entre os valentes?", answer: "Matou dois leões de Moabe e um leão numa cova no dia de neve, além de um egípcio com sua própria lança", distractors: ["Derrotou sozinho um batalhão filisteu de cinquenta homens", "Matou o gigante de Gate que tinha seis dedos em cada mão"], reference: "1 Crônicas 11:22-24" },
    ],
    12: [
      { question: "Quem veio a Davi em Ziclague quando ele ainda fugia de Saul?", answer: "Guerreiros de Benjamim, parentes de Saul", distractors: ["Sacerpotes de Nobe que escaparam do massacre", "Guerreiros de Judá liderados por Abisai"], reference: "1 Crônicas 12:1-2" },
      { question: "O que os gaditas que vieram a Davi eram capazes de fazer?", answer: "Manejar escudo e lança, cujos rostos eram como rostos de leões e eram ligeiros como gazelas", distractors: ["Atirar com arco usando a mão direita ou esquerda", "Conduzir carros de guerra em terreno montanhoso"], reference: "1 Crônicas 12:8" },
      { question: "Quantos de Manassés desertaram para Davi antes da batalha de Jezreel contra os filisteus?", answer: "Dez mil", distractors: ["Cinco mil", "Mil"], reference: "1 Crônicas 12:19-21" },
      { question: "Qual tribo enviou mais guerreiros para coroar Davi em Hebrom segundo 1 Crônicas 12?", answer: "Zebulom enviou cinquenta mil", distractors: ["Judá enviou oitenta mil", "Naftali enviou quarenta mil"], reference: "1 Crônicas 12:33" },
      { question: "O que o texto diz sobre o espírito dos homens de Issacar que vieram a Davi?", answer: "Tinham entendimento dos tempos e sabiam o que Israel devia fazer", distractors: ["Eram guerreiros que conheciam todas as táticas de batalha", "Eram profetas que interpretavam os sinais de Deus"], reference: "1 Crônicas 12:32" },
      { question: "Quantos dias o povo celebrou a coroação de Davi em Hebrom, segundo 1 Crônicas 12?", answer: "Três dias", distractors: ["Sete dias", "Quarenta dias"], reference: "1 Crônicas 12:39-40" },
    ],
    13: [
      { question: "O que Davi quis fazer em 1 Crônicas 13?", answer: "Trazer a arca de Deus de Quiriate-Jearim", distractors: ["Construir um templo para o Senhor", "Realizar um censo de toda Israel"], reference: "1 Crônicas 13:1-3" },
      { question: "Como a arca foi transportada quando saiu de Quiriate-Jearim?", answer: "Num carro novo puxado por bois", distractors: ["Nos ombros dos levitas com varas", "Numa procissão a pé com sacerdotes na frente"], reference: "1 Crônicas 13:7" },
      { question: "O que aconteceu quando Uzá tocou a arca para evitar que caísse?", answer: "O Senhor o feriu e ele morreu ali mesmo", distractors: ["Ficou paralítico pelo resto da vida", "Ficou cego temporariamente"], reference: "1 Crônicas 13:9-10" },
      { question: "Como Davi se sentiu após a morte de Uzá?", answer: "Com medo de Deus e não quis trazer a arca para a Cidade de Davi", distractors: ["Ficou com raiva do Senhor por punir Uzá", "Ficou em luto por sete dias"], reference: "1 Crônicas 13:12-13" },
      { question: "Na casa de quem a arca ficou por três meses após o incidente com Uzá?", answer: "Na casa de Obede-Edom, o giteu", distractors: ["Na casa do sacerdote Abiatá", "No tabernáculo de Gibeão"], reference: "1 Crônicas 13:13-14" },
      { question: "O que aconteceu na casa de Obede-Edom durante os três meses com a arca?", answer: "O Senhor abençoou a casa de Obede-Edom e tudo o que ele tinha", distractors: ["Nada de especial aconteceu", "Milagres de cura ocorreram entre sua família"], reference: "1 Crônicas 13:14" },
    ],
    14: [
      { question: "O que Hirão, rei de Tiro, enviou a Davi?", answer: "Madeira de cedro, carpinteiros e pedreiros para construir um palácio", distractors: ["Ouro e prata para o tesouro real", "Artesãos para fazer utensílios de bronze"], reference: "1 Crônicas 14:1" },
      { question: "Quantas esposas e concubinas Davi tomou em Jerusalém?", answer: "Mais esposas e concubinas além das que já tinha", distractors: ["Sete esposas e dez concubinas", "Três esposas e sete concubinas"], reference: "1 Crônicas 14:3" },
      { question: "Por que os filisteus subiram contra Davi duas vezes em 1 Crônicas 14?", answer: "Porque ouviram que Davi havia sido ungido rei de todo Israel", distractors: ["Porque Davi atacou cidades filistéias na fronteira", "Por causa de um desentendimento diplomático"], reference: "1 Crônicas 14:8,13" },
      { question: "O que Davi perguntou ao Senhor antes de cada batalha contra os filisteus?", answer: "Se deveria subir contra eles e se Deus os entregaria em suas mãos", distractors: ["Quantos soldados deveria levar", "Por qual rota deveria avançar"], reference: "1 Crônicas 14:10,14" },
      { question: "O que Davi fez com os ídolos que os filisteus abandonaram na primeira batalha?", answer: "Mandou queimá-los", distractors: ["Os guardou como troféus no palácio", "Os destruiu pisoteando-os"], reference: "1 Crônicas 14:12" },
      { question: "Na segunda batalha, o que Deus disse a Davi para fazer em vez de atacar de frente?", answer: "Contornar e atacar em frente às amoreiras, esperando o som nas copas", distractors: ["Esperar três dias e atacar de noite", "Enviar a cavalaria primeiro e depois a infantaria"], reference: "1 Crônicas 14:14-15" },
    ],
    15: [
      { question: "O que Davi preparou antes de trazer a arca para Jerusalém desta vez?", answer: "Um lugar para ela e uma tenda, e ordenou que só os levitas a carregassem", distractors: ["Um sacrifício de mil bois e mil ovelhas", "Uma procissão com toda a música do tabernáculo"], reference: "1 Crônicas 15:1-2" },
      { question: "Por que Davi disse que o Senhor havia punido Israel da primeira vez com a arca?", answer: "Porque não a carregaram como ordenado, sendo os levitas com varas nos ombros", distractors: ["Porque não purificaram o povo antes da procissão", "Porque não consultaram o sumo sacerdote"], reference: "1 Crônicas 15:13,15" },
      { question: "Quem Davi designou para liderar a música quando a arca entrasse em Jerusalém?", answer: "Quenanias, chefe dos levitas para o canto", distractors: ["Asafe, com seus címbalos de bronze", "Hemã e Jedutum com as trombetas"], reference: "1 Crônicas 15:22" },
      { question: "O que Mical, filha de Saul, viu pela janela e desprezou?", answer: "Davi dançando e saltando diante do Senhor", distractors: ["Davi oferecendo sacrifícios vestido de sacerdote", "Davi distribuindo pão ao povo"], reference: "1 Crônicas 15:29" },
      { question: "Com que instrumentos os levitas tocavam diante da arca segundo 1 Crônicas 15?", answer: "Saltérios, harpas e címbalos", distractors: ["Trombetas, flautas e tambores", "Alaúdes, cornetas e buzinas"], reference: "1 Crônicas 15:16" },
      { question: "Quem tocava os címbalos de bronze ao som do Salmo durante a procissão?", answer: "Asafe", distractors: ["Hemã", "Jedutum"], reference: "1 Crônicas 15:19" },
    ],
    16: [
      { question: "O que Davi ofereceu ao Senhor quando a arca chegou à tenda que havia preparado?", answer: "Holocaustos e ofertas pacíficas", distractors: ["Mil bois e mil cordeiros", "Ofertas de incenso e pão da proposição"], reference: "1 Crônicas 16:1-2" },
      { question: "O que Davi distribuiu ao povo após os sacrifícios?", answer: "Um pão, um pedaço de carne e um bolo de uvas passas", distractors: ["Prata e ouro do tesouro real", "Vinho e mel da adega real"], reference: "1 Crônicas 16:3" },
      { question: "Quem Davi deixou diante da arca para ministrar continuamente?", answer: "Asafe e seus irmãos", distractors: ["Hemã e os filhos de Coré", "Sadoque e os sacerdotes"], reference: "1 Crônicas 16:37" },
      { question: "Qual é o tema principal do salmo que Davi entregou a Asafe em 1 Crônicas 16?", answer: "Louvor e ações de graças ao Senhor por suas maravilhas e aliança com Israel", distractors: ["Arrependimento pelos pecados de Israel", "Pedido de proteção contra os inimigos"], reference: "1 Crônicas 16:8-36" },
      { question: "O que o salmo de Davi proclama sobre o Senhor em comparação com outros deuses?", answer: "Que o Senhor é grande e digno de louvor, pois todos os deuses dos povos são ídolos", distractors: ["Que o Senhor destruirá todos os outros deuses", "Que o Senhor é the único Deus que ouve a oração"], reference: "1 Crônicas 16:25-26" },
      { question: "Quem Davi deixou diante do tabernáculo em Gibeão para ministrar?", answer: "Sadoque, o sacerdote, e seus irmãos sacerdotes", distractors: ["Abiatá e os levitas de Hebrom", "Joiada e os porteiros do templo"], reference: "1 Crônicas 16:39" },
    ],
    17: [
      { question: "O que Davi disse ao profeta Natã que queria fazer?", answer: "Construir uma casa para a arca de Deus", distractors: ["Expandir os limites de Israel", "Escrever os salmos para o templo"], reference: "1 Crônicas 17:1" },
      { question: "O que Deus disse a Davi por meio de Natã sobre a construção do templo?", answer: "Que não seria Davi quem construiria, mas seu filho", distractors: ["Que o tempo ainda não havia chegado para o templo", "Que Davi deveria preparar os materiais mas não construir"], reference: "1 Crônicas 17:4,11-12" },
      { question: "O que Deus prometeu fazer pela casa (dinastia) de Davi?", answer: "Estabelecê-la para sempre e ser pai de seu filho que construiria o templo", distractors: ["Dar vitória sobre todos os inimigos em vida de Davi", "Multiplicar os descendentes de Davi como as estrelas"], reference: "1 Crônicas 17:12-14" },
      { question: "O que Deus disse que faria quando o filho de Davi pecasse?", answer: "O disciplinaria com varas de homens, mas não retiraria sua misericórdia como retirou de Saul", distractors: ["O removeria do trono e colocaria outro rei", "O castigaria com guerras e doenças"], reference: "2 Samuel 7:14-15" },
      { question: "Que frase resume a promessa de Deus a Davi em 1 Crônicas 17?", answer: "Tua casa e teu reino serão firmados para sempre diante de mim", distractors: ["Teu nome será grande entre todos os reis da terra", "Teu trono será estabelecido enquanto Israel existir"], reference: "1 Crônicas 17:14" },
      { question: "Como Davi respondeu à promessa de Deus em sua oração?", answer: "Com humildade e ação de graças, reconhecendo a grandeza de Deus", distractors: ["Pedindo que a promessa fosse confirmada por um sinal", "Prometendo construir o templo o mais rápido possível"], reference: "1 Crônicas 17:16-27" },
    ],
    18: [
      { question: "Quais nações Davi derrotou e sujeitou segundo 1 Crônicas 18?", answer: "Filisteus, moabitas, sírios (Hadadezer) e edomitas", distractors: ["Amonitas, amorreus e hititas", "Egito, Fenícia e Arabá"], reference: "1 Crônicas 18:1-13" },
      { question: "O que Davi fez com o ouro e bronze que tomou de Hadadezer, rei de Zobá?", answer: "Dedicou-os ao Senhor, e Salomão os usaria para fazer utensílios do templo", distractors: ["Distribuiu entre os guerreiros como recompensa", "Guardou no tesouro real de Jerusalém"], reference: "1 Crônicas 18:8,11" },
      { question: "Quem era Joabe em relação ao exército de Davi?", answer: "Chefe do exército", distractors: ["Comandante da guarda pessoal do rei", "Chefe dos trinta valentes de Davi"], reference: "1 Crônicas 18:15" },
      { question: "Quem era Josafá no governo de Davi?", answer: "O cronista (historiador/secretário)", distractors: ["O tesoureiro do reino", "O comandante da cavalaria"], reference: "1 Crônicas 18:15" },
      { question: "Quem era Sadoque e Abimeleque no governo de Davi?", answer: "Os sacerdotes", distractors: ["O cronista e o juiz supremo", "O chefe dos levitas e o chefe dos cantores"], reference: "1 Crônicas 18:16" },
      { question: "O que o texto diz sobre o reinado de Davi em 1 Crônicas 18?", answer: "Que Davi reinou sobre todo Israel praticando justiça e equidade para com todo o seu povo", distractors: ["Que foi o maior rei que Israel jamais teve", "Que todos os reis vizinhos lhe pagavam tributo anual"], reference: "1 Crônicas 18:14" },
    ],
    19: [
      { question: "Por que Davi enviou mensageiros ao rei Hanun dos amonitas?", answer: "Para consolá-lo pela morte de seu pai, Naás, que havia sido bondoso com Davi", distractors: ["Para renovar a aliança de paz entre os dois reinos", "Para pedir passagem pelo território amonita"], reference: "1 Crônicas 19:1-2" },
      { question: "O que Hanun fez com os embaixadores de Davi?", answer: "Rapou metade de suas barbas, cortou suas vestes até as nádegas e os mandou embora", distractors: ["Prendeu-os como espiões por seis meses", "Os expulsou sem ouvir sua mensagem"], reference: "1 Crônicas 19:4" },
      { question: "Quem os amonitas contrataram para ajudá-los contra Davi?", answer: "Sírios de Mesopotâmia, de Maaca e de Zobá", distractors: ["Filisteus e edomitas", "Moabitas e amalequitas"], reference: "1 Crônicas 19:6-7" },
      { question: "Como Joabe dividiu o exército israelita para enfrentar os amonitas e sírios?", answer: "Ele ficou com os mais valentes contra os sírios; seu irmão Abisai ficou contra os amonitas", distractors: ["Mandou a cavalaria contra os sírios e a infantaria contra os amonitas", "Cercou os amonitas enquanto mandou Abisai flanquear os sírios"], reference: "1 Crônicas 19:10-11" },
      { question: "O que Joabe disse a Abisai antes da batalha em 1 Crônicas 19?", answer: "Que se os sírios fossem mais fortes, Abisai o socorreria, e se os amonitas fossem mais fortes, ele socorreria Abisai", distractors: ["Que deviam orar antes de atacar", "Que o Senhor faria o que fosse bom aos seus olhos"], reference: "1 Crônicas 19:12" },
      { question: "Após a derrota dos sírios, o que eles fizeram?", answer: "Fizeram paz com Davi e se tornaram seus servos", distractors: ["Fugiram para além do Eufrates e nunca mais voltaram", "Pediram reforços da Assíria para uma nova campanha"], reference: "1 Crônicas 19:19" },
    ],
    20: [
      { question: "O que Joabe fez enquanto Davi ficou em Jerusalém na época da guerra em 1 Crônicas 20?", answer: "Devastou o país dos amonitas e sitiou Rabá", distractors: ["Lutou contra os sírios no norte", "Perseguiu os filisteus até o mar"], reference: "1 Crônicas 20:1" },
      { question: "O que Davi tomou da cabeça do rei de Rabá?", answer: "Uma coroa de ouro com uma pedra preciosa que pesava um talento de ouro", distractors: ["Um cetro de prata e uma espada", "Um capacete de ouro com runas reais"], reference: "1 Crônicas 20:2" },
      { question: "Quem matou Sipai, descendente dos refaítas, numa batalha com os filisteus?", answer: "Sibecai, o husatita", distractors: ["Abisai, filho de Zeruia", "Elhanan, filho de Jair"], reference: "1 Crônicas 20:4" },
      { question: "Quem matou o gigante que tinha seis dedos em cada mão e seis em cada pé?", answer: "Jônatas, filho de Simea, irmão de Davi", distractors: ["Abisai, filho de Zeruia", "Benaia, filho de Joiada"], reference: "1 Crônicas 20:7" },
      { question: "De onde eram os gigantes que foram mortos pelos guerreiros de Davi em 1 Crônicas 20?", answer: "De Gate", distractors: ["De Gaze", "De Asdode"], reference: "1 Crônicas 20:6,8" },
      { question: "Quem matou o irmão de Golias na batalha de 1 Crônicas 20?", answer: "Elhanan, filho de Jair", distractors: ["Sibecai, o husatita", "Abisai, filho de Zeruia"], reference: "1 Crônicas 20:5" },
    ],
    21: [
      { question: "Quem incitou Davi a fazer o censo de Israel em 1 Crônicas 21?", answer: "Satanás", distractors: ["Joabe, chefe do exército", "Os príncipes do povo"], reference: "1 Crônicas 21:1" },
      { question: "Por que Joabe se opôs ao censo?", answer: "Porque achava que isso traria culpa sobre Israel", distractors: ["Porque o censo era muito trabalhoso", "Porque a Lei de Moisés proibia censos"], reference: "1 Crônicas 21:3" },
      { question: "Que punição Deus ofereceu a Davi como opção após o pecado do censo?", answer: "Três anos de fome, three meses de derrota diante dos inimigos, ou três dias de espada do Senhor", distractors: ["Sete anos de exílio, sete meses de guerra ou sete dias de praga", "Dez anos de seca, um ano de invasão ou quarenta dias de praga"], reference: "1 Crônicas 21:12" },
      { question: "Qual castigo Davi escolheu?", answer: "Cair nas mãos do Senhor (a praga de três dias)", distractors: ["Três anos de fome", "Três meses de derrota pelos inimigos"], reference: "1 Crônicas 21:13" },
      { question: "Quantos homens morreram na praga após o censo?", answer: "Setenta mil", distractors: ["Cinquenta mil", "Cem mil"], reference: "1 Crônicas 21:14" },
      { question: "O que Davi comprou de Ornã (Araúna), o jebuseu, para construir um altar?", answer: "A eira, os bois e o trigo, pagando seiscentos siclos de ouro", distractors: ["Apenas os bois, pagando cinquenta siclos de prata", "A eira e os instrumentos de madeira, pelo preço que Ornã pediu"], reference: "1 Crônicas 21:22-25" },
    ],
    22: [
      { question: "O que Davi disse sobre o lugar da eira de Ornã?", answer: "Que ali seria a casa do Senhor Deus e o altar dos holocaustos de Israel", distractors: ["Que ali construiria sua própria tumba", "Que ali ergueria um memorial para as vitórias de Israel"], reference: "1 Crônicas 22:1" },
      { question: "Por que Deus não deixou Davi construir o templo?", answer: "Porque Davi era homem de guerra e havia derramado muito sangue", distractors: ["Porque Davi não era sacerdote", "Porque Davi cometeu o pecado do censo"], reference: "1 Crônicas 22:8" },
      { question: "O que Davi preparou para a construção do templo?", answer: "Ferro, bronze, cedro, prata e ouro em abundância", distractors: ["Apenas os planos e a localização do templo", "Ouro e pedras preciosas do tesouro real"], reference: "1 Crônicas 22:2-4" },
      { question: "Quanto ouro e prata Davi preparou para o templo segundo 1 Crônicas 22?", answer: "Cem mil talentos de ouro e um milhão de talentos de prata", distractors: ["Dez mil talentos de ouro e cem mil de prata", "Mil talentos de ouro e dez mil de prata"], reference: "1 Crônicas 22:14" },
      { question: "O que Davi disse a Salomão sobre a construção do templo?", answer: "Que fosse forte e corajoso e o construísse, pois o Senhor estava com ele", distractors: ["Que esperasse ser velho antes de começar a construção", "Que consultasse os sacerdotes em cada etapa da construção"], reference: "1 Crônicas 22:11" },
      { question: "Quem Davi convocou para ajudar Salomão na construção?", answer: "Os príncipes de Israel, os levitas, sacerdotes e todos os chefes", distractors: ["Apenas os mestres de obra e arquitetos estrangeiros", "Hirão de Tiro e seus artesãos"], reference: "1 Crônicas 22:17" },
    ],
    23: [
      { question: "Com que idade Davi fez Salomão rei sobre Israel em 1 Crônicas 23?", answer: "Quando Davi era velho e cheio de dias", distractors: ["Aos setenta anos de Davi", "Quando Davi estava doente no leito"], reference: "1 Crônicas 23:1" },
      { question: "A partir de qual idade os levitas passaram a trabalhar no templo sob a nova contagem de Davi?", answer: "Trinta anos", distractors: ["Vinte e cinco anos", "Quarenta anos"], reference: "1 Crônicas 23:3" },
      { question: "Quais eram as três famílias levíticas segundo 1 Crônicas 23?", answer: "Gérsom, Coate e Merari", distractors: ["Asafe, Hemã e Jedutum", "Sadoque, Abiatá e Joiada"], reference: "1 Crônicas 23:6" },
      { question: "Qual era a nova função dos levitas com a construção do templo fixo?", answer: "Não precisariam mais carregar o tabernáculo, mas assistiriam aos sacerdotes no templo", distractors: ["Guardar o tesouro do templo dia e noite", "Ensinar a Lei de Moisés em todas as cidades de Israel"], reference: "1 Crônicas 23:26,28" },
      { question: "O que os levitas faziam segundo 1 Crônicas 23 quanto ao culto?", answer: "Louvar, agradecer e cantar ao Senhor de manhã e de tarde", distractors: ["Oferecer incenso e cuidar das lâmpadas do santuário", "Ler a Lei e ensinar os escribas"], reference: "1 Crônicas 23:30" },
      { question: "Quantos levitas foram recenseados acima de trinta anos no censo de Davi?", answer: "Trinta e oito mil", distractors: ["Vinte mil", "Cinquenta mil"], reference: "1 Crônicas 23:3" },
    ],
    24: [
      { question: "Como as vinte e quatro ordens dos sacerdotes foram divididas em 1 Crônicas 24?", answer: "Por sorteio entre os descendentes de Eleazar e Itamar", distractors: ["Conforme a antiguidade de cada família sacerdotal", "Por nomeação direta de Davi e Sadoque"], reference: "1 Crônicas 24:3,5" },
      { question: "Quem presidiu o sorteio das divisões sacerdotais?", answer: "Sadoque e Aimelec, filho de Abiatá", distractors: ["Davi e os príncipes de Israel", "Natã, o profeta, e Joiada"], reference: "1 Crônicas 24:3" },
      { question: "Quem foi o primeiro a sair no sorteio das vinte e quatro divisões sacerdotais?", answer: "Joiaribe", distractors: ["Jedaías", "Harim"], reference: "1 Crônicas 24:7" },
      { question: "Por que havia mais chefes entre os descendentes de Eleazar do que de Itamar?", answer: "Porque os descendentes de Eleazar eram mais numerosos", distractors: ["Porque Eleazar era o primogênito de Arão", "Porque os filhos de Itamar haviam sido reduzidos por guerras"], reference: "1 Crônicas 24:4" },
      { question: "O que o sistema das vinte e quatro divisões sacerdotais garantia?", answer: "Uma rotação organizada dos sacerdotes para servir no templo", distractors: ["Que todos os sacerdotes servissem ao mesmo tempo nas festas", "Que cada tribo tivesse seus próprios sacerdotes"], reference: "1 Crônicas 24:19" },
      { question: "Qual era a vigésima quarta ordem sacerdotal no sorteio?", answer: "Maazias", distractors: ["Bilgá", "Seorim"], reference: "1 Crônicas 24:18" },
    ],
    25: [
      { question: "Quem Davi e os chefes separaram para o ministério da profecia musical?", answer: "Os filhos de Asafe, Hemã e Jedutum", distractors: ["Os filhos de Sadoque e Abiatá", "Os filhos de Quenanias e Obede-Edom"], reference: "1 Crônicas 25:1" },
      { question: "Com que instrumentos os músicos do templo ministravam em 1 Crônicas 25?", answer: "Harpas, saltérios e címbalos", distractors: ["Trombetas, flautas e tambores", "Alaúdes, buzinas e cornetas"], reference: "1 Crônicas 25:1" },
      { question: "Quantas divisões de músicos foram organizadas em 1 Crônicas 25?", answer: "Vinte e quatro divisões", distractors: ["Doze divisões", "Trinta e seis divisões"], reference: "1 Crônicas 25:9-31" },
      { question: "Quantos filhos e discípulos hábeis tinha Hemã?", answer: "Quatorze filhos e três filhas", distractors: ["Doze filhos", "Seis filhos e seis discípulos"], reference: "1 Crônicas 25:5" },
      { question: "Qual era o número total de músicos treinados segundo 1 Crônicas 25?", answer: "Duzentos e oitenta e oito", distractors: ["Cento e quarenta e quatro", "Trezentos e sessenta"], reference: "1 Crônicas 25:7" },
      { question: "O que o texto diz sobre Hemã em 1 Crônicas 25?", answer: "Era o vidente do rei segundo as promessas de Deus para exaltar o seu poder", distractors: ["Era o mais habilidoso de todos os músicos de Israel", "Era o chefe de todos os levitas do templo"], reference: "1 Crônicas 25:5" },
    ],
    26: [
      { question: "Quais eram as funções dos porteiros segundo 1 Crônicas 26?", answer: "Guardar as portas do templo e os tesouros", distractors: ["Cantar e tocar instrumentos nas cerimônias", "Oferecer os sacrifícios diários no altar"], reference: "1 Crônicas 26:1,20" },
      { question: "De qual família levítica vinha Obede-Edom, nomeado porteiro?", answer: "Da família dos coratitas", distractors: ["Da família dos merarítas", "Da família dos gersonitas"], reference: "1 Crônicas 26:1,4" },
      { question: "Quantos filhos e netos tinha Obede-Edom, todos capazes para o serviço?", answer: "Sessenta e dois", distractors: ["Quarenta e oito", "Vinte e quatro"], reference: "1 Crônicas 26:8" },
      { question: "Quem foi designado para a porta sul do templo?", answer: "Obede-Edom com seus filhos", distractors: ["Selemias e seus filhos", "Zacarias, filho de Meselemias"], reference: "1 Crônicas 26:15" },
      { question: "O que os levitas que cuidavam dos tesouros eram responsáveis por guardar?", answer: "As coisas sagradas e os presentes dedicados ao templo", distractors: ["Os rolos da Lei e os registros reais", "As armas e equipamentos militares do templo"], reference: "1 Crônicas 26:20" },
      { question: "Quem foram nomeados para cuidar do tesouro externo (tesouros das cidades)?", answer: "Levitas de Hebrom e de Izeias", distractors: ["Os filhos de Asafe e Hemã", "Membros da família de Sadoque"], reference: "1 Crônicas 26:30-32" },
    ],
    27: [
      { question: "Como eram organizados os doze generais militares de Davi segundo 1 Crônicas 27?", answer: "Cada um servia um mês por ano com vinte e quatro mil homens", distractors: ["Cada um comandava uma tribo de Israel permanentemente", "Serviam em rodízio a cada três meses com doze mil homens"], reference: "1 Crônicas 27:1" },
      { question: "Quem foi o primeiro general do primeiro mês segundo 1 Crônicas 27?", answer: "Jasobeão, filho de Zabdiel", distractors: ["Dodai, o aoíta", "Benaia, filho de Joiada"], reference: "1 Crônicas 27:2" },
      { question: "Quem era o supervisor das propriedades de Davi?", answer: "Ezri, filho de Quelube, sobre os lavradores", distractors: ["Zimri, filho de Joiada", "Jaziz, o hagareno"], reference: "1 Crônicas 27:26" },
      { question: "Quem cuidava dos olivais e amoreiras de Davi?", answer: "Baale-Hanan, o gederita", distractors: ["Obil, o ismaelita", "Jaziz, o hagareno"], reference: "1 Crônicas 27:28" },
      { question: "Quem foi o conselheiro de Davi descrito como um amigo do rei?", answer: "Husai, o arquita", distractors: ["Aitofel, de Gilo", "Natã, o profeta"], reference: "1 Crônicas 27:33" },
      { question: "Por que Davi não recenseou os homens menores de vinte anos segundo 1 Crônicas 27?", answer: "Porque o Senhor havia prometido multiplicar Israel como as estrelas dos céus", distractors: ["Porque a Lei proibia contar os jovens", "Porque ainda não estavam em idade de servir no exército"], reference: "1 Crônicas 27:23" },
    ],
    28: [
      { question: "O que Davi convocou em Jerusalém para transmitir suas últimas instruções?", answer: "Todos os chefes de Israel, generais, superintendentes e homens valentes", distractors: ["Apenas os sacerdotes e levitas do templo", "Os anciãos das doze tribos e os profetas"], reference: "1 Crônicas 28:1" },
      { question: "Quem Deus escolheu entre os filhos de Davi para construir o templo?", answer: "Salomão", distractors: ["Adonias, o primogênito", "Natã, o filho amado"], reference: "1 Crônicas 28:5-6" },
      { question: "O que Davi entregou a Salomão para o projeto do templo?", answer: "O plano de tudo que havia sido dado pelo Espírito: átrios, câmaras, tesouros, etc.", distractors: ["Um rolo com as medidas do tabernáculo de Moisés", "As instruções dos sacerdotes e levitas"], reference: "1 Crônicas 28:11-12" },
      { question: "Quanto ouro Davi dedicou para os objetos de ouro do templo?", answer: "O peso de cada objeto de ouro para cada uso", distractors: ["Cem mil talentos para todos os objetos juntos", "A metade do tesouro real"], reference: "1 Crônicas 28:14" },
      { question: "O que Davi disse a Salomão sobre a construção do templo?", answer: "'Sê forte e corajoso, não temas nem te atemorizes, pois o Senhor está contigo'", distractors: ["'Não há tarefa maior que esta, pois é para a glória de Deus'", "'Conclua o que eu comecei, pois é um voto que fiz ao Senhor'"], reference: "1 Crônicas 28:20" },
      { question: "O que Davi disse que Deus faria se Salomão o procurasse?", answer: "Que Deus seria encontrado por ele", distractors: ["Que Deus lhe daria sabedoria para governar", "Que Deus afastaria todos os inimigos de Salomão"], reference: "1 Crônicas 28:9" },
    ],
    29: [
      { question: "Além do que havia preparado oficialmente, o que Davi deu do seu próprio tesouro pessoal para o templo?", answer: "Três mil talentos de ouro de Ofir e sete mil talentos de prata refinada", distractors: ["Mil talentos de ouro e cinco mil de prata", "Todo o ouro e prata que havia acumulado em guerras"], reference: "1 Crônicas 29:3-4" },
      { question: "O que os chefes do povo fizeram ao ver o exemplo de Davi?", answer: "Também contribuíram voluntariamente com ouro, prata, bronze e pedras preciosas", distractors: ["Prometeram construir as cidades ao redor do templo", "Recrutaram trabalhadores de seus territórios"], reference: "1 Crônicas 29:6-8" },
      { question: "Qual foi a oração de Davi na cerimônia de dedicação das ofertas para o templo?", answer: "Uma oração de louvor reconhecendo que tudo vem de Deus e que eles apenas devolviam o que era dele", distractors: ["Uma oração pedindo que o templo fosse construído em um ano", "Uma oração de arrependimento pelos pecados de sua vida"], reference: "1 Crônicas 29:10-19" },
      { question: "O que Davi pediu a Deus por Salomão na sua oração?", answer: "Que Salomão tivesse coração íntegro para guardar os mandamentos e construir o templo", distractors: ["Que Salomão fosse mais sábio que todos os reis da terra", "Que Salomão não cometesse os mesmos pecados que ele"], reference: "1 Crônicas 29:19" },
      { question: "Como o povo respondeu à oração e às ofertas de Davi?", answer: "Regozijou-se e adorou ao Senhor e ao rei", distractors: ["Saiu em procissão ao redor da cidade cantando", "Jejuou três dias em ação de graças"], reference: "1 Crônicas 29:20,22" },
      { question: "Quantos anos Davi reinou sobre Israel?", answer: "Quarenta anos: sete em Hebrom e trinta e três em Jerusalém", distractors: ["Trinta e sete anos no total", "Quarenta e cinco anos no total"], reference: "1 Crônicas 29:27" },
    ],
  },
};
