// Auto-generated by scripts/generate-index.mjs
// Version: ARA | Books: 66/66

import { GENESIS_ARA } from './genesis';
import { EXODO_ARA } from './exodo';
import { LEVITICO_ARA } from './levitico';
import { NUMEROS_ARA } from './numeros';
import { DEUTERONOMIO_ARA } from './deuteronomio';
import { JOSUE_ARA } from './josue';
import { JUIZES_ARA } from './juizes';
import { RUTE_ARA } from './rute';
import { BOOK_1SAMUEL_ARA } from './1samuel';
import { BOOK_2SAMUEL_ARA } from './2samuel';
import { BOOK_1REIS_ARA } from './1reis';
import { BOOK_2REIS_ARA } from './2reis';
import { BOOK_1CRONICAS_ARA } from './1cronicas';
import { BOOK_2CRONICAS_ARA } from './2cronicas';
import { ESDRAS_ARA } from './esdras';
import { NEEMIAS_ARA } from './neemias';
import { ESTER_ARA } from './ester';
import { JO_ARA } from './jo';
import { SALMOS_ARA } from './salmos';
import { PROVERBIOS_ARA } from './proverbios';
import { ECLESIASTES_ARA } from './eclesiastes';
import { CANTARES_ARA } from './cantares';
import { ISAIAS_ARA } from './isaias';
import { JEREMIAS_ARA } from './jeremias';
import { LAMENTACOES_ARA } from './lamentacoes';
import { EZEQUIEL_ARA } from './ezequiel';
import { DANIEL_ARA } from './daniel';
import { OSEIAS_ARA } from './oseias';
import { JOEL_ARA } from './joel';
import { AMOS_ARA } from './amos';
import { OBADIAS_ARA } from './obadias';
import { JONAS_ARA } from './jonas';
import { MIQUEIAS_ARA } from './miqueias';
import { NAUM_ARA } from './naum';
import { HABACUQUE_ARA } from './habacuque';
import { SOFONIAS_ARA } from './sofonias';
import { AGEU_ARA } from './ageu';
import { ZACARIAS_ARA } from './zacarias';
import { MALAQUIAS_ARA } from './malaquias';
import { MATEUS_ARA } from './mateus';
import { MARCOS_ARA } from './marcos';
import { LUCAS_ARA } from './lucas';
import { JOAO_ARA } from './joao';
import { ATOS_ARA } from './atos';
import { ROMANOS_ARA } from './romanos';
import { BOOK_1CORINTIOS_ARA } from './1corintios';
import { BOOK_2CORINTIOS_ARA } from './2corintios';
import { GALATAS_ARA } from './galatas';
import { EFESIOS_ARA } from './efesios';
import { FILIPENSES_ARA } from './filipenses';
import { COLOSSENSES_ARA } from './colossenses';
import { BOOK_1TESSALONICENSES_ARA } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_ARA } from './2tessalonicenses';
import { BOOK_1TIMOTEO_ARA } from './1timoteo';
import { BOOK_2TIMOTEO_ARA } from './2timoteo';
import { TITO_ARA } from './tito';
import { FILEMOM_ARA } from './filemom';
import { HEBREUS_ARA } from './hebreus';
import { TIAGO_ARA } from './tiago';
import { BOOK_1PEDRO_ARA } from './1pedro';
import { BOOK_2PEDRO_ARA } from './2pedro';
import { BOOK_1JOAO_ARA } from './1joao';
import { BOOK_2JOAO_ARA } from './2joao';
import { BOOK_3JOAO_ARA } from './3joao';
import { JUDAS_ARA } from './judas';
import { APOCALIPSE_ARA } from './apocalipse';

export const LOCAL_BIBLE_ARA: Record<number, string[]>[] = [];

export const LOCAL_ARA: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_ARA,
  "exodo": EXODO_ARA,
  "levitico": LEVITICO_ARA,
  "numeros": NUMEROS_ARA,
  "deuteronomio": DEUTERONOMIO_ARA,
  "josue": JOSUE_ARA,
  "juizes": JUIZES_ARA,
  "rute": RUTE_ARA,
  "1samuel": BOOK_1SAMUEL_ARA,
  "2samuel": BOOK_2SAMUEL_ARA,
  "1reis": BOOK_1REIS_ARA,
  "2reis": BOOK_2REIS_ARA,
  "1cronicas": BOOK_1CRONICAS_ARA,
  "2cronicas": BOOK_2CRONICAS_ARA,
  "esdras": ESDRAS_ARA,
  "neemias": NEEMIAS_ARA,
  "ester": ESTER_ARA,
  "jo": JO_ARA,
  "salmos": SALMOS_ARA,
  "proverbios": PROVERBIOS_ARA,
  "eclesiastes": ECLESIASTES_ARA,
  "cantares": CANTARES_ARA,
  "isaias": ISAIAS_ARA,
  "jeremias": JEREMIAS_ARA,
  "lamentacoes": LAMENTACOES_ARA,
  "ezequiel": EZEQUIEL_ARA,
  "daniel": DANIEL_ARA,
  "oseias": OSEIAS_ARA,
  "joel": JOEL_ARA,
  "amos": AMOS_ARA,
  "obadias": OBADIAS_ARA,
  "jonas": JONAS_ARA,
  "miqueias": MIQUEIAS_ARA,
  "naum": NAUM_ARA,
  "habacuque": HABACUQUE_ARA,
  "sofonias": SOFONIAS_ARA,
  "ageu": AGEU_ARA,
  "zacarias": ZACARIAS_ARA,
  "malaquias": MALAQUIAS_ARA,
  "mateus": MATEUS_ARA,
  "marcos": MARCOS_ARA,
  "lucas": LUCAS_ARA,
  "joao": JOAO_ARA,
  "atos": ATOS_ARA,
  "romanos": ROMANOS_ARA,
  "1corintios": BOOK_1CORINTIOS_ARA,
  "2corintios": BOOK_2CORINTIOS_ARA,
  "galatas": GALATAS_ARA,
  "efesios": EFESIOS_ARA,
  "filipenses": FILIPENSES_ARA,
  "colossenses": COLOSSENSES_ARA,
  "1tessalonicenses": BOOK_1TESSALONICENSES_ARA,
  "2tessalonicenses": BOOK_2TESSALONICENSES_ARA,
  "1timoteo": BOOK_1TIMOTEO_ARA,
  "2timoteo": BOOK_2TIMOTEO_ARA,
  "tito": TITO_ARA,
  "filemom": FILEMOM_ARA,
  "hebreus": HEBREUS_ARA,
  "tiago": TIAGO_ARA,
  "1pedro": BOOK_1PEDRO_ARA,
  "2pedro": BOOK_2PEDRO_ARA,
  "1joao": BOOK_1JOAO_ARA,
  "2joao": BOOK_2JOAO_ARA,
  "3joao": BOOK_3JOAO_ARA,
  "judas": JUDAS_ARA,
  "apocalipse": APOCALIPSE_ARA,
};
