// Auto-generated by scripts/generate-index.mjs
// Version: KJV | Books: 66/66

import { GENESIS_KJV } from './genesis';
import { EXODO_KJV } from './exodo';
import { LEVITICO_KJV } from './levitico';
import { NUMEROS_KJV } from './numeros';
import { DEUTERONOMIO_KJV } from './deuteronomio';
import { JOSUE_KJV } from './josue';
import { JUIZES_KJV } from './juizes';
import { RUTE_KJV } from './rute';
import { BOOK_1SAMUEL_KJV } from './1samuel';
import { BOOK_2SAMUEL_KJV } from './2samuel';
import { BOOK_1REIS_KJV } from './1reis';
import { BOOK_2REIS_KJV } from './2reis';
import { BOOK_1CRONICAS_KJV } from './1cronicas';
import { BOOK_2CRONICAS_KJV } from './2cronicas';
import { ESDRAS_KJV } from './esdras';
import { NEEMIAS_KJV } from './neemias';
import { ESTER_KJV } from './ester';
import { JO_KJV } from './jo';
import { SALMOS_KJV } from './salmos';
import { PROVERBIOS_KJV } from './proverbios';
import { ECLESIASTES_KJV } from './eclesiastes';
import { CANTARES_KJV } from './cantares';
import { ISAIAS_KJV } from './isaias';
import { JEREMIAS_KJV } from './jeremias';
import { LAMENTACOES_KJV } from './lamentacoes';
import { EZEQUIEL_KJV } from './ezequiel';
import { DANIEL_KJV } from './daniel';
import { OSEIAS_KJV } from './oseias';
import { JOEL_KJV } from './joel';
import { AMOS_KJV } from './amos';
import { OBADIAS_KJV } from './obadias';
import { JONAS_KJV } from './jonas';
import { MIQUEIAS_KJV } from './miqueias';
import { NAUM_KJV } from './naum';
import { HABACUQUE_KJV } from './habacuque';
import { SOFONIAS_KJV } from './sofonias';
import { AGEU_KJV } from './ageu';
import { ZACARIAS_KJV } from './zacarias';
import { MALAQUIAS_KJV } from './malaquias';
import { MATEUS_KJV } from './mateus';
import { MARCOS_KJV } from './marcos';
import { LUCAS_KJV } from './lucas';
import { JOAO_KJV } from './joao';
import { ATOS_KJV } from './atos';
import { ROMANOS_KJV } from './romanos';
import { BOOK_1CORINTIOS_KJV } from './1corintios';
import { BOOK_2CORINTIOS_KJV } from './2corintios';
import { GALATAS_KJV } from './galatas';
import { EFESIOS_KJV } from './efesios';
import { FILIPENSES_KJV } from './filipenses';
import { COLOSSENSES_KJV } from './colossenses';
import { BOOK_1TESSALONICENSES_KJV } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_KJV } from './2tessalonicenses';
import { BOOK_1TIMOTEO_KJV } from './1timoteo';
import { BOOK_2TIMOTEO_KJV } from './2timoteo';
import { TITO_KJV } from './tito';
import { FILEMOM_KJV } from './filemom';
import { HEBREUS_KJV } from './hebreus';
import { TIAGO_KJV } from './tiago';
import { BOOK_1PEDRO_KJV } from './1pedro';
import { BOOK_2PEDRO_KJV } from './2pedro';
import { BOOK_1JOAO_KJV } from './1joao';
import { BOOK_2JOAO_KJV } from './2joao';
import { BOOK_3JOAO_KJV } from './3joao';
import { JUDAS_KJV } from './judas';
import { APOCALIPSE_KJV } from './apocalipse';

export const LOCAL_BIBLE_KJV: Record<number, string[]>[] = [];

export const LOCAL_KJV: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_KJV,
  "exodo": EXODO_KJV,
  "levitico": LEVITICO_KJV,
  "numeros": NUMEROS_KJV,
  "deuteronomio": DEUTERONOMIO_KJV,
  "josue": JOSUE_KJV,
  "juizes": JUIZES_KJV,
  "rute": RUTE_KJV,
  "1samuel": BOOK_1SAMUEL_KJV,
  "2samuel": BOOK_2SAMUEL_KJV,
  "1reis": BOOK_1REIS_KJV,
  "2reis": BOOK_2REIS_KJV,
  "1cronicas": BOOK_1CRONICAS_KJV,
  "2cronicas": BOOK_2CRONICAS_KJV,
  "esdras": ESDRAS_KJV,
  "neemias": NEEMIAS_KJV,
  "ester": ESTER_KJV,
  "jo": JO_KJV,
  "salmos": SALMOS_KJV,
  "proverbios": PROVERBIOS_KJV,
  "eclesiastes": ECLESIASTES_KJV,
  "cantares": CANTARES_KJV,
  "isaias": ISAIAS_KJV,
  "jeremias": JEREMIAS_KJV,
  "lamentacoes": LAMENTACOES_KJV,
  "ezequiel": EZEQUIEL_KJV,
  "daniel": DANIEL_KJV,
  "oseias": OSEIAS_KJV,
  "joel": JOEL_KJV,
  "amos": AMOS_KJV,
  "obadias": OBADIAS_KJV,
  "jonas": JONAS_KJV,
  "miqueias": MIQUEIAS_KJV,
  "naum": NAUM_KJV,
  "habacuque": HABACUQUE_KJV,
  "sofonias": SOFONIAS_KJV,
  "ageu": AGEU_KJV,
  "zacarias": ZACARIAS_KJV,
  "malaquias": MALAQUIAS_KJV,
  "mateus": MATEUS_KJV,
  "marcos": MARCOS_KJV,
  "lucas": LUCAS_KJV,
  "joao": JOAO_KJV,
  "atos": ATOS_KJV,
  "romanos": ROMANOS_KJV,
  "1corintios": BOOK_1CORINTIOS_KJV,
  "2corintios": BOOK_2CORINTIOS_KJV,
  "galatas": GALATAS_KJV,
  "efesios": EFESIOS_KJV,
  "filipenses": FILIPENSES_KJV,
  "colossenses": COLOSSENSES_KJV,
  "1tessalonicenses": BOOK_1TESSALONICENSES_KJV,
  "2tessalonicenses": BOOK_2TESSALONICENSES_KJV,
  "1timoteo": BOOK_1TIMOTEO_KJV,
  "2timoteo": BOOK_2TIMOTEO_KJV,
  "tito": TITO_KJV,
  "filemom": FILEMOM_KJV,
  "hebreus": HEBREUS_KJV,
  "tiago": TIAGO_KJV,
  "1pedro": BOOK_1PEDRO_KJV,
  "2pedro": BOOK_2PEDRO_KJV,
  "1joao": BOOK_1JOAO_KJV,
  "2joao": BOOK_2JOAO_KJV,
  "3joao": BOOK_3JOAO_KJV,
  "judas": JUDAS_KJV,
  "apocalipse": APOCALIPSE_KJV,
};
