/**
 * Gera lib/bible-local-index.ts com suporte a múltiplas versões.
 * Usage: node scripts/generate-index.mjs [VERSION1] [VERSION2] ...
 * Default: gera para todas as versões encontradas em lib/bible-local/
 *
 * Saída:
 *   lib/bible-local/<VERSION>/index.ts   ← índice por versão
 *   lib/bible-local-index.ts             ← mapa unificado LOCAL_BIBLE
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const LOCAL_BASE = path.join(ROOT, 'lib', 'bible-local');
const MASTER_INDEX = path.join(ROOT, 'lib', 'bible-local-index.ts');

const BOOKS = [
  'genesis','exodo','levitico','numeros','deuteronomio','josue','juizes','rute',
  '1samuel','2samuel','1reis','2reis','1cronicas','2cronicas','esdras','neemias',
  'ester','jo','salmos','proverbios','eclesiastes','cantares','isaias','jeremias',
  'lamentacoes','ezequiel','daniel','oseias','joel','amos','obadias','jonas',
  'miqueias','naum','habacuque','sofonias','ageu','zacarias','malaquias','mateus',
  'marcos','lucas','joao','atos','romanos','1corintios','2corintios','galatas',
  'efesios','filipenses','colossenses','1tessalonicenses','2tessalonicenses',
  '1timoteo','2timoteo','tito','filemom','hebreus','tiago','1pedro','2pedro',
  '1joao','2joao','3joao','judas','apocalipse',
];

function varName(id, version) {
  const raw = `${id.toUpperCase().replace(/[^A-Z0-9]/g, '_')}_${version}`;
  return /^[0-9]/.test(raw) ? `BOOK_${raw}` : raw;
}

// Auto-detect versions from subdirectories unless specified
function detectVersions() {
  try {
    return fs.readdirSync(LOCAL_BASE, { withFileTypes: true })
      .filter(d => d.isDirectory())
      .map(d => d.name.toUpperCase())
      .filter(v => /^[A-Z0-9]+$/.test(v));
  } catch { return []; }
}

function getAvailableBooks(version) {
  const verDir = path.join(LOCAL_BASE, version);
  return BOOKS.filter(id => fs.existsSync(path.join(verDir, `${id}.ts`)));
}

// ── Generate per-version index file ───────────────────────────────────────────
function generateVersionIndex(version) {
  const available = getAvailableBooks(version);
  if (available.length === 0) {
    console.warn(`  ⚠ Nenhum livro encontrado para ${version}`);
    return false;
  }

  const lines = [
    `// Auto-generated by scripts/generate-index.mjs`,
    `// Version: ${version} | Books: ${available.length}/66`,
    ``,
  ];

  for (const id of available) {
    lines.push(`import { ${varName(id, version)} } from './${id}';`);
  }

  lines.push(``);
  lines.push(`export const LOCAL_BIBLE_${version}: Record<number, string[]>[] = [];`);
  lines.push(``);
  lines.push(`export const LOCAL_${version}: Record<string, Record<number, string[]>> = {`);
  for (const id of available) {
    lines.push(`  ${JSON.stringify(id)}: ${varName(id, version)},`);
  }
  lines.push(`};`);
  lines.push(``);

  const outFile = path.join(LOCAL_BASE, version, 'index.ts');
  fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
  console.log(`  ✓ ${version}/index.ts (${available.length} livros)`);
  return true;
}

// ── Generate master index ──────────────────────────────────────────────────────
function generateMasterIndex(versions) {
  const lines = [
    `// Auto-generated by scripts/generate-index.mjs`,
    `// Available versions: ${versions.join(', ')}`,
    ``,
  ];

  for (const v of versions) {
    const available = getAvailableBooks(v);
    if (available.length === 0) continue;
    lines.push(`import { LOCAL_${v} } from './bible-local/${v}/index';`);
  }

  lines.push(``);
  lines.push(`// Map of version code → book id → chapter → verses`);
  lines.push(`export const LOCAL_BIBLE: Record<string, Record<string, Record<number, string[]>>> = {`);
  for (const v of versions) {
    const available = getAvailableBooks(v);
    if (available.length === 0) continue;
    lines.push(`  ${JSON.stringify(v)}: LOCAL_${v},`);
  }
  lines.push(`};`);
  lines.push(``);
  lines.push(`// Convenience: ARA is the primary offline version`);
  lines.push(`export const LOCAL_BIBLE_ARA = LOCAL_BIBLE[${JSON.stringify(versions[0])}] ?? {};`);
  lines.push(``);

  fs.writeFileSync(MASTER_INDEX, lines.join('\n'), 'utf8');
  console.log(`\n✅ lib/bible-local-index.ts gerado (${versions.length} versões)`);
}

// ── Main ──────────────────────────────────────────────────────────────────────
const requestedVersions = process.argv.slice(2).map(v => v.toUpperCase());
const versions = requestedVersions.length > 0 ? requestedVersions : detectVersions();

if (versions.length === 0) {
  console.error('❌ Nenhuma versão encontrada. Rode download-bible.mjs primeiro.');
  process.exit(1);
}

console.log(`\n📦 Gerando índices para: ${versions.join(', ')}\n`);

const generated = [];
for (const v of versions) {
  if (generateVersionIndex(v)) generated.push(v);
}

generateMasterIndex(generated);
