// Auto-generated by scripts/generate-index.mjs
// Version: NTLH | Books: 66/66

import { GENESIS_NTLH } from './genesis';
import { EXODO_NTLH } from './exodo';
import { LEVITICO_NTLH } from './levitico';
import { NUMEROS_NTLH } from './numeros';
import { DEUTERONOMIO_NTLH } from './deuteronomio';
import { JOSUE_NTLH } from './josue';
import { JUIZES_NTLH } from './juizes';
import { RUTE_NTLH } from './rute';
import { BOOK_1SAMUEL_NTLH } from './1samuel';
import { BOOK_2SAMUEL_NTLH } from './2samuel';
import { BOOK_1REIS_NTLH } from './1reis';
import { BOOK_2REIS_NTLH } from './2reis';
import { BOOK_1CRONICAS_NTLH } from './1cronicas';
import { BOOK_2CRONICAS_NTLH } from './2cronicas';
import { ESDRAS_NTLH } from './esdras';
import { NEEMIAS_NTLH } from './neemias';
import { ESTER_NTLH } from './ester';
import { JO_NTLH } from './jo';
import { SALMOS_NTLH } from './salmos';
import { PROVERBIOS_NTLH } from './proverbios';
import { ECLESIASTES_NTLH } from './eclesiastes';
import { CANTARES_NTLH } from './cantares';
import { ISAIAS_NTLH } from './isaias';
import { JEREMIAS_NTLH } from './jeremias';
import { LAMENTACOES_NTLH } from './lamentacoes';
import { EZEQUIEL_NTLH } from './ezequiel';
import { DANIEL_NTLH } from './daniel';
import { OSEIAS_NTLH } from './oseias';
import { JOEL_NTLH } from './joel';
import { AMOS_NTLH } from './amos';
import { OBADIAS_NTLH } from './obadias';
import { JONAS_NTLH } from './jonas';
import { MIQUEIAS_NTLH } from './miqueias';
import { NAUM_NTLH } from './naum';
import { HABACUQUE_NTLH } from './habacuque';
import { SOFONIAS_NTLH } from './sofonias';
import { AGEU_NTLH } from './ageu';
import { ZACARIAS_NTLH } from './zacarias';
import { MALAQUIAS_NTLH } from './malaquias';
import { MATEUS_NTLH } from './mateus';
import { MARCOS_NTLH } from './marcos';
import { LUCAS_NTLH } from './lucas';
import { JOAO_NTLH } from './joao';
import { ATOS_NTLH } from './atos';
import { ROMANOS_NTLH } from './romanos';
import { BOOK_1CORINTIOS_NTLH } from './1corintios';
import { BOOK_2CORINTIOS_NTLH } from './2corintios';
import { GALATAS_NTLH } from './galatas';
import { EFESIOS_NTLH } from './efesios';
import { FILIPENSES_NTLH } from './filipenses';
import { COLOSSENSES_NTLH } from './colossenses';
import { BOOK_1TESSALONICENSES_NTLH } from './1tessalonicenses';
import { BOOK_2TESSALONICENSES_NTLH } from './2tessalonicenses';
import { BOOK_1TIMOTEO_NTLH } from './1timoteo';
import { BOOK_2TIMOTEO_NTLH } from './2timoteo';
import { TITO_NTLH } from './tito';
import { FILEMOM_NTLH } from './filemom';
import { HEBREUS_NTLH } from './hebreus';
import { TIAGO_NTLH } from './tiago';
import { BOOK_1PEDRO_NTLH } from './1pedro';
import { BOOK_2PEDRO_NTLH } from './2pedro';
import { BOOK_1JOAO_NTLH } from './1joao';
import { BOOK_2JOAO_NTLH } from './2joao';
import { BOOK_3JOAO_NTLH } from './3joao';
import { JUDAS_NTLH } from './judas';
import { APOCALIPSE_NTLH } from './apocalipse';

export const LOCAL_BIBLE_NTLH: Record<number, string[]>[] = [];

export const LOCAL_NTLH: Record<string, Record<number, string[]>> = {
  "genesis": GENESIS_NTLH,
  "exodo": EXODO_NTLH,
  "levitico": LEVITICO_NTLH,
  "numeros": NUMEROS_NTLH,
  "deuteronomio": DEUTERONOMIO_NTLH,
  "josue": JOSUE_NTLH,
  "juizes": JUIZES_NTLH,
  "rute": RUTE_NTLH,
  "1samuel": BOOK_1SAMUEL_NTLH,
  "2samuel": BOOK_2SAMUEL_NTLH,
  "1reis": BOOK_1REIS_NTLH,
  "2reis": BOOK_2REIS_NTLH,
  "1cronicas": BOOK_1CRONICAS_NTLH,
  "2cronicas": BOOK_2CRONICAS_NTLH,
  "esdras": ESDRAS_NTLH,
  "neemias": NEEMIAS_NTLH,
  "ester": ESTER_NTLH,
  "jo": JO_NTLH,
  "salmos": SALMOS_NTLH,
  "proverbios": PROVERBIOS_NTLH,
  "eclesiastes": ECLESIASTES_NTLH,
  "cantares": CANTARES_NTLH,
  "isaias": ISAIAS_NTLH,
  "jeremias": JEREMIAS_NTLH,
  "lamentacoes": LAMENTACOES_NTLH,
  "ezequiel": EZEQUIEL_NTLH,
  "daniel": DANIEL_NTLH,
  "oseias": OSEIAS_NTLH,
  "joel": JOEL_NTLH,
  "amos": AMOS_NTLH,
  "obadias": OBADIAS_NTLH,
  "jonas": JONAS_NTLH,
  "miqueias": MIQUEIAS_NTLH,
  "naum": NAUM_NTLH,
  "habacuque": HABACUQUE_NTLH,
  "sofonias": SOFONIAS_NTLH,
  "ageu": AGEU_NTLH,
  "zacarias": ZACARIAS_NTLH,
  "malaquias": MALAQUIAS_NTLH,
  "mateus": MATEUS_NTLH,
  "marcos": MARCOS_NTLH,
  "lucas": LUCAS_NTLH,
  "joao": JOAO_NTLH,
  "atos": ATOS_NTLH,
  "romanos": ROMANOS_NTLH,
  "1corintios": BOOK_1CORINTIOS_NTLH,
  "2corintios": BOOK_2CORINTIOS_NTLH,
  "galatas": GALATAS_NTLH,
  "efesios": EFESIOS_NTLH,
  "filipenses": FILIPENSES_NTLH,
  "colossenses": COLOSSENSES_NTLH,
  "1tessalonicenses": BOOK_1TESSALONICENSES_NTLH,
  "2tessalonicenses": BOOK_2TESSALONICENSES_NTLH,
  "1timoteo": BOOK_1TIMOTEO_NTLH,
  "2timoteo": BOOK_2TIMOTEO_NTLH,
  "tito": TITO_NTLH,
  "filemom": FILEMOM_NTLH,
  "hebreus": HEBREUS_NTLH,
  "tiago": TIAGO_NTLH,
  "1pedro": BOOK_1PEDRO_NTLH,
  "2pedro": BOOK_2PEDRO_NTLH,
  "1joao": BOOK_1JOAO_NTLH,
  "2joao": BOOK_2JOAO_NTLH,
  "3joao": BOOK_3JOAO_NTLH,
  "judas": JUDAS_NTLH,
  "apocalipse": APOCALIPSE_NTLH,
};
